### ISSUE TITLE
Table to Program Page on Bouvet Island

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#104]
### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [x] I've described what I expected to see and what I am seeing
* [x] I am not interested or able to instead create a pull request with a proposed fix

Please incorporate a table into the Program page. I have put in some mock content. It also needs to be able to have 2 columns in the case of multiple tracks.
This is the page that needs the enhancement: 

kubernetes-community-days/content/events/2020-bouvet-island/program.md 

This is a good example of how it should look: 
https://cloudnative.amsterdam/schedule/

Thanks!
-Chris

**Comment by dankohn** [comment]
Closed in favor of #144
