### ISSUE TITLE
Update Template to look for images in local director

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#105]
### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [X] I've described what I expected to see and what I am seeing
* [X] I am not interested or able to instead create a pull request with a proposed fix

Hi Luc,

Can you please update the Bouvet Island Index Template to pull the images from the local directory? We are going to have each site host their own images. 

I've created an images folder in Bouvet Island and uploaded all the images. 
kubernetes-community-days/content/events/2020-bouvet-island/images/

thanks!

**Comment by christinevblum** [comment]
Luc - let me know when this is complete and I will remove all the images from the img file.

**Comment by lucperkins** [comment]
@christinevblum This unfortunately isn't possible due to the way the static site generator handles static assets. All static assets need to be in the `static` folder.

**Comment by dankohn** [comment]
@christinevblum for clarity, let's create the directories /static/img/2020-bouvet-island/speakers and /static/img/2020-bouvet-island/sponsors and add directions that organizers should only modify files in their content and their img directories.

**Comment by xrs888** [comment]
@dankohn do we want to folders? For now, I think one folder will suffice /static/img/2020-bouvet-island. Then each event will have one folder

**Comment by dankohn** [comment]
Your call.
