### ISSUE TITLE
2020 Berlin

### ISSUE THREAD

**Issue by blixtra** [cncf/kubernetes-community-days#117]
### Event City: Berlin

We'd like to propose an event in Berlin the 2nd half of May. This is a perfect time to hold an event in Berlin, with great weather and before the holidays kick in. Berlin also offers a wealth of unique venues and one of the most active tech scenes in all of Europe.

### Experience

We at Kinvolk already organize several successful open source events. For example, next week we have the 3rd iteration of [All Systems Go!](https://all-systems-go.io/), the conference for foundational user-space Linux technologies. In November we'll be putting on the 2nd [Cloud Native Rejekts](https://cloud-native.rejekts.io/) conference, an event that offers a stage to some of the wonderful, but rejected, KubeCon proposals. We also organize the more than 1000 member strong [CNCF Berlin Meetup](https://www.meetup.com/Cloud-Native-Computing-Berlin/).

Kinvolk focuses on putting on no-frills, engineer-oriented events. This seems to be fully inline with what the CNCF is striving to do with KCD.

### Organizer 1: Chris Kuehl, Kinvolk, CEO, chris@kinvolk.io
Chris is a CNCF Ambassador and long-time open source contributor.
 
### Organizer 2: Lexi Nadolski, Kinvolk, Head of Events, lexi@kinvolk.io
Lexi heads the events team at Kinvolk and coordinates volunteer and event diversity efforts.

While Kinvolk is well positioned to execute the event self-sufficiently, we will happily—and can readily—pull in more organizers if needed.

**Comment by christinevblum** [comment]
@blixtra this is very exciting news!  We are very close to launching Kubernetes Community Days events page so your timing is perfect!

We have another organizer who reached out to me earlier this year, I will put you in touch with them.

Finally, here is the getting started checklist:
- No other Kubernetes Community Day event in the local area
- Minimum of 3 organizers from 2 different organizations, and ideally 5 or more organizers
- Organizers are local to the event location
- At least one organizer is an employee of a CNCF member, an Ambassador, or a CNCF project maintainer
- You have a method to accept payments, including sponsorships, and to pay out expenses
- All organizers have agreed to these event guidelines and to abide by the Kubernetes Community Day Code of Conduct
- Event date must be a minimum of 6 months from the day you submit your request, with 9 months being preferable
- Use Eventbrite for registration

Let us know when you are ready with the above and we can you set-up to host KCD Berlin.

**Comment by blixtra** [comment]
Hi @christinevblum, please do put me in touch with them. But we do already have another org we'll be working with on this. I'll add the info later this week and file the PR. All the above boxes should be checked.

**Comment by christinevblum** [comment]
@blixtra we are soft launching tomorrow! You are cleared to be the first KCD to test everything out. Can you create a new event issue (we've updated the template) with all your teams info? I will close this issue.

**Comment by blixtra** [comment]
Sure, will do!

**Comment by tinerehbein** [comment]
Good Morning @blixtra, this is really good news. We would be happy to work with you on the Kubernetes Community Days Berlin.

SysEleven has been a CNCF member since mid 2018, with our own Kubernetes as a Service solution. 

I would be happy if you contact me and we can talk about details.

**Comment by blixtra** [comment]
> @blixtra we are soft launching tomorrow! You are cleared to be the first KCD to test everything out. Can you create a new event issue (we've updated the template) with all your teams info? I will close this issue.

@christinevblum Should I close [the other ticket](https://github.com/cncf/kubernetes-community-days/issues/177) I was requested to open?

**Comment by blixtra** [comment]
> I would be happy if you contact me and we can talk about details.

Sure, we know SysEleven. Can you please send a message to the address above and we can pick it up there?

**Comment by christinevblum** [comment]
@blixtra I will closet this one out and we will work from #177
