### ISSUE TITLE
Setup prose.io configuration

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#12]
Please only allow editing in the content directory and hide everything else.

Please work off of https://github.com/atchai/atchai-hugo/blob/master/_prose.yml but read through the options on https://github.com/prose/prose/wiki/Getting-Started and https://github.com/prose/prose/wiki/Prose-Configuration. Please add comments to the configuration file if you're unsure of anything or want to explain why you are choosing that option.

**Comment by lucperkins** [comment]
Added in d83d944a6aa40ced3ce9be03d01c9d1eaa9c633a
