### ISSUE TITLE
Create event directories inside /static/img

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#131]
We want to create event specific subdirectories inside of `/static/img`. Could you please move the contents of `/static/img/people` into `/static/img/2020-bouvet-island` and change the template to look for the images there. Please do the same for logos, sponsors, and maps. We don't need sub-directories inside of `2020-bouvet-island`.

**Comment by christinevblum** [comment]
I moved the images. @luc can you please update the template. Once that is done I can delete the other folders.

**Comment by dankohn** [comment]
@lucperkins You didn't seem to address the request here.

**Comment by lucperkins** [comment]
@dankohn Oops! I think I fat-fingered that on my phone. PR #138 should address this.
