### ISSUE TITLE
Automatically build tables in program page

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#134]
Could you please reuse the devopsday code to turn this program info https://github.com/devopsdays/devopsdays-web/blob/master/data/events/2019-london.yml#L210 into https://devopsdays.org/events/2019-london/program.

**Comment by lucperkins** [comment]
@dankohn They're using Bootstrap for CSS and adopting a `Scratch`-based approach that strikes me as highly inadvisable, so I'll need to build from scratch

**Comment by dankohn** [comment]
Good news. We just got a license to use Sched so there's no need to do this.
