### ISSUE TITLE
Create sample Sched schedule

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#144]
1. Use your work email to give your personal email access to Sched for KCD Bouvet Island.
2. Create several talks from Phippy and friends.
3. Embed the schedule in https://kubernetescommunitydays.org/events/2020-bouvet-island/program/ (ask on Slack if you need help).
4. Write up directions to do this.
5. Add a requirement to use Sched for the scheduling to the organizing page.

**Comment by christinevblum** [comment]
This is done
