### ISSUE TITLE
Keep top-level menus on the right side

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#146]
On https://kubernetescommunitydays.org/events/2020-bouvet-island/

Please have the menus go:

Overview
Contact
Program
Speakers
Sponsor
Venue
Organizing
Code of Conduct
Speaking
Sponsoring

That is, the last 4 should always stay to the right, and on events pages, the first 6 should appear.

**Comment by lucperkins** [comment]
Resolved by bbbd1e2a5895f73e4904da54bc4e3bb9e8240457
