### ISSUE TITLE
Looking for co-organizers to help plan a Vancouver, BC K8S Community Day

### ISSUE THREAD

**Issue by dmueller2001** [cncf/kubernetes-community-days#155]
I do not have team assembled, I'm  interested in organizing an event in Vancouver perhaps co-located with some other larger tech conference in the Spring of 2020. 

If you are interested in helping plan this event, please add a comment so we can achieve the 3 organizers required to move this forward.

### Organizer 5: Shea Stewart, Artiq.ca  shea.stewart@arctiq.ca

Once we have identified 3 organizers, 2 sponsors, will complete the information below and update this issue. 

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [ ] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [X] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [X] Minimum of 3 organizers from 3 different organizations
* [ ] No other Kubernetes Community Days event in the same city

**Comment by vllry** [comment]
I am interested!

**Comment by troytop** [comment]
SUSE is interested in helping.

**Comment by brentsmi** [comment]
Hi Diane! As Troy said, he and/or I can help.

**Comment by dmueller2001** [comment]
@iennae we have the organizers and verbal commits to sponsors as of today; could we also get a CNCF liason named to this effort and then I'll call a kick off meeting to discuss dates/venues/recruiting more sponsors

**Comment by dankohn** [comment]
The next step we'd planned is for you to post the sponsors who have committed, and then we'll sign off on you creating the event site. Does that work for you?

**Comment by christinevblum** [comment]
There are a couple of items missing from the checklist, please confirm:
All organizers signed off to the event guidelines and CNCF Code of Conduct 
Method to accept payments including sponsorships and payout expenses

**Comment by jtborek** [comment]
Interested in helping, thanks.

**Comment by dankohn** [comment]
@jtborek We require organizers to be in the same city as the KCD. I'd encourage you to consider a Seattle one.

**Comment by dmueller2001** [comment]
@ppodolny opsguru/vancouver interested in participating as well

**Comment by ananthulasrikar** [comment]
I am CNCF Ambassador & moved to Vancouver recently. I would love to help to organize the event.

**Comment by xmulligan** [comment]
@dmueller2001 We are relaunching the KCD program, including virtual events. We would love to have one in Vancouver if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by AudMonte01** [comment]
Hello @dmueller2001 - is this something you and this same or similar team would like to revisit for 2024, or 2025? If not, perhaps start with a cloud native community group via community.cncf.io?
