### ISSUE TITLE
Clarify which menus are event-specific

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#160]
I find it confusing that you can't easily see which menus are universal and which are specific to an event. What would you think of redoing the menus to look something like this:

![image](https://user-images.githubusercontent.com/3083270/65909558-eea68200-e396-11e9-8052-dabbd617a006.png)

Clicking Bouvet Island would just click the menu above it.

**Comment by christinevblum** [comment]
I like it!

**Comment by dankohn** [comment]
Here's a revised idea:

![image](https://user-images.githubusercontent.com/3083270/65915448-7b563d80-e3a1-11e9-8920-706ab8b4533e.png)
