### ISSUE TITLE
Menu name is off

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#164]
First menu of https://kubernetescommunitydays.org/events/2020-bouvet-island/ correctly shows `Bouvet Island Overview`. First menu of https://kubernetescommunitydays.org/events/2019-amsterdam/ incorrectly shows `Kubernetes Community Day Amsterdam Overview` when it should say `Amsterdam Overview`.

**Comment by lucperkins** [comment]
Resolved by b98f9abc96049cb3c79c5eb380dd7f5c642d59bb
