### ISSUE TITLE
Kubernetes Community Days Bay Area (formerly Silicon Valley)

### ISSUE THREAD

**Issue by nickchase** [cncf/kubernetes-community-days#171]
Mirantis would like to host an event in Silicon Valley.  We will be attaching details shortly.

Thank you!

----  Nick Chase, Mirantis

If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Organizer 1: First and Last Name, Company, Title, Email 

Once you have identified your 3 organizers, 2 sponsors, please complete the information below and update your issue.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations.**

### Organizer 1: First and Last Name, Company, Title, Email 
Dave Van Everen, Mirantis, Senior Vice President, dvaneveren@mirantis.com

### Organizer 2: First and Last Name, Company, Title, Email
Karen Chu, Microsoft, Community Program Manager, Karen.Chu@microsoft.com

### Organizer 3: First and Last Name, Company, Title, Email
Kevin Chen, Kong, Developer Advocate, Kevin.chen@konghq.com

**Comment by christinevblum** [comment]
Hi @nickchase! Welcome! Please share the details when you have them and we can get you set-up!

**Comment by nickchase** [comment]
We are in the process of lining up additional organizers, venue, etc.  We are thinking, though, to change the name to "Kubernetes Community Days Northern California".  Would that be acceptable?

**Comment by dankohn** [comment]
We'd prefer not. Northern California is huge. Sacramento, Arcadia, etc, could be separate.

**Comment by nickchase** [comment]
That makes sense.  Thanks!

**Comment by nickchase** [comment]
OK, we're in the final stages of lining up our final organizer, and now I'm being asked if we can change it to "Kubernetes Community Days Bay Area".  Objections?

**Comment by dankohn** [comment]
That’s cool

**Comment by raravena80** [comment]
I would love to help out/organize in any way or another here. I live in the bay area (San Mateo) and work for Rakuten (ricardo.aravena@rakuten.com) also in San Mateo.

**Comment by dnielsen** [comment]
I could also help as an early sponsor and decent following in the Bay Area. I work at Redis Labs and live/work in Mountain View (dnielsen@gmail.com)

**Comment by nickchase** [comment]
Excellent, I will contact you both next week.  Thanks!

**Comment by barkerbob** [comment]
We would like to help out as a sponsor or organizer if possible. I work for Sysdig (bob.barker@sysdig.com) and we are based out of SF.

**Comment by bettyjunod** [comment]
I am interested in helping organize and possibly sponsor - I work for Solo.io (HQ in Boston) but I live in SF (betty.junod@solo.io)

**Comment by Pedigo36** [comment]
We have a location to host the event and can work as a sponsor or organizer. I work for Lacework, and our office is in Santa Clara, near Levi Stadium.
chris@lacework.net

**Comment by karenhchu** [comment]
Hi @Pedigo36 -- can you share more info on the space? Do you know what the capacity is?

**Comment by nickchase** [comment]
I spoke to him in email, it's about 100, which is awesome for a meetup but
not large enough for this event.

**Comment by raravena80** [comment]
I think a great space that devopsdays has used in the past is the computer history museum in Mt View. I'm not sure how feasible it is in terms of price. https://computerhistory.org/venue/

**Comment by nickchase** [comment]
Yes, OpenStack Silicon Valley used it as well.  It's a beautiful space, but
has some limitations.

**Comment by xmulligan** [comment]
@nickchase We are relaunching the KCD program, including virtual events. We would love to have one in the Bay Area if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
