### ISSUE TITLE
Add standard CFP software

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#172]
Please work with Nanci to get pricing on SM Apply and compare to https://sessionize.com. When we pick it, add it as a mandated choice.

Cc @dmueller2001

**Comment by blixtra** [comment]
Some of the folks who will be organizing local KCD events will already have process and systems in place for running events. While I think it is very helpful to have suggested tools for running conferences, mandating certain processes can be an additional burden on others. I know for us at Kinvolk it will be.

For example, for [All Systems Go!](https://all-systems-go.io/) and [Cloud Native Rejekts](https://cloud-native.rejekts.io/) we use Tito for ticketing and Pretalx for CFP and scheduling. We're very familiar with this tools and have gone through a few others before standardizing on these. We'd very much like to be involved in organizing but it's also far more efficient to use the same set of tools for those.

In general, I also think it's important for the CNCF too treat these events like similar to its projects and the organizers of these events as the maintainers of projects. As maintainers of the events, we should be able to choose the tools that we deem right for us, and the CNCF be there as a facilitator.

_Btw, sessionize looks very much like Pretalx. As Pretalz is an OSS project, I'd be surprised if that's not what they're using behind the scenes. We prefer to use and run the OSS project ourselves._

**Comment by dankohn** [comment]
@blixtra We appreciate the feedback and are opening to relaxing the requirements over time. But to start with, we want to mandate the tools so that we are in a position to provide support (and have the community of other KCD organizers provide support).

We are explicitly running this on a less flexible model than how we recommend tools to CNCF-hosted projects. We do not see KCD organizers as necessarily analogous to maintainers of an open source project, since we expect organizers to change much more year to year. The main reason we would step away from our recommended tools in 2020 is for areas (like China) where they don't work effectively.

Philosophically, we're happy to use open source tools (like Hugo for the website) when we can provide adequate support internally. Otherwise, we use closed source ones when we think they work better than the open source alternatives.

**Comment by ams0** [comment]
We had a good first run with sessionize for KCD Amsterdam. It integrated with our Hugo-based website, allowing to live-update the schedule from sessionize; however, perhaps sched.com is even better on that front, but you then have to have a separate process and tool for CFP. Prior to sessionize, I gave OpenCFP (https://github.com/opencfp/opencfp) a try but running your own CFP software was too much burden for our small team.

May I suggest too that, CFP tool are great, but KCD organisers should also receive some guidelines on how to choose a Program Committee? Even better, perhaps maintaining a pool of recognisable industry leaders is a great way to ensure consistency in selecting the talks and the highest standard in quality of such talks. For KCD Amsterdam we had a mix of ambassadors and other local community organisers.

**Comment by dankohn** [comment]
We would love to get some proposed text on finding and working with a program committee. Certainly, you can start with CNCF ambassadors, project maintainers, and local CKAs and CKADs. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by xmulligan** [comment]
@ams0 would you be willing to put together some text on how to pick a program committee?

**Comment by xmulligan** [comment]
@ams0 would you be willing to write something up or should I close this issue?
