### ISSUE TITLE
Organizer count missmatch in organizer docs and new event template

### ISSUE THREAD

**Issue by blixtra** [cncf/kubernetes-community-days#178]
The [guideline in the organizing document](https://github.com/cncf/kubernetes-community-days/blob/master/content/organizing.md#getting-started-checklist) about organizer count is different from that in the template for new issues/events.

The guideline says 3 organizers from at least 2 organizations while the template says 3 organizations.

**Comment by christinevblum** [comment]
@blixtra this has been fixed. Thanks for catching it and bringing to our attention.
