### ISSUE TITLE
KCD Amsterdam, The Netherlands, 24-25 September 2020

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#185]
### Organizer 3: Walter Heck, Helecloud, CTO Netherlands, walterh@helecloud.com

2019 event: https://cloudnative.amsterdam 
Event website on Github: https://github.com/cloudnative-amsterdam/public-website
Mailing list: http://eepurl.com/gxkk6v
[Photos 2019](https://500px.com/cloudnativeams/galleries/kubernetes-community-day-amsterdam-2019)
[Videos 2019](https://www.youtube.com/channel/UCU6l8HfMawParU_Q5JoYILg)

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [X] Method to accept payments including sponsorships and payout expenses
* [X] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer needs to live in or just outside of the KCD location
* [X] No other Kubernetes Community Days event in the same city
* [X] Agree to use Eventbrite for registration
* [X] Agree to use Sched for organizing the program page
* [X]  Minimum of 3 sponsors

**Comment by ticofab** [comment]
Great! My family name is missspelled and I would remove "Fontem" :)

**Comment by walterheck** [comment]
Organizer: Walter Heck, Helecloud, CTO Netherlands, walterh@helecloud.com

**Comment by srknc** [comment]
Organizer: Serkan Capkan, Cloutive, Solutions Architect, serkan.capkan@cloutive.nl

**Comment by ams0** [comment]
Created a sched account https://kcdams20.sched.com/ (will upgrade later)

**Comment by christinevblum** [comment]
Welcome, @ams0 and team! Please confirm that all your organizers are local.
The next step after that would be for you to post the names of the three sponsors, and then we'll sign off on your team creating the event site.

**Comment by dpnl87** [comment]
Organizer: Daniel Paulus, Fullstaq, Devops 🥑, d.paulus@fullstaq.com

**Comment by FloorD** [comment]
Organizer: Floor Drees, Microsoft, Dev PMM, florien.drees@microsoft.com

**Comment by walterheck** [comment]
> Welcome, @ams0 and team! Please confirm that all your organizers are local.
Confirmed, we're all physically based in and around Amsterdam

> The next step after that would be for you to post the names of the three sponsors, and then we'll sign off on your team creating the event site.
Can you elaborate on the three sponsors? Is there somewhere we can read about this?

**Comment by walterheck** [comment]
The list of sponsors for our event last month can be seen here: https://cloudnative.amsterdam/partners/

**Comment by dankohn** [comment]
I remember; I was there! But we'd like you to say which 3 have confirmed that they'll sponsor again.

**Comment by ams0** [comment]
Updated the initial post; Microsoft, Container Solutions, Fullstaq all agreed to sponsor the 2020 edition. We're on, and way early this time!

**Comment by christinevblum** [comment]
That is great news! I will move you to approve to build. Do you want to schedule a kick-off call this week or early next week?

**Comment by ams0** [comment]
Sure! Any preferred scheduling tool we can use? Doodle-like?

**Comment by christinevblum** [comment]
We have Sched for now. I just created your event and added all the organizers as admins on the account. You should receive an email shortly.

**Comment by christinevblum** [comment]
Please use: calendly.com/cblum-1

**Comment by ams0** [comment]
@KTan1226 are we good to go? Are we going to build a website ourselves or we can use the CNCF facilities and personnel (it would be awesome to have a consistent look/logo across all KCD's). Also, we'd be happy to have a call with you soon! thanks

**Comment by KTan1226** [comment]
Hi @ams0. You are approved to build your site and instructions can be found here: https://kubernetescommunitydays.org/organizing-creating-website/. 

To set up a kickoff call, please use: https://calendly.com/kristi-37/30min.  Thanks!

**Comment by dankohn** [comment]
Can you please add your list of 3 sponsors?

**Comment by ams0** [comment]
Added to the main topic (was just mentioned in the comments). And I'm preparing the PR here: https://github.com/cloudnative-amsterdam/kubernetes-community-days/tree/2020-amsterdam/content/events/2020-amsterdam

Question, how can I preview the website before opening a PR?

**Comment by dankohn** [comment]
When you open a PR it creates a preview. We won’t merge until you add an LGTM. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by ams0** [comment]
@KTan1226 can we get invited to the Slack channel?

**Comment by KTan1226** [comment]
You bet @ams0. Just added!

**Comment by dankohn** [comment]
Ready to create your site? Can we help?

**Comment by ams0** [comment]
Just in case, I agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing (@ticofab @dpnl87 @walterheck @FloorD should do the same).

@dankohn I have this #210 open, waiting for the confirmation from the venue (a new, amazing one this year we hope!) and then we open the dance :)

**Comment by Orin0k0** [comment]
Organizer: Sam Attal, Container Solutions, Community Manager, samuel.attal@container-solutions.com

**Comment by KTan1226** [comment]
@ams0 Did you create a Twitter handle for the event? It's optional, but we can help amplify if so.

**Comment by ams0** [comment]
Yes! https://twitter.com/cloudnativeams and it's active already for quite some time. @FloorD is the one managing it mostly. We also have instagram: https://www.instagram.com/cloudnativeams/ but we don't post much there (perhaps I should post last year's pics, which are now on 500px: https://500px.com/cloudnativeams/galleries/kubernetes-community-day-amsterdam-2019). Oh and we have a Youtube channel too! https://www.youtube.com/playlist?list=PLQGLXxvf53b0fzCwFJSLRyn88bCoFNH2G

**Comment by ams0** [comment]
Since the website is now up&running (thanks everyone! https://kubernetescommunitydays.org/events/2020-amsterdam/) should we close this issue now?

**Comment by dankohn** [comment]
Congrats on going live
