### ISSUE TITLE
Looking for Co Organizers and sponsors for event in Houston Texas

### ISSUE THREAD

**Issue by JohnOnTheWeb** [cncf/kubernetes-community-days#186]
### Organizer 3: Dan Kirkpatrick, Kubernetes Consultant at Anadarko, dan@frissoncomputing.com

Once you have identified your 3 organizers, 2 sponsors, please complete the information below and update your issue.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [ ] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [ ] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [ ] Minimum of 3 organizers from 3 different organizations
* [ ] Each organizer needs to live in or just outside of the KCD location
* [ ] No other Kubernetes Community Days event in the same city
* [ ] Agree to use Eventbrite for registration
* [ ] Agree to use Sched for organizing the program page

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations.**

**Comment by christinevblum** [comment]
Welcome, @JohnOnTheWeb! Please update the issue as you complete the items on the checklist. Once everything is complete we'll sign off on your team creating the event site.

**Comment by thedancollins** [comment]
I am the second organizer for Houston:
Organizer 2: Dan Collins, American Bureau of Shipping, Director, Enterprise Architecture, realdancollins@outlook.com

**Comment by xmulligan** [comment]
@JohnOnTheWeb We are relaunching the KCD program, including virtual events. We would love to have one in Houston if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
