### ISSUE TITLE
2020 Tokyo, JAPAN

### ISSUE THREAD

**Issue by superbrothers** [cncf/kubernetes-community-days#187]
### Experience
We are organizers of [Kubernetes Meetup Tokyo](https://k8sjp.connpass.com/), which is the largest successful Kubernetes meetup in JAPAN. The meetup has over 5000 members. We hold this meetup every month, and total 29 times since May 2017.

Kazuki Suda is a Cloud Native Ambassador, and he, Ian lewis, and Aya Igarashi are employees of CNCF member companies.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Identify 3 organizations that have agreed to sponsor the event.

## Sponsor 3 CyberAgent, Inc.

**Comment by dankohn** [comment]
This is a great start. Please note that in addition to identifying a method to accept payment, we also need you to identify 3 organizations that have agreed to sponsor the event.

**Comment by ianlewis** [comment]
The checklist included "Minimum of 3 organizers from 3 different organizations". Do we need to identify the organizations separately from the organizers?

**Comment by dankohn** [comment]
What you have is good. But listing the 3 sponsors is an additional requirement. (Sorry, we left it off of the initial version of the issue template.)

**Comment by idealhack** [comment]
👋 Hello from [APAC coordinator](https://github.com/kubernetes/community/blob/master/sig-contributor-experience/role-handbooks/apac-coordinator.md) of Kubernetes community. I've been involved in organizing four Kubernetes Contributor Summits, let me know if you need any help related to contributor experience (e.g. new contributor workshop) :)

**Comment by superbrothers** [comment]
We found  3 organizations that have agreed to sponsor the event.

**Comment by KTan1226** [comment]
Great @superbrothers- who is your fiscal sponsor for the event and method for accepting payments? Once you confirm, we can sign off creating your site.

**Comment by superbrothers** [comment]
@KTan1226 I'm sorry for late reply. We are currently finding our fiscal sponsor.

**Comment by superbrothers** [comment]
@KTan1226 We found a fiscal sponsor. It is Z Lab Corporation I work for. In addition, we decided the method for accepting payments is PayPal, but if sponsors can deposit money directly into the account, they will do so.

Finally, we decided to hold the event on 6/13. However, depending on the status of the 2019-nCoV, we'll choose whether postpone in late April.

**Comment by KTan1226** [comment]
Thanks for the update @superbrothers. We understand. Let me know what you decide in April and if you decide to move forward, I'll set you up with email aliases and access to our CFP tool.

**Comment by superbrothers** [comment]
@KTan1226 we'll decide in late April, but I'd like to start preparing the event.
Below is our plan:

- In late March
    - Publishing the website
    - Opening CFP
- In late April
    - Deciding whether to postpone
    - Starting registration

Could you set us up with email aliases and access to your CFP tool?

**Comment by KTan1226** [comment]
Hi @superbrothers- sure thing! Please use the following aliases:

- organizers-tokyo@kubernetescommunitydays.org (for communications with your organizers)
- sponsors-tokyo@kubernetescommunitdays.org (for sponsor inquiries, will forward to general organizers alias)

I will reach out to test your organizers' alias and to grant you access to our CFP tool. Let me know if you have any questions in the interim!

**Comment by superbrothers** [comment]
@KTan1226 Do we have the option of changing this to a virtual event other than postponing it? We'll decide at the end of April, but we want to know before then.

**Comment by KTan1226** [comment]
Hi @superbrothers- At this time, we are strongly encouraging all KCDs to be in person. However, we can be flexible with the timing if you need to postpone it. Thanks!

**Comment by superbrothers** [comment]
@KTan1226 We decided to make Kubernetes Community Day Tokyo 2020 a virtual event.

We understand that CNCF is strongly encouraging it to be in person. However, no one knows when the effects of COVID-19 will subside. In this context, we believe that for a community to survive, we have to keep the activity going, whether it's offline or online. Please support our decision.

**Comment by iennae** [comment]
@superbrothers Totally understand. I would recommend giving it a slightly different name to differentiate it from your eventual first in person KCD. I'm happy to support your virtual event efforts as I think it's critical like you said to encourage community participating even now.

**Comment by superbrothers** [comment]
@iennae Thank you for understanding. The name of the event will be discussed in KCD Tokyo organizers and communicated to you.

**Comment by superbrothers** [comment]
@iennae We decided to name the event "Kubernetes Community Day Tokyo | Virtual 2020".

**Comment by iennae** [comment]
@superbrothers To be really clear, CNCF has asked that the KCD name not be used for virtual events. They want to make sure that KCD is only associated with in person events.

**Comment by superbrothers** [comment]
@iennae The name of the event, "Kubernetes Community Day Tokyo | Virtual 2020", makes it really clear that it's a virtual event. That should be enough for the participants. However, KCD is the property of CNCF. Therefore, for whatever reason, we will abide by CNCF's decision.

If CNCF has a good idea for a name for this virtual event, please let us know for our reference.

**Comment by superbrothers** [comment]
We have decided on a new name, "Kubernetes Fest Tokyo". This event will be held as an unofficial CNCF event. A new site is currently being prepared. Once the site has been created, create a PR to add a link to it from 2020-tokyo site.

Once COVID-19 is under control, we would like to hold KCD Tokyo as an in person event. We would appreciate your support in doing so. Thank you very much.

**Comment by KTan1226** [comment]
Hi @superbrothers and team- Just following up here, any updates on your new website? We can link to it but need to remove your KCD website from the webpage as it is no longer an official KCD event.

**Comment by dankohn** [comment]
Apologies, but you can't use the name "Kubernetes Fest Tokyo either". You could do "Cloud Native Fest Tokyo Featuring Kubernetes". Please see https://www.linuxfoundation.org/trademark-usage for much more detail.

**Comment by superbrothers** [comment]
@dankohn Thank you for letting us know.

> Do not use logos or names of The Linux Foundation in any commercial or marketing context other than as expressly permitted in this policy unless you have obtained explicit written permission from The Linux Foundation to do so.

This event is completely free and there is no commercial or marketing element. The organizers are individual members of the community. Sponsors will be providing the Zoom meeting room, etc., and no money will be provided. As such, this event can be considered a slightly larger version of the Kubernetes meetups that are being held around the world.

If this event name is not available even under these conditions, we will consider a name such as Cloud Native XX featuring Kubernetes under your rules and policies.

**Comment by dankohn** [comment]
I'm sorry we can't accommodate you here, but we need to apply the naming
policy consistently. All day events are not meetups, and we're not allowing
the use of the name for other virtual events.

Again, I apologize for the inconvenience.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by superbrothers** [comment]
@dankohn We would like to name the event "KubeFest Tokyo 2020". We believe that this is in accordance with The Linux Foundation Trademark Usage Guidelines.

**Comment by dankohn** [comment]
Sounds great! Thanks for your accommodation here.  





On Thu, May 21, 2020 5:33 AM, Kazuki Suda notifications@github.com  wrote:


@dankohn  We would like to name the event "KubeFest Tokyo 2020". We believe that
this is in accordance with The Linux Foundation Trademark Usage Guidelines.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



--Dan Kohn <mailto:dan@linuxfoundation.org>Executive Director, Cloud Native
Computing Foundation <https://cncf.io/>
tel:+1-415-233-1000

**Comment by superbrothers** [comment]
We've changed all the names to "KubeFest Tokyo 2020" on our new event sites.

- https://k8sjp.connpass.com/event/176105/
- https://k8sjp.github.io/kubefest-2020/

**Comment by KTan1226** [comment]
Hi @superbrothers- Could you please update your website on the KCD webpage and link it to your new website? I would just update the text to say the event is now virtual and information can be found here: https://k8sjp.connpass.com/event/176105/. Thank you!

**Comment by superbrothers** [comment]
@KTan1226 I've created a PR. Please check it out. https://github.com/cncf/kubernetes-community-days/pull/356

**Comment by superbrothers** [comment]
@dankohn @KTan1226 We held KubeFest Tokyo 2020 on June 13th. The number of registered participants was 1777. We share the attribute information of the participants with you.  https://docs.google.com/spreadsheets/d/1-LdwLFiDL50gLcbyM3I39pnS7abkf-gkiwn7BHTez50/edit?usp=sharing

**Comment by dankohn** [comment]
Congratulations

**Comment by xmulligan** [comment]
@superbrothers We have relaunched the KCD program and are now including virtual events https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/. If you are interested in organizing another event in Tokyo, we would love to have you! Let me know if you have any questions, I am happy to help :)

**Comment by superbrothers** [comment]
@xmulligan Thank you for letting me know. I'll read the blog post 😊

**Comment by xmulligan** [comment]
@superbrothers Great! Please reach out if you have any questions, kcd@cncf.io or https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03
