### ISSUE TITLE
2020 Washington, D.C.

### ISSUE THREAD

**Issue by Sramsel** [cncf/kubernetes-community-days#190]
**Event City:** Washington, D.C. 

**Dates:**
September 15, 2020

**Experience:**
We are organizers of the [All Things Kubernetes Meetup](https://www.meetup.com/All-Things-Kubernetes-k8s-DC/) in Washington, D.C., with almost 700 members. We have been successfully organizing meetups for over 2 years and look forward to hosting a larger event here in the D.C. Area.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

**Organizer 1:** Sophia Ramsel, Kublr, Marketing Assistant, sophia@kublr.com, Catherine Paganini, Kublr, Marketing Director, catherine@kublr.com
**Organizer 2:** Matthew Cascio, Red Cross, matthew.cascio@redcross.org
**Organizer 3.** Marina Kazakova, EastBanc Technologies, mkazakova@eastbanctech.com 
**Organizer 4.** Jason Morgan, VMware, jmorgan@pivotal.io

**Comment by danpopSD** [comment]
Hello Sophia/Catherine.  we (Sysdig)  would like to help sponsor this event and all get to know the https://www.meetup.com/All-Things-Kubernetes-k8s-DC/ meetup group and assist as we can.

Organizer 1/Sponsor : Dan Papandrea/Rob Wolf , Sysdig,  Field CTO /Federal Lead ,  pop @ sysdig dot com.

**Comment by Sramsel** [comment]
Hi Dan, we would love to have Sysdig as a sponsor! Can you shoot me an email at sophia@kublr.com so that we can organize an introduction call?

**Comment by iennae** [comment]
@Sramsel reminder that the event needs at least 3 individuals from 3 different organizations.

**Comment by boydj** [comment]
Hello, we (Booz Allen) would like to help sponsor this event but need to understand the costs associated to get this approved internally.

Josh Boyd, Booz Allen Hamilton, Chief Technologist, boyd_joshua @ bah dot com.

**Comment by aclater** [comment]
Howdy - we (Red Hat) would also like to sponsor and assist, but need to understand costs as well :) adam @ red hat dot com

**Comment by KTan1226** [comment]
Hi @Sramsel- can you please confirm the fiscal sponsor for your event? Once you confirm, I can sign off on you creating your website. Thank you!

**Comment by Sramsel** [comment]
Hi @KTan1226, EastBanc Technologies will be the fiscal sponsor. On that note, we do have a question from the accounting department. The legal entity accepting and making payments will be EastBanc Technologies, correct? There is no other legal entity unless we create an LLC for the event which I don't believe we have to do. Thank you!

**Comment by KTan1226** [comment]
Hi @Sramsel. Yes, that is correct. No need to create an LLC for the event if EastBanc will accept and make payments. 

You are now approved to build your site! Here are guidelines on how to get started: https://kubernetescommunitydays.org/organizing-creating-website/.

I will create your email aliases (for organizing and sponsorships) and reach out to set up your CFP in SM Apply. Please let me know if you have any questions in the interim!

**Comment by Sramsel** [comment]
Thank you @KTan1226!

**Comment by KTan1226** [comment]
Hi all! Please use the following aliases:
- organizers-dc@kubernetescommunitydays.org (for organizer communications)
- sponsors-dc@kubernetescommunitydays.org (for potential sponsors, forwards to organizer alias)

I will now send a test of the organizers' alias and details on how to proceed with the CFP access. Thanks!

**Comment by xmulligan** [comment]
@Sramsel Are you still planning on having an event in 2021? We will shortly be updating the program and I didn't want to close this issue if you are still actively working on it.

**Comment by xmulligan** [comment]
closing this discussion and moving the discussion over to #381
