### ISSUE TITLE
2020 Kubernetes Community Days Minneapolis

### ISSUE THREAD

**Issue by dstrebel** [cncf/kubernetes-community-days#191]
### Date:
We would like to propose an event in Minneapolis in early May. This would provide us ample time to find sponsors and event location. This will also avoid summer vacations in the US that typically happen between June-Aug.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [ ] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [ x ] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [ x ] Minimum of 3 organizers from 3 different organizations
* [ x ] Minimum of 3 sponsors
* [ x ] Each organizer needs to live in or just outside of the KCD location
* [ x ] No other Kubernetes Community Days event in the same city
* [ x ] Agree to use Eventbrite for registration
* [ x ] Agree to use Sched for organizing the program page

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

**Comment by mcapra** [comment]
@dstrebel do you have a ballpark for the financial commitment expected of an initial sponsor?

**Comment by xmulligan** [comment]
@dstrebel We are relaunching the KCD program, including virtual events. We would love to have one in Minneapolis if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
