### ISSUE TITLE
 Add standard Registration software

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#196]
### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [X] I've described what I expected to see and what I am seeing
* [X] I am not interested or able to instead create a pull request with a proposed fix

Review registration software for KCD and pick the one that will best meet our needs. 
https://docs.google.com/spreadsheets/d/1gZyOQGGQSAkQYzqYdOg2XAorxejTTnl9E9aUYrak0Uo/edit#gid=0

**Comment by ams0** [comment]
We used Eventbrite Professional for the Amsterdam 2019 event, and we are very satisfied. I think the table should include this features for Eventbrite Pro:

- [x] Discount Codes
- [x] Web based check in or scanner
- [x] Webhooks and API
- [x] Full Data export
- [x] Ticket printing
- [x] payment available immediately
- [x] print out badges
- [x] Multi Language

The analytics features are great, and we could be flexible in pricing (giving out discount to local meetups for example); also great to be able to refund/transfer registrations very easily. Payments can happen at the end or every month leading to the event, providing some much needed cash before hand.

**Comment by xmulligan** [comment]
This will be Bevy going forward. https://community.cncf.io/
