### ISSUE TITLE
Update CoC 

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#197]
### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [X] I've described what I expected to see and what I am seeing
* [X] I am not interested or able to instead create a pull request with a proposed fix

Update CoC https://kubernetescommunitydays.org/code-of-conduct/ to include the escalation process, consquences, etc.

**Comment by xmulligan** [comment]
@christinevblum can you be more specific about what you think is missing?
