### ISSUE TITLE
Warsaw-kubernetes-community-days

### ISSUE THREAD

**Issue by ElizaCognitive** [cncf/kubernetes-community-days#198]
If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Organizer 1: Piotr Szwed, Cognitive Cloud Solutions Sp. z o.o., Owner, pszwed@cognitive-cs.com 

Once you have identified your 3 organizers and 3 sponsors, please complete the information below and update your issue.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

**Comment by christinevblum** [comment]
Welcome, @ElizaCognitive! What are you using for your method to accept payment? Once we have that you are ready to get started.

**Comment by ElizaCognitive** [comment]
@christinevblum Hi, currently we have a company (Cognitive Cloud Solutions Sp. z o.o. NIP 5423292509) which will accept payments and do the invoicing for the events.

**Comment by KTan1226** [comment]
@ElizaCognitive What date are you planning on launching the event?

**Comment by ElizaCognitive** [comment]
@KTan1226 Hi, we are planning to have the event on 29-30.04.2020.

**Comment by KTan1226** [comment]
Thanks, @ElizaCognitive. You are approved to create your site. I will also be in touch shortly with your KCD email alias.

**Comment by KTan1226** [comment]
Organizers, can you please share your Slack usernames? I will add you to the KCD organizer Slack channel as well.

**Comment by szwed** [comment]
@KTan1226 can we change ticket's status to:  "Approved to Build Site" ??

slack: pszwed, for now it will be only me

**Comment by KTan1226** [comment]
Sure thing @szwed- all set!
