### ISSUE TITLE
Add faceted search to events listing

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#20]
Let people filter events by continent and country the way we do with the location dropdown on https://www.cncf.io/events-well-be-at/.

There are a [number](https://www.google.com/search?q=faceted+search+javascript) of possible libraries to use.

**Comment by lucperkins** [comment]
@dankohn Due to the amount of work that this entails, I'd suggest that we set a threshold for the number of total events required before adding a selector. In my view, it doesn't make much sense for 2 or 3 but might for, say, 8.

**Comment by dankohn** [comment]
Agreed. Note that this is post-launch.

**Comment by lucperkins** [comment]
Ah, gotcha. I didn't spot the project designation.
