### ISSUE TITLE
2020: Sofia, Bulgaria 

### ISSUE THREAD

**Issue by OrlinVasilev** [cncf/kubernetes-community-days#200]
### Organizer 1: First and Last Name, Company, Title, Email 
Orlin Vasilev, VMware, Software Infrastructure Engineer - orlin@orlix.org

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [X] Method to accept payments including sponsorships and payout expenses
* [X] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Minimum of 3 sponsors
* [X] Each organizer needs to live in or just outside of the KCD location
* [X] No other Kubernetes Community Days event in the same city
* [X] Agree to use Eventbrite for registration
* [X] Agree to use Sched for organizing the program page

Financial Entity:
DevOps At Work Ltd.

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

Organizer 1: Orlin Vasilev, VMware, CNCF Ambassador - orlin@orlix.org
Organizer 2: Vladimir Dimov(NDA) - vladimir@devopsatwork.com
Organizer 3: Spas Atanasov, Ship.cars - airstand@gmail.com

## Sponsor 1
VMware Bulgaria
## Sponsor 2
SAP Bulgaria
## Sponsor 3
Mirantis Bulgaria(ex Docker Bulgaria)

https://www.meetup.com/Cloud-Native-Computing-Bulgaria/

https://github.com/cncf-bulgaria/meetups

**Comment by christinevblum** [comment]
Welcome, @OrlinVasilev. Please update your issue when you have your 3 sponsors and method of collecting payments.

**Comment by OrlinVasilev** [comment]
@christinevblum @KTan1226  I have updated the sponsors with the minimum , also payments are set , we will have local entity for that, also we have contacted an even company for helping us with the organisation.

**Comment by KTan1226** [comment]
Great @OrlinVasilev! Can you confirm who your fiscal sponsor (company or organization that will accept payments) and update on the ticket? Once you confirm, I can sign off for you to begin building your website.

**Comment by OrlinVasilev** [comment]
@KTan1226 - the company that we will use for the financial stuff is : DevOps At Work Ltd. Issue Updated!

**Comment by airstand** [comment]
@KTan1226 did you have a chance to review the latest updates in regards to this issue?
Thank you in advance :)

**Comment by KTan1226** [comment]
Hi @airstand! Great- you are approved to build your website. To proceed, can you:
- Share the CNCF Slack usernames for your team so I can add you to the KCD organizers channel?
- Confirm the Twitter account for your event?

I will be in touch shortly with your email aliases and details about setting up your CFP. Thanks!

**Comment by KTan1226** [comment]
Please use the following email aliases:
- organizers-sofia@kubernetescommunitydays.org (for organizer communications)
- sponsors-sofia@kubernetescommunitydays.org (for potential sponsors, email forwards to organizers alias)

I will now send a test to the alias and details on how to proceed with the CFP. Thanks!

**Comment by OrlinVasilev** [comment]
@KTan1226 - slack usernames : OrlinVasilev, vlady, Atanasov
Twitter - @KcdSofia

**Comment by airstand** [comment]
> @KTan1226 - slack usernames : OrlinVasilev, vlady, Atanasov
> Twitter - @KcdSofia

To be precise - my username in kubernetes slack is: airstand

**Comment by KTan1226** [comment]
Thanks @OrlinVasilev- I've added you and your team to the KCD organizers Slack channel.

**Comment by xmulligan** [comment]
@OrlinVasilev We are relaunching the KCD program, including virtual events. We would love to have one in Sofia if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by OrlinVasilev** [comment]
Thanks for sure we will re-launch the organisation efforts for end of this year

**Comment by xmulligan** [comment]
Awesome! Please feel free to reach out if you have any questions or there is anything I can help with along the way
