### ISSUE TITLE
2021, KCD Eugene TEST

### ISSUE THREAD

**Issue by KTan1226** [cncf/kubernetes-community-days#203]
If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Organizer 1: TEST

Once you have identified your 3 organizers and 3 sponsors, please complete the information below and update your issue.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [ x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x ] Method to accept payments including sponsorships and payout expenses
* [x ] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x ] Minimum of 3 organizers from 3 different organizations
* [x ] Minimum of 3 sponsors
* [x ] Each organizer needs to live in or just outside of the KCD location
* [ x] No other Kubernetes Community Days event in the same city
* [x ] Agree to use Eventbrite for registration
* [x ] Agree to use Sched for organizing the program page

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

**Comment by christinevblum** [comment]
Welcome, @KTan1226! Please be to sure to add organizers and sponsors as you add them. Also, be sure to check all the submission checkboxes when you are ready to build your event pages.
