### ISSUE TITLE
2020: New York!!!

### ISSUE THREAD

**Issue by justaugustus** [cncf/kubernetes-community-days#212]
### Event City: New York, NY

Once you have identified your 3 organizers and 3 sponsors, please complete the information below and update your issue.

### Submission checklist

*Please check each of these indicating that you have met these requirements:

- [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
- [x] Method to accept payments including sponsorships and payout expenses
- [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
- [x] Minimum of 3 organizers from 3 different organizations
- [x] Minimum of 3 sponsors
- [x] Each organizer needs to live in or just outside of the KCD location
- [x] No other Kubernetes Community Days event in the same city
- [x] Agree to use Eventbrite for registration
- [x] Agree to use Sched for organizing the program page
- [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel
  - **Stephen Augustus (`@justaugustus`)**
  - **Ralph Squillace (`@ralph`)**
  - **Paul Burt (`@pburt`)**
  - **Dan Papandrea (`@POP`)**
  - **Ariel Jatib (`@ariel`)**

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

### Organizers

- **Stephen Augustus**, VMware, Lead, Cloud Native Developer Strategy, stephen@agst.us
- **Ralph Squillace**, Microsoft, Principal Program Manager, Azure Cloud Native Upstream, ralph.squillace at microsoft.com
- **Paul Burt**, NetApp, Technical Product Marketing Engineer, paul.burt at netapp dot com
- **Dan Papandrea**, Field CTO, Sysdig, pop@sysdig.com
- **Ariel Jatib**, NetApp, Business Development - Cloud Native, ariel.jatib at netapp dot com

### Sponsors

- VMware
- Microsoft
- NetApp
- Sysdig

**Comment by justaugustus** [comment]
FYI: @dankohn
I'll work on coordinating additional sponsors.

@pgburt @arieljatib -- want to work on this together?

**Comment by squillace** [comment]
Organizer 2: First and Last Name, Company, Title, Email
Ralph Squillace, Microsoft, Principal Program Manager, Azure Cloud Native Upstream, ralph.squillace at the microsoft.com.

**Comment by justaugustus** [comment]
@squillace -- Let's do this!

**Comment by squillace** [comment]
HONK

**Comment by squillace** [comment]
OK, boomer, let's dance.

**Comment by pgburt** [comment]
HONK
Organizer 3: First and Last Name, Company, Title, Email

**Comment by danpopSD** [comment]
Organizer or Sponsor
POP and Sysdig wants in...
Dan Papandrea, Sysdig pop@sysdig.com

**Comment by ams0** [comment]
This is one not to be missed! @squillace and @arieljatib both were at KCD Amsterdam 2019, count on us for previous experience (and you're all invited to Amsterdam 2020 of course!)

**Comment by KTan1226** [comment]
Great start @justaugustus. Can you confirm the fiscal sponsor?

**Comment by danpopSD** [comment]
@KTan1226 is there a sponsorship fee being discussed?

**Comment by arieljatib** [comment]
@justaugustus - let's go. :)

Organizer 4: First and Last Name, Company, Title, Email
Ariel Jatib, Netapp, ariel.jatib at netapp dot com

**Comment by squillace** [comment]
@justaugustus who is the fiscal sponsor, or shall you and I and @karenhchu have a chat?

**Comment by arieljatib** [comment]
@KTan1226 - can you define the criteria for the fiscal sponsor requirement? For AMS, there were several sponsors. 

@ams0 - I recall you showed me a really great repo you all used for organizing the wonderful event in Amsterdam. It included a bunch of good insight into how the business of the event was managed - e.g. I recall you all set up a discrete entity. Could you link up the repo here?

@squillace @karenhchu - please include @pgburt @danpopSD and myself on the thread / chat. I'll be offline through the 11th and can get updates from Paul as necessary.

**Comment by squillace** [comment]
All in! Let's do this together. :-)

**Comment by dankohn** [comment]
There are two separate requirements:
1. You need 3 sponsors, that is companies that have agreed to sponsor.
2. You need a fiscal sponsor, meaning a company with a bank account that is able to collect money (from sponsors and registration) and pay it out (for venue, catering, etc.)

**Comment by squillace** [comment]
Thanks Dan!

**Comment by ams0** [comment]
Yes, in Amsterdam we used an escrow company (they also helped with the general organisation) that issued all invoices and paid all suppliers. Also avoids potential conflict of interests between organisers and their employers.

**Comment by jberkus** [comment]
@ams0 huh!  I wonder if such things exist in the USA.  What was the company's name?

**Comment by dankohn** [comment]
@jberkus DevOpsDays recommends two such services that you are welcome to use: https://devopsdays.org/organizing/#handling-money

However, I believe each charges around ~10% and so we would generally recommend getting a company to agree to act as fiscal sponsor, if possible.

**Comment by squillace** [comment]
Definitely Microsoft will be at least one fiscal sponsor here, but we should get together and decide how to run it together!

**Comment by squillace** [comment]
@justaugustus @pgburt @danpopSD @arieljatib shall we scheduled a virtual or physical chat to see where we're all at on this? What are we thinking about timing, venues, cost/features, and so on?

**Comment by danpopSD** [comment]
yes plz...  virtual first,  then physical?  im pretty free tomorrow.  (fridays slammed).

**Comment by squillace** [comment]
sounds fine to me. Let's hear from the others. I'm free tomorrow basically 11-3, and 4-6 I think.

**Comment by danpopSD** [comment]
free tomorrow 12-1PM

**Comment by danpopSD** [comment]
@justaugustus @pgburt ,  should we take this to slack?

**Comment by justaugustus** [comment]
First meeting held today to discuss themes, content, messaging, sizing, etc.
We'll get a recurring meeting on the calendar as well for the new year.

**Comment by arieljatib** [comment]
Initial research into venues - added to the working notes Google doc. It's linked up in Slack.

**Comment by KTan1226** [comment]
Great! I've added all organizers to the Slack channel (for KCD organizers) and will create your email alias. You are approved to create your site. Let me know if you have any questions in the interim.

**Comment by KTan1226** [comment]
Hi NYC team! Just checking in, how is your website coming along? Would you like some extra support? Happy to help- just let me know.

**Comment by justaugustus** [comment]
@KTan1226 -- It's on the list, but nothing yet. Will give a holler if we need an assist! :)

**Comment by xmulligan** [comment]
@justaugustus We are relaunching the KCD program, including virtual events. We would love to have one in New York if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
