### ISSUE TITLE
KCD 2020 Paris, France

### ISSUE THREAD

**Issue by rbenzair** [cncf/kubernetes-community-days#213]
### Event: 
City: Paris, France
Venue:  https://stationf.co/venues/
Date: 4th or 6th November (to confirm soon).

### Organizer 7:  Christophe Gasmi, D2SI, Consultant DevOps, rekcah78@gmail.com

3 active CNCF Paris meetup organizer in Paris and 2 CNCF ambassadors.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel

We still are looking for a sponsor or other  Organizer before to lock the date during 2020.

### Method of accepting payment
The CNCF Paris non-profit organization have a Bank Account (bank transfer preferred).

**Comment by dankohn** [comment]
Great start. Please add a 4th organizer from a different company (we want 3 different companies represented).

**Comment by rbenzair** [comment]
hi @dankohn i fixed.

**Comment by KTan1226** [comment]
Great @rbenzair. Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by rbenzair** [comment]
fine @KTan1226 , we are focusing to identify the potential sponsors.

**Comment by rbenzair** [comment]
list potential sponsor to be confirmed: Scality, OVH

**Comment by gclem** [comment]
About OVH as Sponsor, feel free to reach me @rbenzair

**Comment by KTan1226** [comment]
I've added you to the KCD-organizers Slack channel @rbenzair. Can you share the Slack usernames for the additional organizers? Thanks!

**Comment by rbenzair** [comment]
hi @KTan1226  can you add all the  organizers on the  KCD-organizers Slack channel. Thanks

**Comment by KTan1226** [comment]
Hi @rbenzair- sure thing. I just added all organizers. Thanks!

**Comment by clook** [comment]
Hi, really pleased to find this "issue"! (Thanks for the pointer @jcsirot)
Would love to give a hand in any way if needed.

**Comment by KTan1226** [comment]
Hi @rbenzair- can you please confirm your third sponsor? Also, who is your fiscal sponsor for the event? Once you confirm, I will approve for you to begin building your website and share your email alias. Thanks!

**Comment by rbenzair** [comment]
hi @KTan1226  we are working to close the third sponsor and the venue.

**Comment by rbenzair** [comment]
Hi @KTan1226  as i answer :
All team under CNCP The CNCF Paris non-profit organization created on 2016. As non-profit organization, we have a Bank Account (bank transfer preferred) and we will be able to manage the invoices and fiscal.

**Comment by KTan1226** [comment]
Sounds good @rbenzair. Did you confirm your third sponsor? Once you do, I can sign off on creating your site and create your email alias.

**Comment by rbenzair** [comment]
hi @KTan1226  the event moving forward, i update the PR all the conditions were checked.  We find the venue and date, we are on the stage of the sponsoring.

**Comment by KTan1226** [comment]
Hi KCD Paris team! Please use the aliases below:
- organizers-paris@kubernetescommunitydays.org (for organizer communications)
- sponsors-paris@kubernetescommunitydays.org (for potential sponsors, email forwards to organizer alias)

I've also sent an email with details on how to access your CFP and admin access to SM Apply.  Please let me know if you have any questions. Thanks!

**Comment by xmulligan** [comment]
@rbenzair Are you still planning on having an event in 2021? We will shortly be updating the program and I didn't want to close this issue if you are still actively working on it.

**Comment by xmulligan** [comment]
@rbenzair We are relaunching the KCD program, including virtual events. We would love to have one in Paris if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by xmulligan** [comment]
Awesome! Looking forward to speaking with you
