### ISSUE TITLE
KCD 2020 - São Paulo, SP, Brasil

### ISSUE THREAD

**Issue by rikatz** [cncf/kubernetes-community-days#214]
If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Event City: São Paulo, SP, Brasil

Once you have identified your 3 organizers and 3 sponsors, please complete the information below and update your issue.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

### Method of accepting payment
Credit Card (via EventBrite, Probably)

**Comment by pasimoes** [comment]
I am want to participate as organizer.. please let’s talk about.

**Comment by KTan1226** [comment]
Great start @rikatz. Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by rikatz** [comment]
@KTan1226 tks. We're going to make a kickoff with the Organizers next week to check what's missing, distribute tasks and so.

Will keep you posted

**Comment by jhonatanmorais** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

My username on CNCF Slack is **jhonatancmorais**.

**Comment by rmedivh** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

My username on CNCF Slack is **rmedivh**

**Comment by s4rd1nh4** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

My username on CNCF Slack is s4rd1nh4

**Comment by nullck** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

My username on CNCF Slack is nullck.

**Comment by duboc** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

My username on CNCF Slack is duboc.

**Comment by yagonobre** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

My username on CNCF Slack is yago.

**Comment by rikatz** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

My username on CNCF Slack is rpkatz

@KTan1226 As almost everyone signed to the COC and the event guideline I would like to ask to invite us to the Slack Channel, as We have some questions (mainly about the financial stuff) and would like to share them and see if other organizers have some insights :)

Thank you!!!

**Comment by KTan1226** [comment]
Sure thing @rikatz- I've added you and all organizers.

**Comment by xmulligan** [comment]
@rikatz We are relaunching the KCD program, including virtual events. We would love to have one in Sao Paulo if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
