### ISSUE TITLE
KCD 2020 - Looking for more Organizers - Dublin, Ireland

### ISSUE THREAD

**Issue by estebangarcia** [cncf/kubernetes-community-days#215]
I want to express my interest in organizing a KCD event.

Event City: Dublin, Ireland
Organizer 1: Esteban Garcia, Synchronoss Technologies, Deployment Architect, estu91@gmail.com
Organizer 2: Michael Hausenblas, AWS, Developer Advocate, michael.hausenblas@gmail.com
Organizer 3: Ryan Craig, JP Morgan Chase, DevOps Engineer, ryandpcraig@gmail.com
Organizer 4: Chris Kranz, Sysdig, Principal Sales Engineer for EMEA, chris.kranz@sysdig.com

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [ ] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel
  * Esteban Garcia (@esteban.garcia)
  * Michael Hausenblas (@michael.hausenblas)
  * Ryan Craig (@ryan.craig)
  * Chris Kranz (@chris.kranz)

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

**Comment by KTan1226** [comment]
Welcome @estebangarcia! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by mhausenblas** [comment]
As mentioned on Slack, I'm happy to serve on the OC and we can check the "One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer" as well since I'm an Ambassador ;)

**Comment by estebangarcia** [comment]
We have our third organizer :D

**Comment by xmulligan** [comment]
@estebangarcia We are relaunching the KCD program, including virtual events. We would love to have one in Dublin if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
