### ISSUE TITLE
KCD 2021 - Quebec city, Canada

### ISSUE THREAD

**Issue by mathieu-benoit** [cncf/kubernetes-community-days#217]
### Organizer 1: 
Mathieu Benoit, **Google**, Customer Engineer, mathieu-benoit[at]hotmail[dot]fr / Slack: mathieu-benoit / GitHub: @mathieu-benoit

### Organizer 2: 
Sébastien Couturier, **Victrix**, Solution Architect, sebcouturier[at]gmail[dot]com / Slack: sebastien-couturier / GitHub: @scouturier

### Organizer 3: 
Sébastien Thomas, **Tetrate**, Customer Reliability Engineer, prune[at]lecentre[dot]net / Slack: TBD / GitHub: @prune998

### Organizer 4: 
Martin Guy Lapointe, **SSQ Insurance**, DevOps Architect, ipnextgen[at]gmail[dot]com / Slack: MartinGL / GitHub: @ipnextgen

### Organizer 5: TBD
Ayrat Khayretdinov, **CNCF Ambassador**, ayrat[dot]khayretdinov[at]gmail.com / Slack: archyufa / GitHub: @archyufa

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [X] Method to accept payments including sponsorships and payout expenses
* [X] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [X] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 3 sponsors
* [X] Each organizer needs to live in or just outside of the KCD location
* [X] No other Kubernetes Community Days event in the same city
* [X] Agree to use Eventbrite for registration
* [X] Agree to use Sched for organizing the program page
* [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel

### Sponsor 1
**[Microsoft](https://microsoft.com)** (venue/gold)
### Sponsor 2
**[RedHat](https://redhat.com)** (bronze)
### Sponsor 3
**[iA Financial Group](https://ia.ca)** (bronze)
### Sponsor 4
**[Lecentre.net Inc.](http://www.lecentre.net)**

### Method of accepting payment
Throughout our Financial Sponsor Lecentre.net Inc.

**Comment by KTan1226** [comment]
Welcome @mathieu-benoit! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by dmueller2001** [comment]
@dmueller2001 is willing to be a co-organizer

**Comment by dankohn** [comment]
@dmueller2001 we ask organizers to live in or just next to the city, so we’d encourage you to do one in Vancouver.

**Comment by mathieu-benoit** [comment]
Hi @KTan1226 and @dankohn, great news, we now have 4 co-organizers and 3 sponsors (more to come). We will discuss soon with the co-organizers which method of payment we will use, in the meantime could you confirm what are you expected from us regarding "All organizers signed off to the event guidelines and CNCF Code of Conduct."? Thanks!

**Comment by KTan1226** [comment]
Hi @mathieu-benoit. Can you confirm the fiscal sponsor (company that will accept payments)? 

For the event guidelines and Code of Conduct, we need all organizers to review and agree to them. Once complete, I will add all organizers to the KCD organizers Slack channel. Thanks!

**Comment by mathieu-benoit** [comment]
@KTan1226, just to make sure with what you mean by "fiscal sponsor", there is going to have one sponsor which will receive all the payments from the other sponsors for example and will pay the different invoices involved for that event, is that correct? Sorry, we are not clear here how it works... Thanks for your clarification.

**Comment by KTan1226** [comment]
Hi @mathieu-benoit. Yes, there needs to be a sponsor that will receive all payments. In most cases, this is a company that one of the organizers is from. 

Here is a link for the Code of Conduct (including events): https://github.com/cncf/foundation/blob/master/code-of-conduct.md

Thanks!

**Comment by mathieu-benoit** [comment]
Hi @KTan1226, we, as the organizers of this KCD 2020 Quebec city, reviewed and we agree with the CNCF Code of Conduct.

Regarding our Financial Sponsor to receive all the payments and pay the invoices associated to this event we have the confirmation by our Sponsor Lecentre.net Inc.

So I think we are good, just let us know if you need any complementary information. Thanks.

**Comment by KTan1226** [comment]
Great @mathieu-benoit- you are approved to create your site. I've added all organizers to the KCD organizers channel on Slack and will be in touch with your email alias.

Let us know if you have any questions!

**Comment by KTan1226** [comment]
FYI- Mathieu created a private channel on Slack #kcd-quebec for the organizers.

**Comment by mathieu-benoit** [comment]
Good news, we have @archyufa joining us as co-organizer!

**Comment by xmulligan** [comment]
@mathieu-benoit Are you still planning on having an event in 2021? We will shortly be updating the program and I didn't want to close this issue if you are still actively working on it.

**Comment by mathieu-benoit** [comment]
Hi @xmulligan, thanks for asking, we are targeting to do it in 2021 if an in-person conference in possible. But we don't what the future will be on this... We currently have a random date on July 2021: https://kubernetescommunitydays.org/events/2021-quebeccity/ but will be likely adjusted depending on the pandemic situation.
Hope that makes sense, and maybe you could close this issue since we created the event?
