### ISSUE TITLE
Kubernetes Community Days - Roma

### ISSUE THREAD

**Issue by ndecandia** [cncf/kubernetes-community-days#218]
If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Organizer 1: Nicola Marco Decandia, Desotech S.r.l., CEO, n.decandia@desotech.it 

Once you have identified your 3 organizers and 3 sponsors, please complete the information below and update your issue.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [ ] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [X] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [X] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 3 sponsors
* [X] Each organizer needs to live in or just outside of the KCD location
* [X] No other Kubernetes Community Days event in the same city
* [X] Agree to use Eventbrite for registration
* [ ] Agree to use Sched for organizing the program page
* [] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

**Comment by KTan1226** [comment]
Great start @ndecandia. Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by genbutsu** [comment]
COMPANY: Genchi Genbutsu SRL as a sponsor, if we get in contact...

**Comment by ndecandia** [comment]
Hello,
sure, please give me your contact, I will update you.

Nicola Marco Decandia
Desotech S.r.l.

**Comment by genbutsu** [comment]
I've mailed you from diego@genchi-genbutsu.io

**Comment by ndecandia** [comment]
> I've mailed you from [diego@genchi-genbutsu.io](mailto:diego@genchi-genbutsu.io)

I will send you some documents ASAP.
