### ISSUE TITLE
KCD 2020 Belo Horizonte, MG, Brasil

### ISSUE THREAD

**Issue by pasimoes** [cncf/kubernetes-community-days#219]
If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [x] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

### Method of accepting payment
Credit Card (via EventBrite, Probably)

### Date and Venue
Date: 13 Jun 2020
Venue: PucMinas Savassi

**Comment by andrealmar** [comment]
my Slack handle is **@andrealmar**

**Comment by KTan1226** [comment]
Great start @pasimoes. Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by andrealmar** [comment]
@KTan1226 how do we sign off to the event guidelines and CNCF Code of Conduct?

**Comment by KTan1226** [comment]
Hi @andrealmar- Please have each organizer review the guidelines and CNCF Code of Conduct first. If all organizers agree to both, please check off the first box in the checklist to confirm.

**Comment by pasimoes** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by andrealmar** [comment]
I Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by umbertoss** [comment]
my Slack handle is @Marcelo Umberto Ferreira Da Silva

**Comment by umbertoss** [comment]
I Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by amandabhmg** [comment]
I Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by KTan1226** [comment]
@andrealmar Great! You are approved to create your website. I will be in touch with your email aliases (for sponsors and organizers) as well as information to get you up and running with the CFP tool SM Apply.

Are you planning to create a Twitter account for your event?

**Comment by andrealmar** [comment]
Hi @KTan1226 thank you. Yes we are planning to create the social network accounts for the event. @amandabhmg is taking care of this.

**Comment by pasimoes** [comment]
Hi @KTan1226 we will build our site . Thank you.

Our Twitter is 
https://twitter.com/bh_kcd

**Comment by Jeskz0rd** [comment]
I Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by Zandler** [comment]
I Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by KTan1226** [comment]
Hello! Please use the following aliases:
- organizers-belo@kubernetescommunitydays.org (for organizer communications)
- sponsors-belo@kubernetescommunitydays.org (for potential sponsors, forwards to organizer alias)

I will send a test now and instructions on how to get set up with the CFP. Let me know if you have any questions in the interim!

**Comment by andrealmar** [comment]
Hi @KTan1226 may I give a suggestion?

On DevOps Days Belo Horizonte the previous alias was `organizers-belo-horizonte@devopsdays.org` but they changed to `belo-horizonte@devopsdays.org`. 

What do you think? Can you change to `belo-horizonte@kubernetescommunitydays.org` ?

Thank you

**Comment by KTan1226** [comment]
Hi @andrealmar- Thanks for the feedback. I've changed your aliases to:
- organizers-belohorizonte@kubernetescommunitydays.org
- sponsors-belohorizonte@kubernetescommunitydays.org

I will delete the old alias. Let me know if you have any questions! cc @pasimoes

**Comment by andrealmar** [comment]
Hi @KTan1226 it is possible that we have just ONE alias? `belo-horizonte@kubernetescommunitydays.org` ?

**Comment by xmulligan** [comment]
@pasimoes We are relaunching the KCD program, including virtual events. We would love to have one in Belo Horizonte if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
