### ISSUE TITLE
KCD 2020 Porto Alegre, RS, Brasil

### ISSUE THREAD

**Issue by pasimoes** [cncf/kubernetes-community-days#220]
If you do not have your team assembled, please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well. Continue to update the issue when you add new organizers and sponsors until you are ready to commit to hosting, then complete the submission checklist below. 

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [ ] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [x] One organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Minimum of 3 sponsors
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel

**Please include all the organizers following the format specified. At a minimum, you must have 3 organizers from 3 different organizations, and 3 sponsors.**

### Method of accepting payment
Credit Card (via EventBrite, Probably)

**Comment by KTan1226** [comment]
Welcome @pasimoes. Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by pasimoes** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by pasimoes** [comment]
> Welcome @pasimoes. Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

We are working hard to complete all the items! Thank you Kristi.

**Comment by somatorio** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by csdiedrich** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by rcazambuja** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by amioranza** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by xmulligan** [comment]
@pasimoes We are relaunching the KCD program, including virtual events. We would love to have one in Porto Alegre if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
