### ISSUE TITLE
KCD 2020 Florianópolis, Santa Catarina - Brazil

### ISSUE THREAD

**Issue by B0go** [cncf/kubernetes-community-days#223]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application and ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] All organizers signed off to the event guidelines and CNCF Code of Conduct.
* [ ] Method to accept payments including sponsorships and payout expenses
* [x] At least one organizer is a CNCF Member employee, Ambassador, or CNCF Project Maintainer
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Minimum of 3 sponsors identified
* [x] Each organizer needs to live in or just outside of the KCD location
* [x] No other Kubernetes Community Days event in the same city
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Share Slack usernames (on [CNCF Slack](https://slack.cncf.io/)) for all organizers so that we can add you to the #kcd-organizers channel

**Comment by B0go** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by B0go** [comment]
> Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

 @caarlos0 @merencia @diogonicoleti @kassyuz @cleberwarmling

**Comment by pasimoes** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by caarlos0** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by cleberwarmling** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by diogonicoleti** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

Slack display name: Diogo Nicoleti

**Comment by merencia** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

Slack display name: Lucas Merencia

**Comment by kassyuz** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

Slack display name: Cassio Moreto

**Comment by KTan1226** [comment]
Great start @B0go. Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by xmulligan** [comment]
@vijay938 I would check with @pasimoes and join https://cloud-native.slack.com/archives/C01NL9M5HPG for further discussion

**Comment by B0go** [comment]
I am still interested in organizing this KCD here in Santa Catarina, but I need to restart conversations with the other organizers and CNCF in order to understand the current COVID-19 scenario (will other events be online?)

I apologize for taking this long to update this issue

**Comment by xmulligan** [comment]
@B0go we will be updating the program shortly, look for the annoucement

**Comment by xmulligan** [comment]
@B0go We are relaunching the KCD program, including virtual events. We would love to have one in Florianopolis if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
