### ISSUE TITLE
Kubernetes Community Day 2020 - Naples, Italy

### ISSUE THREAD

**Issue by ppatierno** [cncf/kubernetes-community-days#228]
We are expressing the interest of organizing a Kubernetes Community Day in Naples, Italy.

Planned is September 2020.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Method of accepting payment

Bank transfer

**Comment by KTan1226** [comment]
Welcome, @ppatierno! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by ppatierno** [comment]
@KTan1226 it's not clear to me which usernames you need for CNCF Slack. I am already registered (even if with my personal email) and I am already in the #kcd-formation channel. The Slack registration needs emails, not usernames. Can you clarify, please?

**Comment by KTan1226** [comment]
Hi @ppatierno- Apologies for the confusion. I just checked and it looks like you are already a member of the #kcd-organizers Slack channel. Can you please share the usernames for your other organizers? I'm happy to add them as well.

**Comment by ppatierno** [comment]
@KTan1226 not a Slack expert but I am confused about the term "username" ... you would need the email they use with Slack? Isn't CNCF Slack open to register using https://slack.cncf.io/ ?

**Comment by KTan1226** [comment]
@ppatierno No problem, I'll direct message you on Slack so we can resolve in real time.

**Comment by jberkus** [comment]
Please add Red Hat as a third sponsor.

**Comment by ppatierno** [comment]
@KTan1226 what's the next step? I think we filled all the information in the checklist.

**Comment by KTan1226** [comment]
Hi @ppatierno- can you confirm who the fiscal sponsor that will accept payments will be?

**Comment by ppatierno** [comment]
Hi @KTan1226 I can confirm that we have one of the local user group (NaLUG, the Linux User Group) organizing the event which can receive payments from sponsors. Anyway here sometimes happens that sponsors pay stuff directly (i.e. the venue or the catering). Btw there is no problems in either ways.

**Comment by KTan1226** [comment]
Hi @ppatierno- The fiscal sponsor needs to be a company that agrees to accept payments and has a bank account to distribute funds as well. In most cases, the fiscal sponsor is the company one of the organizers is from. Thanks!

**Comment by ppatierno** [comment]
@KTan1226 sorry, this company should accept payments from who? from other companies? Regarding the event fee, I think that we are going to deliver it for free to the attendees. It's quite difficult here that people pay for events.

**Comment by ppatierno** [comment]
@KTan1226 why it has to be a company? The NaLUG user group has a bank account for getting payment and then distribute funds for paying the venue, lunch, etc etc.

**Comment by ppatierno** [comment]
@KTan1226 any feedback on my comments?

**Comment by dankohn** [comment]
It may be possible for NaLUG to be your fiscal sponsor. The key thing is a bank account so they can receive money from sponsors and pay it to the venue, catering, and other vendors.

**Comment by ppatierno** [comment]
@dankohn yes yes, NaLUG has a bank account to receive money and pay for the rest. For this reason, I was asking why it should have been a company.

**Comment by dankohn** [comment]
There's no need for it to be a company; that's just the most common case.

**Comment by ppatierno** [comment]
@dankohn ok thanks! @KTan1226 so I guess that we are all set :-)

**Comment by KTan1226** [comment]
Great @ppatierno! You are approved to build your website. I will be in touch with an email alias for your use. Are you planning to create a Twitter account for your KCD?

**Comment by ppatierno** [comment]
@KTan1226 Yes I thought about creating a Twitter account for that. Maybe I can use the email alias you are setting up?

**Comment by KTan1226** [comment]
Hi @ppatierno- apologies for the delay! Yes, you can absolutely use the email alias to set up the Twitter account. I would recommend something like @KCD-Naples if its available. Let me know if you need any help.

**Comment by ppatierno** [comment]
@KTan1226 so the email alias to use is the one all the organizers got a verification email from you? If I use that one I think I should have access to the inbox because the process of creating a new Twitter account.

**Comment by KTan1226** [comment]
Yes @ppatierno that is correct. The alias is: organizers-naples@kubernetescommunitydays.org.

**Comment by ppatierno** [comment]
@KTan1226 but how I can get access to the inbox? I am pretty sure that if I use it for creating the twitter account I will get an email with a confirmation link to click. So I guess you should provide organizers the way (password?) to access the mailbox for this alias.

**Comment by KTan1226** [comment]
Hi @ppatierno! If you use the alias for your account, it should automatically send you the verification email (as you are on the alias). If you would like to test it or have additional questions, feel free to ping me on Slack and I can help.

**Comment by ppatierno** [comment]
@KTan1226 may I ask what's the timeframe to have the website available and the others platform for handling C4P and attendees?

**Comment by KTan1226** [comment]
Hi @ppatierno. How is your website coming along? Is there something we can help with? We recommend submitting the PR of your website for approval before gaining access to the CFP tool. Happy to chat live as well if you have any questions.

**Comment by ppatierno** [comment]
@KTan1226 ok so I misunderstood :) I understood that your team was in charge to setting up the website for us, but it seems not to be the case. Is there any guide, template, repo we can starting from in order to have same template as other KCDs?

**Comment by KTan1226** [comment]
No problem @ppatierno. We have a guide for creating your website here: https://kubernetescommunitydays.org/organizing-creating-website/. If you have any questions or get stuck, just let me know and we're happy to help. Thanks!

**Comment by xmulligan** [comment]
@ppatierno We are relaunching the KCD program, including virtual events. We would love to have one in Naples if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
