### ISSUE TITLE
Kubernetes Community Day 2020 - Portland, Oregon

### ISSUE THREAD

**Issue by ahpook** [cncf/kubernetes-community-days#230]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event City:

Portland, Oregon

### Submission checklist:

*Please check each of these as you complete them:

* [ ✅] No other Kubernetes Community Days event in the same city
* [ ✅] Minimum of 3 organizers from 3 different organizations
* [ ✅] Each organizer lives in or just outside of the KCD location
* [ ✅] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ✅] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ✅] Minimum of 3 sponsors committed
* [✅ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [ ✅] Agree to use Eventbrite for registration
* [ ✅] Agree to use Sched for organizing the program page
* [ ✅] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
Eric Sorenson, Puppet Inc, Technical Product Manager, eric@puppet.com, eric.sorenson
### Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username
Josh Berkus, Red Hat, Kubernetes Community Manager, jberkus@redhat.com, jberkus
### Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username
Aaron Schlesinger, Microsoft, Cloud Advocate, aaron@ecomaz.net, Aaron Schlesinger

### Sponsor 1
Puppet
### Sponsor 2
Red Hat
### Sponsor 3
Microsoft

### Fiscal sponsor that will accept payments
Red Hat

**Comment by KTan1226** [comment]
Welcome @ahpook! Excited to see KCD come to the Rose City (my hometown). Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by jberkus** [comment]
Hey, I'm Josh Berkus, CNCF ambassador, and lead of Cloud Native PDX meetup.  I'll be co-organizing KCDPDX.

I am also Red Hat's Kubernetes Community Manager, so Red Hat is on board as one of the sponsors.

**Comment by jberkus** [comment]
I've checked with our Events organization, and Red Hat is prepared to be fiscal sponsor for this event.  However, that has to be acceptable to the other sponsors, so let's wait on choosing that until we have all three sponsors.

**Comment by arschles** [comment]
Hi, I'm Aaron, Cloud Advocate at Microsoft focusing on Kubernetes and Cloud Native technologies. I'll be the third organizer of KCDPDX.

**Comment by arschles** [comment]
I am unable to edit the original post directly, so posting here. Microsoft has committed to being sponsor 3

**Comment by ahpook** [comment]
@arschles great! i updated the issue.

**Comment by jessedearing** [comment]
Hi all. I'd love to help organize it as well.

I'm an SRE at VMware and I'll check with VMware about sponsorship as well.

**Comment by KTan1226** [comment]
Great work @jberkus! You are approved to create your site. I just added all organizers to the KCD-organizers Slack channel and will be in touch shortly with your email alias.

**Comment by lucperkins** [comment]
@jberkus @ahpook I work under the CNCF and live in Portland. Happy to help out any way I can!

**Comment by jberkus** [comment]
@lucperkins I forgot that you were local!  I expect we're gonna ask you for a CNCF panel if nothing else ;-)

**Comment by lucperkins** [comment]
@jberkus I specifically asked to get roped into this, so rope away! 🤣

**Comment by xmulligan** [comment]
@ahpook We are relaunching the KCD program, including virtual events. We would love to have one in Portland if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
