### ISSUE TITLE
KCD 2020 Madrid, Spain

### ISSUE THREAD

**Issue by raelga** [cncf/kubernetes-community-days#231]
### Event City:

Madrid, Spain, 2020

### Submission checklist:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Organizer 1

**Rael Garcia Arnés**, Red Hat, Senior Software Engineer, rael@redhat.com, `rael`

### Organizer 2

**Rafael Fernández López**, SUSE, Architect, rfernandezlopez@suse.com, `ereslibre`

### Organizer 3

**Ángel Barrera Sánchez**, SIGHUP, Kubernetes Engineer, angel@sighup.io, `AngelBarrera`

### Sponsor 1

**Red Hat**, https://www.redhat.com

### Sponsor 2

**SIGHUP**, https://sighup.io

### Sponsor 3

SUSE, https://www.suse.com

### Fiscal sponsor that will accept payments

**Red Hat**, https://www.redhat.com

**Comment by jberkus** [comment]
Red Hat will sponsor KCD Madrid.

Also, Red Hat is prepared to act as a fiscal sponsor for this event if needed.  Thanks to Fedora, we have financial workflows set up to handle 3rd-party sponsorships and event expensese.

**Comment by raelga** [comment]
Thank you very much @jberkus for stepping in, first sponsor added. :tada:

**Comment by angelbarrera92** [comment]
SIGHUP will sponsor KCD Madrid.

Thanks @jnardiello

**Comment by KTan1226** [comment]
Welcome @raelga! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by gusraggio** [comment]
Some sponsors are asking how leads will be handle to them ? will this be the same as kubecon or should be sorted out by the local organization ?

**Comment by gusraggio** [comment]
SUSE will sponsor

**Comment by raelga** [comment]
We got the third sponsor, thanks @gusraggio and @ereslibre ! 🎉 

We're staring building the website https://madrid2020.k8scd.es/ and forming the event team [Build Kubernetes Community Day Madrid 2020 Team](https://github.com/kcd-es/madrid-2020/issues/1).

**Comment by KTan1226** [comment]
Sounds good @raelga. You are approved to build your site. Let us know if you have any further questions along the way!

**Comment by raelga** [comment]
Thanks @KTan1226, already working on it.

**Comment by xmulligan** [comment]
@raelga We are relaunching the KCD program, including virtual events. We would love to have one in Madrid if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by raelga** [comment]
Hey @xmulligan, we are working on the virtual event already! 

Happy to reach you once we have a date.

**Comment by xmulligan** [comment]
Perfect! Looking forward to it and let me know if you need any help along the way
