### ISSUE TITLE
KCD 2020 Seattle, Washington

### ISSUE THREAD

**Issue by ericknauer** [cncf/kubernetes-community-days#233]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [ ] Minimum of 3 organizers from 3 different organizations
* [ ] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [ ] Agree to use Eventbrite for registration
* [ ] Agree to use Sched for organizing the program page
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

**Comment by KTan1226** [comment]
Welcome @ericknauer! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by rbitia** [comment]
Microsoft can also sponsor the Seattle meetup and I can be listed as a Organizer. LMK :)

**Comment by dingyin** [comment]
Futurewei would like to be a sponsor of KCD 2020 Seattle. I can be listed as an Organizer.

**Comment by dingyin** [comment]
My account in CNCF Slack is dingyin@gmail.com

**Comment by iennae** [comment]
@ericknauer you want to talk to @dingyin and @rbitia about organizing? Looks like 3 different sponsors and 3 individuals from different organizations with them volunteering.

**Comment by xmulligan** [comment]
@ericknauer We are relaunching the KCD program, including virtual events. We would love to have one in Seattle if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
