### ISSUE TITLE
KCD 2020 Boston, MA

### ISSUE THREAD

**Issue by izgeri** [cncf/kubernetes-community-days#237]
### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [ ] Minimum of 3 organizers from 3 different organizations
* [ ] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [ ] Agree to use Eventbrite for registration
* [ ] Agree to use Sched for organizing the program page
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

**Comment by KTan1226** [comment]
Welcome @izgeri! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by danpopSD** [comment]
Hi John and Geri,  Sysdig would also like to help organize/sponsor @rrs8 (Rich Schofield from our field engineering team)

**Comment by bettyjunod** [comment]
Hi John and Geri,  Solo.io would also like to help organize.. our HQ is in Cambridge

**Comment by bettyjunod** [comment]
Hey @izgeri WDYT about @danpopSD and my comments? Do you want to set up a quick chat with us and our teams?

**Comment by izgeri** [comment]
@bettyjunod that sounds great. Sometime next week at the earliest would be good, there are a couple of people I'd like to include who are traveling right now.

@bettyjunod @rrs8 @danpopSD can you please share your contact info in the format from above (**First and Last Name, Company, Title, Email, CNCF Slack Username**) and I can get in touch via email with an invite. Please also lmk if there are days / times that work better for you - here or in slack is fine. I look forward to speaking with you all! Thanks for the ping, @bettyjunod :)

**Comment by jonasrosland** [comment]
Hi folks!

I'd be happy to help out as an organizer, I'm at VMware, a CNCF Member company. I also co-organize the Boston Cloud Native Meetup, which is a CNCF-owned meetup.

**Comment by rrs8** [comment]
Hi @izgeri - Rich Schofield, Sysdig, Solution Architect, rich@sysdig.com, @schofr

**Comment by bettyjunod** [comment]
Betty Junod, Solo.io, VP Marketing, betty.junod@solo.io, @bettyjunod

**Comment by bettyjunod** [comment]
@izgeri confirming that you'll be sending invite or do you want me to? flex either way

**Comment by izgeri** [comment]
@bettyjunod sent! It was one of the time windows you said worked for you. I look forward to speaking with you!

**Comment by lauren-sysdig** [comment]
Lauren Hernandez, Sysdig, Field Marketing Manager, lauren@sysdig.com, @lauren-sysdig

**Comment by izgeri** [comment]
Note: we had an initial meeting on 1/23 with the people who've commented on the issue so far in attendance. We are still looking for additional people to agree to organize and/or sponsor this event. Please comment if you are also interested in being involved! We are due to meet again and check in on status today.

**Comment by xmulligan** [comment]
@izgeri We are relaunching the KCD program, including virtual events. We would love to have one in Boston if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
