### ISSUE TITLE
KCD 2020 Bern, Switzerland

### ISSUE THREAD

**Issue by jogy** [cncf/kubernetes-community-days#238]
### Submission checklist:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [ ] Agree to use Eventbrite for registration - _we want to use ti.to (know-how & experience)_
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Organizer 1

Johann Gyger, Levingo, CNCF Ambassador, johann.gyger@levingo.ch, Slack: \_jogy\_

### Organizer 2

Philipp Grossenbacher, La Mobiliere, philipp.grossenbacher@mobi.ch, Slack: philogros

### Organizer 3

Thomas Philipona, Puzzle ITC, philipona@puzzle.ch, Slack: tphilipona

### Organizer 4

Mathias Herzog, PostFinance, mathias.herzog@postfinance.ch, Slack: mathu

### Sponsor 1

Swisscom, https://www.swisscom.ch/en

### Sponsor 2

PostFinance, CNCF End User, https://www.postfinance.ch/en

### Sponsor 3

La Mobiliere, CNCF End User, https://www.mobiliar.ch

### Sponsor 4

Puzzle ITC, KCSP, https://www.puzzle.ch

**Many more sponsors are not definitively confirmed yet.**

### Fiscal sponsor that will accept payments

https://bernerit.rocks (Swiss nonprofit association)

**Comment by dankohn** [comment]
Thanks for this submission. A few issues:
* Events in this program need to be called Kubernetes Community Days, because CNCF has a trademark for Kubernetes, but not for Cloud Native. You're welcome to run your own Cloud Native Day event, but not as part of this program.
* Events need to host their website on https://kubernetescommunitydays.org/ rather than on a separate domain, as it allows us to track changes over time.
* The event would need to be called Kubernetes Community Days Bern (or Kubernetes Community Days Berne) as it won't (hopefully) be the only event in Switzerland.

Please let us know if you want to make these changes or if you'd rather run your own event that's not under the KCD program. Thanks.

**Comment by jogy** [comment]
Thanks @dankohn for the quick reply. We‘d love to be under the umbrella of CNCF.

A couple of questions:
* Could we co-host or double host the event under „Kubernetes Community Days Bern“, similar to KubeCon + CloudNativeCon?
* Is Eventbrite a strict requirement? What are the benefits? Does CNCF have a corporate account like Meetup Pro? Do we get support to set it up?

Apart from that I think we meet all the requirements. We are also investing a lot o personal time and passion. Additionally, we even founded a Swiss nonprofit association to handle all the legal and tax stuff in Switzerland.

PS. From the description on https://kubernetescommunitydays.org/organizing it wasn‘t clear to me that all KCD websites are going to be hosted on the same domain. Maybe this could be clarified?

**Comment by KTan1226** [comment]
Hi @jogy. Yes- your event should be titled "Kubernetes Community Days Bern." In response to your question about event management tools like Eventbrite, we are currently evaluating and will get back to you soon. 

I'd also recommend reviewing the updated FAQ: https://kubernetescommunitydays.org/organizing-faq/. Thanks!

**Comment by jogy** [comment]
We've decided to run our own Cloud Native Day event.

**Comment by KTan1226** [comment]
Best of luck @jogy! I will close the issue now.
