### ISSUE TITLE
KCD 2020 Buenos Aires, Argentina

### ISSUE THREAD

**Issue by heraym** [cncf/kubernetes-community-days#242]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [ ] No other Kubernetes Community Days event in the same city
* [ ] Minimum of 3 organizers from 3 different organizations
* [ ] Each organizer lives in or just outside of the KCD location
* [ ] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [ ] Agree to use Eventbrite for registration
* [ ] Agree to use Sched for organizing the program page
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

**Comment by KTan1226** [comment]
Hi @heraym! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.
