### ISSUE TITLE
2020 Kubernetes Community Days - Los Angeles county, CA

### ISSUE THREAD

**Issue by joshbav** [cncf/kubernetes-community-days#243]
### Event City: Los Angeles area, CA
Aiming to move locations around within LA county because.... traffic. Thus "LA area" rather than LA proper only.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [ ] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to use Eventbrite for registration
* [ ] Agree to use Sched for organizing the program page
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
Josh Baverstock, Sysdig, Field Systems Engineer, joshb+cncf@sysdig.com, <not yet>

### Sponsor 1
Sysdig

**Comment by KTan1226** [comment]
Welcome, @joshbav! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by joshbav** [comment]
I'm going to pull out as the organizer until I can confirm I have other sponsors, in order to free up the region for others. I had hoped to have at least one other confirmed by now.

**Comment by KTan1226** [comment]
Thanks for letting us know!
