### ISSUE TITLE
Multiple sponsors in one category makes the logos too small

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#249]
I'm trying to updated the 2019-amsterdam site with #248 , and as you can see in the preview here: https://deploy-preview-248--kubernetes-community-days.netlify.com/events/2019-amsterdam/sponsor/ when there are more that a few sponsor in a category (like Gold) their logos are scaled down to fit half page width. Am I missing something or is that something that can be fixed? We plan to have 10 gold sponsors for 2020-amsterdam, will be great to have a minimum size and if needed a category spanning two or more rows.

**Comment by dankohn** [comment]
Sorry for the delay. @lucperkins could you please engage on this?
