### ISSUE TITLE
Kubernetes Community Days - Tel Aviv, Israel

### ISSUE THREAD

**Issue by itaysk** [cncf/kubernetes-community-days#251]
### Submission checklist:
* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Sponsor 1
Microsoft
### Sponsor 2
Codefresh
### Sponsor 3
Aqua Security
### Sponsor 4
Spotinst
### Sponsor 5
JFrog

### Fiscal sponsor that will accept payments
Aqua Security

**Comment by itaysk** [comment]
Hi, I'm adding this issue uncompleted, as a placeholder as I am finalizing the organizing team and securing more sponsors.

**Comment by KTan1226** [comment]
Great @itaysk and welcome! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by itaysk** [comment]
@KTan1226 @iennae we are all set!

**Comment by KTan1226** [comment]
Great @itaysk! I will be in touch with your email aliases (for organizers and sponsorship), as well as an email to get your CFP set up. Are you planning to create a Twitter handle for your event?

**Comment by KTan1226** [comment]
Please use the following aliases:

- organizers-telaviv@kubernetescommunitydays.org (for organizer communication)
- sponsors-telaviv@kubernetescommunitydays.org (for potential sponsors, forwards to organizer alias)

Let me know if you have any questions!

**Comment by xmulligan** [comment]
@itaysk We are relaunching the KCD program, including virtual events. We would love to have one in Tel Aviv if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by itaysk** [comment]
Thanks for the update! Yes, definitely still interested. Will take some time to regroup with the team and see how we want to proceed

**Comment by xmulligan** [comment]
Awesome! Please feel free to reach out if you have any questions along the way
