### ISSUE TITLE
KCD 2020, Pune, India

### ISSUE THREAD

**Issue by vishal-biyani** [cncf/kubernetes-community-days#252]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [ ] Minimum of 3 organizers from 3 different organizations
* [ ] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [ ] Agree to use Eventbrite for registration
* [ ] Agree to use Sched for organizing the program page
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
Vishal Biyani, InfraCloud Technologies, CTO, vishal@infracloud.io, 
### Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username
WIP
### Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username
WIP

### Fiscal sponsor that will accept payments
InfraCloud Technologies

**Comment by KTan1226** [comment]
Welcome, @vishal-biyani! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by ashish-cognologix** [comment]
I represent @cognologix and would love to be one of the sponsors for KCD 2020, Pune. We are heavily using k8s in our project and love to give back.

**Comment by xmulligan** [comment]
@vishal-biyani We are relaunching the KCD program, including virtual events. We would love to have one in Pune if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
