### ISSUE TITLE
KCD 2020, Manchester UK

### ISSUE THREAD

**Issue by yankcrime** [cncf/kubernetes-community-days#253]
### Submission checklist:

*Please check each of these as you complete them:

* [X] No other Kubernetes Community Days event in the same city
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [X] Agree to use Eventbrite for registration
* [X] Agree to use Sched for organizing the program page
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
Nick Jones, D2iQ, Community Engineering Lead, `nick@dischord.org`, `nick`
### Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username
Matt Jarvis, D2iQ, Senior Director, Open Source Program Office, D2iQ, Matt Jarvis `matt@mattjarvis.org.uk`, `mattj`
### Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username
Danny Abukalam, SoftIron, Solutions Architect, `danny@abukalam.com`, `dabukalam`
### Organizer 4: First and Last Name, Company, Title, Email, CNCF Slack Username
Jenny Nilsen, BookingGo, Platform Engineer, `JennyNilsen@rentalcars.com`, `Jenny Nilsen`
### Organizer 5: First and Last Name, Company, Title, Email, CNCF Slack Username
Tom Riley, Nuance Communications, Senior Solutions Architect, `contact@thomasriley.co.uk`, `Riley`

### Sponsor 1
D2iQ
### Sponsor 2
Open Source Events Ltd.
### Sponsor 3
TBC

### Fiscal sponsor that will accept payments
Open Source Events Ltd.

**Comment by KTan1226** [comment]
Great start @yankcrime! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by johnstudarus** [comment]
Please put Packet down as a sponsor and send me the details!

**Comment by yankcrime** [comment]
Awesome, thanks @johnstudarus - and will do!

**Comment by xmulligan** [comment]
@yankcrime We are relaunching the KCD program, including virtual events. We would love to have one in Manchester if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
