### ISSUE TITLE
KCD 2020, Tunis, Tunisia

### ISSUE THREAD

**Issue by nzoueidi** [cncf/kubernetes-community-days#254]
### Submission checklist:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
Naeil Ezzoueidi, AWS, CNCF Ambassador and DevOps & Cloud Engineer II, `naeil@nzoueidi.com`, `nzoueidi`
### Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username
Ahmed Hosni, Vistaprint, Technology Manager, `ahmedhosni.contact@gmail.com`, `tty0`
### Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username
Mohamed Chiheb Ben Jemaa, MaibornWolff, DevOps engineer, `mohamed.chihebbenjemaa@maibornwolff.de`, `medchiheb`
### Organizer 4: First and Last Name, Company, Title, Email, CNCF Slack Username
Semah Mhamdi, Onepoint, DevOps engineer, `mhamdi.semah@gmail.com`, `mhamdi_semah`

### Sponsor 1
WIP
### Sponsor 2
WIP
### Sponsor 3
WIP

### Fiscal sponsor that will accept payments
WIP

**Comment by KTan1226** [comment]
Welcome @nzoueidi! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by nzoueidi** [comment]
Hey @KTan1226, is there any template for the sponsoring packs? I have seen some examples for previous KCDs but is there any official template from CNCF to follow? 
Also, could you please add me and the other three organizers to the #kcd-organizers channel? 

Thank you.

**Comment by dankohn** [comment]
Here's a template: https://kubernetescommunitydays.org/organizing-sponsor-prospectus/

**Comment by KTan1226** [comment]
Hi @nzoueidi- no problem. I've added you and the organizers to the #KCD organizers Slack channel. Let me know if you have any questions!

**Comment by xmulligan** [comment]
@nzoueidi We are relaunching the KCD program, including virtual events. We would love to have one in Tunis if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by nzoueidi** [comment]
Indeed with the possibility of going virtual, we will be very happy to organize one.

**Comment by xmulligan** [comment]
Awesome! Let me know if you have any questions or if there is something I can help with

**Comment by xmulligan** [comment]
You also might be able to leverage some of the energy coming out of KCD Africa https://community.cncf.io/events/details/cncf-kcd-africa-presents-kubernetes-community-days-africa/#/
