### ISSUE TITLE
KCD 2020 - Campinas/SP - Brazil

### ISSUE THREAD

**Issue by eduardo-eth0** [cncf/kubernetes-community-days#256]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Sponsor 1
Mandic Cloud Solutions - https://www.mandic.com.br/
### Sponsor 2
PagSeguro - https://www.pagseguro.com.br
### Sponsor 3
Aqua - https://www.aquasec.com/

### Fiscal sponsor that will accept payments
Eventbrite For tickets
Apice Solutions for sponsorship payments and pay out expenses

**Comment by pasimoes** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by papodesysadmin** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by KTan1226** [comment]
Welcome, @eduardo-eth0! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by eduardo-eth0** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by KTan1226** [comment]
Looks great @eduardo-eth0- you are approved to build your site. I have added all organizers to the KCD organizers channel on Slack and will be in touch with your email alias shortly. Can you also share the Twitter account created for this event? We recently updated the requirements and can help amplify from our KCD handle. Let me know if you have any questions!

**Comment by papodesysadmin** [comment]
@KTan1226 Kristi
I am Christiano from KCD Campinas - Brazil the twitter we will create is @KCD-Campinas?
For in the manual there are two options - https://kubernetescommunitydays.org/

**Comment by KTan1226** [comment]
Sounds good @pablodelarocha. Please share a link to your Twitter account once created. To confirm, we do have a general CNCF KCD Twitter account (https://twitter.com/KubernetesDays) but are asking organizers to create their own as well.

**Comment by eduardo-eth0** [comment]
@KTan1226 for call for papers we can use https://papercall.io?

**Comment by papodesysadmin** [comment]
add
Organizer 4: Carol Vilas Boas, Zup IT Innovation, Trainner, carolina.vilasboas@zup.com.br, Slack display name: carolfvb

**Comment by papodesysadmin** [comment]
add
Organizer 5: Gabriela Dias, PagSeguro, Manager SRE, gadias@pagseguro.com  Slack display name: Gaby Dias

**Comment by gabydias** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by carolfvb** [comment]
Agree to https://kubernetescommunitydays.org/code-of-conduct/ and https://kubernetescommunitydays.org/organizing

**Comment by pasimoes** [comment]
@KTan1226 Unfortunately, we from KCD Campinas officially are canceling the event. The effect of CONVID-19 for the planning/organization was terrible and it will not feasible to reorganize for this year. Let’s pray to be safe and in 2021, try to organize a great event.

**Comment by xmulligan** [comment]
@eduardo-eth0 We are relaunching the KCD program, including virtual events. We would love to have one in Campinas if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
