### ISSUE TITLE
KCD 2020 - Ottawa, Canada

### ISSUE THREAD

**Issue by archyufa** [cncf/kubernetes-community-days#261]
### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and payout expenses
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)  https://twitter.com/KCD_Ottawa

### Organizer 3: William Hearn, Statistics Canada, Cloud Architect, William.hearn@canada.ca, William Hearn
Organizer 4: Suvrojeet Ghosh, Ribbon Communication, Software Engineer, ghosh.suvrojeet@gmail.com, suvro
Organizer 5: Andrew Whitehead,  IBM, IBM Cloud Specialist, Andrew.Whitehead@ibm.com, Andrew Whitehead

### Fiscal sponsor that will accept payments
Kubrat Inc Ltd

**Comment by KTan1226** [comment]
Welcome, @archyufa! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by archyufa** [comment]
@KTan1226 Completed. We sending PR for website

**Comment by KTan1226** [comment]
Wonderful @archyufa! You are approved to create your website. A few other items:

- I've created the organizers' email alias for your team to use (organizers-ottawa@kubernetescommunitydays.org
- I also created a sponsor alias for your use (sponsors-ottawa@kubernetescommunitydays.org)
- All organizers are now part of the KCD Organizers Slack channel

Let me know if you have any questions!

**Comment by fOO223Fr** [comment]
Organizer 4: Suvrojeet Ghosh, Ribbon Communication, Software Engineer, ghosh.suvrojeet@gmail.com, suvro

**Comment by archyufa** [comment]
@KTan1226 Can you please add Suvro and Andrew in google group?

**Comment by archyufa** [comment]
@KTan1226 Quick update on the event.
Venue and dates - WIP. We'll decide in late April if we going to organize an event in Sep/Oct 2019. Currently, the issue is to lock venues as we can't visit them and all venues got booked with people who cancel their events in April, May, June.
Website - WIP PR sent.
CFP - WIP

**Comment by KTan1226** [comment]
Thanks for the update @archyufa! I've sent an email with training materials and access to your CFP tool. Let me know if you have any questions.

**Comment by xmulligan** [comment]
@archyufa We are relaunching the KCD program, including virtual events. We would love to have one in Ottawa if you are still interested! You can [read the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
