### ISSUE TITLE
Please fail on build when sponsor logos aren't SVGs

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#263]
Please emit a clear error and mention that many sponsor logos are available at landscape.cncf.io and at kubecon.io.

https://github.com/cncf/kubernetes-community-days/pull/210#discussion_r372900739

**Comment by lucperkins** [comment]
@dankohn There isn't really a good way to fail the build without introducing a separate checker script, as Hugo supports error output but not conditional build failure. Personally, I would prefer to enforce this in PR reviews rather than introduce additional complexity in the build process.

**Comment by dankohn** [comment]
OK, we can revisit later if it becomes an issue. With the landscapeapp, we get Netlify to report errors back to the pull request: https://github.com/cncf/landscape/pull/1541#issuecomment-580929614
