### ISSUE TITLE
Please add sponsor and speaker start dates

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#264]
Often when KCDs launch, they're not yet ready to accept sponsorships and their speaker CFP isn't open yet, so they shouldn't be listed in the sponsor and speaker pages. Could you please add an *optional* start date, and change the calculations so that if you're before the start date or after the end date, they're not listed.

**Comment by lucperkins** [comment]
@dankohn As far as I know, this is the current behavior. The [sponsoring](https://kubernetescommunitydays.org/sponsoring) and [speaking](https://kubernetescommunitydays.org/speaking) pages, for example, do not include the Portland event because it's not yet open to sponsors/speakers.

**Comment by dankohn** [comment]
OK, we'll just ask people to comment out the keys until it's open.
