### ISSUE TITLE
KCD 2020 - Montreal, Canada

### ISSUE THREAD

**Issue by archyufa** [cncf/kubernetes-community-days#267]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)  https://twitter.com/kcd_montreal

### Fiscal sponsor that will accept payments
Kubrat Inc Ltd

**Comment by KTan1226** [comment]
Welcome, @archyufa! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by archyufa** [comment]
@KTan1226 We completed with a checklist. Starting to work on website and venue.

**Comment by idcrosby** [comment]
@archyufa My info:
Ian Crosby, Container Solutions, Managing Director, ian.daniel.crosby@gmail.com, Ian Crosby (on CNCF slack)

**Comment by huats** [comment]
@archyufa  My info:
Christophe Sauthier, LinkByNet, Head of Consuling North America, christophe.sauthier@gmail.com, Christophe Sauthier (on CNCF slack)

**Comment by jfchevrette** [comment]
@archyufa My info:
Jean-François Chevrette, Principal SRE @ Red Hat
Email: jfchevrette@gmail.com
Slack: @jfchevrette (CNCF, Kubernetes)

**Comment by archyufa** [comment]
@KTan1226 Quick update on the event.
Venue and dates - WIP. We'll decide in late April if we going to organize an event in Sep/Oct 2019. Currently, the issue is to lock venues as we can't visit them and all venues got booked with people who cancel their events in April, May, June.
Website - WIP PR sent.
CFP - WIP

**Comment by KTan1226** [comment]
Thanks for the update @archyufa! Please use the following email aliases:
- organizers-montreal@kubernetescommunitdays.org (for organizer communications, general questions)
- sponsors-montreal@kubernetescommunitydays.org (for potential sponsors)

I've also added your team to the KCD Organizers Slack channel and am sending over access/training videos for your CFP. Let me know if you have any questions!

**Comment by anthonydahanne** [comment]
Hello all,
The Montreal event for September 2020 was cancelled; we don't think we'll have one this year.
I'm about to submit a PR to reflect that - what should I, just plain and simple delete the whole folder?
Or should I just comment the dates? Or archive it somehow?
Thanks for your help // cc @KTan1226 
Anthony

**Comment by xmulligan** [comment]
@archyufa We are relaunching the KCD program, including virtual events. We would love to have one in Montreal if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).
