### ISSUE TITLE
Event team pages do not link to twitter accounts or URLS

### ISSUE THREAD

**Issue by iennae** [cncf/kubernetes-community-days#268]
The team page does not link to twitter accounts or URLs even though they are configured. The <a href> is blank. 
Example:

https://kubernetescommunitydays.org/events/2019-amsterdam/contact/

Location I originally saw this (but might disappear)
https://deploy-preview-210--kubernetes-community-days.netlify.com/events/2020-amsterdam/contact/
Source code for a snippet of HTML for a URL
```
<a href>Daniel Paulus</a>

```
and for the twitter URL
```
<a class="button is-twitter-blue"><span class=icon><i class="fab fa-twitter"></i></span></a>
```

and the example from the configuration
```
- name: Daniel Paulus
  image: team/daniel_paulus.jpeg
  twitter: https://twitter.com/dpnl87
  homepage: https://twitter.com/dpnl87
```

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [x] I've described what I expected to see and what I am seeing
* [ ] I am not interested or able to instead create a pull request with a proposed fix

**Comment by lucperkins** [comment]
Fixed in commit c8ffca7e2490c6b03fb1b3ecde54466bfb0a53fa
