### ISSUE TITLE
Improve sponsor logo layout

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#272]
Sponsor logos should be centered horizontally as well as vertically. Size should shrink from diamond to lower levels.

https://kubernetescommunitydays.org/events/2025-bouvet-island/

**Comment by lucperkins** [comment]
@dankohn The issue with horizontal centering is that it looks quite bad when there's a single logo:

<img width="542" alt="Screen Shot 2020-01-31 at 3 43 52 PM" src="https://user-images.githubusercontent.com/1523104/73582077-877e0480-4440-11ea-8bd4-5405becb9428.png">

**Comment by dankohn** [comment]
I'm thrilled by the improvements here. @lucperkins I think you can close unless there's more you want to do.

**Comment by lucperkins** [comment]
@dankohn Thanks for the kind words! I would like to continue to improve this as the project goes on but I think we can close this for now.
