### ISSUE TITLE
Embedding Google Analytics code on pages

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#276]
Is it possible to track page visits with Google Analytics? Ideally, this could be left to the individual KCD by adding a custom code on each event.

**Comment by dankohn** [comment]
Yes, we will track and share, but we want it to be the CNCF account, as it is under our privacy policy.

**Comment by dankohn** [comment]
@cjyabraham Could you please say what code needs to be embedded for this to appear on CNCF's Google Analytics and then assign to @lucperkins to implement.

**Comment by cjyabraham** [comment]
@ccraigross can you setup a new Google Analytics property for https://kubernetescommunitydays.org/ please?

**Comment by ccraigross** [comment]
@cjyabraham - UA-82811140-39

**Comment by cjyabraham** [comment]
@lucperkins do you need anything else in order to install the Google Analytics tracking?

**Comment by dankohn** [comment]
@cjyabraham whats the exact tag he should create, please?

**Comment by lucperkins** [comment]
@dankohn @cjyabraham Don’t worry, I can take care of this tomorrow

**Comment by cjyabraham** [comment]
Here's the code in case you need it:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-82811140-39"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-82811140-39');
</script>
```

**Comment by lucperkins** [comment]
Addresses in 850e52892b485a3e1dd549e4ea6981e7dee56495
