### ISSUE TITLE
The sponsoring page doesn't seem to honor the sponsor_deadline field

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#278]
The page at https://kubernetescommunitydays.org/sponsoring/ doesn't seem to take in consideration the field `sponsor_deadline:` in content/events/2020-amsterdam/_index.md and lists "September 9, 2020".

**Comment by lucperkins** [comment]
FIxed in ca46c86df80001249aa5cf31496bd40076238f14
