### ISSUE TITLE
Support missing social accounts

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#28]
https://kubernetescommunitydays.org/events/2020-bouvet-island/

Kubernetes Community Day Bouvet Island has a Twitter account but no Facebook. Please support non-existent social accounts.

**Comment by lucperkins** [comment]
Resolved in 0714786342418ae481827651057097eb49dc5cb3

**Comment by dankohn** [comment]
Still unresolved: https://kubernetescommunitydays.org/events/2020-bouvet-island/
