### ISSUE TITLE
Do US cities need the state?

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#280]
Events like London and Amsterdam appear with just the city name; however, Portland appears as "Portland, Oregon". Should we instead use just the city name? DevOpsDays (https://devopsdays.org/) uses only the city name on the left side list.

**Comment by lucperkins** [comment]
@ams0 In some cases no (Chicago, Los Angeles, etc.), but some city names are very common in the US. There are, for example, 25 Springfields! In this case, Portland, Maine is also a very well known city. If you're on the East Coast and say you're from Portland, people will assume you mean Maine. The DevOpsDays site, in fact, also distinguishes between Portland, OR and Portland, ME.

Fun historical fact: the name of Portland, Oregon was either going to be Portland or Boston. The name was decided by a coin toss, and you can see the coin in a local museum here in the city. We could've been Boston, Oregon!!

**Comment by ams0** [comment]
You totally right - sometime us Europeans don't realise that the world is much bigger :) Thanks for the historical fact! I'll make sure I'm going to the right Boston in November :D
