### ISSUE TITLE
KCD 2024 - Toronto, Canada

### ISSUE THREAD

**Issue by archyufa** [cncf/kubernetes-community-days#281]
### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event.
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event - https://twitter.com/KCD_Toronto

### Fiscal sponsor that will accept payments
Kubrat Inc. Ltd

**Comment by KTan1226** [comment]
Great work @archyufa! You are approved to begin building your site. I've added all organizers to the KCD Slack channel and will create your email alias. Can you also share the handle for your Twitter account? We can help amplify via our KCD account. Thanks!

**Comment by archyufa** [comment]
@KTan1226 Added Twitter: https://twitter.com/KCD_Toronto

**Comment by archyufa** [comment]
@KTan1226 Quick update on the event.
Venue and dates - WIP. We'll decide in late April if we going to organize an event in Sep/Oct 2019. Currently, the issue is to lock venues as we can't visit them and all venues got booked with people who cancel their events in April, May, June.
Website - WIP PR sent.
CFP - WIP

**Comment by KTan1226** [comment]
Thanks for the update @archyufa! Please use the following email aliases:
- organizers-toronto@kubernetescommunitydays.org (for organizer communication, general inquiries)
- sponsors-toronto@kubernetescommunitydays.org (for potential sponsors, email forwards to organizers alias)

I've also added your team to the KCD Organizers Slack channel and am reaching out via email for access to the CFP tool. Let me know if you have any questions!

**Comment by xmulligan** [comment]
@archyufa We are relaunching the KCD program, including virtual events. We would love to have one in Toronto if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by archyufa** [comment]
We just started in Person meetups and it's pretty sad seen. We trying to gage the community readiness to see if it make sense.

**Comment by AudMonte01** [comment]
Hi @archyufa - we see you changed the title of this to 2023. Are you planning to do a KCD for sure this next year in Canada? If so, we should call it a general name like "KCD Canada" so it is open to more cities. Let me know your thoughts and we can re-open this issue

**Comment by archyufa** [comment]
There is huge interest from Community to do KCD in several cities. We will plan activities in January.

**Comment by AudMonte01** [comment]
Hi @archyufa - let's schedule a kick-off meeting: https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by AudMonte01** [comment]
Closing this as the GitHub issue has been updated extensively. Please file a new one when you are ready.
