### ISSUE TITLE
Add a Program Committee section

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#285]
As an organiser, I'm selecting a Program Committee (PC) to help vet and select talks for the conference. It would be great to have a section (can be under the Team section, but in a second "box") to display the PC members.

**Comment by dankohn** [comment]
@lucperkins Could you please support optional additional teams.

**Comment by lucperkins** [comment]
Fixed in 6d4edbbb3d207ad3cc657111d15c4a5ec2956774. You can see an example of how to implement this under `extra_teams` [here](https://raw.githubusercontent.com/cncf/kubernetes-community-days/master/content/events/2025-bouvet-island/_index.md).
