### ISSUE TITLE
Change location links

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#286]
Please make the location links on https://kubernetescommunitydays.org/ (like "Igloo 74") go to the venue page of the KCD rather than lead offsite.

![image](https://user-images.githubusercontent.com/3083270/74093531-0ad2d200-4aa1-11ea-858c-bdff809f25f1.png)

**Comment by lucperkins** [comment]
@dankohn One issue in play is that, as far as I know, a venue page is not strictly required when initially creating an event page. The upcoming [KCD Portland](https://kubernetescommunitydays.org/events/2020-portland-oregon), for example, does not have one. What's your preferred method for handling that case?

**Comment by dankohn** [comment]
No link, then, please.

**Comment by lucperkins** [comment]
Fixed in 9c52b7344471bafba908e16813208069cb47c6aa

**Comment by dankohn** [comment]
Could you please link to the venue page if it exists, and otherwise not have it be a link.

**Comment by lucperkins** [comment]
Fixed in 7c8500249b098b2c47aeb095d487245ba780b249

**Comment by dankohn** [comment]
Great. Could you please also make the text blue or more recognizably a link, when it is.

**Comment by lucperkins** [comment]
Fixed in ba2f81961e37fdda1eac9332ce7f80f660e5b6af
