### ISSUE TITLE
Clicking on headers should create a fragment link

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#291]
If you go to https://kubernetescommunitydays.org/organizing/ and click on "Getting Started Playlist" the URL should change to https://kubernetescommunitydays.org/organizing/#getting-started-checklist. I thought we had that functionality working before but it disappeared.

Note that GitHub Readme files work that way. E.g.: https://github.com/cncf/kubernetes-community-days#running-the-site-locally

**Comment by lucperkins** [comment]
@dankohn We definitely had that working previously. I suspect there may have been an errant merge somewhere along the line.

**Comment by lucperkins** [comment]
Fixed in 6c5694ea39c614e0b7a48aee0980a00a15ae9d57
