### ISSUE TITLE
KCD 2020 - Lyon, France

### ISSUE THREAD

**Issue by xinity** [cncf/kubernetes-community-days#294]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [X] No other Kubernetes Community Days event in the same city
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event.
* [X] Agree to use Eventbrite for registration
* [X] Agree to use Sched for organizing the program page
* [X] Agree to use SM Apply for CFP
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) : @KcdLyon

**Comment by KTan1226** [comment]
Welcome, @xinity! Please update the issue as you complete the items on the checklist. Once everything is complete, we'll sign off on your team creating the event site.

**Comment by xmulligan** [comment]
@xinity  We are relaunching the KCD program, including virtual events. We would love to have one in Lyon if you are still interested! You can read [the blog post here](https://www.cncf.io/blog/2021/03/01/relaunching-kubernetes-community-days-with-kcd-africa-bengaluru/). If you have any questions, please contact me at kcd@cncf.io or [book a meeting with me](https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03).

**Comment by xinity** [comment]
We'll do, we are currently rebooting the project 😁

**Comment by xmulligan** [comment]
Awesome! Glad to hear. Please reach out if there is anything I can help with
