### ISSUE TITLE
Use non-reversed Twitter icons

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#297]
Please use non-reversed Twitter and Facebook icons.

https://worldvectorlogo.com/logo/twitter
https://worldvectorlogo.com/logo/facebook-2

**Comment by lucperkins** [comment]
Could you clarify what you mean by non-reversed?

**Comment by dankohn** [comment]
Reversed is white in a blue square. Non-reversed is just blue, like the ones I linked to.

**Comment by lucperkins** [comment]
Fixed in 22513603c32934f59dc7e0d85d7d22c370506b14
