### ISSUE TITLE
Sponsor logo policy

### ISSUE THREAD

**Issue by iennae** [cncf/kubernetes-community-days#3]
Rather than have every event have a copy of the sponsor logo, it might be beneficial to have a centralized place within the repository so that the logo is saved once. It needs to be flexible so that as companies change logos it doesn't update past instances of events.

**Comment by lucperkins** [comment]
I think the best way to do this would be to enable companies to add multiple logos with different names. So OmniCorp could intially add `omnicorp.svg` and later `omnicorp-updated.svg` or something like that. One way or another, the different images will need to have different names.

**Comment by dankohn** [comment]
I believe essentially every company would like to have their logo updated, so there's no need to maintain old ones. Instead, I think @iennae could just create some guidelines along the lines of:

1. All logos must be SVGs and follow the guidelines at https://github.com/cncf/landscape#logos.
2. The filename needs to be lowercase with hypens in place of spaces (e.g., `acme-corporation.svg`).
3. If the logo already exists in `/static/sponsor-images/`, don't add another copy.
4. If an outdated version of the sponsor logo exists in `/static/sponsor-images/` replace it.

**Comment by dankohn** [comment]
We're going to go with having every event keep their own copy of logos for now.
