### ISSUE TITLE
Dealing with lots of menus

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#310]
I'm open to suggestions on how to make these menus work better. One option would be to just switch to a hamburger menu when they're too long.

https://kubernetescommunitydays.org/events/2020-quebeccity/

**Comment by lucperkins** [comment]
@dankohn One suggestion: we enable projects to specify `dropdown: true` in `_index.md` if they want a dropdown menu instead of the current setup. The issue with collapsing to a dropdown when the list is "too long" is that it's tricky to programmatically detect that.

**Comment by lucperkins** [comment]
Closing this for now. Re-open if a different solution is desired.
