### ISSUE TITLE
Instructions link not correct

### ISSUE THREAD

**Issue by OrlinVasilev** [cncf/kubernetes-community-days#328]
Hi,

the instruction link is broken: https://github.com/cncf/kubernetes-community-days/blob/master/organizing-creating-website
on the organising page.

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [X] I've described what I expected to see and what I am seeing
* [ ] I am not interested or able to instead create a pull request with a proposed fix

**Comment by lucperkins** [comment]
Sorry, on which page is there a broken link?

**Comment by OrlinVasilev** [comment]
@lucperkins will create PR

**Comment by OrlinVasilev** [comment]
sorry my mistake for reading it from github will close that
