### ISSUE TITLE
Homepage Upcoming Events display of events

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#33]
Please change the way events are shown in Upcoming Events on the homepage to replicate [DevOpsDays](https://devopsdays.org). They're in forward chronological order. Specifically:

2019
SEPTEMBER
Sep 5 - 6: Cape Town
Sep 10 - 12: Portland

OCTOBER
Oct 1 - 2: Raleigh
Oct 2 - 3: Hartford

Don't say the event name. Just have the city link to the event.

**Comment by lucperkins** [comment]
Resolved by 38b208216d7ef2008e9d7312b8c8efb20f4b3223
