### ISSUE TITLE
Code of Conduct in Japanese

### ISSUE THREAD

**Issue by superbrothers** [cncf/kubernetes-community-days#338]
We'd like to prepare Code of Conduct in Japanese for KCD Tokyo 2020. Where should we add it on kubernetescommunitydays.org.

/ref #187

**Comment by dankohn** [comment]
Could you please just create a Japanese language version and link to it from your pages.

**Comment by superbrothers** [comment]
I found a Japanese language version on the Linux foundation Japan site. https://www.linuxfoundation.jp/code-of-conduct/ It is almost the same content, so we link to it from the Tokyo Overview page.
