### ISSUE TITLE
Kubernetes Community Day El Salvador

### ISSUE THREAD

**Issue by flanets** [cncf/kubernetes-community-days#361]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist: 

*Please check each of these as you complete them:

* [X ] No other Kubernetes Community Days event in the same city

* [X ] Minimum of 3 organizers from 3 different organizations

1. Mauricio Quevedo, Korinver, San Salvador, El Salvador
2. Raul Flamenco, Acopula Networks, Lincoln, CA, USA
3. Victor Morales, Samsung, Mountain View, CA, USA 
4. Stanley Jovel, Korinver, San Salvador, El Salvador
5. Eduardo Chavez, Korinver, San Salvador, El Salvador
6. Rene Martinez, Asociacion de Becarios de Estados Unidos (ABEU), San Salvador, El Salvador

* [X ] Each organizer lives in or just outside of the KCD location

* [X ] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
Victor Morales, Samsung

* [X ] All organizers agree to follow the event guidelines and CNCF Code of Conduct

* [X ] Minimum of 3 sponsors committed

* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses

* [X ] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event.

* [X ] Agree to use Eventbrite for registration

* [X ] Agree to use Sched for organizing the program page

* [ X] Agree to use SM Apply for CFP

* [ X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

* [X ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 

### Fiscal sponsor that will accept payments
Asociacion de Becarios de Estados Unidos (ABEU), San Salvador, El Salvador

**Comment by KTan1226** [comment]
Hi @flanets. Could you please confirm the date for your event? Once confirmed, the event will be approved. Thanks!

**Comment by flanets** [comment]
KCD ES will take place on January 30, 2021.

**Comment by KTan1226** [comment]
Great, thanks! Your event is approved. I will be in touch with an email alias for your use. I know you've been in contact with @idvoretskyi on getting the event set up in Bevy as well.

**Comment by flanets** [comment]
Hi there,

How can we (more than one user) gain access to Bevy?

Thanks!

Raul

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by KTan1226** [comment]
Hi @flanets - @idvoretskyi can help you with this. Thanks!

**Comment by xmulligan** [comment]
@flanets do you have any updates on this event? Is it still going forward?

**Comment by xmulligan** [comment]
@flanets Can I close this issue?

**Comment by flanets** [comment]
Hi Bill,

Eduardo Chavez and Carlos Recinos (CC here), Kubernetes Community Day El Salvador Contributors, will submit an update shortly.

Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by eduardo3150** [comment]
Hi @xmulligan ! A PR has been created with the latest updates for KCD San Salvador, https://github.com/cncf/kubernetes-community-days/pull/372
We still need to make some updates to the agenda piece but we already have everything else in place

**Comment by xmulligan** [comment]
Thanks! It has been merged 👍

**Comment by idvoretskyi** [comment]
@eduardo3150 any reason why community.cncf.io is not used for this?

**Comment by xmulligan** [comment]
You can find the event here https://community.cncf.io/events/details/cncf-san-salvador-presents-kubernetes-community-day-el-salvador/#/

**Comment by eduardo3150** [comment]
Hi @xmulligan , @idvoretskyi ! I've just created one PR #374  containing the final agenda and speaker lineup for KCD San Salvador, I'd appreciate your help reviewing these changes

Best,

**Comment by caniszczyk** [comment]
looks like this was done: https://community.cncf.io/events/details/cncf-san-salvador-presents-kubernetes-community-day-el-salvador/#/

please upload the videos on the community.cncf.io page :)
