### ISSUE TITLE
KCD Africa 2021 - Virtual

### ISSUE THREAD

**Issue by abuango** [cncf/kubernetes-community-days#363]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

#### Goals and Objectives
We are opting for an inaugural event to be Africa based to shore up interest and present opportunities for others to localize it, after which we will switch to either Abuja/Lagos as City when it picks up.

The main objective is to create a platform for members of the community to share their knowledge, tips, tricks, use-cases and learnings. Kubernetes and the cloud-native eco-system is not popular in the region, a major KPI of this event will be how much interest we are able to create towards learning, using or contributing to the projects.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Days event in the same city
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and payout expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event.
* [x] Agree to use Eventbrite for registration
* [x] Agree to use Sched for organizing the program page
* [x] Agree to use SM Apply for CFP
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used): twitter.com/kcd_africa

**Comment by iennae** [comment]
Hey @abuango , CNCF is not approving any virtual events for KCDs at this time.

**Comment by abuango** [comment]
@xmulligan FYI

**Comment by xmulligan** [comment]
let's shoot for the end of March to get this on the schedule

**Comment by thisisobate** [comment]
Super excited about this initiative! @abuango

**Comment by CloudGrimm** [comment]
This looks great, looking forward to it! @abuango

**Comment by xmulligan** [comment]
@samswag

**Comment by sltet** [comment]
nice initiative! can't wait to see this happen @abuango

**Comment by xmulligan** [comment]
This event is now live https://community.cncf.io/events/details/cncf-kcd-africa-presents-kubernetes-community-days-africa/#/

**Comment by xmulligan** [comment]
All videos from KCD Africa are now up on Youtube. Thanks again everyone for such an amazing event! :tänzerin:
https://www.youtube.com/playlist?list=PLj6h78yzYM2P9aHZVgJOb7WG1wyQSepwW
