### ISSUE TITLE
Markdown from _index.md is not rendered

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#37]
I noticed that adding markdown to the `_index.md` of an event (like my PR here: https://github.com/cncf/kubernetes-community-days/blob/59b809d70ede2f8b6233dfae79a4302f69e8b181/content/events/2019-amsterdam/_index.md) doesn't render on the event (preview [here](https://deploy-preview-36--kubernetes-community-days.netlify.com/events/2019-amsterdam/)). Or is there something wrong with the markdown?

**Comment by lucperkins** [comment]
Resolved by #9b8a5bef6dd2cc58e258f2d3ef7621ee2d1c5a16
