### ISSUE TITLE
KCD Brasil 2021 - Virtual

### ISSUE THREAD

**Issue by pasimoes** [cncf/kubernetes-community-days#383]
# Kubernetes Community Days Brasil 2021 -- Online Edition

## Goals and Objectives
The main objective is to create a platform for community members to share their knowledge, tips, tricks, use-cases, and learning. Kubernetes and the cloud-native eco-system is very popular in the region, a major KPI of this event will be how much interest we can create towards learning, using, or contributing to the projects.

### Submission checklist:

*Please check each of these as you complete them:

* [] No other Kubernetes Community Day event in the same region 
* [] Minimum of 3 organizers from 3 different organizations
* [] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [] Each organizer lives in or just outside of the KCD location
* [] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [] Identified fiscal sponsor that can accept payments such as from sponsorships and payout expenses
* [] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [] Agree to use SM Apply for CFP
* [] Event date and time has been chosen
* [] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Organizer email alias has been created
* [x] Region and event has been created in Bevy

### Organizer email
organizacao@kcdbrasil.online

### Twitter Account
https://twitter.com/kcdbrasil
### Instagram Account
https://instagram.com/kcdbrasil
### Facebook
https://fb.me/kcdbrasil

### PC Member :

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by pasimoes** [comment]
I agree to the [event guidelines](https://community.cncf.io/kubernetes-community-days/about-kcd/) and I agree to abide by the Kubernetes Community Day [Code of Conduct](https://kubernetescommunitydays.org/code-of-conduct/)

**Comment by amandabhmg** [comment]
I agree to the event guidelines and I agree to abide by the Kubernetes Community Day Code of Conduct as well.

**Comment by cpanato** [comment]
I agree to the event guidelines and I agree to abide by the Kubernetes Community Day Code of Conduct as well.

**Comment by xmulligan** [comment]
Thanks everyone for putting this together 🎉

Are you planning on having any financial sponsors and will this be a free event?

**Comment by pasimoes** [comment]
We are closing the financial sponsor this week.

**Comment by prithvi1307** [comment]
I am really looking forward to KCD Brazil! This is going to be great! Thanks @pasimoes :)

**Comment by xmulligan** [comment]
@pasimoes is this still on track for August and do you need any help from me?

**Comment by pasimoes** [comment]
> @pasimoes is this still on track for August and do you need any help from me?

@xmulligan Yes, we are closing some points and having conversations with potential sponsors. At this moment, we have to meet the sponsorship rule.

**Comment by xmulligan** [comment]
@pasimoes do you know when the website and CfP will be ready? Our newsletter is going out next week and it would be great to be able to include them

**Comment by pasimoes** [comment]
Event Canceled

**Comment by KTan1226** [comment]
In order to serve the Brazilian cloud native community, CNCF will take over the lead organizer responsibilities and reschedule KCD Brazil to a new date. To learn more about our decision, please read this Twitter thread by our GM Priyanka Sharma: https://twitter.com/pritianka/status/1415148020362977283?s=20.  Updated issue coming soon.

**Comment by KTan1226** [comment]
This issue has been closed. In order to serve the Brazilian cloud native community, CNCF will take over the lead organizer responsibilities and reschedule KCD Brazil to a new date. To learn more about our decision, please read this Twitter thread by our GM Priyanka https://twitter.com/pritianka/status/1415148020362977283?s=20.

Please find the new issue here:  https://github.com/cncf/kubernetes-community-days/issues/407.
