### ISSUE TITLE
KCD Spain 2021 - Virtual

### ISSUE THREAD

**Issue by raelga** [cncf/kubernetes-community-days#385]
### Event Location

Spain

### Event Date and Time

- 8th and 9th of June 2020, with the possibility of extending to the 10th if there is enough content and interest.
- The duration will be about 3-4 hours max each day, to avoid fatigue and be as work friendly as possible.
- The time frame will be the afternoon, somewhere between 15:00 and 20:00 to be friendly to Latin American folks.

### Event type

Virtual

### Goals and Objectives

Last year, we started working on the KCD Madrid 2021 (https://github.com/cncf/kubernetes-community-days/issues/231) but had to cancel it due to the worldwide health situation.

To get things back in track, we are proposing a Spain wide virtual event to raise awareness of the KCD framework and hopefully set the ball rolling  for future city based KCD events throughout Spain. The event organization will be completely open and available at https://github.com/kcd-es/, meetings and team creation follows the `sig-contribex` best practices and every step in the way will be documented (tasks completed by each team, roles responsibilities, issues and mistakes,...).

### Submission checklist:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed ⚙️ 
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses  **(Free and virtual event)**
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event **(Free event)**
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Organizer email alias has been created
* [x] Region and event has been created in Bevy

### Organizer 1 @raelga

**Rael Garcia Arnés**, Red Hat, Senior Software Engineer, rael@redhat.com, `rael`

### Organizer 2 @angelbarrera92

**Ángel Barrera Sánchez**, SIGHUP, Kubernetes Engineer, angel@sighup.io, `AngelBarrera`

### Organizer 3 @javierprovecho

**Javier Provecho**, Telefonica, Platform SRE, javier.provechofernandez@telefonica.com, `javierprovecho`

### Organizer 4 @agonzalezro

**Álex González**, Auth0, Software Engineer, agonzalezro@gmail.com, `agonzalezro`

### Organizer 5 @altudela

**Alba Tudela**, Tesera, CMO

### Organizer 6 @jorgermp

**Jorge Martinez**, ISRG - Sprinter, DevOps Team Leader

### Sponsors

Being virtual and free, we didn't require any sponsors, just time.

### Fiscal sponsor that will accept payments

At this point, being virtual and free, we probably don't need a fiscal sponsor.

### Social

Project repo: https://github.com/kcd-es/spain-2021
Twitter account: https://twitter.com/KCDSpain
Team formation issue: https://github.com/kcd-es/spain-2021/issues/1
Meetings notes and agenda: [KCD Spain 2021  Weekly Meeting](https://docs.google.com/document/d/1vw8jJRmhfNREqYqjTeTHbICHObavTLbevuCMYGCjiCs/edit?usp=sharing)

**Comment by xmulligan** [comment]
@raelga Thanks for putting this together! I have added all of the organizers to the slack channel and created the email alias organizers-spain@kubernetescommunitydays.org

**Comment by xmulligan** [comment]
For virtual events, it is up to you if you want sponsors. KCD Africa is using the funds to get new people into the ecosystem, but it is up to you https://community.cncf.io/events/details/cncf-kcd-africa-presents-kubernetes-community-days-africa-virtual/#/

**Comment by xmulligan** [comment]
Once the event date is chosen, I can create your account in SM Apply for the CfP. Looking forward to an amazing event 🚀

**Comment by raelga** [comment]
Thank you @xmulligan for all the information and the cheering, really looking forward to get things started!

**Comment by raelga** [comment]
@xmulligan we have a date and time frames! 📆 🕥 

The proposal has been added to the issue, but for the sake of context, the idea is the following:

> 8th and 9th of June 2020, with the possibility of extending to the 10th if there is enough content and interest.
> The duration will be about 3-4 hours max each day, to avoid fatigue and be as work friendly as possible.
> The time frame will be the afternoon, somewhere between 15:00 and 20:00 to be friendly to Latin American folks.

Let us know what you think ✨

**Comment by xmulligan** [comment]
@raelga Thanks for putting this together. I've added you as an admin for SM Apply. Let me know who else you want me to add. 

I've also created created the region in Bevy for you. https://community.cncf.io/kcd-spain/ I've added everyone except Alex as he doesn't have an account there, once he does, I can add him.

Let me know if you need anything else!

**Comment by raelga** [comment]
Thank you very much @xmulligan!

We will start working on the site and the CfP program right now 💙

**Comment by xmulligan** [comment]
@raelga we are about six weeks out from the event. Is there anything you need from CNCF or do you have any questions we can help answer? I see your Twitter is very active 🚀

**Comment by raelga** [comment]
Hey @xmulligan,

Thanks for the ping! We are quite on track, already have about 20 talks summited and we are looking for more speakers to improve the panelists diversity.

We are about to launch the event image (a bit late, but it will be still useful for this event and for future events!). Once we have the event "branding", we will push further the twitter and other social media visibility.

**Comment by xmulligan** [comment]
Great and glad to hear you are working to improve the diversity! Let me know if you need any other help from me. Looking forward to it!

**Comment by raelga** [comment]
![kcdspain2021](https://user-images.githubusercontent.com/795289/122636404-637c9b00-d0e9-11eb-9feb-0235c7b57a2b.jpg)

## KCD Spain 2021 ✅ 

The event concluded last week with awesome numbers!

- **+80 proposals received during the CfP**
- **876 attendees**
- **over 30 talks selected**
- **43 speakers from 31 companies**
- **25+ hours of content 100% in Spanish**

Videos are already uploaded to https://yt.kcdspain.com and will be published during the following weeks, one each day.

## After KCD Spain 2021...

The reception was incredible and exceeded all our expectations. We are going to keep pushing forward the Spanish community with new initiatives. Some of them may work, and others don't, but we are going to try nonetheless.

### [cloudnativo.es](https://cloudnativo.es) ⚙️ 

A hub for Spanish speaking communities. Open to collaboration at https://github.com/cloudnativos/comunidad/issues/1.

### Cloud Native Spain chapter ⚙️ 

New CNCF Chapter for monthly virtual events not tied to a particular location, but the entire Spanish speaking community. Open to collaboration at https://github.com/cloudnativespain/comunidad/issues/1. Already available at https://community.cncf.io/cloud-native-spain/.

### CloudNative.tv talk show 💭 

We have some ideas that may fit into the CloudNative.tv framework. After our post-event vacations, we may work on some proposals. 

### KCD Spain 2022 ✨ 

And, of course, see you back in KCD Spain 2021. Also open to collaboration at https://github.com/kcdspain/spain-2022/issues/2.

---

Thanks to everyone involved from the CNCF and Bevy, the framework is awesome.

And a big shoutout to @xmulligan for his support, help and cheering during the event formation and execution. 💙

**Comment by xmulligan** [comment]
Honestly a spectacular event put on by an amazing team 😍 I think this is a spark that will drive forward the Spanish speaking cloud native community and bring them to the next level. Can't wait to work with you on next year's event and all of the other things being planned!
