### ISSUE TITLE
KCD Korea 2021 - Virtual

### ISSUE THREAD

**Issue by seungkyua** [cncf/kubernetes-community-days#386]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Organizer email alias has been created

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

**Comment by xmulligan** [comment]
Thanks for creating this event @seungkyua ! Looking forward to working with you 

I couldn't find James Tokko or Hanbae Seo in the CNCF slack and Jinwoong Kim has three accounts. Can you let me know what the correct ones for them are so I can invite them to the channel?
 
I've added each of you to the organizers-korea@kubernetescommunitydays.org email forward, feel free to use it. 

If you can fill out the expected number of attendees, I can create the region in bevy. Also you list sponosors, but don't have someone that can accept payments, how to you want to handle it?

Who do you want added as the admin for the CfP in SM Apply?

**Comment by protess** [comment]
@xmulligan I and Hanbae Seo are in CNCF slack and in kcd-organizers channel we joined last year to prepare the KCD event but couldn't continue due to COIVD-19.
Anyhow, we have had about 300 virtual attendees last year so we'd expect more this year and as for the payments process what/where do we have fill out the information?
Also, if you could add me and Seungkyu Ahn as admin we'd much appreciate it.

**Comment by xmulligan** [comment]
@protess glad to hear you are both already in slack. I've added you and James as admins for SM Apply. It is a copy from KCD Berlin, so that just needs to be updated along with any other changes you want to make to it.

There are a couple different ways to set up a financal sponsor, you can find them https://github.com/cncf/kubernetes-community-days/blob/master/content/organizing-budget-finances.md#finance-sponsormanagement-options. Let me know which option you would prefer.

**Comment by xmulligan** [comment]
@seungkyua @protess I've created the chapter in Bevy and added the orgnaizers as lead for the chapter. The chapter is currently hidden, but we can make it public whenever you are ready.

Can you let me know how many people you expect? Also have you decided what to do about a financial sponsor?

**Comment by protess** [comment]
@xmulligan we are expecting 500 virtual attendees for this year's event and as for the financial sponsor, we will be using a local agency. Also, we are hoping to set concrete details by the first week of May for the event

**Comment by xmulligan** [comment]
@protess Great! Let me know if you need help from me once you have the details sorted

**Comment by xmulligan** [comment]
@protess just checking in again, is there anything I can do to help? When do you think the CfP and event page will be live?

**Comment by xmulligan** [comment]
@protess @seungkyua Are you still planning on moving forward with this event? It is only 6 weeks away and the CfP still hasn't been launched. Do you need to delay the date?

**Comment by protess** [comment]
@xmulligan We don't plan on delaying the event and we were getting CfP by using google form as we are not comfy with the platform yet.

**Comment by xmulligan** [comment]
@protess ok, can you share a link to the google form?

also when do you think your event will go live on the community.cncf.io platform?

**Comment by protess** [comment]
@xmulligan Below is the link to the google form and we are planning open the event page on 8/2
https://docs.google.com/forms/d/e/1FAIpQLScMxjkfFYEoypk-nWwc6Qi7JEVFjztwxEiubr-yoMXfTH28WA/viewform

**Comment by xmulligan** [comment]
@protess  Great, thanks for the quick update! Let me know if you need any help with the getting the event page launched :)

**Comment by xmulligan** [comment]
@protess do you need any help getting the page out? Are there any other parts of the event that I can help with?

**Comment by protess** [comment]
@xmulligan I am planning to finish the event page today so, if I need any assistance I will call for your help thanks in advance.

**Comment by protess** [comment]
@xmulligan how is this booth work? I have made one but can't find anywhere on the draft page

**Comment by xmulligan** [comment]
@protess You can find the full article here https://help.bevylabs.com/article/514-booths

Let me know if you need more help

![image](https://user-images.githubusercontent.com/29048870/128152422-be15cc7b-7441-45df-a450-e74a216b4464.png)

**Comment by protess** [comment]
@xmulligan I have published the event but there are few things that I still have to fix. I will let you know once I am done

**Comment by protess** [comment]
![image](https://user-images.githubusercontent.com/9170833/128181573-8979e256-7161-4e94-8bea-b5c304580a6f.png)
@xmulligan how do I add a speaker?

**Comment by xmulligan** [comment]
@protess you first need to add them as a speaker https://help.bevylabs.com/article/364-add-a-speaker-profile
then you can add them to the agenda https://help.bevylabs.com/article/516-adding-speakers-sponsors

**Comment by xmulligan** [comment]
@protess do you need any other help making the event go live?

**Comment by protess** [comment]
@xmulligan from the guide it says "Booths and Networking tables do not display in the Agenda, they are available in the event from the top navigation bar. If you do not add a Booth or Networking table, the links will not display in the Navbar (You will only see the Agenda + Stage)." but I can't find this navbar.

**Comment by xmulligan** [comment]
@protess the nav bar is in the event, see the screenshot (its in German though). If you want more help, I would also be happy to have a call with you to make sure everything is all set  https://calendly.com/billmulligan/1-1-with-bill-mulligan
![image](https://user-images.githubusercontent.com/29048870/128323007-84281366-61b6-49a6-a543-28d4f10b75e3.png)

**Comment by xmulligan** [comment]
@protess Great job on getting the site live! Do you need any more help from me before the event?

**Comment by protess** [comment]
@xmulligan So far so good, I am getting used to the platform if I bump into issues I will surely let you know. Thanks!

**Comment by xmulligan** [comment]
Another awesome KCD in the books! Attendees: 1245 Check Ins: 663

Videos can be found here https://www.youtube.com/playlist?list=PLj6h78yzYM2OO9_EWXS13LxAe-Bkn0xXt

Can't wait for next year 💯
