### ISSUE TITLE
KCD UK 2021 

### ISSUE THREAD

**Issue by mattj-io** [cncf/kubernetes-community-days#387]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location:

UK

### Event Date and Time:

15-16 September 10am-5pm

### Event type: 

Virtual with some Hybrid elements

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event https://twitter.com/kcduk_io 
* [x] Organizer email alias has been created

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

### Organizer 1: 
Matt Jarvis, Snyk, Senior Developer Advocate, matt@mattjarvis.org.uk, Matt Jarvis
### Organizer 2: 
Cheryl Hung, CNCF, VP Ecosystem, cheryljhung@gmail.com, Cheryl Hung
### Organizer 3: 
Nick Jones, Rancher/SUSE, Consulting Engineer, nick@dischord.org, yankcrime
### Organizer 4: 
Adrian Mouat, Container Solutions, Chief Scientist, adrian.mouat@containersolutions.com, mouat
### Organizer 5: 
Lewis Denham-Parry, Control Plane, Head of Training, lewis@cloudnativewales.io, denhamparry
### Organizer 6: 
Chris Kranz, Sysdig, EMEA SE Manager, chris.kranz@sysdig.com , chris kranz
### Organizer 7: 
Josh Michielsen, Snyk, Senior Software Engineer, j@mickey.dev, jmickey
### Organiser 8:
Aled James, Jetstack, Solutions Engineer, aled@cloudnativewales.io, Aled James
### Organizer 9:
Danny Abukalam, SoftIron, Product Engineering Lead, danny@abukalam.com, dabukalam
### Organizer 10:
Paula Kennedy, Syntasso, Chief Operating Officer, paula.louise.kennedy@gmail.com, Paula Kennedy

### Sponsor 1 
Snyk
### Sponsor 2 
Container Solutions
### Sponsor 3 
Sysdig

### Fiscal sponsor that will accept payments

We have a not for profit umbrella company for this purpose - Open Source Events Ltd.

**Comment by xmulligan** [comment]
Thanks for putting this together @mattj-io ! 

I've added Adrian and Josh to the slack channel. 

I've also added all the organizers to the organizers-uk@kubernetescommunitydays.org alias

What is your expected number of attendees? Once you add that and the twitter account, I can create the region

Who do you want added as an admin for SM apply?

Let me know if you have any questions :)

**Comment by mattj-io** [comment]
Josh Michielsen will be the admin for SM Apply

**Comment by mattj-io** [comment]
Expected attendees updated, Twitter account incoming

**Comment by xmulligan** [comment]
I've added Josh as the admin in SM Apply. Once you have the twitter account, I can create the region in Bevy

**Comment by mattj-io** [comment]
@xmulligan I've added an extra organiser, could you add Aled James to the alias pls ?

**Comment by xmulligan** [comment]
@mattj-io I just added him

**Comment by xmulligan** [comment]
@mattj-io I've created the region in Bevy and added you as the admin. Let me know who else should be added. The chapter is also currently hidden until you have time to build it out.

Have you had a chance to create the Twitter account yet?

**Comment by amouat** [comment]
I've created the twitter account https://twitter.com/kcduk_io (not sure why there's a restricted warning currently) but I had an issue with the e-mail alias, so it's currently going to me. 

We wanted to use hello@kcduk.io which I believe Nick Jones configure to forward to organizers-uk@kubernetescommunitydays.org. However, I never received any e-mail using that address. Could we verify organizers-uk@kubernetescommunitydays.org is working? I just sent a test e-mail asking for replies.

**Comment by xmulligan** [comment]
@amouat thanks for creating the account! I've also updated your email so it should work now

**Comment by amouat** [comment]
Thanks!

**Comment by amouat** [comment]
@xmulligan we'd like to get the CfP out this week. Is there anything else we need to do move to the next stage in the workflow?

**Comment by xmulligan** [comment]
Josh Michielsen should have access already. Let me know if you need me to resend or if there is anyone else you would like me to add

**Comment by denhamparry** [comment]
@xmulligan please could you give me access as admin

**Comment by denhamparry** [comment]
All completed and I now have access, thanks @xmulligan :pray:

**Comment by amouat** [comment]
Sorry to pester you again @xmulligan, but could we add two more organizers? Details as follow:

Danny Abukalam, SoftIron, Product Engineering Lead, danny@abukalam.com, dabukalam
Paula Kennedy, Syntasso, Chief Operating Officer, paula.louise.kennedy@gmail.com, Paula Kennedy

**Comment by xmulligan** [comment]
@amouat I've added them above and as organizers to the chapter. Let me know if you need anything else!

**Comment by amouat** [comment]
Thanks @xmulligan ! We're not sure about next steps; how do we announce the CFP - will CNCF help here?

**Comment by xmulligan** [comment]
@amouat CNCF is happy to help promote the CFP. We have a section in our monthly newsletter dedicated to KCD and we are happy to add it there. If you make Tweets from the KCD UK handle, both the KCD and CNCF handles can reweet them. We can also add them to KubeWeekly if you are interested. Does that help or are there other channels you would like to leverage?

The team for Bengaluru also wrote a blog for the CNCF blog if that is something you are interested in too

I would also reccomend setting up the event on https://community.cncf.io/ so there is a "homepage" for the event. Let me know if you need help with any steps along the way!

**Comment by xmulligan** [comment]
@amouat @mattj-io I wanted to check back in with the team. Is there anything you need from CNCF for the event? Are you happy with the CfP?

**Comment by xmulligan** [comment]
An awesome event 🎊 I was blown away by the quality of the presentations and production. I think the whole team can be proud of everything they did to make this event a success! Fingers crossed for an in person event next year
