### ISSUE TITLE
KCD Mumbai, India 2021 - Virtual

### ISSUE THREAD

**Issue by kesseract** [cncf/kubernetes-community-days#388]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location: 
Mumbai & Pune, India

### Event Date and Time: 
26th December, 2021

### Event type: 
Virtual

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [ ] Minimum of 3 organizers from 3 different organizations
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [ ] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [ ] Event date and time has been chosen
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [ ] Organizer email alias has been created
* [ ] Region and event has been created in Bevy

### Organizer 1: 
Sumit Shatwara, Red Hat, Solution Architect, sumitshatwara@gmail.com, CNCF Slack: Sumit Shatwara

### Organizer 2: 
Piyush Baderia, Dream11, DevOps Engineer, piyush.baderia@outlook.com, Piyush Baderia

**Comment by xmulligan** [comment]
@kesseract looking forward to seeing this event come together! Let me know if you need any help along the way. I'm also happy to schedule a call if/when you have any questions. https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-03

**Comment by pbaderia01** [comment]
> 3: First and Last Name, Company, Title, Email, CNCF Slack Username

Piyush Baderia, Dream11, DevOps Engineer, piyush.baderia@outlook.com, Piyush Baderia

**Comment by divya-mohan0209** [comment]
I'd like to withdraw my name from the list of organizers after giving it considerable thought. Apologies Sumit & Bill.

**Comment by nikhita** [comment]
@kesseract @pbaderia01 :wave: Hi, I am from Mumbai as well.

Can you elaborate on why it might help to have a separate KCD Mumbai conference as well, given that we have KCD Bengaluru too? To be clear, I don't want to block the effort. I am just curious. :blush: 

We don't have a big k8s community in Mumbai. It also looks like most folks are burnt out from virtual conferences. I think it would have been wonderful if we were able to do this in person but the virtual aspect of it might not draw a big audience.

**Comment by kesseract** [comment]
> I'd like to withdraw my name from the list of organizers after giving it considerable thought. Apologies Sumit & Bill.

@divya-mohan0209  - No worries. Thanks for your update.



> > 3: First and Last Name, Company, Title, Email, CNCF Slack Username
> 
> Piyush Baderia, Dream11, DevOps Engineer, [piyush.baderia@outlook.com](mailto:piyush.baderia@outlook.com), Piyush Baderia

@pbaderia01 - Thanks for showing your interest. 




> @kesseract @pbaderia01 👋 Hi, I am from Mumbai as well.
> 
> Can you elaborate on why it might help to have a separate KCD Mumbai conference as well, given that we have KCD Bengaluru too? To be clear, I don't want to block the effort. I am just curious. 😊
> 
> We don't have a big k8s community in Mumbai. It also looks like most folks are burnt out from virtual conferences. I think it would have been wonderful if we were able to do this in person but the virtual aspect of it might not draw a big audience.

@nikhita  - Thanks for looking into it and your wise thought. I agree with you to some extent. Based on your comment, below are my thoughts:

1. Since KCD Bengaluru is scheduled on 26th June 2021, can we look for KCD Mumbai dates in December or during shut down period? With this, there will be 6 months gap between both the virtual events. Many IT folks will have less work and will not go on a vacation due to pandemic. We may get a good number of participants during that period of time.

2. You are right, we don't have a big K8s community in Mumbai. Can we club Mumbai & Pune cities together? Both of these cities have a huge number of IT professionals. 

3. Considering the release cadence and innovation of K8s and the ecosystem of projects around it,  we have a lot of good subjects to cover which are not a part of the agenda of the KCD Bengaluru Event.

4. Since many banks and financial institutions have started using Kubernetes in production, current K8s community events are having no or less focused on FSI and other industry verticals. How to target participants from those financial institutions?

If you think the above points are not justifiable for KCD Mumbai/Pune event, we can drop this event for 2021.

@xmulligan  - Any thoughts on this?

**Comment by pbaderia01** [comment]
Hey @nikhita!

I understand that we don't have a big community in Mumbai at the moment but we're starting to garner some support for a community in Mumbai. I believe https://community.cncf.io/mumbai/ is evident of that (we've gone from about 5-6 members to 60 in the last couple of days) and we have many other meetups on the cards as well. This conference in itself will take a couple of months to form and will most likely be pushed till after Kubecon NA and very likely till early 2021 to avoid any overlap between the attendees. 

The original idea was to have an in-person conference (https://github.com/cncf/kubernetes-community-days/issues/240) but considering the situation, I believe that going forward almost all conferences will have a virtual aspect to them and this issue was created primarily to initiate the efforts in the right direction.

Hope this clears things up!

**Comment by xmulligan** [comment]
CNCF generally leaves it up to the community to decide what is best for them. You can wait for in person to come back or if the community is still growing, you could also consider a smaller event. Washington DC is doing a half day event since they have a smaller community. https://community.cncf.io/events/details/cncf-kcd-washington-dc-presents-kubernetes-community-days-washington-dc-2021/

It is totally fine if multiple cities want to team together to create an event as long as everyone agrees to it.

For FSI, you might want to reach out to the https://github.com/cncf/financial-user-group

Let me know if there is anything else I can help with.

**Comment by pbaderia01** [comment]
@xmulligan The idea to have a smaller event sounds really great! I will try and sync up with a couple of other organisers/community leaders to see which communities can make a joint effort to organise a single event.

**Comment by kesseract** [comment]
> CNCF generally leaves it up to the community to decide what is best for them. You can wait for in person to come back or if the community is still growing, you could also consider a smaller event. Washington DC is doing a half day event since they have a smaller community. https://community.cncf.io/events/details/cncf-kcd-washington-dc-presents-kubernetes-community-days-washington-dc-2021/
> 
> It is totally fine if multiple cities want to team together to create an event as long as everyone agrees to it.
> 
> For FSI, you might want to reach out to the https://github.com/cncf/financial-user-group
> 
> Let me know if there is anything else I can help with.

Thanks Bill, for your suggestion.

FSI User Group doesn't seem to be active. I think we can engage if few people starts discussion around this FSI community.


> @xmulligan The idea to have a smaller event sounds really great! I will try and sync up with a couple of other organisers/community leaders to see which communities can make a joint effort to organise a single event.

Agree with you Piyush. Let's work on it.

**Comment by xmulligan** [comment]
@kesseract do you have any updates on this event?

**Comment by kesseract** [comment]
@xmulligan - We need to move this event early next year. I have tried reaching out to multiple CNCF community members but I am not seeing active participation. I am happy to jump on a call to discuss this with you and @pbaderia01

**Comment by xmulligan** [comment]
@kesseract thanks for the update, I would be happy to have a call with you. I also have a couple ideas about how to make this program unique based on what other KCDs have done to be successful. You can book a call with me anytime with https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-09 Looking forward to connecting :)

**Comment by kesseract** [comment]
@xmulligan - As discussed I am closing this issue. We will plan an in-person event in 2022.
