### ISSUE TITLE
KCD Amsterdam 2023 (February 23-24)

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#389]
We are back for a great edition in 2023! We have set the dates (23+24 February) and the venue. More info: https://bit.ly/kcdams , sponsor prospectus: https://bit.ly/kcdams-sponsor , CFP: https://bit.ly/kcdams-cfp

### Event Location:

[WesterUnie/Westergasterras](https://www.westerunie.nl/) (Amsterdam, The Netherlands)

### Event Date and Time:

23+24 February, 2023

First day: Conference+speakers dinner+ workshops
Second day: Conference+BBQ+Attendee's party!

### Event type: 

Hybrid: in-person+remote attendance, all keynotes and sessions streamed and recorded, virtual and physical booths, and more ways to enjoy the event remotely.

### Submission checklist:

*Please check each of these as you complete them:

* [X] No other Kubernetes Community Day event in the same region 
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] Minimum of 3 sponsors committed
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Agree to use SM Apply for CFP (exception agreed with CNCF, since we had an outstanding sessionize event with 60+ papers already, we can use that).
* [X] Event date and time has been chosen
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [X] Organizer email alias has been created

CFP open and close dates (at least 6 weeks ahead of the event):
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created (organizers-netherlands@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [ ] Marketing Plan shared

### Post Event checklist:
* [x] Post event survey sent out
* [x] Removed from Bevy header
* [x] CFP deactivated
* [ ] Videos uploaded to YouTube and linked to event page
* [ ] Collect event analytics

### Expected Number of Attendees:

400+

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username

Alessandro Vozza, Microsoft/CNCF/Lovelace Engineering, CNCF Ambassador, alessandro.vozza@outlook.com, UAPQCHK1B

### Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username

Andrea Giardini, Freelancer / Overstory B.V. , Infrastructure Engineer, contact@andreagiardini.com, Andrea Giardini @AndreaGiardini

### Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username

Lian Li, Loft.sh, Developer advocate, cncf@lianmakesthings.dev, Lian Li

### Organizer 4: First and Last Name, Company, Title, Email, CNCF Slack Username

Andy Repton, Red Hat, Black belt, cncf@falconsupport.com or a.repton@gmail.com, Andy

### Sponsor 1

Microsoft

### Sponsor 2

Fullstaq

### Sponsor 3

Lovelace Engineering

### Fiscal sponsor that will accept payments

Lovelace Engineering B.V. (Registered in NL with number 64231798)

**Comment by xmulligan** [comment]
@ams0 thanks for putting this together! Let me know when you have a third organizers and I can start moving forward from the CNCF side. Excited to have this again!

**Comment by ams0** [comment]
@xmulligan we have 3 organizers (more in fact) and we're all geared up for 2022. We have a date (12-13 May, close to Kubecon but should be fine).

**Comment by xmulligan** [comment]
@ams0 thanks for putting together the organizers! Really looking forward to the event!

You have the date listed in the top as April 14-15, but say May 12-13. Which is it? Can you also add the Twitter handle there too?

I've created the KCD Netherlands chapter in Bevy and added you and Andrea. Fabrizio Marras doesn't have an account yet on Bevy. Let me know if you want to add anyone else. 

I've added each of the organizers to the email forward organizers-netherlands@kubernetescommunitydays.org.

**Comment by xmulligan** [comment]
@ams0 I just wanted to check in with you. Do you have any updates on the dates? Also once you get into the full swing of planning, I would like to set up a monthly check in with the team to make sure everything is on track and help resolve any issues

**Comment by xmulligan** [comment]
Hi @ams0 just wanted to check in with you before the end of the year. Is there anything you need from me to plan your KCD for next year?

**Comment by ams0** [comment]
Hi there, nothing special, we are starting to contact sponsors and get everything ready for October 2022 this month. Events are coming back in-person and we are planning some meetups too soon. We would like to create the event page this month, it's under "KCD Netherlands" (I have access) and create a "Meetup", right?

**Comment by xmulligan** [comment]
Sounds good, Please create the "Conference" event type

**Comment by ams0** [comment]
https://community.cncf.io/events/details/cncf-kcd-netherlands-presents-kubernetes-community-days-amsterdam-2022/

We also have a Github org and a repo where we will store other assets (sponsor prospectus for example: https://github.com/KubernetesCommunityDaysAmsterdam/kcd2022)

**Comment by xmulligan** [comment]
@ams0 Hope the new year is starting well for you! When do you want to start the monthly check ins? and when will you move forward with planning the event?

**Comment by AndreaGiardini** [comment]
Hello @xmulligan 

We found out that the dates KCD Amsterdam conflict with Kubecon Detroit, which is unfortunate... We met with the venue last Tuesday and we are waiting to get their availability for a new date. Ideally, we will have KCD Amsterdam a couple of weeks before/after Kubecon Detroit. As soon as we get the availability of the venue we will make a final decision on the dates

**Comment by xmulligan** [comment]
@AndreaGiardini Thanks for the update! Let me know if you need anything in the meantime

**Comment by k8tgreenley** [comment]
@ams0 when you have confirmed your new dates, please update the issue to reflect. I would also like to set up a call once you have confirmed your dates for us to set up Bevy and SMapply

**Comment by ams0** [comment]
Thanks @k8tgreenley , dates are confirmed by the venue, we will shortly put the event on community.cncf.io back up and re-open CFP and sponsor signup. Happy to have a call with @AndreaGiardini and you to get started (again :))

**Comment by k8tgreenley** [comment]
@ams0 Great! I am excited to talk to you about getting your event started, again :) I also would like to hear more about your current experience with the program so far. Please use this link to [Book a Meeting with Me](https://calendly.com/kgreenley/katie-greenley). 

I will be onsite next week for Open Source Summit + Embedded Linux Con North America.

**Comment by AudMonte01** [comment]
Hi @ams0 and @AndreaGiardini - It was a pleasure meeting with you both yesterday!

Before I create your SMapply CFP and Bevy event, please update as much as you can in the above issue. For example, the date as 23+24 February 2023, as well as your CFP dates (closing at least 6 weeks prior to the event). Please ping me here once you have done so. Thank you in advance. :-)

**Comment by AudMonte01** [comment]
Thank you, @ams0 ! I just sent you @AndreaGiardini and Fabrizio a platform update via email, with next steps.

**Comment by lianmakesthings** [comment]
Hi all, excited to join the organising team 🎉 
 First and Last Name, Company, Title, Email, CNCF Slack Username
Lian Li
Loft Labs
Developer Advocate
cncf@lianmakesthings.dev
Lian Li on Slack (there are a couple former accounts, I'm the one who's online 😬)

**Comment by AudMonte01** [comment]
Hi everyone! Looking forward to our touch-base tomorrow.

Aside from following up about Bevy Pay, and generally where you are at in the planning process - @ams0, is there anything you and the team want to be sure to cover in this meeting?

**Comment by Seth-Karlo** [comment]
Hi all, I'm also interested in helping to organise. I've spoken with @ams0 already about this, but making a formal request here. Adding some info and please let me know next steps:

Andy Repton
Red Hat
Managed OpenShift Black Belt
cncf@falconsupport.com
Andy on Slack, or SethKarlo depending on time account was created

**Comment by AudMonte01** [comment]
Thank you @Seth-Karlo and @ams0 - I have added Seth-Karlo as an admin to SMapply. In order to add you as a Host/Organizer to [this page](https://community.cncf.io/events/details/cncf-kcd-netherlands-presents-kubernetes-community-days-amsterdam-2023/), please create an account [here](https://sso.linuxfoundation.org/login/?state=hKFo2SBDVmhjY1l5U0ZkSVUzUjRTMklQcG04aWViU2N4eEpTWKFupWxvZ2luo3RpZNkgYnFaZ0tKME9PVFhkVWhqUzhTSWIxRHpxNWp3c2JJQUGjY2lk2SBBY1ZGUFlMTGZXdHh2dW83TUpDeldPcVQ5ZkJMY1B0Tg&client=AcVFPYLLfWtxvuo7MJCzWOqT9fBLcPtN&protocol=oauth2&redirect_uri=https:%2F%2Fcommunity.cncf.io%2Faccounts%2Fauth0%2Flogin%2Fcallback%2F&scope=email%20profile%20openid&response_type=code).

**Comment by Seth-Karlo** [comment]
I've created the account!

**Comment by AudMonte01** [comment]
> I've created the account!

Thank you, @Seth-Karlo - what is your email address? I cannot find you when I type your name. It may also be that you first need to become a member of the Netherland community [here](https://community.cncf.io/kcd-netherlands/).

**Comment by Seth-Karlo** [comment]
@AudMonte01 You can use cncf@falconsupport.com for me :-) It'll come through!

**Comment by ams0** [comment]
I noticed the search works in the chapter page but not on the event page, I think I had to create the organizers there manually, not a big deal tho

**Comment by AudMonte01** [comment]
Yes @ams0 - thank you! @andycochran shows up now.

**Comment by AudMonte01** [comment]
1/11/23 MEETING NOTES

Publishing program soon
4 workshops in the morning (1.5 hours)

Diversity out of 22 speakers
* non-male speakers 6  (27%)
* underrepresented 9 or 10 (45%)

Fun ideas
* DJ Booth
* Stand-up comedian 
* Arcade machines run a broken K8s cluster
* Ping Pong table
* Friday BBQ with German DJs (have a sponsor) with drinks

To-Do
* Audra to follow-up with @k8tgreenley re design assets. But first, we need to know design vendor's print deadline
* @k8tgreenley to share KubeCon discount codes with organizers once ready
* Audra to look into other regional speakers who can keynote in the area, as well Priyanka for a Friday keynote
* Audra already added a note about sponsorships opportunities in KubeWeekly newsletter (goes out Friday January 13)

**Comment by ams0** [comment]
We implemented all the fun ideas (except the ping pong table :D) and the party is here https://ra.co/events/1652319

As of today we have 274 tickets sold, 20 silver, 7 gold, 5 bronze, Party and bbq sponsor, 6 keynotes, 24 speakers, 4 workshops and lighting talks all sorted out. Full steam ahead in selling the last 100ish tickets, we can use some help on social media from CNCF! @AudMonte01

**Comment by ams0** [comment]
Update: we sold out 3 days in advance, 450 ticket sold. I'd like to thank the organising committee::

@AndreaGiardini
@Seth-Karlo 
@ayodejidev
@wrkode
@pmusa
@mkerker
@srknc
@meglicious

who created a beautiful event machine with little previous experience. I'm humbled and excited for this week! I've been dreaming about it for 3 years, I'm privileged to finally see the dream come true and the community step up big time.

**Comment by ams0** [comment]
Pictures are here: https://cloudnative.amsterdam/images/album/2023/photos/ and report is in the making

**Comment by AudMonte01** [comment]
Excellent! We are excited to hear more. This looks like a successful event! Please see my email to schedule a retrospective. Alternatively, here is my calendly: https://calendly.com/audmonte/kcd-restrospective

**Comment by AudMonte01** [comment]
RETROSPECTIVE MEETING ON 3/13/2023

Speakers
* Most professional speakers that applied to CFP were vendors (tried to alleviate pitching). These came in via the CFP ahead of sponsorships
* Thursday (Day 1) was speakers dinner
* Speakers were very engaged on social media

Attendees
* Didn't spam the attendees with much email
* Friday (Day 2) was attendee party (BBQ)

Tools
* Used Sessionize for CFP and scheduling (replaced Bevy eventually)

Sponsors
* Many of them signed up close to event (end of fiscal year may affected this)
* Sponsors didn't seem to care much about their plug in the email or social media
* Good feedback on the amount of end-users that were attending

Attendee Feedback
* Only negative feedback was the venue was cold, and some feedback around the food
-- Vegan food for everyone (sustainability message and easy to accommodate everyone)

Organizer Feedback
* Only a handful of attendees were at the 2019 event, so it was good to start a new initiative this year
* 2024 event, they will wait until KubeCon EU is announced and plan for it be afterwards
* Only 5% of food waswasted
* Might have a party on both days so the majority of people can attend on Day 1

To-Dos
* @ams0 to send Audra videos once they are complete
* @AndreaGiardini to update this GitHub issues with all organizers so CNCF can properly assign Credly badges
* Google drive of resources will be shared with other KCD organizers

**Comment by AudMonte01** [comment]
* Post event transparency report can be [found here](https://docs.google.com/document/d/13EPy1fQPOo9FJiZW54aybc2puKg-ZPtFSlmpyOZDSCs/edit)
* Videos can be [found here](https://www.youtube.com/@kubernetescommunitydaysams8302/streams).
-- Audra to create a playlist via the CNCF YouTube channel

**Comment by ams0** [comment]
Videos playlist[ here ](https://www.youtube.com/watch?v=1OWL6Yjfaj8&list=PLj6h78yzYM2NPE43-gdq3s4phTqR_Q-oG&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D) and blog post [here](https://www.cncf.io/blog/2023/04/11/the-longest-running-kubernetes-community-days-is-back/)

Let's close this one, on and onwards to KubeconEU now and soon announcing plans for KCD Amsterdam 2024!
