### ISSUE TITLE
Use CommonMark-compliant Markdown processor

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#39]
Hugo uses BlackFriday which has subtle incompatibilities with the GitHub preview renderer. 

For example, it requires a return above bullets:
https://github.com/cncf/kubernetes-community-days/commit/99aee7683811cf26de819dc6f514c566c9824007

Switch to using the new Goldmark processor instead.
https://github.com/russross/blackfriday/issues/329

Goldmark support in Hugo is underway
https://github.com/gohugoio/hugo/issues/5963

It may become the new default in 0.58, in which case we would just need to upgrade when that ships.

**Comment by lucperkins** [comment]
The site has been switched to Hugo 0.62.2, which supports GoldMark by default

**Comment by dankohn** [comment]
Fanatstic!
