### ISSUE TITLE
Kubernetes Community Day Italy 2021

### ISSUE THREAD

**Issue by bsctl** [cncf/kubernetes-community-days#395]
### Event Location:
Milan, Italy

### Event Date and Time:
17/18 November 2021

### Event type: 
Virtual

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organisers from 3 different organisations
* [x] Every organiser has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organiser lives in or just outside of the KCD location
* [x] At least one organiser is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organisers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organisers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Organizer email alias has been created

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Organisers
Organiser 1: Adriano Pezzuto, CLASTIX, Founder, adriano@clastix.io
Organiser 2: Jacopo Nardiello, SIGHUP, Founder, jacopo@sighup.io
Organiser 3: Paolo Mainardi, SparkFabrik, CTO, paolo.mainardi@sparkfabrik.com
Organiser 4: Fabrizio Pandini, VMware, Member of Technical Staff, fpandini@vmware.com
Organiser 5: Natale Vinto, Red Hat, Solution Architect, nvinto@redhat.com
Organiser 6: Chiara Muzzolon, Mia-Platform, Marketing Communications Specialist, chiara.muzzolon@mia-platform.eu
Organiser 7: Diego Braga, Cloud Native Solution Architect, Kiratech, diego.braga@kiratech.it

### Sponsors
Sponsor 1: [CLASTIX](https://clastix.io)
Sponsor 2: [SIGHUP](https://sighup.io)
Sponsor 3: [SparkFabrik](https://sparkfabrik.com)
Sponsor 4: [Mia Platform](https://mia-platform.eu)
Sponsor 5: [VMware](https://vmware.com)
Sponsor 6: [Red Hat](https://redhat.com)
Sponsor 7: [Kiratech](https://kiratech.it)

### Fiscal sponsor that will accept payments
[APROPOS](https://www.apropos.srl)

**Comment by xmulligan** [comment]
@bsctl thanks for putting this together!

I've updated the email forward organizers-milan@kubernetescommunitydays.org to all of the organizers listed above. A note on the date, #387 will be hosted September 15-16 and KubeCon NA will be October 12-15. I'm not sure how much overlap there will be between the audiences for the different events, but I just wanted to make you aware while you are scheduling.

Do you have an expected number of attendees? Also when will you be creating a Twitter account?

I've created a CfP for you in SMApply and made you the admin. Let me know if you want me to add anyone else. 

I've also created your chapter in Bevy and made you an admin. You have a couple accounts, but it is under the hello@clastix email. I've also added all of the other organizers to the chapter. It is currently hidden so you can add details before it goes live.

Let me know if you have any questions!

**Comment by bsctl** [comment]
@xmulligan thanks for your review. Actually, the date of Sept 2021 is just a placeholder. We'll update it as soon we find a suitable date.

**Comment by xmulligan** [comment]
@bsctl good to know. Just wanted to make sure you were aware and let me know when you finalize the date.

**Comment by bsctl** [comment]
Hey @xmulligan could you please add Annalisa.Gennaro@sparkfabrik.com to organizers-milan@kubernetescommunitydays.org? She’ll help us for the organization.  @paolomainardi

**Comment by xmulligan** [comment]
@bsctl yes, I've just added her to the forward

**Comment by fabriziopandini** [comment]
Yay!

**Comment by bsctl** [comment]
@xmulligan since no other events in Italy, we wonder to ask you if we can rename it as "Kubernetes Community Day Italy 2021"

**Comment by xmulligan** [comment]
@bsctl that is fine for me unless another event in Italy steps forward and also wants to have an event

**Comment by bsctl** [comment]
> @bsctl that is fine for me unless another event in Italy steps forward and also wants to have an event

Thanks for quick replay. In such case, we'll manage it.

**Comment by xmulligan** [comment]
@bsctl I've also updated the name of the chapter in Bevy

**Comment by paolomainardi** [comment]
thanks a lot @xmulligan

**Comment by xmulligan** [comment]
@paolomainardi have you chosen a date for the conference yet? Also  do you know when the CfP will  launch?

**Comment by paolomainardi** [comment]
@xmulligan hi! Yes, we have a date: **17/18 November 2021** 
The CFP  date is still on hold as we need to launch the website, i'll keep you posted.

**Comment by xmulligan** [comment]
@paolomainardi Great! Looking forward to the final confirmation. Let me know if you need any help with the website or CfP

**Comment by fabriziopandini** [comment]
@xmulligan date confirmed. We are going to follow up with dates for CFP asap

**Comment by xmulligan** [comment]
Awesome! Can you just udpate it in the issue at the top. Excited to see the CfP launch

**Comment by xmulligan** [comment]
@fabriziopandini do you know when you will be ready to launch the CfP? Our newsletter is going out next Friday and it would be great to include

**Comment by fabriziopandini** [comment]
@xmulligan we have a tentative calendar with CFP opening the 15th of July and closing the 15th of September. I will confirm dates after our sync up on Monday next week

**Comment by bsctl** [comment]
@xmulligan hello we have renamed the event from "KCD Milan to KCD Italy. Could you please update the email forward `organizers-milan@kubernetescommunitydays.org` to `organizers-italy@kubernetescommunitydays.org`? Thank you very much!

**Comment by annalisag-spark** [comment]
@xmulligan we solve with @idvoretskyi in the meantime ;)
thanks anyway!

(e grazie @bsctl !) 

> @xmulligan hello we have renamed the event from "KCD Milan" to "KCD Italy". Could you please update the email forward `organizers-milan@kubernetescommunitydays.org` to `organizers-italy@kubernetescommunitydays.org`? Thank you very much!

**Comment by xmulligan** [comment]
Sorry was out on vacation, glad you were able to resolve it in the meantime. Let me know if you need anything else :)

**Comment by xmulligan** [comment]
I would also like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by annalisag-spark** [comment]
That's awesome! We will all be back at the end of August (here in Italy it's vacation time, more or less) and we'll have a team meeting on the 6th of September at 5:00 pm CEST to go through the scheduled pending activities.

What about a day picked during that week, same time? I do not remember where you are located though.

**Comment by xmulligan** [comment]
@annalisag-spark I'm based in Germany so quite easy :) 

I can do that same time any day that week except Thursday (9th) Let me know what which works and you can send an invite to bmulligan@linuxfoundation.org

Enjoy your vacation!

**Comment by annalisag-spark** [comment]
oh ok, cool!
let's say Wednesday 8th at 5:00 pm.

we send you a placeholder and confirm when everyone is back.
in the meantime, enjoy your German summer - staycation, workcation, vacation, whatever you are gonna experience ;)

and thanks!

**Comment by xmulligan** [comment]
Perfect! Enjoy your vacation too :)

**Comment by xmulligan** [comment]
Really loved this event! Hopefully we can be in person next year and I can get some pizza IRL 🍕
