### ISSUE TITLE
KCD Latin America 2021 -- Virtual

### ISSUE THREAD

**Issue by pasimoes** [cncf/kubernetes-community-days#397]
# Kubernetes Community Days Latin America 2021 -- Online Edition

## Goals and Objectives
The main objective is to create a platform for community members to share their knowledge, tips, tricks, use-cases, and learning. Kubernetes and the cloud-native eco-system is very popular in the region, a major KPI of this event will be how much interest we can create towards learning, using, or contributing to the projects.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and payout expenses
* [ ] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [ ] Agree to use SM Apply for CFP
* [ ] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [ ] Organizer email alias has been created
* [ ] Region and event has been created in Bevy

**Comment by xmulligan** [comment]
@pasimoes thanks for putting this together! Really looking forward to seeing this event come together. Let me know if you have any questions or if there is anything I can help with

**Comment by xmulligan** [comment]
Just wanted to check in on the planning of this event. Do you have a rough date for it?
