### ISSUE TITLE
KCAD UFRJ Brasil 2021 -- Virtual

### ISSUE THREAD

**Issue by pasimoes** [cncf/kubernetes-community-days#400]
Kubernetes Community Academy Days UFRJ, Brasil 2021 -- Online Edition

## Goals and Objectives
The main objective is to create a platform for community members to share their knowledge, tips, tricks, use cases, and learning for students and teachers of the Academy and assist in community expansion to the Academy. Kubernetes and the native cloud ecosystem are very popular in the region. An important KPI for this event will be how much interest we can create to learn, use or contribute to the projects.

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Minimum of 1 organizer from the Academy Institution
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCAD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Minimum of 3 sponsors committed
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and payout expenses
* [ ] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Please list who should be added as an admin for the CFP:
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCAD event (except for countries like China and Korea where Twitter is not used) 
* [ ] Organizer email alias has been created
* [ ] Region and event has been created in Bevy

### Member 4: Valeria Bastos, **UFRJ**, Professor & Research, valeriab@dcc.ufrj.br, CNCF Slack TBD

**Comment by xmulligan** [comment]
This is amazing and I can't wait to see this event come together! Let me know if you need any help along the way 🎉

**Comment by xmulligan** [comment]
@pasimoes I know the event date is a month away. Do you think you have enough time to plan and execute the event? Is there anything that CNCF can help with?

**Comment by pasimoes** [comment]
> @pasimoes I know the event date is a month away. Do you think you have enough time to plan and execute the event? Is there anything that CNCF can help with?

Yes. We will make it.

**Comment by pasimoes** [comment]
Cancelled 😞
