### ISSUE TITLE
KCD Indonesia 2021 - Virtual

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [cncf/kubernetes-community-days#402]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location:
Online

### Event Date and Time:
27/11/2021

### Event type: 
Virtual

### Submission checklist:
*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] All organizers take LFC102: https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and payout expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Please list who should be added as an admin for the CFP: 
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Provided CNCF access to all event social handles

CfP open and close dates: 08-06 to 09-15
Website launch date: 2021-08-27

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

### Expected Number of Attendees:
300

### Organizer
- Zufar Dhiyaulhaq, Gojek, Cloud Platform Engineer, zufar.dhiyaulhaq@gojek.com, Slack: Zufar Dhiyaulhaq
- Irwan Shofwan, Gojek, Cloud Platform Engineer, irwan.shofwan@gojek.com, Slack: N/A
- Sartika Lestari, Boer Technology, Marketing, sartika@btech.id, Slack: N/A
- Bachril Qirom, Tokopedia, DevOps Engineer, bachril.qirom@tokopedia.com, Slack: N/A
- Giri Kuncoro, Gojek, Senior Software Engineer, giri.kuncoro@gojek.com, Slack: Giri Kuncoro (CNCF ambassador)
- Muhammad Luthfi As Syafii, Boer Technology, Cloud Engineer, luthfi@boer.id, Slack: N/A
- Go Frendi Gunawan, kata.ai, Software Engineer, gofrendiasgard@gmail.com, Slack: N/A
- Dewa Putu Prasta Maha Gangga, Boer Technology, Cloud Engineer, prasta@btech.id, slack: N/A
- Aris Cahyadi Risdianto, NUS, Research Fellow, aris@comp.nus.edu.sg, slack: N/A

### CFP Admin
- Giri Kuncoro, Gojek, Senior Software Engineer, girikuncoro@gmail.com, Slack: Giri Kuncoro (CNCF ambassador)
- Aris Cahyadi Risdianto, NUS, Research Fellow, aris@comp.nus.edu.sg, slack: N/A
- Zufar Dhiyaulhaq, Gojek, Cloud Platform Engineer, zufardhiyaulhaq@gmail.com, Slack: Zufar Dhiyaulhaq
- Irwan Shofwan, Gojek, Cloud Platform Engineer, abigaelse2@gmail.com, Slack: N/A

### Sponsor
- TBD

We are looking for sponsorship, anyone who is interested can contact organizer@kubernetesdays.id.

### Fiscal sponsor that will accept payments
Perkodi (https://perkodi.org/). Non-profit organizations in Indonesia.

**Comment by zufardhiyaulhaq** [comment]
cc  @cloudnative-id/kubernetes-community-days

**Comment by zufardhiyaulhaq** [comment]
@xmulligan can you check and verify? thanks.

**Comment by zufardhiyaulhaq** [comment]
@xmulligan we also have several questions about KCD.
1. did we get free SurveyMonkey for CFP and Bevy for the event free from CNCF?
2. how we create KCD page on community.cncf.io, did we need to submit it to some repository?

**Comment by idvoretskyi** [comment]
1. Yes
2. We’ll create it for you once the event is approved

**Comment by zufardhiyaulhaq** [comment]
Hi @idvoretskyi,

Since @xmulligan is out of the office until 22 August, do you know other people who can approve this? since we want to have CFP, search for sponsors, and do the marketing as soon as possible to get more people to contribute and join the event.

**Comment by idvoretskyi** [comment]
@zufardhiyaulhaq I believe that Bill is coming back sooner, so let's wait for him :)

**Comment by zufardhiyaulhaq** [comment]
@idvoretskyi for the online conference, it's also using Bevy platform provided by CNCF right?

**Comment by xmulligan** [comment]
@zufardhiyaulhaq sorry for the delay getting back to you, just getting back from vacation and Github doesn't have an OOO yet :D 

Yes the CfP and Bevy platform for the conference will be provided by CNCF

It looks like you already have many of the boxes completed. One that has been recently added and hasn't been updated in the template yet is that the CFP admins must take [Inclusive Open Source Community Orientation](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/). Once you take it, I can provide you access to both SM Apply and Bevy

Let me know if you have any other questions :)

**Comment by xmulligan** [comment]
I've also added the organizers-indonesia@kubernetescommunitydays.org alias to go to all of the organizers

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan, can you forward the alias to organizer-kcd-indonesia@googlegroups.com since our organizer email (organizer@kubernetesdays.id.) also forward to this group. So in the future, if we need more organizers, we can add directly to the group without involving you.

**Comment by xmulligan** [comment]
@zufardhiyaulhaq yes, organizer-kcd-indonesia@googlegroups.com has been added too :)

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan we currently have two people from the organizer that will be reviewing CFP, both of them already take the LFC102 course, you can see the progress tracking here https://github.com/cloudnative-id/kubernetes-community-days/issues/13.

can you help create the SM and Bevy?

**Comment by xmulligan** [comment]
Great! I just created the accounts for you, let me know if anyone else needs access.

Have you planning on having sponsors for the event?
Can you give me access to the social handles for the events?

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan, will give you a list of people that need access to the Bevy. 

Yes, we plan on having sponsors for the events.
We only have Twitter for the KCD but until still not managed, since we still plan for proposal & CFP.

**Comment by zufardhiyaulhaq** [comment]
also @xmulligan please check [this document](https://docs.google.com/document/d/1xcLsZtpZXWm9ZueT67rRwBDEAhOuUnSB_KQKOUEgym8) related to CFP. we are in progress for the content tracked here. https://github.com/cloudnative-id/kubernetes-community-days/issues/6

**Comment by xmulligan** [comment]
@zufardhiyaulhaq can you give me access to it?

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan give you the access. please check Slack. Also, I collect several questions from other organizer:
1. We plan to make this event a paid event with low price to allow student participations. The reason behind it is because we don't want to have a high drop rate. As a commitment fee of 2$, we will send them a small merch. For the paid events, do we have any flow or requirements that we must pass?
2. Yesterday, my team is checking Bevy, and she said that we only can add a maximum of 10 speakers, it's correct?
3. Is the virtual event permalink generated from bevy (community.cncf.io) identical with the video streaming link for the day event? 
- If yes, so the attendees and organizers will able to access the streaming only on the day event? Then how if we want to do some tests (dry run) before the event?
- If no, where and how can we run a test of bevy features or setting up the platform? maybe the event’s backstage link, etc.
- If we don’t have any access, can we get the explanation about how to use, event schema, how to have interaction with audiences, the backstage, and others bevy features we may use for this event?
4. Just to clarify, In the event dashboard > sponsors & partners, to create sponsor, we need to create invoice details as well. What is this feature used for? do invoices to sponsors need to be submitted via the bevy platform? or do the details need to submit just as saved documents?

**Comment by xmulligan** [comment]
@zufardhiyaulhaq thanks for access! To answer your questions:

1. All of our previous virtual events have been free without a large drop rate. If you still want to be able to charge for the event, would you be willing to donate the proceeds to the CNCF scholarship fund? Reimbursing them to you is also possible just more complicated.
2. You don't need to use that feature. You can do all of your invoices without using Bevy. It is only there as optional.
3. You shoud have access to virtual confernce now

let me know if you need anything else :)

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan thanks for the answer, we will get back to you by EOW.

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan

We decide to make this even free, with an additional package of merchandise (IDR 100.000 or 7$) that people can choose from, and we will send them a merch like a t-shirt and a sticker pack (all money will be returned to them in the form of merchandise).

We are ready to open CFP, can you help us give access to smapply.io?

**Comment by xmulligan** [comment]
@zufardhiyaulhaq sorry I forgot to note it here earlier. I already created the SM Apply account and gave Giri  and Aris access. They should have both already received emails about it three days ago. Let me know if they didn't and I can resend. Or if anyone else needs access.

**Comment by xmulligan** [comment]
Sounds good about the merchandise 💯

**Comment by zufardhiyaulhaq** [comment]
Hi, @xmulligan I need to check with Giri and Aris. meanwhile, can you give me access to the SM Apply? 

FYI, In the next few days or months, we will actually have more people for CFP reviewers, we want to invite people from other open-source organizations in Indonesia like OpenStack, DevOps, and Open Networking community.

**Comment by xmulligan** [comment]
@zufardhiyaulhaq you should have the invite now too. For reviewers, you should be able to invite them yourself https://help.smapply.io/hc/en-us/articles/115001428533-How-to-Add-Remove-a-Reviewer

Let me know if you need anything else :)

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan thanks. we finish setup the smapply.io to accept CFP, can you help take a look?

**Comment by zufardhiyaulhaq** [comment]
Thanks @xmulligan we will publish our KCD page and CFP today.

**Comment by xmulligan** [comment]
Awesome news! I would also like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan sure, let me discuss with other organizers the prefered time from our side.

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan we will set up a monthly check with you, start on 19 August. Meanwhile, can you move our status to CFP Launch in https://github.com/cncf/kubernetes-community-days/projects/2? thanks

**Comment by xmulligan** [comment]
Done! Looking forward to catching up with you

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan scheduling a monthly check for August with you. Also, do you know how this event can be published on the cncf.io website?

**Comment by xmulligan** [comment]
@zufardhiyaulhaq perfect, thanks for doing that. Where would you like it published? It is already automatically on the LF community events. https://events.linuxfoundation.org/about/community/

**Comment by xmulligan** [comment]
@zufardhiyaulhaq it looks like you have a great number of CfP submissions! Do you want to schedule our next check in? https://calendly.com/billmulligan/1-1-with-bill-mulligan?month=2021-06

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan did you have a KCD slide template that we can use for our speakers?

**Comment by xmulligan** [comment]
@zufardhiyaulhaq yes sorry, I forgot to send this sooner https://docs.google.com/presentation/d/1H6Mxsp3bBy5LzqVni5FZGE679XB8OG4h/edit?usp=sharing&ouid=101495988975166790399&rtpof=true&sd=true

**Comment by xmulligan** [comment]
@zufardhiyaulhaq I just wanted to check back in with you. Do you know when you will upload the videos to Youtube? Anything else you need help with to wrap up this event?

**Comment by zufardhiyaulhaq** [comment]
Hi @xmulligan we already upload the video to our channel.
https://www.youtube.com/playlist?list=PLDAA8KTg2foaQ11_OtwD3KPDEaHNIe2Zk

It's possible to add this to CNCF channel? thanks

**Comment by xmulligan** [comment]
Perfect, I just added it to the CNCF channel https://www.youtube.com/playlist?list=PLj6h78yzYM2PcnQdAVsHhcBAGJ4bNtNyb. I also found a couple videos I have to go back and watch! Lots of great content 🎊

**Comment by xmulligan** [comment]
I was also really impressed by the size and scale of the event your team was able to pull off. Awesome job  🥇
