### ISSUE TITLE
KCD Brazil 2021

### ISSUE THREAD

**Issue by KTan1226** [cncf/kubernetes-community-days#407]
### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles
* [x] Organizer email alias has been created

CfP open and close dates: 15/09-29/09
Website launch date: 08/09

### Submission checklist for CNCF:
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
Bill Mulligan, Marketing Manager, CNCF, bmulligan@linuxfoundation.org

### Sponsor 1
Getup
### Fiscal sponsor that will accept payments
CNCF

**Comment by KTan1226** [comment]
In order to serve the Brazilian cloud native community, CNCF will take over the lead organizer responsibilities and reschedule KCD Brazil to a new date. To learn more about our decision, please read this Twitter thread by our GM Priyanka https://twitter.com/pritianka/status/1415148020362977283?s=20.

**Comment by ellenkorbes** [comment]
> In order to serve the Brazilian cloud native community, CNCF will take over the lead organizer responsibilities and reschedule KCD Brazil to a new date. To learn more about our decision, please read this Twitter thread by our GM Priyanka https://twitter.com/pritianka/status/1415148020362977283?s=20.

"Para servir a comunidade cloud native brasileira, a CNCF vai assumir a liderança das responsabilidades de organização e remarcar o KCD Brasil para uma nova data. Para ler mais sobre nossa decisão, veja esta thread no Twitter da nossa GM Priyanka [...]"

**Comment by xmulligan** [comment]
@KTan1226 we are waiting to update the issue until it is all public. The planning doc is for internal purposes only

**Comment by xmulligan** [comment]
The event is now live
https://www.linkedin.com/posts/kcdbrasil_kubernetes-community-days-brasil-2022-cncf-activity-6841338934396506113-7cHM
https://twitter.com/kcdbrasil/status/1435573045486309376

**Comment by xmulligan** [comment]
Awesome event with over 3000 attendees 
![Copy of KCD Diversity Data](https://user-images.githubusercontent.com/29048870/153053043-534b5c00-dd40-4a7f-8346-06a05a5c56ee.jpg)
