### ISSUE TITLE
KCD Guatemala 2021

### ISSUE THREAD

**Issue by sergioarmgpl** [cncf/kubernetes-community-days#408]
### Event Location:
Guatemala

### Event type: 
Virtual

### Submission checklist:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Minimum of 3 sponsors committed
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [x] Please list who should be added as an admin for the CFP: Sergio Méndez
* [x] Event date and time has been chosen
* [x] All organizers have taken Inclusive Community Orientation
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) 
* [x] Access to Twitter provided to CNCF
* [x] Organizer email alias has been created

CfP open and close dates: Sep/17 - Oct/15
Website launch date: Sep/17

### Submission checklist for CNCF:
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

### Organizer 1:
Sergio Méndez, USAC University, Professor, sergioarm.gpl@gmail.com, CNCF Slack Sergio Méndez

### Organizer 2:
Erick Pineda, UVG University, Professor, ejpineda@uvg.edu.gt, CNCF Slack Erick Pineda

### Organizer 3:
Bart Farrel, Data on Kubernetes, CNCF Ambassador, bart@dok.community, CNCF Slack: Bart Farrell

### Organizer 4:
Leonel Aguilar,  USAC University, Student, leoaguilarsanchez97@gmail.com

### Organizer 5:
CARLOS RAMIREZ,  USAC University, Student, 2111724640101@ingenieria.usac.edu.gt

### Organizer 6:
Emily Mansilla: USAC University, Student, 202110524@farusac.edu.gt

### Sponsor 1
USAC University (Confirmed)

### Sponsor 2
Nabenik

### Sponsor 3
Yalo Pending to confirm (In progress)

### Sponsor 4
OReilly 5 Ebooks for the event (Confirmed)

### Sponsor 5
Software Guru (Confirmed)

**Comment by xmulligan** [comment]
@sergioarmgpl thanks for creating this, really looking forward to the event!

I've added each organizer to the slack channel. Let me know once you have more updates and need access to other things

**Comment by sergioarmgpl** [comment]
Sure, thanks for all 🙂😎

**Comment by xmulligan** [comment]
I've created the organizers-guatemala@kubernetescommunitydays.org forward for the organizers above.

If you are planning on having a social account, can you provide me access with it too?

**Comment by sergioarmgpl** [comment]
@xmulligan Thanks, I added Leo and Carlos as new organizers. About the social account, do you mean an email or the part to create the Twitter?

**Comment by xmulligan** [comment]
the twitter account, we already have access to the email :)

**Comment by xmulligan** [comment]
I've also added both Leo and Carlos to the slack channel and the email

**Comment by sergioarmgpl** [comment]
@xmulligan I created the Twitter is this https://twitter.com/kcdguatemala

**Comment by sergioarmgpl** [comment]
Do we have to complete this course? https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/ I read some of Priyanka's tweet. @xmulligan

**Comment by sergioarmgpl** [comment]
I have this other question, if our event is free, do we need this part:
- Fiscal sponsor that will accept payments
Or could you give an example about what I have to look for this requirement, maybe in my country refers to another thing. @xmulligan

**Comment by xmulligan** [comment]
@sergioarmgpl great, can you also provide me access to the twitter account?

Yes, you do need to take that course. It seems you are using the old issues template, but I'll add it above

No, you don't need a financial sponsor if you are doing the event virtual.

Let me know if you need anything else :)

**Comment by xmulligan** [comment]
I would also like to schedule a monthly check in with you until the event so we have a regular check in point where I can help you with any issues that have arisen. Obviously, you can also contact me or have a meeting outside that time too. Can you suggest a time that works for you?

**Comment by sergioarmgpl** [comment]
I think that 8AM GMT-6 works, but let me ask the other organizers. @xmulligan I sent you the password and user of our Twitter on the CNCF slack

**Comment by xmulligan** [comment]
Thanks I have received it. Let me know what time works to meet

**Comment by sergioarmgpl** [comment]
I think that I am the first one to finish the course.

**Comment by sergioarmgpl** [comment]
I think that 8AM GMT-6 works for me for the meetings @xmulligan

**Comment by xmulligan** [comment]
@sergioarmgpl sure, how about the last Wednesday of every Monday (starting on August 25th?)

**Comment by sergiopsyalo** [comment]
@xmulligan It works for me

**Comment by sergioarmgpl** [comment]
@xmulligan It works for me

**Comment by sergioarmgpl** [comment]
OReilly will provide us 5 ebooks for the event, Yalo is going to provide us some funds for the streaming with Streamyard, we are going to do the same as KCDSpain redirect Streamyard to Bevy

**Comment by racarlosdavid** [comment]
@sergioarmgpl I also finished the course

**Comment by leoaguilar97** [comment]
Hi! I finished the _**Inclusive Open Source Community Orientation**_ course last week!

**Comment by sergioarmgpl** [comment]
Update: @xmulligan.  
- I added myself as the CFP admin
- A third sponsor was confirmed
Pending that some of the organizers finish the Community Orientation course.

**Comment by sergioarmgpl** [comment]
@xmulligan Can you add Emily to the organizers she is going to manage our social network accounts, she is the designer, her email is 202110524@farusac.edu.gt

**Comment by sergioarmgpl** [comment]
@xmulligan the CFP will be launch this Monday.

**Comment by xmulligan** [comment]
Glad to hear about the CfP! What do you need me to add Emily to?

**Comment by sergiopsyalo** [comment]
Please add her to the mailing list, because she will be in charge of the Twitter account. @xmulligan

**Comment by xmulligan** [comment]
I've added  her to the email :) Let me know if you need anything else

**Comment by xmulligan** [comment]
Awesome event covering both students and professionals with content in English and Spanish. I'm sure this inspired many people 🎊

**Comment by sergioarmgpl** [comment]
Nice experience doing the event, I have pending a blog post about it.

**Comment by xmulligan** [comment]
Can't wait to read it! Let me know if you want to get it published on the CNCF blog
