### ISSUE TITLE
KCD 2022 Paris, France

### ISSUE THREAD

**Issue by rbenzair** [cncf/kubernetes-community-days#409]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

The information related to the original event scheduled in 2020 : https://github.com/cncf/kubernetes-community-days/issues/213

### Event Location:
City: Paris, France
Venue: https://stationf.co/venues/

### Event Date and Time:
Date: Q1 2022 (to confirm soon).

### Event type: 
We try to build a Hybrid event with in person in the venues but able to follow online.

### Submission checklist:

*Please check each of these as you complete them:

* [X] No other Kubernetes Community Day event in the same region 
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] Monthly check in with KCD Core Organizer scheduled
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Minimum of 3 sponsors committed (not required for virtual only events)
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Agree to use SM Apply for CFP
* [X] Please list who should be added as an admin for the CFP:
* [ ] Event date and time has been chosen
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles
* [ ] Organizer email alias has been created

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Expected Number of Attendees:

Team available on the CNCF Slack : #kcd-paris

### Sponsor 1
Enix.io
### Sponsor 2
RedHat
### Sponsor 3
OVHCloud

### Fiscal sponsor that will accept payments
The CNCF Paris is non-profit organization have a Bank Account (bank transfer preferred).

**Comment by xmulligan** [comment]
@rbenzair Thanks for putting this together! Looks like you already have a lot of the pieces. All of the organizers are already in the Slack channel and on the organizers-paris@kubernetescommunitydays.org email forward. Let me know when you have the dates chosen and the organizers have taken the training and we can work on getting everything built. :)

**Comment by xmulligan** [comment]
Hi @rbenzair  just wanted to check in with you. Do you have an update on the planned event date? Also, is there anything you need from me to plan your KCD for next year?

**Comment by xmulligan** [comment]
Great to hear! Let me know if you need anything before you kick off planning and we can set up meetings once you are ready

**Comment by xmulligan** [comment]
@Smana I hope you enjoyed the holidays 🎄 I wanted to check in on your current planning. Are you ready to start our monthly sync calls? https://calendly.com/billmulligan/1-1-with-bill-mulligan

**Comment by xmulligan** [comment]
@Smana @rbenzair are you still interested in hosting the event this year?

**Comment by Smana** [comment]
@xmulligan thanks for reaching out. Yes we're gonna have a meeting this month.

**Comment by xmulligan** [comment]
https://training.cmxhub.com/p/how-to-run-a-virtual-conference

**Comment by Smana** [comment]
Updating the list of organizers:
* Alexandre Buisine, Enix, Managing partner, alexandre.buisine@enix.fr, Alex B.
* Aurélien Violet, Enix, CMO, aurelien.violet@enix.fr, Aurelien Violet
* Emmanuel Lagrée, Mirakl, Site Reliability Engineer, emmanuel.lagree@protonmail.com, Emmanuel L.
* Jean-Christophe Sirot,  Aircall, Lead Software Engineer, jcsirot@gmail.com, jcsirot
* Reda Benzair, Lumen, CNCF Ambassador/Director of development, reda.benzair@gmail.com, rbenzair
* Smaine Kahlouch, KMTX, CNCF Ambassador/SRE Team leader, smaine.kahlouch@gmail.com, smana
* Stanislas Chollet, Doctolib, Engineering director, stanislas.chollet@gmail.com, Stan Chollet
* Sylvain Huguet, Kasten, Director technical product management, sylvaint@huguet.me , Sylvain Huguet
