### ISSUE TITLE
Have Edit this Page track branches

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#41]
It would be great if clicking Edit this Page on https://deploy-preview-40--kubernetes-community-days.netlify.com/events/2020-bouvet-island/sponsors/ opened up https://github.com/lucperkins/kubernetes-community-days/blob/lperkins/sponsors-template/content/events/2020-bouvet-island/sponsors.md instead of https://github.com/cncf/kubernetes-community-days/blob/master/content/events/2020-bouvet-island/sponsors.md.

**Comment by lucperkins** [comment]
@dankohn I don't really see a way of implementing this. The site generator would have to be aware of both the GitHub org/repo of the PR as well as the branch.

**Comment by dankohn** [comment]
The info seems to be in this variable in this theme: https://learn.netlify.com/en/shortcodes/siteparam/

**Comment by lucperkins** [comment]
@dankohn I'm afraid that that example does not illustrate this. It simply extracts a static parameter from the site configuration, i.e. `site.Params.foo`. It does not infer the org/repo or branch.

**Comment by dankohn** [comment]
I think the branch is available as an environment variable: https://www.netlify.com/docs/continuous-deployment/#build-environment-variables

Anyway, note that I ranked this as a post-deploy feature, unless you want to work on it now.
