### ISSUE TITLE
KCD Nanjing, China 2023 (Postponed from 2022)

### ISSUE THREAD

**Issue by kerthcet** [cncf/kubernetes-community-days#412]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location:
Nanjing, China

### Event Date and Time:
Q2 2022, Nanjing

### Event type: 

In-person

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP
* [ ] Event date and time has been chosen
* [x] Agree that there will not be an all male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Organizer 1:
Kante Yin, DaoCloud, DaoCloud Opensource Team, CNCF member employee, kerthcet@gmail.com, Kante Yin

### Organizer 2: 
Kevin Wang, Huawei, Leader of Huawei-Cloudnative, CNCF Ambassador, kevinwzf0126@gmail.com, Kevin(Zefeng) Wang

### Organizer 3: 
Xin Gao, Shanghai Cloud Valley, Assistant General Manager, gaoxin@shcloudvalley.com , Vivi

### Organizer 4
Jin Guo, CIBFINTECH, Cloud-Native Architect, guojfsl@gmail.com, guojin

### CfP Admin: 
mail: kerthcet@gmail.com
github: @kerthcet

### Sponsor 1
@DaoCloud
### Sponsor 2
Huawei
### Sponsor 3
Shanghai Cloud Valley

### Fiscal sponsor that will accept payments
TBD

**Comment by xmulligan** [comment]
@kerthcet just wanted to check if you had any updates on this or are you focusing on #411 for now?

**Comment by kerthcet** [comment]
hey bill, since we're going to host KCD chengdu in Q1 2022, we'd like to change this event time to Q2 2022, I have already updated. And we have also contacted with local companies in NanJing, I'll let you know if we make any progress.

**Comment by xmulligan** [comment]
@kerthcet Thanks for letting me know and updating! Please keep me updated on the progress and let me know if you have any questions

**Comment by kerthcet** [comment]
Hi @xmulligan , there are some Covid-19 cases without symptoms found in several cities these days, so we need to cooperate with the relevant authorities. What's more, we don't want to host two events too closely(Chengdu and Nanjing). So we are planning to delay Nanjing's event, possibly late May or early June.  

Just keep you updated with our plans. And if you have any concerns, pls let me known. Thanks.

**Comment by xmulligan** [comment]
@kerthcet thanks for the update. That makes sense to me. Just let me know when you have a new date or if you have any other questions in the meantime

**Comment by kerthcet** [comment]
Absolutely.

**Comment by kerthcet** [comment]
Close as no plan on this anymore. Thanks for everyone's efforts.
/close
