### ISSUE TITLE
KCD Malaysia, 2022

### ISSUE THREAD

**Issue by shardulsrivastava** [cncf/kubernetes-community-days#426]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Submission checklist for organizers: 

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check-in with KCD Core Organizer scheduled
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Minimum of 3 sponsors committed (not required for virtual-only events)
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Agree that there will not be an all male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date: 15th April - 31st May

### Submission checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Organizer 1:
Shardul Srivastava, Air Asia, Engineering Manager, shardul.srivastava007@gmail.com, CNCF Slack: Shardul

### Organizer 2: 
Suresh Bora,  Salt One, Founding Member, sureshbora1989@gmail.com, CNCF Slack: sureshbora1989

### Organizer 3:
Mohammed Fazalullah, AWS, Senior Developer Advocate, mfazal.q@gmail.com, CNCF Slack: Faz

### Organizer 4:
Thirumalai Aiyalu, AWS, Partner Solutions Architect, thiru85@gmail.com, CNCF Slack: thiru

### CfP Admin: 
Shardul Srivastava

**Comment by xmulligan** [comment]
@shardulsrivastava Very excited to see this event starting to come together! 🚀 Let me know if there is anything I can do to help or if you have any questions I can help answer

**Comment by xmulligan** [comment]
Also let me know when you want to start our monthly check ins too. Looking forward to meeting you :) https://calendly.com/bill-mulligan/1-to-1?month=2022-02&date=2022-02-07

**Comment by shardulsrivastava** [comment]
@xmulligan I have picked a time from the calendar, looking forward to catchup, Have a lot of questions.

**Comment by xmulligan** [comment]
Awesome, looking forward to meeting you :)

**Comment by shardulsrivastava** [comment]
@xmulligan I have checked all the relevant boxes, Twitter handle is `@KcdMalaysia`, I will share the credentials with you on Slack. Please help to create a page for KCD Malaysia and create access for CFP portal.

**Comment by AudMonte01** [comment]
Hi @shardulsrivastava - checking in to see how things are going? I only see 3 submissions in KCD Malaysia CFP. Can I help with anything?

**Comment by AudMonte01** [comment]
Event organizers have moved to different countries and are happy to pass this KCD along to anyone that wants to take it over.
