### ISSUE TITLE
KCD Italy 2022

### ISSUE THREAD

**Issue by blues-man** [cncf/kubernetes-community-days#427]
---
name: Host a KCD
about: Host a KCD and use this checklist to get started by submitting an issue
title: KCD Region and Year
labels: ''
assignees: ''

---

# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Milan, Italy
* [x] Event Date and Time: November 17, 2022
* 2 tracks
* [x] Expected Number of Attendees: Goal is 300 attendees
* [ ] Event cost per ticket, and if you will have early bird pricing or not

#### Event type:
* [x] Virtual
* [ ]  Hybrid
* [ ] In person
#### Organizers Details (identify who will be the CFP admin, as well as the financial officer)
* Organiser 1: Chiara Muzzolon, Mia-Platform, Marketing Communications Specialist, [chiara.muzzolon@mia-platform.eu](mailto:chiara.muzzolon@mia-platform.eu), Chiara Muzzolon
* Organiser 2: Annalisa Gennaro, SparkFabrik, Head of Marketing and Communication, [annalisa.gennaro@sparkfabrik.com](mailto:annalisa.gennaro@sparkfabrik.com), annalisa Spark
* Organiser 3: Sara Trappetti, SIGHUP, Marketing Team, [sara@sighup.io](mailto:sara@sighup.io), Sara Trappetti
* Organiser 4: Nikla Lazzari, Kiratech, Digital Marketing Manager, [nikla.lazzari@kiratech.it ](mailto:nikla.lazzari@kiratech.it ), Nikla Lazzari
* Organiser 5: Natale Vinto, Red Hat, Developer Advocate, [nvinto@redhat.com](mailto:nvinto@redhat.com), Natale Vinto
* Organiser 6: Adriano Pezzuto, CLASTIX, Founder, [adriano@clastix.io](mailto:adriano@clastix.io), Adriano Pezzuto
* Third party agency to handle fees and sponsorships

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] All inquiries / communication to come via GitHub forum for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to use Cloud Native Community Groups (Bevy), scheduling, and event website. Using Bevy for registration is optional.
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schdule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by braghettos** [comment]
I would like to candidate myself to support the organization of KCD Italy 2022!

**Comment by xmulligan** [comment]
@blues-man looking forward to seeing another great event come together! 😍 🍕

**Comment by AudMonte01** [comment]
Adding notes here:
* Annalisa submitted program schedule / lineup via Slack and I approved it under thee condition they have another female speaker on the waitlist in case one or both of the female speakers cancel.

Action items:
* Checking in to see if all the organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)?

**Comment by AudMonte01** [comment]
NOTES FROM TODAY'S MEETING

All speakers confirmed, only 1 speaker will be recorded
* three women out of 10 speakers

Social posting is going well

Sponsors
* confirmed participation of virtual AND 2023 in-person

Newsletter will go out 1 week before, 1 day before, and morning of

Will use Streamyard and livestreaming on YouTube
* to share total views and unique views

Received slides from speakers in advance, so we have

Only 145 attendees registered 
* CNCF main social accounts to amplify KCD Italy social media
* Audra to give a shout out to KCD in next week's Marketing Committee meeting
* Audra to ask Rael from KCD Spain if they have a community session that can mention KCD Italy

**Comment by AudMonte01** [comment]
MEETING NOTES FROM DECEMBER 6

Registrations
* Had 285 registrations (94 check-in) and last year they had 380 registrations (260 check-in)
* Chat was lively and engaged 
* Guessing people are tired of virtual events and then the venue cancelation of 

Speakers
* Very happy with the lineup!
* Diverse representation (36%)

Sponsors
* 8 sponsors
* Confirmed their willingness to sponsor the 2023 event

Videos for CNCF YouTube upload and promotion
* Currently in editing mode and will publish them in January
* Will add to their playlist and will point to their playlist

Next steps
* Put a request out for new organizers
* Media partners to also evaluate for 2023
* Going to buy kcd.pizza web domain
** connect CNCG point of contact to Annalisa
