### ISSUE TITLE
KCD UK 2022

### ISSUE THREAD

**Issue by yankcrime** [cncf/kubernetes-community-days#428]
### Event Location:

London, UK

### Event Date and Time:

November 2022

### Event type: 

In-person

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [X] No other Kubernetes Community Day event in the same region 
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Monthly check in with KCD Core Organizer scheduled
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Minimum of 3 sponsors committed (not required for virtual only events)
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [ ] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [X] Agree to use SM Apply for CFP
* [X] Event date and time has been chosen
* [X] Agree that there will not be an all male speaker lineup
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [ ] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Organizer 1:

Matt Jarvis, Snyk, Director of Developer Relations, [matt@mattjarvis.org.uk](mailto:matt@mattjarvis.org.uk), Matt Jarvis

### Organizer 2:

Carla Gaggini, Container Solutions, Head of Events, [carla.gaggini@container-solutions.com](mailto:carla.gaggini@container-solutions.com), Carla Gaggini

### Organizer 3:

Nick Jones, EscherCloudAI, Head of Cloud Native, [nick@dischord.org](mailto:nick@dischord.org), yankcrime

### Organizer 4:

Adrian Mouat, Chainguard, [adrian.mouat@gmail.com](mailto:adrian.mouat@gmail.com), mouat

### Organizer 5:

Lewis Denham-Parry, Chainguard, Head of Training, [lewis@cloudnativewales.io](mailto:lewis@cloudnativewales.io), denhamparry

### Organizer 6:

Chris Kranz, Sysdig, EMEA SE Manager, [chris.kranz@sysdig.com](mailto:chris.kranz@sysdig.com) , chris kranz

### Organizer 7:

Josh Michielsen, Weaveworks, Technical Lead, [j@mickey.dev](mailto:j@mickey.dev), jmickey

### Organizer 8:

Danny Abukalam, SoftIron, Director, Product Engineering, [danny@abukalam.com](mailto:danny@abukalam.com), dabukalam

### Organizer 9:

Paula Kennedy, Syntasso, Chief Operating Officer, [paula.louise.kennedy@gmail.com](mailto:paula.louise.kennedy@gmail.com), Paula Kennedy

### Fiscal sponsor that will accept payments

We have a not for profit umbrella company for this purpose - Open Source Events Ltd.

**Comment by xmulligan** [comment]
Thanks for submitting this! I'm excited to see the next edition 🌹 🌷

**Comment by AudMonte01** [comment]
Hi folks (@yankcrime and team) - checking in to see how review is going and if you need any assistance?

**Comment by AudMonte01** [comment]
JANUARY 10, 2023 MEETING NOTES 

Retrospective
* 233 registered and 220 in-person. They suspect some people came in without a badge
* 19 sponsors total. It was easy to sell out sponsorships
* Good content! Many smart speakers.
** All speakers were offered the option to ask for T&L and only 3 requested help.
* KCD UK had an EOD Retro session on-site with 4 attendees
* Venue: CodeNode was awesome, and will use them again
** 2 big rooms and 1 workshop room
* Advocated for sustainability, which was asking for sponsors not to have too much swag so there was no waist
* Karaoke for ancillary event was fun
* Made 10-15k GBP with some going to a charity donation, and the rest will be used as a deposit for the 2023 KCD

Cons
* Workshops should be in a different day. They were competing with keynotes and other sessions
* Food from venue was not that great

Next Steps
* KCD 2023 - thinking week of Nov 16 (after KubeCon Chicago)
