### ISSUE TITLE
KCD Sri Lanka 2022

### ISSUE THREAD

**Issue by Shehanka** [cncf/kubernetes-community-days#431]
### Event Date and Time:
September 3-4

### Event type: 
Virtual

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Agree that there will not be an all male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Organizer 1: 
Chamod Perera, WSO2, Software Engineer, hcsperera@gmail.com, chamodshehanka

### Organizer 2:
Bawantha Rathanayake, Orel IT, Software Engineer, bawantharathnayake@gmail.com, bawantha

### Organizer 3: 
Kaveesha Gimhana, Omobio, Software Engineer, uakaveeshagimhana@gmail.com,<TBD>

### Organizer 4: First and Last Name, Company, Title, Email, CNCF Slack Username
Kesara Weerathunge, MIT ESP, Software Engineer, kesaraw@mitesp.com, <TBD>

### Organizer 5: First and Last Name, Company, Title, Email, CNCF Slack Username
Shanaka Mendis, Mitrai, Software Engineer, smendis@mitrai.com, <TBD>

### Organizer 6: First and Last Name, Company, Title, Email, CNCF Slack Username
Kemila De Silva, Aeturnum Inc, DevOps Engineer, kemila.d@aeturnum.com, kemila.d

### Sponsor 1
WSO2

### Sponsor 2
TBD

### Sponsor 3
TBD

### Slack channel for KCD 
`kcd-srilanka`

**Comment by xmulligan** [comment]
@Shehanka Thanks for putting this together. I'm excited to see this event come together 🎊 Can you book an introductory meeting so we can go over everything? https://calendly.com/bill-mulligan/1-to-1?month=2022-02&date=2022-02-07

**Comment by Shehanka** [comment]
> @Shehanka Thanks for putting this together. I'm excited to see this event come together 🎊 Can you book an introductory meeting so we can go over everything? https://calendly.com/bill-mulligan/1-to-1?month=2022-02&date=2022-02-07

Done! See you soon

**Comment by k8tgreenley** [comment]
@Shehanka I wanted to check in your progress of the event. I know you booked time with Bill back in late March. I would like to meet with you next week to see how things are going and if you need anything from me at this time.

**Comment by Shehanka** [comment]
> @Shehanka I wanted to check in your progress of the event. I know you booked time with Bill back in late March. I would like to meet with you next week to see how things are going and if you need anything from me at this time.

Yeah! Sure, Looking forward to meeting you next week 😃

**Comment by k8tgreenley** [comment]
@Shehanka please book a time on my [calendar](https://calendly.com/kgreenley/katie-greenley?month=2022-04)

**Comment by k8tgreenley** [comment]
CFP (SM Apply): https://kcd.smapply.io/prog/kcd_sri_lanka_2022

CFP Closes: July 8, 2022

If you would like for me to adjust this date, please let me know. 

Virtual Event Platform (Bevy):  [CNCF KCD Sri Lanka](https://community.cncf.io/kcd-sri-lanka/)

Organizer Email: [organizers-srilanka@kubernetescommunitydays.org](mailto:organizers-srilanka@kubernetescommunitydays.org)

**Comment by AudMonte01** [comment]
Hello @Shehanka and team - allow me to introduce myself as the new KCD Program Manager coming in to help @k8tgreenley. 

I am checking in to see if you want to extend your CFP and postpone the event dates since there are only 3 submissions that I can see in SMapply? I realize you already extended once (from 30, June to 8, July).

**Comment by Shehanka** [comment]
> Hello @Shehanka and team - allow me to introduce myself as the new KCD Program Manager coming in to help @k8tgreenley.
> 
> I am checking in to see if you want to extend your CFP and postpone the event dates since there are only 3 submissions that I can see in SMapply? I realize you already extended once (from 30, June to 8, July).

Hi Katie, Please extend the CFP since we have postponed event to 3rd September

**Comment by AudMonte01** [comment]
Hi @Shehanka - I had already extended it to close at midnight tomorrow, 23 July Sri Lanka time. That will allow 6 weeks time to let speakers plan for the event. Given there are still only 3 proposals submitted, would you like it open a little longer? Or do you plan on curating some of the content through the yours and the other organizers' networks?
