### ISSUE TITLE
KCD Washington, DC 2022

### ISSUE THREAD

**Issue by faheem556** [cncf/kubernetes-community-days#436]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location: 
American Red Cross DC
1730 E Street NW 20006 
Washington DC

### Event Date and Time: 
Sep 14th, 2022 - 9am to 4pm

### Event type:  
In Person

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Agree that there will not be an all male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

CfP open and close dates: 2022-06-1 to 2022-07-31
Website launch date: 2022-05-23

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [x] Videos uploaded to Youtube and linked to event page

### Organizer 1:
Faheem Memon, Amobee Inc, DevOps Architect, faheem.memon@amobee.com, Faheem Memon

### Organizer 2:
Matthew Cascio, Executive Director, matthew.cascio@redcross.org, Matthew Cascio

### Organizer 3:
Brandon Mitchell, BoatBox, DevOps Solutions Architect, docker@bmitch.net, Brandon Mitchell

### Organizer 4:
Jason Morgan, Buoyant, Developer Evangelist, jason@buoyant.io, jmo

### Organizer 5:
Robert Brown, USCIS, CTO, robert.d.brown@uscis.dhs.gov, Robert Brown(?)

### CfP Admin: 
Faheem, Brandon, Jason, Robert

### Sponsor 1
Rancher Gov Solutions

### Sponsor 2
BoxBoat Technologies

### Sponsor 3
American RedCross (HOST)

### Fiscal sponsor that will accept payments
[NaOM Lab](https://opencollective.com/naomlab)

**Comment by sudo-bmitch** [comment]
I see the CFP has been created at <https://kcd.smapply.io/prog/kcd_washington_dc_2022_cfp/>. Can our accounts be added as reviewers/admins over there?

**Comment by AudMonte01** [comment]
Closing notes:
* Matthew Cascio posted [a retrospective blog](https://www.cncf.io/blog/2022/10/06/kubernetes-community-days-washington-dc-2022-a-retrospective/)
* [Videos are on YouTube](https://www.youtube.com/watch?v=lAasbspEcG0&list=PLrDNB_yjsmB6t8jAcpTtU0CthO2dibIQ9)
* 52 registered and 32 attendees (aside from organizers) showed up in person
