### ISSUE TITLE
KCD Guatemala 2023 (August 18 - 19)

### ISSUE THREAD

**Issue by sergioarmgpl** [cncf/kubernetes-community-days#437]
# KCD Details

* Event Location: Guatemala, Venue [Campus Tec](https://tec.gt/)
* Event Date and Time: Postponing to August 18 & 19
* Event type: Hybrid
* Expected Number of Attendees: 400

## Organizers
* Organizer 1: Sergio Méndez, CNCF, Ambassador, sergioarm.gpl@gmail.com, CNCF Slack Username Sergio Méndez
* Organizer 2: Jefferson Molina, San Carlos University, Student, jeffersogmb7@gmail.com, CNCF Slack Username
* Organizer 3: Diana Menéndez, Capital valley tech, Developer, dcmc2297@gmail.com, CNCF Slack Username
* Organizer 4: Kevin Villatoro, Wallmart, SRE, villatorokevin@gmail.com, CNCF Slack Username
* Organizer 5: Salvador López, Telus, Senior Applications Developer, shlopezm4@gmail.com, CNCF Slack Username
* Organizer 6: Alvin Estrada, CNCF, Ambassador, adawolfs@gmail.com, CNCF Slack Username

-- Sponsors
* Organizer 7: Douglas López, Company, Role, lopez.douglas@gmail.com, CNCF Slack Username

-- CFP and Bevy Admin
* Organizer 8: Jossie Castrillo, Canella S.A. & Edutek, Senior Developer/Instructor, bkcastrillo@gmail.com, CNCF Slack Username: Jossie Castrillo
* Organizer 9: Juan Pablo García, USAC, Analista de sistema, pablo2011euro@gmail.com, CNCF Slack Username
* Organizer 10: Jossemar Cordero, CTO.ia, Senior Lead Platform Engineer, jossemargt@gmail.com, CNCF Slack Username

## Submission checklist for organizers:
Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Agree that there will not be an all male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date: End of February

### Submission checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-guatemala@kubernetescommunitydays.org](mailto:organizers-guatemala@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header: chapter vs event since there are 2 events. 1 dedicated to students, and 1 to the professional community
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

**Comment by sergioarmgpl** [comment]
@k8tgreenley sorry for the late reply, well we can talk on CNCF if you want, my plan is to organize this for this semester with my students, the same as we did last year :) so we have to wait maybe 15 days to start the organization maybe.

**Comment by k8tgreenley** [comment]
@sergioarmgpl do you want to plan to connect on the event in mid-July? Will you be hosting virtually or in-person?

**Comment by sergioarmgpl** [comment]
@k8tgreenley Hi, yes, sure, let's talk in July, the event will be virtually.

**Comment by sergioarmgpl** [comment]
Hi @k8tgreenley I think that we can schedule a call next week, my time zone is GMT-6, or chat on the CNCF slack

**Comment by k8tgreenley** [comment]
Hi @sergioarmgpl great, please book time for us to chat using this link: https://calendly.com/kgreenley/katie-greenley

**Comment by AudMonte01** [comment]
NOTES FROM 8/17/22 MEETING:
* Event will be anywhere from Nov 26 - the first week of January
* First order of business is @sergioarmgpl to get his organizer committee together by next meeting
* Set next meeting for September 14
* Some students will present
* Audra to look into whether Sergio needs to retake the Inclusive Open Source Community Orientation
* If possible - Audra suggests Sergio give away digital copies of his book at this virtual event: https://www.amazon.com/Edge-computing-K3os-k3s-technologies-ebook/dp/B0B2PSZ1BK/

**Comment by sergioarmgpl** [comment]
Retaking our KCD

**Comment by AudMonte01** [comment]
Hi @sergioarmgpl - have you decided on a date for KCD Guatemala yet?

**Comment by sergiopsyalo** [comment]
@AudMonte01 yes, March 24-25th, now I am talking with the graph designer

**Comment by AudMonte01** [comment]
That seems like good timing. The only KCD that is close to that is KCD Los Angeles with is March 9-10

**Comment by AudMonte01** [comment]
I think you will be fine given the point about different languages used for KCD Guatemala and KCD LA. Also, both are in-person events, so the element of travel and convenience in location for regional people will help prevent competition.

**Comment by sergioarmgpl** [comment]
We had a good advance with the logo this Christmas @AudMonte01 its almost done, just play with letter styles.

**Comment by AudMonte01** [comment]
MEETING NOTES FROM 2/3 CHECK-IN

Date
* Moving to first week of June (2nd and 3rd)
* NOTE: KCD Colombia will be June 5, so 

Organizers
* Sergio is hosting a meetup with students this evening to gauge interest in who wants to help organize the event

Social Media
* Guatemala and Central America uses Facebook
* A lot of the younger generations are using Discord

**Comment by AudMonte01** [comment]
Hi @sergioarmgpl - please add the student organizers that are confirmed to help organize this event, by simply adding them in the original issue above. Also, can you confirm Brad McCoy is helping organize this as well?

**Comment by bradmccoydev** [comment]
I confirm my participation and attended the community meeting today.

**Comment by AudMonte01** [comment]
> I confirm my participation and attended the community meeting today.

Awesome! I see all the organizers have now been added! @k8tgreenley - can you please create an organizer email alias for KCD Guatemala?

**Comment by AudMonte01** [comment]
Hi @k8tgreenley - can you please update the [organizers-guatemala@kubernetescommunitydays.org](mailto:organizers-guatemala@kubernetescommunitydays.org) alias with the above new organizers?

**Comment by k8tgreenley** [comment]
The email alias has been updated

**Comment by AudMonte01** [comment]
May 19 Update

Team
* A new marketing person has joined
* Bart is to helping with recording speaker videos

**Comment by AudMonte01** [comment]
JUNE 2 MEETING NOTES

Agenda
* This Sunday EOD deadline for speaker to confirm the new dates work

New organizer
* Argentinian marketing contributor
* Experience is online events
* Action: Sergio to invite to next meeting

Action items
* Audra to set some time with Nicole, Bevy expert to learn a know-before-you go

Sponsorships
* UBG University is a partner
* Press Kit created for other partnerships

Streaming
* Action: Sergio to speak to Pedro Galvan from Mexico
* Last time used Streamyard

**Comment by AudMonte01** [comment]
JUNE 16 MEETING NOTES

Streaming
* Spoke to Pedro Galvan from Mexico at KCD Colombia, and he said yes to streaming, but a contract needs to be secured

Things to focus on
* Publish agenda
* Secure new graphic designer
* Create slide template for speakers
* Talk with Samantha from KCD Colombia to be a community partner and help promote

CNCF Actions
* [ ] Audra to send training and sticker voucher codes

**Comment by AudMonte01** [comment]
JUNE 27 CHECK-IN

@k8tgreenley - can you double check this alias [organizers-guatemala@kubernetescommunitydays.org](mailto:organizers-guatemala@kubernetescommunitydays.org) has all of the above email addresses on it? It wasn't working for Sergio when he tested it.

Event agenda
* Day 1 schedule is to go LIVE this week

Venue
* Will confirm if day 2 is in-person or not

Live-streaming
* Once venue is confirmed, team can secure Pedro's streaming services

**Comment by k8tgreenley** [comment]
Confirmed all the emails above are on the list, and must be something in the recipients' email that might be blocking the forward

**Comment by AudMonte01** [comment]
JULY 18 MEETING NOTES

Marketing
* Announcing to attendees this week, about the hybrid option, including a list of companies and communities

Dinner + Venue sponsorship = $1,000 USD
* [ ] Audra to give Sergio template

Final in-person speakers
* Collecting title of sessions

**Comment by AudMonte01** [comment]
JULY 28 MEETING NOTES

Sponsorship Prospectus
* Spanish version is ready
* [ ] Audra to send recommendation letters to prospecting companies per LF
-- Official CNCF-supported event

Content
* Yes - session titles have been added to the banner graphic
* Kong is sponsoring the dinner, and wants to have meetup in exchange
* The agenda feature is still not showing up when someone is logged out - Audra followed up with Bevy
* Streaming strategy talk with Pedro Galvan and his team

Other marketing
* Social media needs to be more active (LinkedIn at least)
* Use the CNCF #socialmedia channel more for CNCF to amplify: https://cloud-native.slack.com/archives/C12MRQ97A

**Comment by AudMonte01** [comment]
AUGUST 7 MEETING NOTES

Nearly 300 attendees across both events
Stickers should arrive this week

Marketing
* [ ] Sergio to post promotional video from KCD Colombia on social media. Audra to amplify in KubeWeekly newsletter

Sponsorships
* [ ] Sergio to add 5 sponsors on KCD website

Want to meet with Bevy professional, Nicole?
* [ ] Sergio to reach out to Audra on Wednesday to let know how to the test run goes

**Comment by AudMonte01** [comment]
FINAL CNCF CHECK-IN AHEAD OF EVENT

Test run last Wednesday went well, but still need to test virtual booth
* Audra reached out to Bevy expert to see if she can meet with Sergio and team
* Using Pedro Galvan's team for streaming platform

Housekeeping slides
* Audra shared mentor and mentee resources, as well as CNCG and CNCF landscape QR codes

Stickers arrived on time!

**Comment by AudMonte01** [comment]
YouTube Playlist created: https://youtube.com/playlist?list=PLj6h78yzYM2NXtL5GdtOJwIEuxHlYEO7F&si=Kwl1rR5JDbmHBfTe

**Comment by AudMonte01** [comment]
Blog Post published last week: https://www.cncf.io/blog/2024/02/02/a-kcd-lead-by-the-next-generation-of-cloud-native-engineers/
