### ISSUE TITLE
KCD MENA

### ISSUE THREAD

**Issue by walidshaari** [cncf/kubernetes-community-days#438]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location:
UAE - Dubai

### Event Date and Time:

Between 13 October, along GITEX DevSlam 2022, last day afternoon from 1:00- 5:00 pm

### Event type: 

Hybrid

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check-in with KCD Core Organizer scheduled
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Minimum of 3 sponsors committed (not required for virtual-only events)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [x] Agree to use SM Apply for CFP
* [x] Event date and time have been chosen
* [x] Agree that there will not be an all-male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Added to KCD Drop-down menu
* [x] CfP created

### Post Event checklist:
* [x] Removed from Bevy header
* [x] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to the event page

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
         Walid Shaari, Saudi Aramco, Mr, walid.shaari@linux.com,  wshaari
### Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username
         Mohammed Fazalullah Qudrath, Amazon Web Services, Snr Developer Advocate, qudrat@amazon, thecloudranger

### Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username
         Karim Benzidane, Independent, Technical Trainer, [k.benzidane@gmail.com](mailto:k.benzidane@gmail.com), The_Mirak

**Comment by AudMonte01** [comment]
Hi @walidshaari! Given this event is due to happen as early as 10, October 2022 It seems like we should open the CFF as soon as possible. That said, would you like it to close 6 weeks or 8 weeks ahead of the event? Something to consider is that some KCDs add a planned 1-week buffer / extension.

**Comment by walidshaari** [comment]
@AudMonte01  six weeks, around end of August.

**Comment by AudMonte01** [comment]
Excellent - thank you, @walidshaari . Yesterday, you should have received access to the [Mena CFP in SMapply](https://kcd.smapply.io/admin/awards/264604/manage/dashboard/) I created.

**Comment by boredabdel** [comment]
@AudMonte01 could you please allow me to add myself as an organizer to this one? I believe it's a permissions issue.

**Comment by walidshaari** [comment]
@the-mirak can we have your organizer details, you and @boredabdel

**Comment by the-mirak** [comment]
Karim Benzidane, Independent, Technical Trainer, k.benzidane@gmail.com, The_Mirak

**Comment by boredabdel** [comment]
Abdelfettah SGHIOUAR, Google, Senior Cloud Dev Advocate, abdelfettah@google.com, abdelsource

**Comment by AudMonte01** [comment]
> 

Thank @the-mirak - would you prefer this email address be used in SMapply?

**Comment by AudMonte01** [comment]
> Abdelfettah

Excellent - looks like Katie gave you access in SMapply.

**Comment by the-mirak** [comment]
@AudMonte01 - Katie already gave me admin access. Thank you.

**Comment by AudMonte01** [comment]
Update from 9/30 meeting:
* Walid is essentially planning by himself, with little help with Faz and will ask CNCF Ambassador, Divya Mohan for help (should know by October 3)
* Two logos prepared by volunteers
* 1 Fiscal Sponsor (AdFolks.com), 1 Diversity Sponsor (Synapse Analytics), 3rd Sponsor DWTC (Venue and F&B Sponsor)
* Program schedule:
-- Liz Rice as a keynote speaker
-- John Boero from HashiCorp
-- 3 ladies from RedHat from open source side of K8s operators (45 minute session)
-- (Divya Mohan)[https://www.linkedin.com/in/divya-mohan0209/] (Ambassador will be speaking virtually)
* Audra to create Bevy chapter and give Walid access

**Comment by AudMonte01** [comment]
Today, per a Slack message from Walid - Divya Mohan said yes to help organizing, AND presenting a session!
