### ISSUE TITLE
Kubernetes Community Day Nordics

### ISSUE THREAD

**Issue by Solisol** [cncf/kubernetes-community-days#439]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location:
Stockholm Sweden

### Event Date and Time:
29th November, 2022
8:00-20:00

### Event type: 

hybrid

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] Monthly check in with KCD Core Organizer scheduled
* [X] All inquiries / communication to come via GitHub forum for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [ ] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event
* [X] Event date and time has been chosen
* [X] Agree that there will not be an all male speaker lineup
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

CfP open and close dates:
Website launch date:

### Submission checklist for CNCF:
* [x] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [x] CFP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Expected Number of Attendees:
210 (Limit of physical attendees), +500 virtual attendees

### Organizer 1: First and Last Name, Company, Title, Email, CNCF Slack Username
Jessica Andersson, Kognic, CNCF Ambassador/Product Area Lead Engineering Enablement, jesandeit@gmail.com, Jessica
### Organizer 2: First and Last Name, Company, Title, Email, CNCF Slack Username
Abdellfetah SGHIOUAR, Google, Strategic Cloud Engineer, abdelfettah@google.com, Abdellfetah SGHIOUAR
### Organizer 3: First and Last Name, Company, Title, Email, CNCF Slack Username
Kasper Borg Nissen, Lunar, Lead Platform Architect, kaspernissen@gmail.com, phennex
### Organizer 4: First and Last Name, Company, Title, Email, CNCF Slack Username
Rasmus Steiniche, Neurospace, CEO, rasmus@steiniche.net, Steiniche
### Organizer 5: First and Last Name, Company, Title, Email, CNCF Slack Username
Federico Hernandez, Meltwater, Principal Software Engineer, f@ederi.co, @recollir 
### Organizer 6: First and Last Name, Company, Title, Email, CNCF Slack Username
Lennart Jern, Ericsson, Experienced Software Developer, lennart.jern@est.tech, Lennart Jern
### Organizer 7: First and Last Name, Company, Title, Email, CNCF Slack Username
Kashif Nizam Khan, Ericsson, Master Developer/ Product Owner, kashif.khan@est.tech, Kashif Khan
### Organizer 8: First and Last Name, Company, Title, Email, CNCF Slack Username
Johan Tordsson, Elastisys, CEO, tordsson@elastisys.com, Johan Tordsson, Elastisys
### Organizer 9: First and Last Name, Company, Title, Email, CNCF Slack Username
Furkat Gofurov, Ericsson, Experienced Cloud Developer, furkat.gofurov@est.tech, Furkat Gofurov 
### Organizer 10: First and Last Name, Company, Title, Email, CNCF Slack Username
Lucas Käldström, Independent, CNCF Ambassador, lucas@luxaslabs.com, luxas

### Sponsor 1
Google

**Comment by Solisol** [comment]
Just getting this kicked off since we just got location and date confirmed! Will add third organizer and fill out more details as it becomes more clear!

**Comment by Solisol** [comment]
https://twitter.com/KCDNordics

**Comment by AudMonte01** [comment]
Hi @Solisol and Abdel - thank you for meeting with me today. Here are my takeaways:

* 4 additional people joining the committee - Jessica to ping Audra once they are added to this GitHub issue
* Jessica published Bevy page, but Audra to figure out how to hide the tickets
* Audra went over the marketing plan
* Ticketing platform: Eventbrite and Bevy Pay are too expensive. Abdel is looking into http://eventbee.com/

**Comment by Solisol** [comment]
@AudMonte01 Hi! The ticket is now updated with additional organisers for the program committee :)

**Comment by recollir** [comment]
@AudMonte01 It was decided to cancel KCD nordics. For different reasons. I am looking into the related tasks now regarding the CFP and smapply. How can we close down applications on https://kcd.smapply.io/prog/kcd_nordics_2022_cfp and change the text? I would also like to see who has already sent in a CFP to be able to inform them directly. I tried to access the shapely site. But I can't access anything there other than submitting a CFP. Are you able to help.

Is there anything else to know about when cancelling an event? Apart from removing the event on the different sites, etc. //cc @NissesSenap

**Comment by AudMonte01** [comment]
Hello @recollir and @NissesSenap - I am sorry to hear of this event discontinuing. Is there any way it can live on by adding another organizer to the team?

**Comment by NissesSenap** [comment]
@AudMonte01 with the current timeline, no.
In short we just don't have enough time to create an event with the quantity that we want to achieve. 

We might revisit creating a event again but if that is the case it will be sometime in 2023.

**Comment by AudMonte01** [comment]
Thank you for the prompt response. Please let me know if this event simply needs a push of dates to 2023. For now I will close this issue, and we can always re-open it.

cc// @k8tgreenley

**Comment by NissesSenap** [comment]
@AudMonte01 do you have access to the CFP page? Nether me nor @recollir have access to shut it down it.

**Comment by recollir** [comment]
Didn't see any slack msg. But I think we are good now. Thank you @AudMonte01

**Comment by lonefreak** [comment]
@recollir @NissesSenap I know it is kinda far away now, but I would like to help organise this in 2023. What is a good channel to keep up and offer help?

**Comment by recollir** [comment]
@lonefreak You could join the Cloud Native Nordics slack space and the corresponding channel there.
