### ISSUE TITLE
KCD Spain 2022

### ISSUE THREAD

**Issue by raelga** [cncf/kubernetes-community-days#440]
### Event Location:

Online

### Event Date and Time:

Nov 15 - 16, 2022

### Event type:

Virtual

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [x] All inquiries / communication to come via GitHub forum for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) ⚙️
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
* [x] ~Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses~ Free event
* [x] ~Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event~ Free event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender)
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event
* [x] Event date and time has been chosen
* [x] Agree that there will not be an all male speaker lineup
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender)
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

CfP open and close dates: TBD (Will probably start late July till early September)
Website launch date: Already online at [kcdspain.com](https://kcdspain.com), working on the 2022 edition.

### Submission checklist for CNCF:
* [x] Organizer email alias has been created (organizers-spain@kubernetescommunitydays.org)
* [x] Region created in Bevy (https://community.cncf.io/kcd-spain/)
* [x] Added to Bevy header
* [x] CFP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Expected Number of Attendees:

1000

### Organizers

| First and Last Name     | Company         | Title             | Email                         | CNCF Slack Username |
| ----------------------- | --------------- | ----------------- | ----------------------------- | ------------------- |
| Rael Garcia Arnes       | Red Hat         | SRE               | rael@redhat.com               | rael                |
| Jorge Martinez          | ISRG - Sprinter | DevOps            | jorgemartinez@sprinter.es     | Jorge Martinez      |
| Javier Provecho         | Okteto          | Software Engineer | jpf@okteto.com                | javierprovecho      |
| Alvaro Agea             | Napptive        | CEO               | alvaro@napptive.com           | Alvaro Agea         |
| Rosa Maria Carpio López | HBO Max         | DevSecOps         | rocarlo91@gmail.com           | Rosa Carpio         |
| Nicolas Quiceno         | AstroKube       | CEO               | nicolas.quiceno@astrokube.com | Nicolas Quiceno     |
| Jorge Turrado           | DocPlanner      | SRE               | kabestrus@gmail.com           | Jorge Turrado       |

### Sponsors

| Company   | First and Last Name | Email               | CNCF Slack Username |
| --------- | ------------------- | ------------------- | ------------------- |
| Red Hat   | Rael Garcia Arnes   | rael@redhat.com     | rael                |
| Okteto    | Javier Provecho     | jpf@okteto.com      | javierprovecho      |
| Napptive  | Alvaro Agea         | alvaro@napptive.com | Alvaro Agea         |
| AstroKube | Nicolas Quiceno     | kabestrus@gmail.com | Nicolas Quiceno     |

### Fiscal sponsor that will accept payments

Not needed being a free virtual event.

### Team

| Role               | Lead                              | Shadow                                                                                                                             | Notes |
| ------------------ | --------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------- | ----- |
| Event coordination | @raelga                           | @aagea <br> @borjareinares <br> @pfuentesg <br> @javierprovecho <br> @mario-ezquerro <br> @92nqb <br> @JorTurFer   <br> @pasqualet |       |
| Content            | @JorTurFer   / @jorgermp          | @vthot4  <br> @aagea <br> @raelga <br> @borjareinares <br> @xoanmm <br> @javierprovecho <br> @92nqb <br>  @mvazquezc  @pasqualet   |       |
| Marketing          | @92nqb  / @raelga                 | <br> @rcarpio-hbo <br> @vjjmiras  <br>   @pasqualet                                                                                |       |
| Multimedia         | @javierprovecho / @mario-ezquerro | @mario-ezquerro <br> @jorgermp <br> @raelga                                                                                        |       |

https://github.com/kcdspain/spain-2022/issues/1

### Social channels:

Slack: [CNCF/#kcd-spain](https://cloud-native.slack.com/archives/CUFASEGCU)
Telegram: [t.me/KCDes](https://t.me/KCDes)
Twitter: [@KCDSpain](https://twitter.com/kcdspain)

### Past editions:

https://github.com/cncf/kubernetes-community-days/issues/385

**Comment by AudMonte01** [comment]
Hi @raelga - I am writing to set up an on-boarding call to see how the CNCF can help KCD Spain this year, and learn about what you all want to do different from last year (if anything). Please [use my Calendly](https://calendly.com/audmonte/kcd-onboarding-kickoff-call) to book our 1-hour kickoff call, and invite those who you think should be attend. Thank you!

**Comment by raelga** [comment]
Awesome! Let me check with the team during the next weekly meeting and get back to you! :)

**Comment by raelga** [comment]
#### Some updates

* Final date: November 22 - 24, 2022

#### Items completed

* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request

**Comment by AudMonte01** [comment]
> Awesome! Let me check with the team during the next weekly meeting and get back to you! :)

Sounds good! Any news on when will work best @raelga ?

**Comment by raelga** [comment]
Hey @AudMonte01, we're working on that, sorry for the delay. 😅 

In the meantime, see you next week on the KCD Organizer Monthly Interest Group :)

**Comment by AudMonte01** [comment]
Adding notes here:
* Real and Audra connected in the monthly organizer interest group where he let me know the dates are changing
* We re-connected via Slack and the dates are November 15-16 (1 day ahead of KCD Italy)
-- Katie and I connected on the dates being so close, and we agree that since KCD Spain is in Spanish and virtual, and KCD Italy is in English and in person, the events should not be a worry for competition.

**Comment by raelga** [comment]
- Dates updated in the issue 📆 
- CFP soft-closed with 97 submissions 🥳 
<img width="261" alt="Screenshot 2022-10-01 at 10 36 33" src="https://user-images.githubusercontent.com/795289/193400863-9a936a99-6759-4711-98dc-48fa90342c57.png">

We will start working on the review next week with the content team.

**Comment by AudMonte01** [comment]
That's a great number of proposals, @raelga! Nice work! Also, thank you for updating this issue.
