### ISSUE TITLE
KCD Belgium 2023 (October)

### ISSUE THREAD

**Issue by cedricve** [cncf/kubernetes-community-days#444]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [ ] Event Location: TBD
* [ ] Event Date and Time: Oct 2023
* [x] Expected Number of Attendees: 300
* [ ] Event cost per ticket, and if you will have early bird pricing or not: TBD
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* Organizer 1: Cedric Verstraeten, Microsoft, Developer Relations, cverstraeten@microsoft.com, Cédric Verstraeten
* Organizer 2: Jorge Garcia Ximenez, Company, Title, Email, CNCF Slack Username
* Organizer 3: Tom Kerkhove, Microsoft,
* Organizer 4: Dieter, dieter@cncfcommunity.be

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] All inquiries / communication to come via GitHub forum for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [ ] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [ ] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by cedricve** [comment]
@gxjorge including for supper

**Comment by AudMonte01** [comment]
NOTES FROM TODAY'S MEETING 

Timing
* Friday in April 2023

Venue is almost secured (Brussels - Blue point)
* Includes catering - breakfast, lunch, and dinner
* 30k Euros for 300 people (2 rooms can be partitioned, and separate booth space)

Schedule
* I track

Prospectus
* Using KCD Amsterdam prospectus examples

Next steps:
* Have a draft of the Prospectus
* Finalizing organizer team
* Figuring out CFP open date

**Comment by AudMonte01** [comment]
NOTE: Tried to meet on December 14 and Jorge had a family emergency, and Cedric seemed to be on holiday already and did not show. Good news is Cedric attended the SM Apply working group/training.

**Comment by AudMonte01** [comment]
1/16/23 MEETING NOTES

Event date is May 5

Sponsors
* Created prospectus
* Fiscal sponsors (treasurer)

Venue
* Finalizing venue by the end of this week

Figuring out CFP open date
* Goal is to open February 1

Branding
* @cedricve - I meant to ask to see your logo

**Comment by AudMonte01** [comment]
Hi @cedricve  - checking in on progress and if we can schedule a check-in next week?
https://calendly.com/audmonte/30min

**Comment by cedricve** [comment]
Hi @AudMonte01  We will postpone to Oct 2023.

**Comment by AudMonte01** [comment]
Thank you for letting us know, @cedricve - please note that KCD UK will be October 17. Happy to meet if you would like to discuss any blockers. https://calendly.com/audmonte/30min

**Comment by AudMonte01** [comment]
Hi @cedricve - I will close this issue until you are ready to plan this event

**Comment by cedricve** [comment]
Working on this to redeliver in 2025 @AudMonte01

**Comment by AudMonte01** [comment]
Unfortunately it will only be possible to apply for 2026 starting in April. Please have a look at our program refresh and updates via [this blog post](https://www.cncf.io/blog/2024/08/06/refreshing-the-kcd-program-a-new-chapter-in-community-building/).

**Comment by cedricve** [comment]
Thank you @AudMonte01 we will
go through the new application process 👍
