### ISSUE TITLE
KCD Colombia 2023 (June 5-6)

### ISSUE THREAD

**Issue by dagoshe** [cncf/kubernetes-community-days#446]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: [University EAFIT](https://www.eafit.edu.co/)
* [x] Event Date and Time: June 5-6, 2023
* [x] Expected Number of Attendees: 600-800 people in-person (1,600 virtual)
* [x] Event cost per ticket, and if you will have early bird pricing or not
#### Event type:
* [ ] Virtual
* [x] Hybrid
* [ ] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Nathalia Miranda, CEO and Founder of Transformente, nathalia@transformente.com, CNCF Slack
* [x] Organizer 2: Jose Rodriguez, Marketing Director at Cuembly, jose.rodriguez@cuemby.com, CNCF Slack
* [x] Organizer 3: Angel Ramirez, Chief Executive Officer at Cuemby, angel@cuemby.com, CNCF Slack
* [x] Organizer 4: Martin Elias Quintero Osorio, Cofounder and CTO at guane Enterprises, elias@guane.com.co, CNCF Slack
* [x] Organizer 5: Samantha Upegui, Cuembly, samantha.vuc@gmail.com, CNCF Slack

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] All inquiries / communication to come via GitHub forum for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-colombia@kubernetescommunitydays.org](mailto:organizers-colombia@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
NOTES from 10/31 meeting
* There are about 13 people who will be on the program committee
* Each organizer will bring different expertise to the table, including an event organizer based on Brazil (she can travel to Columbia)
* Angel to connect with Matthew Cascio about NaomLab as a fiscal sponsors: https://www.naomlab.com/do-you-need-a-fiscal-sponsor/
* We will meet again at the end of November where all organizers will join the meeting to discuss venue and the sponsor prospectus

**Comment by AudMonte01** [comment]
Here are notes from our 11/30/2022 meeting:
* Met Nathalia who will be focusing on DE&I and there are already interested women leaders in LATAM who would be great keynotes!
* The venue is the [EAFIT University](https://www.eafit.edu.co/) which is an engineering program
* They would like Audra to speak to CNCF and the landscape as well the KCD journey (1-2 minute keynote)
* Elias will be acting like a Program Chair managing the program committee

To-Dos:
* @dagoshe to share sponsor prospectus slide deck with Audra (audra@cncf.io)
* Audra to give Angel Bevy access and SM Apply access
* @k8tgreenley to create email alias with listed organizers

**Comment by AudMonte01** [comment]
Also @dagoshe and @ar4mirez - can you confirm the [elias@guane.com.co](mailto:elias@guane.com.co) address is correct for Elias with the ".co" at the end?

**Comment by AudMonte01** [comment]
Hi @ar4mirez and @dagoshe - I was able to invite you as a writer, as I think you both were only readers in this repo. You should now be able to edit this issue directly. Please let me know if you have any issues.

**Comment by AudMonte01** [comment]
1/20/23 MEETING NOTES

Venue
* Can secure venue for June dates (likely June 5)
* Now at a University is the largest university in Columbia, and in the second largest, expecting about 600 people

Samantha who is a co-organizer of CN Columbia community groups will be joining: https://www.youtube.com/@fhcn

Website
* Angel will be finishing up the CFP over the weekend

**Comment by AudMonte01** [comment]
2/9/2023 MEETING NOTES

CFP launch dates
* Launched CFP on Tuesday
* TO-DO: Needs help reviewing automations
* Already have 5 speakers
** Ericsson, top 100 female leaders in LATAM
** Speakers from Kids Cartoon Development in Pixar based in Canada

Ticketing platform
* Using external

Venue
* Dedicating an auditorium for speed networking
** Would like to use Sched or Swapcard to be able to support this
** Audra to TO-DO: look
* University is happy and want to showcase their Engineering program

Marketing
* Shared social strategy
* University has a newsletter
* Government and digital agencies will be promoting the event as well

Sponsorships
* TO-DO: Audra to share a list of International airports on West Coast
* Adding CNCF as a community sponsor

**Comment by AudMonte01** [comment]
CNCF To-Do
* Inform maintainers around widely adopted projects in Colombia to promote submitting a talk (Prometheus, etc (@ar4mirez to send Katie and Audra a list)
* Audra added KCD Colombia to the KCD About page drop-down page
* Audra to review writeup in email from Jose to transition into a blog post
* Bancolombia is wanting to send a team of people (silver CNCF end user). Is there a discount? @k8tgreenley to send typical KubeCon discount % and will send an email to Jose for review and approval

Venue
* Main stage can hold 600 people 

Speakers
* Potential technical speakers are dependent on CNCF physical representation at the event

**Comment by k8tgreenley** [comment]
@dagoshe @ar4mirez I have confirmed that we typically provide 10 free passes to KubeCon for end users. We don't expect you to match this level of discount. Bancolobmia is looking to send 15 people, so any discount will be appreciated

**Comment by dagoshe** [comment]
Hello Katie,

It is something that for sure we would like to consider and I believe that we are going to make it happen some way or another, we want that all the Silver members feel the CNCF experience all along. 
Also what we want to know is to whom shall we contact, we also consider we would be able to get a good perk for them on the sponsor side.

Kind Regards,

Jose Rodriguez

**Comment by AudMonte01** [comment]
3/23 MEETING

Marketing efforts
* Blog posted on Monday: https://www.cncf.io/blog/2023/03/21/latin-america-and-cloud-native-a-love-story/

CFP
* Closes March 31
* 15 submissions - 60 should be goal, but they have a lot of curated content
* Extended period?

Sponsors
* Sponsor Prospectus was shared
* Oracle Brazil and Bank in Equador signed on
* Bank of Colombia is interested and wants to send their people, but who should we focus on? Director of Inclusion, Director of Product, Electronic Payments...Audra to inquire about an OSPO (open source program office)

Speakers
* Microsoft Azure
* Google: "I am remarkable" program
-- asked for a small session room for privacy
* CNCF speaker TBD - ideally we figure this out by the end of the month

To-Do
* Audra to connect with memberships team to see which department of Bank of Colombia is best to meet with
* Audra to create a 60-second video from a CNCF perspective, inviting people to join

**Comment by AudMonte01** [comment]
3/28 MEETING NOTES

* CFP extended to March 31
* TO-DO: CNCF to let organizers know who from Bancolombia should be attending
* A lot of interest already! On the ups of 1200, and already having to hold tickets for sponsors, and speakers
* The hybrid aspect
-- broadcasting in-person keynotes and potentially adding pre-recorded sessions
-- They have re-stream platform if needed main stage. Can broadcast to both CNCF YouTube and their community YouTube channels

**Comment by AudMonte01** [comment]
Sponsors
* Secured 2 sponsors
* Next week they will begin their call for sponsors

Marketing
* working with K8learning

Lineup
* 90% complete
* CNCF presence
** Lori cannot make it
** Audra is willing to go and speak to community, promote other KCDs (per Jose)
** Ambassador representation (Angel)

To-Do: Audra to send bio and headshot once her presence is confirmed by CNCF

**Comment by AudMonte01** [comment]
May 10 update

* [DotLabs](https://github.com/dotlabs-academy/dotlabs-web-page) will be running a hackathon  IoT unfolded in Kubernetes using Raspberry PI V.4

**Comment by AudMonte01** [comment]
RETROSPECTIVE MEETING NOTES

Analytics
* Total registered vs total checked in 784 combined (430 in-person)
-- DevOps and Executives
* 100 proposals, 76 total speakers, and 34 non-male speakers (45%)
* Total out of pocket (in the)

Sustainability
* Donated leftover food to the university and non-profits
* Biodegradable cups and bags

Swag
* Angel, and Elias donated ambassador budget and shirts
* CNCF stickers

Attendee feedback
* Eduardo, wants to make Buenes Aires and possibly a KCD Argentina

Definitely doing a 2024 event in Q2
* [ ] Action item: Team to send Audra transparency report
* [ ] Team to share Audra videos to post on CNCF YouTube channel

**Comment by AudMonte01** [comment]
Hi @ar4mirez - following up here to see if the team received the transparency report template I shared and was able to fill it out? Also, how are the YouTube videos coming along?

**Comment by ar4mirez** [comment]
@AudMonte01 I'm checking with the about the report template, unfortunately I can't find it in y inbox would you mind send it again, please.

About the videos, here is the YouTube playlists:

- [ ] Day one https://www.youtube.com/playlist?list=PLBY1aWruoyLUPz9XIPgWePNZx3Tz4SVVo
- [ ] Day two https://www.youtube.com/playlist?list=PLBY1aWruoyLWf3MXG4QzvRVIEW1gmp6MU
- [ ] Highlights (WIP) https://www.youtube.com/playlist?list=PLBY1aWruoyLWm5-MRVX87fwoOeZuGTT1H

**Comment by AudMonte01** [comment]
I created [a YouTube playlist on the CNCF main account](https://www.youtube.com/watch?v=E015QWwldw8&list=PLj6h78yzYM2NGlhxZ1P0JXujDJWy-rMLU) which is encompassing for both Days 1 and 2 minus the hackathons

**Comment by AudMonte01** [comment]
Received transparency report and added it to: https://www.cncf.io/reports/kcd-colombia-2023/
