### ISSUE TITLE
KCD Israel 2023 (March 23)

### ISSUE THREAD

**Issue by shimont** [cncf/kubernetes-community-days#447]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [X] Event Location: Israel, Tel-Aviv, ZOA House TLV
* [X] Event Date and Time: 23/3/2023
* [X] Expected Number of Attendees: 400
* [X] Event cost per ticket, and if you will have early bird pricing or not
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [X] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: (CNCF member employee) Shimon Tolts, Datree, CEO & Co-Founder, [shimon@datree.io](mailto:shimon@datree.io), Shimon Tolts
* [X] Organizer 2: (CNCF ambassador) Itay Shakury, Aqua Security, Open Source Engineer, itay@itaysk.com, itaysk
* [X] Organizer 3: (CNCF member employee) Dana Fine, Datree, Community Manager, dana@datree.io, Dana Fine
* [X] Organizer 4: Arthur Berezin, JovianX, CEO & Co-Founder, arthur@jovianx.com, Arthur Berezin
* [X] Organizer 5: Dotan Horovits, Logz.io, Principal Developer Advocate, [dotan.horovits@gmail.com](mailto:dotan.horovits@gmail.com), Dotan Horovits (CNCF Tel-Aviv organizer, CNCF member employee) 
* [X] Organizer 6: Ronen Levinson, Snyk, Senior Software Engineer, [ronenrl21@gmail.com](mailto:ronenrl21@gmail.com), Ronen Levinson

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub forum for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender)
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schdule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Amazon Web Services

* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-israel@kubernetescommunitydays.org](mailto:organizers-israel@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF videos to be uploaded to YouTube
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hello @shimont - I'm very excited to see that a KCD Isreal is in the works! Let us schedule some time to have a kick-off meeting. Here is my calendly: https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by shimont** [comment]
Hey @AudMonte01, I just booked some time :)

**Comment by AudMonte01** [comment]
Notes:
* Audra to give Shimon SMapply access today
* Shimon thinks they will use an external platform for registration, but using Bevy as the event interface
* Will not be streaming, but possibly recording sessions depending on venue
* AWS is committed as a sponsor, but need to create a sponsor prospectus
* Dana is responsible for venue which we will discuss at our next meeting on December 5

**Comment by horovits** [comment]
@shimont @AudMonte01 please add the following KCD Israel organizers:

(CNCF Tel-Aviv organizer, CNCF member employee) Dotan Horovits, Logz.io, Principal Developer Advocate, [dotan.horovits@gmail.com](mailto:dotan.horovits@gmail.com), Dotan Horovits

Ronen Levinson, Snyk, Senior Software Engineer, [ronenrl21@gmail.com](mailto: ronenrl21@gmail.com), Ronen Levinson

**Comment by AudMonte01** [comment]
* Venue is secured?
* Sponsor prospectus is built?
* Audra has given SM Apply access to Shimon
** Discuss CFP dates?

**Comment by AudMonte01** [comment]
2/21 MEETING NOTES
* Insurance from venue was a last-minute surprise (Audra to add to KCD documentation)
* Agenda will be published soon (just waiting on speaker confirmation)
** Keynotes are established: Andrew (CNCG Tag Security) and Lori (CNCG Marketing Chair)
** 100 registrations so far
* STARS meeting (10-12 volunteers) - Audra provided CKA vouchers
* Business Development team to be on-site. Housekeeping mention of David and Leigh on the keynote stage 
** organizers to check on lounge space for David to meet with people who have questions about CNCF

**Comment by AudMonte01** [comment]
Attendance
* Sold out at 400 with consideration to sponsors and bringing more employees

CNCF Attendance
* David is invited to speaker dinner
* David will be given a space to be found for CNCF inquiries, within the venue

CNCF Store issue
* Order is stuck in customs, @k8tgreenley to help with receipt name so customs knows this is for an event

Housekeeping Deck with Acknowledgements
* WHEN: Suggest during keynotes to have slides looping, and verbal acknowledgement on stage at the beginning and end of keynotes
* CONTENT: Core Flavor, Hebrew talks, focused on Tech side vs DevOps

**Comment by AudMonte01** [comment]
April 24 RETROSPECTIVE MEETING

* What went well?
-- sold out
-- good feedback from the audience
-- great environment, and all about cloud native (friendly safe and environment), fun factor
-- achieved deep technical, cloud native content 

* What would you do better next time?
-- The venue was too small (take another hall next year. Should be able to afford to do that with sponsorships). Increase from 1 to 2 tracks
-- Have a social media leader to build cadence and consistency, through ramp-up, during and after the event
-- Have more volunteers and 1-2 more organizers (take 1-2 additional months in planning process)
-- Focus more on Hebrew presentation. Technical content is half English anyway. Change language to encourage submissions in Hebrew
-- Diversity could still be better 

* Stats (ticket price, attendees, check-ins, sponsors)
-- 418 attendees
-- ticket price $270 Sheqel / $80 USD
-- 17 speakers and 13 sessions (23% diversity)

* Will there be another KCD like this next year?
-- Yes - see above notes on what
-- Not looking to sell out. Focus on quality vs quantity 

* CNCF support
-- Better insights and collaboration to KubeDays and other CNCF events going forward
-- @k8tgreenley working with events team to get tickets. Will send call for program committee to team once it is ready

To-Dos
* @k8tgreenley or Audra to share retrospective template to use for future KCD, and put on the website
* Audra to create CNCF YouTube playlist from: https://www.youtube.com/playlist?list=PLAZYrWd6aONCI909gGj-X8DxQsE_kwIbt
