### ISSUE TITLE
KCD Zürich 2023 (June 15)

### ISSUE THREAD

**Issue by agehrig** [cncf/kubernetes-community-days#449]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Zürich City | Google Zurich venue confirmed
* [x] Event Date and Time: June 14 (workshops) and 15, 2023
* [x] Expected Number of Attendees: 200 (250-300 registrations)
* [x] Event cost per ticket, and if you will have early bird pricing or not: CHF 100-150
#### Event type:
* [ ] Virtual
* [x] Hybrid
* [ ] In person
#### Organizers Details (identify who will be the CFP admin, as well as the financial officer)
* [x] Organizer 1: Philipp Meier, Isovalent, Head of Global Ecosystem Partner, [philipp@isovalent.com](mailto:philipp@isovalent.com), @tschabalori
* [x] Organizer 2: Andreas Gehrig, arch.cloud, Co-Founder, andreas@arch.cloud, @agehrig
* [x] Organizer 3: Thomas Philipona, ROKT, Founder, thomas@rokt.cloud, @tphilipona
* [x] Organizer 4: Milena Thalmann, Founder White Rabbit Communications, milena@whiterabbitcom.ch, 

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub forum for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1: Google
Sponsor 2: Isovalent
Sponsor 3: VMware
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-zurich@kubernetescommunitydays.org](mailto:organizers-zurich@kubernetescommunitydays.org)
* [x] SM Apply CFP created and access granted
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared: https://docs.google.com/document/d/1vWMCdXlWKgpIMhAGdVBZM5w-W5cJFSVsh7Jaqwhf9dY/edit?usp=sharing

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF videos to be uploaded to YouTube
* [x] Link videos from YouTube to event page: https://www.youtube.com/watch?v=1-wD56yUczs&list=PLA_kepINgW45ZDtksu056xeCyeV13Isze
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [x] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hello @agehrig  - I'm very excited to see that a KCD Zürich is in the works! Let us schedule some time to have a kick-off meeting. Here is my calendly: https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by AudMonte01** [comment]
NOTES from our 10/27 meeting

Diversity goal for speakers is 20-25%

Other organizers:
* VSHN: Silver member of CNCF
* Wide Rabbit Communications

Organizer assignments thus far:
* Phillip will organizer venue (possible Google Zurich venue / 230 potential attendees) and staffing, project management, speaker talent help
* Thomas will managing platforms
* Andreas to run sponsorships

Website
* Interested in website template that KCD Spain used, who [is using DevFest's template](https://github.com/GDGToulouse/devfest-theme-hugo)
* NOTE: Bevy provides an opportunity to have 1 page built out with a schedule, speakers, sponsors, and a registration button

To-Dos
* Audra to send SMapply access to Thomas and Adrian. Clone Munich
* organizers to create a sponsorship prospectus by the beginning of November
* NOTE: Next meeting has been set for December 19

**Comment by AudMonte01** [comment]
Hello @agehrig and team - I have created a Bevy Chapter for KCD Zurich and an event in draft mode here: https://community.cncf.io/accounts/dashboard/#/chapter-533/events-Draft/. I was able to add Phillip and Thomas as team members which will allow them to access the event, but Andreas does not seem to have a CNCF.io account if he can please make one.

**Comment by AudMonte01** [comment]
Ticket sales are already in budget

Sponsors
* many verbal 
* Community sponsor diversity initiative [Tech Face](http://techface.ch/) who will be diversity sponsor
* 30-40k Swiss Francs already signed out of 70k goal

Registrations
* 100 swiss francs
* Different ticketing tool for 

Flow of show
* 2 tracks of sessions

Swiss IT Media (Insight IT)
* Interview two speakers
* Promote on their channels

Speakers
* 50% non-male speakers so far

Website
* Linking from Bevy page
* Online in January

Slack
* do not need a CNCF workspace slack channel
* But will use channel for attendees

To-Dos
* Create an email alias with 3 organizers + hello@kcdzurich.ch + milena@whiterabbitcom.ch
* Audra to create attendee slack channel
* Audra to check that Philip and Andreas has access to SM apply

**Comment by k8tgreenley** [comment]
Organizer email has been created: organizers-zurich@kubernetescommunitydays.org

**Comment by AudMonte01** [comment]
1/16/23 MEETING NOTES

Website
* Launches end of January which is when marketing will begin

Sponsors
* Already have 12 sponsors
* Stopped taking sponsorships

CFP
* Launching CFP beginning of February

CNCF Support
* Audra provided them with sticker coupon code
* Audra let them know of KubeCon 50% discount
* Audra let them know about CKA exam voucher option

**Comment by AudMonte01** [comment]
APRIL 25 MEETING

Agenda
* 88 proposals
* finishing reviewing the proposals
* above 20% on the diversity front

Sponsors
* No talks in part of their

Tickets
* Another 40 open for sale
* Sponsor tickets will be released soon
* On track towards goals

Workshops
* 5 workshops needing to be filled

To-Dos
* Audra to send voucher codes to organizer via email and Slack

**Comment by AudMonte01** [comment]
MAY 22 MEETING NOTES 

* Tickets: Sold out at 250 seats. Event waitlist tickets are sold out
* Sponsorships: Plenty. Will be able to forward funds to 2024 KCD
-- Google is sponsoring badges, catering, and A/V

Marketing
* Ancillary events (speaker dinner)
* Will create good video assets
* Podcast interview with 5 speakers post-event (about 10 days after)
* Speaker videos will be uploaded to YouTube and CNCF will create a playlist

Program
* Looking to confirm 1 s. last speaker. They have a few back-up speakers
* @agehrig - Kelsey Hightower said it's hard to work for free during the travel and time there. Here is his pricing: aaespeakers.com/keynote-speakers/kelsey-hightower

On-site
* Volunteers for directional and registration guidance
* Photographer on-site and Milena + organizers will be posting LIVE content
* Organizers will emcee

**Comment by AudMonte01** [comment]
Thank you for creating a [playlist of videos here](https://www.youtube.com/watch?v=1-wD56yUczs&list=PLA_kepINgW45ZDtksu056xeCyeV13Isze).

A CNCF playlist was created from this here: https://www.youtube.com/playlist?list=PLj6h78yzYM2M4oTo8BEsrRSutWO8xomiV

**Comment by AudMonte01** [comment]
I will till wait for the blog post to post on CNCF, but will close this. issue in the meantime.
