### ISSUE TITLE
KCD Czech & Slovak - Bratislava 2023 (May 19 - 21)

### ISSUE THREAD

**Issue by georg007** [cncf/kubernetes-community-days#450]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [X] Event Location: Slovakia, Bratislava, Slovenská technická univerzita v Bratislave
Fakulta informatiky a informačných technológií, Ilkovičova 6276/2, 842 16 Bratislava 4 
* [X] Event Date and Time: 19 - 21 May 2023
* [X] Expected Number of Attendees 400
* [X] Event cost per ticket, and if you will have early bird pricing or not 
#### Event type:
* [ ] Virtual
* [X] Hybrid
* [X] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [X] Organizer 1: Juraj Hantak, Conag, CTO, georg007@gmail.com, CNCF Slack Username: Juraj Hantak
* [X] Organizer 2: Filip Pohronsky, DITEC, TSA, pohronsky@ditec.sk, CNCF Slack Username: Filip Pohronsky
* [X] Organizer 3: Zdenek Vana, Prusa Research a.s., Cloud DevOps Architect, vanazde1@gmail.com, CNCF Slack zdenek.vana
* [X] Organizer 4: Tomas Jamrich, LMC, s.r.o. platform infrastructure engineer, tomas.jamrich@lmc.eu,CNCF Slack tomas jamrich
* [X] Organizer 5: Tomas Bocinec, Siemens Healthcare s.r.o., Site reliability engineering, t.bocinec@gmail.com. 
* [X] Organizer 6: Lenka Bocincova, Red Hat, Community Architect, lenka.bocincova@gmail.com, CNCF Slack Lenka Bocincova

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub forum for easy tracking
* [X] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [X] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
NGO:
Združenie pre podporu Cloud Native technológií
ID NO (ICO): 52821595
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: organizers-czech-slovak@kubernetescommunitydays.org 
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] [Marketing Plan shared](https://docs.google.com/document/d/1vWMCdXlWKgpIMhAGdVBZM5w-W5cJFSVsh7Jaqwhf9dY/edit) - You can make a copy and edit it to your specific KCD

### Organizer Planning Timeline
* [X] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hello @georg007 - we are so happy to hear this event is happening again in May! Please to meet you. I joined CNCF in June to manage KCDs from the CNCF side as your support. Let's kick off a meeting if you and the team can please find a time that best suites you: https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by AudMonte01** [comment]
MEETING NOTES FROM November 21 meeting

Venue
* University that can accommodate up to 500 people
* Possibly free venue because it is during exam time

Program
* Opening attendance up to Hungaria, Austria, Polan by  having one track in English
* The other/main track will be in Slovak 

Hybrid Model
* Background: virtual event was set at the wrong event type (could not collect stats to send to sponsors)
* Use Slido with QR code that can be used in-person and virtually

Tickets
* Possibly using eventbrite platform, but will use a ticketing service external from Bevy

**Comment by AudMonte01** [comment]
12/12 MEETING NOTES

Schedule
* Plan to offer workshops in a separate room on same days as sessions and keynotes
* 2 tracks / 2 rooms (1 small room for local language, and 1 large room in English)
* evening social event

Registration
* Using an external platform
* Opening early bird ticketing end of December and closing in February?

Call for Proposals
* Close CFP at the end of February

To-Do:
* Audra to send new CNCF branding
* Audra to send transparency report for KubeCon EU 2022
* Launch CFP and assure are dates are accurate

Bevy platform Feedback
* Better automation within the schedule changing (notification to speakers)
* Utilizing calendar feature

SIDE NOTE: Ambassador applications open December 15 and close February 26

**Comment by AudMonte01** [comment]
1/16/23 MEETING NOTES

Bevy page is ready
* TO-DO: Audra to review and get back to team with feedback
* Publish it and add it to the drop-down

CFP Marketing (closes March 1)
* CNCF blog post will be written in English. Post at beginning of February at latest
* Post part of the program at the end of February for people who already paid for tickets

Sponsorship Prospectus
* In contact with 30-40 companies (Google and Grafana, etc), and includes previous year's sponsors

**Comment by AudMonte01** [comment]
Hello - let's create a monthly check-in to meet again. Would after KubeCon work for at least 2 of you? If so, here is my Calendly for scheduling: https://calendly.com/audmonte/30min. This would be a good time to review your schedule ahead of publishing the lineup of speakers

**Comment by AudMonte01** [comment]
Hi @k8tgreenley - can you make sure this alias is up-to-date with the above organizers emails?
organizers-czech-slovak@kubernetescommunitydays.org

**Comment by AudMonte01** [comment]
May 9 check-in

* Social event on Saturday for speakers and sponsors (80-100 people)
* Housekeeping slides with Slido survey at the end of the looping deck
* Would like to use Kahoot! - Audra to check to see if events team has an account
* Audra shared signage templates for any last-minute printing / design needs

**Comment by AudMonte01** [comment]
MAY 15 MEETING

* Event is this weekend!
* Tickets sold?
-- 182 waiting for final speakers and volunteers to register
* Speakers
-- Audra let them know about offering a Credly badge: https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform
* Panel discussion
--To-Do: Asking Lenka if she can be the moderator, and Zdenek can stay on as a panelist

**Comment by AudMonte01** [comment]
MAY 26 RETROSPECTIVE MEETING

Number of people on-site / check-ins vs final number of registrations
* 295 registration (62 tickets virtual, 230 in-person)
* 210 checked-in / 91% attendance
-- 140/150 each day with Friday (students attended) as the strongest day
-- Sunday 60/70 people stayed until the end of the day)
* 62 people engaged in the end of event raffle

Thoughts on how the event went:

Went well
* Pycon organizers helped with vendor and supplier recommendations 
* Marketing with community groups and DevOps days
* No speakers backed out
* Using Slido for questions and on-site agenda worked well

Lessons Learned
* Consider national holidays in surrounding regions ahead of creating the events
* Deliver discount codes earlier to community groups
* Start marketing the lineup earlier (start 1-2 months earlier)
* Agenda in bevy was a struggle with multiple points being updated on the agenda side

Platform Feedback
* Would be great to have an integration with Slido or Sched
* Action: Can we organize agenda in Sessionize and integrate with other platforms
* Registration tool should have help with printing badges on-site
* [ ]Action: Audra to check with Bevy on-site badge
* Bevy feedback
-- good to have a help page that shows how backend functionality and speed of sites
-- NOTE: In May 5-10 minutes of website was down

Video timeline for YouTube
* Videos will be ready early next week
* CNCF to promote Czech and Slovak playlist

Social Media
* Social media during event helped with follower account
* [ ] Action: Audra to look into follower inncrease for social during small CNCF events

Juraj Blog Post
* Working on it over the weekend and will have team review ahead of
