### ISSUE TITLE
KCD Munich 2023 (17-18th July)

### ISSUE THREAD

**Issue by mkorbi** [cncf/kubernetes-community-days#451]
# KCD Organizer Checklist

### Event Details
* [x] Event Location: Smart Village Arabellapark, Munich, Germany
* [x] Event Date and Time: 17-18th of July
* [x] Expected Number of Attendees: 400
* [x] Event cost per ticket, and if you will have early bird pricing or not
  * [ ] Ticket prices
  * [ ] Regular: 160€
  * [ ] Late Joiner: 190€
  * [ ] 1 Day Pass: 100€
  * [ ] Early Bird: 100€
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Max Körbächer, Liquid Reply, Co-Founder, m.koerbaecher@reply.de, Max Körbächer
* [x] Organizer 2: Hannes Hanusch, Unikube, Co-Founder, hannes@unikube.io, <>
* [x] Organizer 3: Tabea Hessler, Unikube, Online Marketing Manager, tabea@unikube.io, <>
* [x] Organizer 4: Tom Uhlig, Liquid Reply, Consultant, t.uhlig@reply.de, <>
* [x] Organizer 5:  Nico Meisenzahl, whiteduck, Cloud Solution Architect, nico.meisenzahl@whiteduck.de, Nico Meisenzahl
* [x] Organizer 6:  Markus Sümmchen, whiteduck, Founder, markus.suemmchen@whiteduck.de, <>
* [x] Organizer 7: Anela Avdibegovic, whiteduck, Marketing Manager, anela.avdibegovic@whiteduck.de, <> 
* [x] Organizer 8: Dominik Bittl, x-cellent, Senior Lead Professional DevOps, dominik.bittl@gmail.com <> 

- [x] CFP Admin: Max 
- [x] Financial Officer: Markus
- [x] Ticket Master: Hannes

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub forum for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [ ] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
- Liquid Reply
- whiteduck
- Unikube
- x-cellent
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
whiteduck / Markus Sümmchen
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
  * [x] [Twitter](https://twitter.com/KCDMunich)
  * [x] [LinkedIn](https://www.linkedin.com/company/kubernetes-community-days-munich)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: organizers-munich@kubernetescommunitydays.org
  * [x] Need to update the recipients 
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in Sessionize with access provided to CNCF
* [x] Marketing Plan shared: https://docs.google.com/document/d/1vWMCdXlWKgpIMhAGdVBZM5w-W5cJFSVsh7Jaqwhf9dY/edit#heading=h.dx1tr63u8jgp

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [x] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by mkorbi** [comment]
@AudMonte01 we are not yet sure if we want to use SMapply anything else is ready

**Comment by AudMonte01** [comment]
> we are not yet sure if we want to use SMapply anything else is ready

@mkorbi - what CFP platform would you use?

**Comment by mkorbi** [comment]
sessionize will be our CFP platform

**Comment by AudMonte01** [comment]
> sessionize will be our CFP platform

Okay Max - adding here what we talked about in Slack. 

Thanks in advance for providing both @k8tgreenley and I access, and adding a link to the CFP backend here.

**Comment by AudMonte01** [comment]
@k8tgreenley - can you please update the KCD Munich organiser alias for the organisers here?

**Comment by k8tgreenley** [comment]
I have updated the email alias with the new team

**Comment by AudMonte01** [comment]
Hi @k8tgreenley - could you please update Dominik's email address on the organiser alias? The issue above has his email (gmail).

**Comment by k8tgreenley** [comment]
This has been updated

**Comment by AudMonte01** [comment]
MAY 9 MEETING NOTES

Program
* 197 submissions, and reviews will wrap up reviewing this weekend, but having schedule built by May 15
* About 20 submissions from non-male speakers with 2-3 asking for T&L help

Tickets
* Tickets are open with early period having ended in March
-- Have already given away 3 diversity tickets (for every Gold + Silver sponsor there are 3 more tickets added)
-- Criteria are students, or laid off employees

Other notes
* Volunteers - Women in Computer science from the Munich Technical University (10-20 people)
* Community - there is more traction this year with GitLab and other Dev Advocates promoting the event.
* Sponsors - Great traction, only waiting on 5 companies to come through to meet goal
* CNCF on-site presence - Small table near the entrance and side by side with the registration desk

To-Do
* Audra to send sticker and exam voucher codes via email

**Comment by AudMonte01** [comment]
June 9 MEETING NOTES

New Website
* Will migrate more details to main website and then link from Bevy page

Exam vouchers
* 6 giveaways as part of the diversity package

Content
* Day 1: Mixed in terms of intermediate and advanced, and some business topics.
-- Workshops + co-located workshops (slightly overlaps with sessions, and attendees get access to the rest of the event). Workshops are very niche topics and more software oriented 
* Day 2: Community-driven, and open source ecosystem, and lightning talks

Sponsorships
* Gold sponsors are sold out including Google. Dynatrace is due to sign
* Silver and Bronze are theoretically sold out with 3 open requests
-- Action: Pending visa letters written by @k8tgreenley 

Tickets
* 50 speakers still need to register
* 13 sponsors still need to register

Marketing
* Nico might write a blog for CNCF blog
* Social amplification of linkedin.com/posts/kubernetes-community-days-munich_kubernetes-kubernetescommunitydays-kcd-activity-7070045699853168643-l4w1?

Printers on-site
* [ ] Badge printers - does LF have printers in storage, or Cvent brings them?
* Large cost for KCDs including shipping and insurance just for lending printers

**Comment by AudMonte01** [comment]
Hi @mkorbi, CNCF-hosted events use Cvent for their registration platform, and Cvent brings the printers on-site. So to answer your question, CNCF does not own, store and insure badge printers.

You might consider having attendees print their own badges, and to check-in, they bring their badge with their identification, and in exchange, you give them a badge holder and lanyard.

"With Eventbrite, it’s easy to create, edit, and send printable custom tickets to your event attendees. Our online ticketing system automatically generates and distributes digital event tickets as a PDF attachment with order confirmation emails. Attendees can easily download and print tickets via the Eventbrite app after completing their online order. Event ticket printing has never been easier!"

**Comment by AudMonte01** [comment]
@mkorbi - do you have or want to create a transparency report for this event?

**Comment by mkorbi** [comment]
We looked into this already last year, but we didn't collect enough data to provide this report.

**Comment by AudMonte01** [comment]
Not to worry. We will properly enable your team for the 2024 version to have a robust transparency report.

I will close this issue now.
