### ISSUE TITLE
KCD Bengaluru 2023 (June 2-3)

### ISSUE THREAD

**Issue by nkhare** [cncf/kubernetes-community-days#452]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: NIMHANS Convention Centre, Bengaluru 
* [x] Event Date and Time: 2nd & 3rd June'23
* [x] Expected Number of Attendees: 500
* [x] Event cost per ticket - INR 1500 (~$18) Regular and for early bird INR 100 (~$12) 
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify who will be the CFP admin, as well as the financial officer)
* [x] Organizer 1 and financial officer : Neependra Khare , CloudYuga, Founder & Principal Consultant , neependra@cloudyuga.guru, neependra
* [x] Organizer 2: Kiran Mova, VMware, Senior Manager, kmova@vmware.com, 
* [x] Organizer 3: Prithvi Raj, Harness, Community Manager,prithvi.raj@harness.io, CNCF Slack Username
* [x] Organizer 4: Aravind Putrevu, Calyptia Inc, Head of Developer Experience, aravind@devrel.cloud,aravind 
* [x] Organizer 5: Rachna Anuj, Nirmata Inc., Program manager, rachna@nirmata.com,  @Rachna Anuj 

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub forum for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (prospectus [found here](https://drive.google.com/file/d/1TjfsJUiTEvaeAbpUOOgFdgKqvw9F4oik/view))
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: using Google group instead
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by humblec** [comment]
@nkhare I was about to create one and noticed this issue :) ..  please let me know how can I help ?

**Comment by cloudyuga** [comment]
> @nkhare I was about to create one and noticed this issue :) .. please let me know how can we collaborate ?

Sure. We'll start planning soon. Will keep you posted.

**Comment by nkhare** [comment]
@k8tgreenley it seems we are not able to create the new program under KCD SMapply (https://kcd.smapply.io). Can you please help for the same. We need to launch the site on 6th Feb. cc @kmova

**Comment by k8tgreenley** [comment]
@nkhare can you please send me the details for your CFP and I will create it. Who should have permissions from your team to create CFPs?

**Comment by nkhare** [comment]
> @nkhare can you please send me the details for your CFP and I will create it. Who should have permissions from your team to create CFPs?

## Details 
- CFP of KCD Bengaluru 
-  Start Date: 9th Feb'23
- Last Submission Date: 20th March'23 

For now please give to @kmova (kmova@vmware.com) and me (neependra@cloudyuga.guru)

**Comment by degreerising** [comment]
Hi KCD bangalore 2023  team,
How volunteer for support in kcd bangalore even?
Some enthusiastic have shown interest but they are not sure what kind of skills  or what they can do to support the event.

**Comment by nkhare** [comment]
> Hi KCD bangalore 2023 team, How volunteer for support in kcd bangalore even? Some enthusiastic have shown interest but they are not sure what kind of skills or what they can do to support the event.

We rolled out a form for volunteers and received overwhelmed response. We have selected few and and taking the next steps now. For this year's KCD we are now good but if someone is interested, then they volunteer in the other KCD events, which are now happening across India.

**Comment by AudMonte01** [comment]
March 21 MEETING NOTES

* Might change event to 2 days, depending on a couple of factors.
* 134 submission so far in the CFP!
* 4 sponsors (2 gold and 2 silver) - with a few more who have showed interest
* Sponsor Prospectus [found here](https://drive.google.com/file/d/1TjfsJUiTEvaeAbpUOOgFdgKqvw9F4oik/view)
* They have venue meeting next week to discuss sponsor booth space
* Sold 151 tickets so far
* March 27 is when the CFP closes, 2 weeks for review, targeting April 30 for agenda release
* April 22 workshops will start (10 workshops total) hosted on the weekends
** 2 volunteers are currently helping with workshops

**Comment by nkhare** [comment]
Thanks to our sponsors and community support,  the event is now for 2 days 2nd and 3rd June'23.

**Comment by AudMonte01** [comment]
MEETING NOTES

Sponsors
-- a few more in Silver
-- finalizing layouts for each tiers

Agenda
-- Will release around April 30
-- Audra shared diversity goals of over 21%
CFP
-- approximately 90+ companies have applied
-- 126 applicants are in the age group of 20-39, about 25 in 40+, rest have not disclosed
-- Around 160+ are identified as man and 21 as woman

Tickets
-- 25 Free tickets to students

Swag
-- Idea would be interested in a CNCF swag for purchases 

To-Dos
-- Audra to send exam voucher and CNCF store codes via email
-- Signage templates can be [found here]: https://cloud-native.slack.com/archives/GQ7D26NPQ/p1676481369625229

**Comment by nkhare** [comment]
> MAY 29 CHECK-IN MEETING NOTES

>   Fun addition
> * sketch of each speaker

Small correction. We'll be having sketchnote done for each talk.

**Comment by AudMonte01** [comment]
June 9 RETROSPECTIVE

How many actual check-ins did the program have?
* 689 checked-in our of 800 sold tickets (86.13% attendance rate)

Positives of the event
* Location was good
* Surplus to carry over to next event (awaiting 2 sponsor payments)
* Content (62 speakers and 14 companies represented)
-- 14 women (23%) and 10 students (16%)
* Attendee feedback was good! 4.35 out of 5 stars

Lessons learned
* Sell more tickets at base cost to allow for a 2-day event with respect to giving back to the audience with a T-shirt and food, vs relying on sponsorships for this.
* Smaller booths to accommodate more sponsors
-- Use a different vendor for the building of the booths
* Leftover food donated to hospital. Could have been better food.
* How to get workshops to submit to CFP? Perhaps open it longer than 1.5 months and shorten the review and selection process
-- release schedule earlier than 4 weeks (6-8 weeks ahead of the event)
-- will add advanced content next time
-- retaining attention of the audience
-- Topics: Security, clusters and multi-cluster, and observability. Favorite was K8s
* A/V
-- Laptop resolution was not supported 
* Comms
-- email marketing and housekeeping
-- scout quality representation of diversity in advance
* Bevy platform integration with Slack would be best for community interaction during the virtual part of the event

CNCF presence
* Ambassadors as a resource (use their budget to travel)
-- workshop or CNCF table/booth
* Add a 5-minute pre-recorded session from CNCF about what it is
* Standard quiz to gauge audience awareness and provide experimental piece

Action Items
* [ ] Audra to provide transparency report template

**Comment by AudMonte01** [comment]
UPDATE

* Transparency report template shared
* Credly badge for contributor created and distributed

Outstanding
* Videos for YouTube playlist (Rohit to share with Audra)

**Comment by prashil-g** [comment]
> > Will the slides from KCD Bangalore 2023 be shared somewhere?
> 
> Yes. Please allow a week to share the details.

@nkhare Are the slides shared somewhere? 
Also, youtube video link if it can be shared?

**Comment by nkhare** [comment]
@AudMonte01 I am closing this issue and opening a new one for 2024 :)

**Comment by prashil-g** [comment]
> > > Will the slides from KCD Bangalore 2023 be shared somewhere?
> > 
> > 
> > Yes. Please allow a week to share the details.
> 
> @nkhare Are the slides shared somewhere? Also, youtube video link if it can be shared?

@nkhare Can you please share the slides and video sessions link if uploaded?

**Comment by nkhare** [comment]
> > > Will the slides from KCD Bangalore 2023 be shared somewhere?
> > 
> > 
> > Yes. Please allow a week to share the details.
> 
> @nkhare Are the slides shared somewhere? Also, youtube video link if it can be shared?
https://www.youtube.com/playlist?list=PLo4lFffE9Ct9rvNjSOOL64VTs_qVnrSnI
