### ISSUE TITLE
KCD Ukraine 2023 - Charity (March 16)

### ISSUE THREAD

**Issue by mkorbi** [cncf/kubernetes-community-days#454]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Online
* [x] Event Date and Time: March 16
* [x] Expected Number of Attendees: 200
* [x] Event cost per ticket: FREE
#### Event type:
* [x] Virtual
* [ ] Hybrid
* [ ] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Max Körbächer, Liquid Reply, Co-Founder, m.koerbaecher@reply.de, Max Körbächer
* [x] Organizer 2: Kateryna Ivashchenko, Company, Teleport, kateryna@goteleport.com, Kateryna Ivashchenko
* [x] Organizer 3: Wojtek Cichoń, Akuity, Marketing Manager, wojtek@akuity.io, Wojtek Cichoń
* [x] Organizer 4: Volodymyr Tsap, Shalb, CTO, voa@shalb.com, Volodymyr Tsap
* [x] Organizer 5: Ihor Dvoretskyi, CNCF, Sr. Developer Advocate, ihor@cncf.io, Ihor Dvoretskyi

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [ ] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
* [ ] Identified beneficiary of event and setup crowdsourcing page 
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-ukraine@kubernetescommunitydays.org](mailto:organizers-ukraine@kubernetescommunitydays.org),
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by idvoretskyi** [comment]
Awesome news!

FYI @voatsap

**Comment by AudMonte01** [comment]
MEETING NOTES

Speakers
* Reach out via Krupe(?) IT Arena in Ukraine (usually 20k attendees)
-- pre-recorded option
* GitLab (Max is connected to Dev Advocate in Germany) and Gramerly founders
* Kelsey Hightower (Audra is connected and can ask for his presence) - opening speaker with technical touch
* Ukrainian IT Ministry 
* Fireside chat option
* CTO of [Shelb](https://www.shalb.com/) 

Open CFP
* Early January

Donations: Tracking via the collaboration with website 
* Charge for the event and the choices can be donated to the following
-- Crowd Sourcing via TLF website
-- Paws for Ukraine
-- Razom for Ukraine 

Streaming platform
* Bevy vs Streamyard

To-Do
* Set up SM Apply (mimic Munich workflow - edit from there)
* Audra to check with TLF events team 
* Audra to introduce Volodymyr Tsap to Max for co-organization or program committee 
* Audra to send Bevy resources to Max regarding streaming

**Comment by idvoretskyi** [comment]
I'd suggest considering @voatsap n joining the program committee or as a co-org (he's a Kyiv community group co-founder and lead - https://community.cncf.io/kyiv/).

Also, if you need connections with the Razom for Ukraine, drop me a note.

**Comment by AudMonte01** [comment]
Nice to connect with you on Slack @idvoretskyi :-)

noting here that I have connect Max and Volodymyr via email, and that we would love to be in touch with the Razom for Ukraine folks to figure out the best way to track how many funds will be coming from this event to them. Per your suggestion, a crowd funding page dedicated to this would be great!

**Comment by AudMonte01** [comment]
@mkorbi - here are the [Self-paced Bevy video tutorials](http://vimeo.com/showcase/bevy-virtual-conference) [Use Password: "devfest"] which covers how to use virtual streaming within the platform.

**Comment by wojtekidd** [comment]
👋🏻 If we don't have anything yet in terms of the "about the event" media blurb, I can start writing the content for the page of this meeting. Also, let me know what kind of graphical assets we will need re: Bevy - I can make them happen with our designer.

**Comment by wojtekidd** [comment]
@idvoretskyi Razom was my first choice when I thought about whom we should donate. If no one else has reached out yet, I can do this too 👍🏻

**Comment by AudMonte01** [comment]
@wojtekidd - regarding design assets: the logo should be 400x400 pixels and should be what contains the title of the event as it will sit on top of a header image that should be 2560 x 650 pixels and focus on having a visual graphic centered, and without words (scales funny in different browsers where words can get lost). Both can be JPG or PNG files.

**Comment by idvoretskyi** [comment]
@wojtekidd I'll make a connection, no worries :)

**Comment by wojtekidd** [comment]
Here it is 👇🏻  I hope you like it 🤞🏻 

<img width="1280" alt="ukr-kubernetes-bg" src="https://user-images.githubusercontent.com/6146254/207401656-dded24bb-26e3-4bc6-8a2e-4a3db13a68f6.png">
<img width="512" alt="ukr-kubernetes-logotype-1" src="https://user-images.githubusercontent.com/6146254/207401668-da9eac3e-f8af-4f52-bbd2-daca3cba4be4.png">
<img width="512" alt="ukr-kubernetes-logotype" src="https://user-images.githubusercontent.com/6146254/207401673-7549721e-cc0c-43df-aa3c-98ef83d7fe83.png">

**Comment by AudMonte01** [comment]
Very nice! @mkorbi, @idvoretskyi - what do you think?

**Comment by idvoretskyi** [comment]
@AudMonte01 looks good to me.

**Comment by mkorbi** [comment]
Let's go for it! @AudMonte01 

Thank you @wojtekidd :)

**Comment by wojtekidd** [comment]
No problemo - I just replaced the background image - our designer just noticed small discrepancy between the shades of blue - it's ok now.

**Comment by AudMonte01** [comment]
Okay - I have added both images to the draft event in Bevy.
