### ISSUE TITLE
KCD Kerala 2024 (February)

### ISSUE THREAD

**Issue by humblec** [cncf/kubernetes-community-days#455]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Cochin
* [x] Event Date and Time: Feb 2024
* [x] Expected Number of Attendees: 500
* [x] Event cost per ticket, and if you will have early bird pricing or not : Early Bird pricing will be there. Yet to decide the pricing.

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)

* [x] **Lead organizer and Financial Officer**:
    Humble Chirammal, VMware, Staff Engineer, humble.devassy@gmail.com

* [x] Organizer 2: ( CFP Admin)
    Sreejith Anujan, Red Hat, Senior Consultant, sreejithanujan@gmail.com 

* [x] Organizer 3: Dhanesh, Salescode, Co-founder & Technology Head , dhaneeshTNair@gmail.com

* [x] Organizer 4: Dipu Devarajan, KnownHost, Support Supervisor,  dipudevarajan@gmail.com

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Red Hat
VMware
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments: 
Fiscal sponsor: Ambersand Inc.

* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) : @KCDKerala
* [x] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hello @humblec - great to see this submission! Would you consider calling this KCD Kerala so it is a larger region in India?

Also, please let me know once you have secured two more organizers from different companies, and we can have a kick-off/launch call. Thank you!

**Comment by humblec** [comment]
> Hello @humblec - great to see this submission! Would you consider calling this KCD Kerala so it is a larger region in India?

Indeed , more than happy to do that!! I have retitled this to KCD kerala. 

> 
> Also, please let me know once you have secured two more organizers from different companies, and we can have a kick-off/launch call. Thank you!

Sure.. yw! and Thanks @AudMonte01 :+1:

**Comment by humblec** [comment]
Working towards meeting some prerequisites for the event . will update this thread soon after finalizing some part of it.. thanks!

**Comment by AudMonte01** [comment]
Please note that [KCD Bengladesh](https://github.com/cncf/kubernetes-community-days/issues/471) and [KCD Gurugram](https://github.com/cncf/kubernetes-community-days/issues/472) hope to be in December, but they have yet to secure 3 organizers. We require that every KCD that happens in India at least be 2 months a part.

**Comment by AudMonte01** [comment]
Yes, and you might even consider 2024 because we will be hosting a KubeDay India at the end this year as well.

**Comment by AudMonte01** [comment]
Excellent @humblec - it will likely have to be in 2024. Please also refer to events here: https://www.cncf.io/events/

**Comment by AudMonte01** [comment]
Hi @humblec - January 6 would be ideal since Bengalure India is only 2.5 hours flying time to Kerala, Bangladesh.

I have removed the need organizers tab.

Let's host a kick-off meeting! https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by humblec** [comment]
@AudMonte01 Awesome!! I have changed the date from November to Jan 6th!! Scheduling a kickoff call! Thanks 👍

**Comment by AudMonte01** [comment]
Hi @humblec - my apologies, I missunderstood your earlier message, and thought you were implying that Kerala was in Bengladesh. Given Kerala is India, and KubeDay India is happening December 8, we need to assure all KCDs and CNCF-hosted events in the same country are at least 2 months apart. So this would have to be the first week of February to apply to the terms.

**Comment by AudMonte01** [comment]
KICK-OFF MEETING NOTES

Venues
* Team already has a shortlist and will now pursue with final dates
* Goal to have 300 attendees, but will look for a capacity if 500 max

Audience (mixed crowd)
* Student track
* Professional track

Organizers
* Humble: VMware tech lead. Contributing to K8s since 2016. Was with RedHat for a long time.
* Prasad: Site reliability and infrastructure. Worked with RedHat and EmC. Moved back to Kerala 6 years ago (home town). 16 years in the industry.
* Sreejith: Worked RedHat for 15 years and active open source and community evangelist. In industry for about 20 years.

Actions
* [ ] Audra to create Slack channel for organizers
* [ ] Audra to add organizers to main kcd organizer channel
* [ ] Audra to share Sponsorship Template with entire team

**Comment by AudMonte01** [comment]
SEPTEMBER 12 MEETING NOTES

Dates February 3 or 10

Final venue location
* Kochin Le Meridian with a max capacity of 800

CFP dates
* Entertaining using Sessionize
* Close by December 3 and December 15 notifications go out

Actions
* [ ] Audra to download PDF of prospectus and send to Humble
* [ ] Audra to see if there are videos for Sessionize training
* [ ] Audra to enable team with Bevy

**Comment by iamvishnuks** [comment]
@AudMonte01 I’m part of CNCG Kochi, and we’ve been committed to fostering a vibrant tech community in Kerala through our offline meetups over the past few years. We’ve noticed that Kubernetes Kerala is planning a KCD event in the region, despite not having held any offline events here so far.

We appreciate the enthusiasm for promoting Kubernetes in Kerala but feel concerned that our longstanding efforts might be overshadowed by this new initiative. We’ve invested a lot of time and resources into cultivating the tech community here, and it would be disheartening to see these efforts diluted.

https://community.cncf.io/kochi/

**Comment by AudMonte01** [comment]
Hi @iamvishnuks - thank you for reaching out and expressing your concern in a productive way. My apologies for not looping your organizer team in sooner, as I did not realize KL stood for Kerala (your chapter location is Kochi, KL, India). That said, let's see how you can collaborate with one another. Please stay tuned.

**Comment by AudMonte01** [comment]
OCTOBER 19 MEETING NOTES

Logo
*[ ] Audra to provide other KCD examples and inquire with LF Creative team about regional aspect of globe

Call for Proposals
* October 20 launch

Sponsorships
* Team will reach out to community partners in mid November

**Comment by iamvishnuks** [comment]
@AudMonte01 We are awaiting a prompt response regarding the matter of territorial conflict. It's essential to recognize that the Kubernetes Kerala community chapter was originally founded in Thrissur, not in Kochi. There already exists an active community group in Kochi, and overlapping territories could result in unnecessary conflicts.

With all due respect, we strongly recommend reverting the venue for the upcoming KCD event back to Thrissur. This would help maintain the integrity and historical foundation of our community chapter. Our team has been actively contributing to the development of the tech community in this region, and we believe it's equitable that we continue to spearhead the efforts here.

We trust that you will give this matter the serious consideration it deserves. We would hate for anyone to inadvertently step on toes. Thank you for your attention to this issue.

@humblec  Could you please clarify why Kochi was chosen as the venue, given that you were already aware of an active community there? While @AudMonte01 may argue that Kochi, Kerala and Kochi, KL are distinct, it seems you were informed from the outset about the existing community.

**Comment by AudMonte01** [comment]
Hi @iamvishnuks - this GitHub issue was submitted nearly 1 year ago, and the team has worked hard to get the current venue due to CNCF pushing their event from 2023 to 2024 because of conflicts in other events in India. Therefore, we do not want to undo the hard work that has been done, and hope the two groups can collaborate in the spirit of open source. That said, we hope your team can take part in a community partnership with this event. This opportunity will open in mid November.

**Comment by dijeesh** [comment]
👋  @AudMonte01  @k8tgreenley 

Thank you for the response and collaboration spirit, We're all about fostering an open-source community and don't want to disrupt anyone's flow. I've let my team know to hang tight.

As mentioned by our team members, we've invested significant time and effort in cultivating a thriving community in Kochi— hosting meetups, running workshops, amplifying the CNCF message, and working towards bringing KCD to our town. 

The sudden announcement of KCD in Kochi by individuals not actively engaged in any of the local tech communities, located around 400-500km away from Kochi, without proper confirmation from CNCG Kochi Organizers, has raises some concerns about work ethics.

Let's keep it professional and in the spirit of collaboration, please ensure this will not happen in upcoming years.

**Comment by AudMonte01** [comment]
NOVEMBER 28 MEETING NOTES

Content
* 78 submissions with 10 or 11 in progress
* 3 tracks (or 2 tracks + a poster session)
* May have some native speaking sessions
* Reviewing in the next weeks

Marketing
* Audra shared marketing plan for team to copy
* [ ] Audra to link to sponsor prospectus in KubeWeekly newsletter

**Comment by AudMonte01** [comment]
Agenda

Sponsor prospectus
* Humble sent PDF, and Audra uploaded to [the KCD GitHub repo here](https://github.com/cncf/kubernetes-community-days/blob/main/sponsor-resources/open-prospectuses/2024_Kerala_SponsorProspectus_KCD.pdf)

Community collaboration
* No submissions have come through from other local community groups
* There is an incentive for a free ticket

Logo update
1. [ ] Team will async with Audra on how they want their logo shown with the new KCD logo
2. [ ] Audra to submit request to LF Creative
