### ISSUE TITLE
KCD Istanbul 2023 (June 13-15)

### ISSUE THREAD

**Issue by AudMonte01** [cncf/kubernetes-community-days#457]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Medipol University
* [x] Event Date and Time: June 13-15 (2 days + day 3 of workshops)
* [x] Expected Number of Attendees: 400-600
* [x] Event cost per ticket, and if you will have early bird pricing or not

**VIP** = 4.500,00 ₺ (Early Bird = 3.500,00 ₺)
**Regular+** = 750,00 ₺ (Early Bird = 350,00 ₺)
**Regular** = 350,00 ₺
**One Day Pass** = 250,00 ₺
**Workshop Pass** = 500,00 ₺
**Late Pass** = 1.000,00 ₺ (Physical Ticket at the Door)
_(Details will be on the website and social media.)_
_(The student discount rate is 25%.)_
_(Sponsor company personnel discount rate is 30%.)_
_(Supporter University student discount rate is 30%.)_

#### Event type:
* [x]  Hybrid (livestream)
* [x]  In Person
#### Organizers Details (identify who will be the CFP admin, as well as the financial officer)
* [x] Organizer 1: Halil BUGÖL, KubeSphere, Turkey Product Manager, halil.bugol@kubesphere.io, CNCF Slack: halil
* [x] Organizer 2: Eda KONYAR, KubeSphere, Turkey Team Lead, eda.konyar@kubesphere.io, CNCF Slack: eda
* [x] Organizer 3: Calvin YU, KubeSphere, Product Manager, calvin.yu@yunify.com, CNCF Slack: waya calvin
* [x] Organizer 4: Ray Zhou, KubeSphere, Creator of Open Source KubeSphere, ray@kubesphere.io, CNCF Slack: Ray Zhou
* [x] Organizer 5: Stephane YASAR, EquoSystem, General Manager, s.y@equosys.com, CNCF Slack Username
* [x] Organizer 7: Yavuz SARI, yavuzsari.1989@gmail.com, CNCF Slack Yavuz Sarı
* [x] Organizer 8: Rıza Can SEVİNÇ, Huawei, Solution Architecht, riza.can.sevinc@huawei.com, CNCF Slack Rıza Can Sevinç
* [x] Organizer 9: Batuhan APAYDIN, Trendyol, Container Dude, batuhan.apaydin@trendyol.com, CNCF Slack: developer-guy
* [x] Organizer 10: Emin ALEMDAR, Container Solutions, Cloud Native Engineer, [emnalmdr@gmail.com](mailto:emnalmdr@gmail.com), CNCF Slack: Emin Alemdar

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [ ] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [ ] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)

**- Co-Organizer** 50K$+
- [EquoSystem](https://www.equosys.com)
- [KubeSphere](https://kubesphere.cloud)

**- Platinium** 30K$ - 50K$
- [JibuData](https://www.jibudata.com)

**- Diamond** 20K$ - 30K$
**- Gold** 10K$ - 20K$
**- Silver** 5K$ - 10K$

* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

- * [x] [Twitter](https://twitter.com/KcdTurkey)
- * [x] [LinkedIn](https://www.linkedin.com/company/kcdturkey/)
- * [x] Website (kcd.istanbul)

* [x] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-turkey@kubernetescommunitydays.org](mailto:organizers-turkey@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated

**Comment by AudMonte01** [comment]
Excellent! Since you take part in the Istanbul Cloud Native Community Groups, I think this is a great opportunity for everyone to come together. KCDs are meant to support multiple organizations. @halil-bugol please confirm adding @developer-guy would be in the current group's interest.

**Comment by developer-guy** [comment]
Yep I got your invitation and accepted it 🫡 thx we should schedule a meeting to discuss the further details🙋🏻‍♂️

**Comment by rayzhou2017** [comment]
Excellent! Thank @halil-bugol and all organizers and sponsors.

**Comment by AudMonte01** [comment]
@halil-bugol and team - the organizers listed above are now on one alias hosted by CNCF that can be used for communications around the event: [organizers-turkey@kubernetescommunitydays.org](mailto:organizers-turkey@kubernetescommunitydays.org)

**Comment by AudMonte01** [comment]
NOTE: Postponing by 1 month due to earthquakes on the other side of Turkey.

**Comment by AudMonte01** [comment]
Hi @k8tgreenley - Emin above updated his email address to her personal address, as he is no longer with his previous company. Can you please update the organizer alias?

**Comment by k8tgreenley** [comment]
was the old email that needs to be removed: l.d@equosys.com

**Comment by AudMonte01** [comment]
> * emnalmdr@gmail.com

Hi @eminalemdar  - it looks like your container solutions email was added. I just removed it and added you as a reviewer with your personal email address. Please let me know if you still have access reviewing. NOTE: the CFP closes on April 1, so depending on how the automations are set up in the workflow, you may not be able to see those applications until after that date.

**Comment by eminalemdar** [comment]
Thanks a lot @AudMonte01! I can see the review dashboard now.

**Comment by AudMonte01** [comment]
3/28/2023 UPDATE

* Ticket sales will start from April 1 - April 7.
* They have prepared the website that we will go live in the kcd.istanbul domain the first week of April.
-- Audra expressed that this needs to be linked from a bevy page

**Comment by AudMonte01** [comment]
April 17, 2023 MEETING UPDATE

* Tickets launched last week
* Sponsors to be added today
* Speaker lineup is being reviewed by Audra ahead of publication

**Comment by AudMonte01** [comment]
NOTES FROM APRIL 27 MEETING
* 200 tickets sold so far and just over 2 weeks out from the event. Space industry and others similar to Lockheed Martin, are attending, along with students.
* Election is on May 14 (may see the digital transformation office there, but they will not make their presence political)
-- All private companies are in Istanbul
-- All use government specialized cloud (don't allow data to leave Turkey - so no Microsoft or AWS)
* Microsoft and Red Hat are now sponsors

Agenda will be sent for review on May 1
* Content focusing on the end-user
* 6 workshops
* Keynotes on both day 2 and 3
-- 3 virtual speakers are main stage speakers. One is Fatih Degirmenci

**Comment by AudMonte01** [comment]
May 2, 2023 UPDATE

Due to elections and earthquakes
* 6 sponsors cannot fully participate in the event
* Schools were taken from online to offline by the state administration today
* The venue closed 3 of the 4 halls that were planned for the event

NOTE: elections were initially going. to be in June. But early elections are being held in May. There is an election one day after the initial May event date.

For the above reasons, this event will be postponed to June. The final date is to be announced.

**Comment by aliok** [comment]
We just had this event in Istanbul this week and it went quite well!

Thanks organizers for initiating such an event!

**Comment by AudMonte01** [comment]
JUNE 27 RETROSPECTIVE MEETING

Cons
* Postponement was the hardest for some speakers and attendees who couldn't make it for the new dates
* Istanbul is chaos, so the traffic was very difficult 
* Getting non-male speakers was difficult, but they have a list of speakers they would like to ask for the 2024 event
* Video system broke on-site, so no recordings

Pros
* Foreign speakers from big companies from Sysdig, Solio, RedHat
* Attendees feedback was good (QR codes distributed on-site for survey)
* Workshops - many attendees went forward and earned certificates
* Spoke with Ayşe kaya from slim.ai, fatih degirmenci from CD Foundation, Engin Diri from pulumi
* Luckily have photos were captured, despite the video system failing

Analytics
* Total attendees = 570 (of those, 26 speakers, 50 students, 50 are sponsors)
* 26 speakers with 3 non-male speakers (11.5%) - 
* 12 sponsors - have come ahead with funds and will forward to future KCD to help with initial venue costs

Marketing
* [ ] Audra to send examples of articles written by other KCD organizers
* [ ] Organizers to send Audra about 800-words for a CNCF blog post (possibly including pictures from the event)
* [ ] Audra to send over transparency report via Canva

**Comment by AudMonte01** [comment]
Actions
* [x] Audra shared transparency report
* [x] Audra assigned Credly badges

**Comment by AudMonte01** [comment]
Actions
* [x] Audra shared transparency report
* [x] Audra assigned Credly badges
