### ISSUE TITLE
KCD Norway 2024 (January)

### ISSUE THREAD

**Issue by roberthstrand** [cncf/kubernetes-community-days#459]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [X] Event Location: Microsoft Oslo
* [X] Event Date and Time: January 24 & 25
* [x] Expected Number of Attendees : 100
* [x] Event cost per ticket: 649 NOK
* [X] Event type: In person

#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [X] Organizer 1: Roberth Strand, Amesto Fortytwo, Principal Cloud Engineer, roberth@cloudnativenorway.org, Roberth Strand
* [X] Organizer 2: Kristina Devochko, Admincontrol, Software Architect, kristina@cloudnativenorway.org, happyunicorn
* [x] Organizer 3: Roger Karlsson, Norwegian Police IT-unit, Principal Platform Engineer, roger.karlsson@politiet.no, Roger Karlsson
* [X] Organizer 4: Steffen Pøhner Henriksen, Geodata AS, Cloud Native Developer, steffen@pohnerhenriksen.com, Steffen Pøhner Henriksen
* [X] Organizer 5: Magnhild Eltoft, Independent, Student, magnhild@cloudnativenorway.org, Magnhild Synnøve Eltoft
* [X] Organizer 6: Emil Brasø, Sopra Steria, Cloud Native Engineer, emilantoni@hotmail.no, Emil Brasø
* [x] Organizer 7: Øyvind Randa, NextGentel, Software Architect, Oyvind.Randa@gmail.com, Øyvind Randa
* [x] Organizer 8: Hans Kristian Flaatten, NAV, Platform Engineer, hans@flaatten.org, Starefossen

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Microsoft - Location Sponsor
_More sponsors TBA_
* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Cloud Native Norway
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-norway@kubernetescommunitydays.org](mailto:organizers-norway@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [x] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by roberthstrand** [comment]
Just for transparency, we will be working against hosting a KCD in Oslo by late January 2024, and most of the requirements are work in progress. We are also establishing a non-profit organization to among other things help with financial tasks.

**Comment by k8tgreenley** [comment]
Hi @roberthstrand thank you for sharing your initial information. We are excited to hear that you are starting on your journey to planning KCD Oslo. Would you be willing to meet with our team to discuss your initial steps at this time?

**Comment by roberthstrand** [comment]
Absolutely, @k8tgreenley! I know I can, and I'm sure @guidemetothemoon would like that as well.

**Comment by guidemetothemoon** [comment]
Yes, I'd love that, absolutely!

**Comment by roberthstrand** [comment]
Just keeping you updated @k8tgreenley;

We're currently going through some of the prerequisites, and have a kick-off meeting with the organizers on Friday. When that is done, we can have a meeting with you about details. Should I just send a Doodle for that to kcd@cncf.io?

**Comment by k8tgreenley** [comment]
@roberthstrand my apologies for the late reply. I would be happy to have a meeting with your team on Friday, please use my [calendly](https://calendly.com/kgreenley/katie-greenley)

**Comment by roberthstrand** [comment]
@k8tgreenley, booked 30 minutes. @guidemetothemoon will be joining us, and the rest might join if they have the time.

**Comment by AudMonte01** [comment]
2/3 MEETING NOTES

To-Dos
* Audra to provide Bevy and SM Apply access as well as platform tutorials
* Organisers to reach out in (kcd-organizers)[https://cloud-native.slack.com/archives/GQ7D26NPQ] Slack channel to get feedback on attendee size and venue
* Roberth to connect with (Kasper Nissen)[https://www.linkedin.com/in/kaspernissen/] for good insight into keep overhead costs low
* Roberth to update organiser emails before Katie creates alias 

Fiscal sponsorship via their non-profit business
* Can assist other Norwegian event

Website
* Can use Bevy web page as a "Coming 2024)

Venue
* 2-4 places that are capable of having an event of 
* Rebel is a tech house that DevOps Days Oslo uses

**Comment by k8tgreenley** [comment]
Here is your organizers email alias: organizers-norway@kubernetescommunitydays.org

**Comment by AudMonte01** [comment]
3/3/2023 MEETING NOTES

* Timeline template shared
* Spoke to Kasper as a resource (CN Nordics) - Roberth is going to coordinate virtually re CN Norway
* They will also connect with CN Iceland group
* Thinking 2-day event with 1 day being a workshop day (may not be in the same venue space)
-- Roberth's company could offer space and possibly lunch (Amesto Fortytwo)
* Have venue ideas like..
-- [Rebel](https://www.rebel.no/) tech house - several floors with different venues. Could have 2 tracks as long as the rooms are isolated from one another.
-- [Sentralen](https://www.sentralen.no/en) (DevOps Days used this) - just has 1 stage
* To-Do: Logo idea - viking ship with Phippy characters, sale of the boat or shields would have the K8s wheel/helm

**Comment by AudMonte01** [comment]
MAY 2 MEETING UPDATE

Dates: January 24 and 25

Organizers
* 2 new folks are joining
* ACTION: Roberth will update issue with the 2 new organizer details

CFP
* Close the week of November 13 to allow for 1 week review and 2 weeks for speakers to confirm their acceptance

Keynotes
* Lize Rice or [Margarita](https://www.linkedin.com/in/margamanterola/)

Workshops
* K8s sustainability hackathon 

Venue
* Microsoft can give space
* Potential for large space that can be divided
* Will be vendor neutral - will just say welcome to the space
* Potential lunch sponsor

Sponsor
* Connected with Abdul from Google for potential sponsorship

Pricing
* Developer conferences need to be inexpensive 
* So no need for tiered pricing

**Comment by AudMonte01** [comment]
JULY 10 MEETING NOTES

Venue
* Microsoft location is TBD per attendee ticket payment (day 2 | main day)
-- non profit vs for profit
-- 130 max capacity
-- has food service option (includes setup and teardown)
* Workshop day (day 1) will be another location (organizer employer location)

Website
* Launch website before CFP, will use domaine name and re-direct. Done by next meeting
* Opening CFP in August

To-Do
[ ] Audra to introduce [Margarita](https://www.linkedin.com/in/margamanterola/)
[ ] Audra to touch base on Sessionize

**Comment by AudMonte01** [comment]
AUGUST 14 MEETING NOTES

Logo
* Good with standardized logo and will get creative with Phippy and friends

Workshops
* Limited seating on the day before

Action items
* [ ] Audra to put in logo request with Norwegian flag and globe showcasing Europe
* [ ] Audra to create SM apply program for organizers
* [ ] Roberth to add new organizers to Slack channel and update this GitHub issue with their details
* [ ] Audra to share Canva sponsorship template
* [ ] Team to look into ticketing platform before next meeting

**Comment by AudMonte01** [comment]
OCTOBER 23 MEETING NOTES

Content
* Might have 3 keynotes including OpenTofu
* CFP so far 28 submissions and 14 pending and CFP closes November 13
* Cannot pay for speaker travel

Sponsors
* [ ] Finalizing prospectus 
* Plenty of inquiring organizations
* Only outstanding cost is the speaker/organizer dinner the day before and might be sponsored by Amesto Fortytwo or team would take on the cost

Ticketing platform
* Ti.to
* Tito has a check-in app
* Label maker
* [ ] Audra to find out on-site app for badge scanning (sponsors)

Oslo chapter activity (over 120 days since last meetup) - 90 day activity requirement
* Meetup coming up in November
*[ ]  Entertaining doing a CFP writing, or speaker tip and tricks session ahead of November 13 and point to the CFP

**Comment by AudMonte01** [comment]
NOVEMBER 15 MEETING NOTES

Content
* 87 submissions
* [ ] Roberth to send Audra additional reviewers like Jessica and Hans

Sponsorships
* Sold out all packages
* Bronze package exceptions

Registration
* 64 so far
* Ticket Butler offers printers (KCD Denmark used). Along with Floppy disk for the badge itself
* [ ] Roberth to speak to Paula Kennedy from KCD UK team about printing QR codes from ti-to

**Comment by AudMonte01** [comment]
Total registered versus total checked in

Stats
* 150 out of 160 people registered attended (94%) including sponsors and speakers (filled to the brim). Reaching 300 will be easy due to requests coming way after selling
* Total speakers with non-male speaker percentage (4 out of 15 / 27%)
* Total sponsors were 6 (Conference, Media, 2 Gold, and 2 Silver)
* Profit that will go towards 2025 KCD

Pros
* Attendees enjoyed it, and want it again!
* Many want to contribute in upcoming years
* Even interest in another city in Norway
* Speaker dinner went well

Lessons learned + feedback
* Defining responsibilities among the organizer teams
* Needed an agenda on-site, could have utilized LED screens at Microsoft, but agendas were on QR code on the back of badge
* One sponsor they lost communication with (were also supposed to have an opening talk), which had a domino affect
* UNIX user group could have used them as a sponsor or partner

Actions
* [ ] Audra to share transparency report template from CNCF
* [ ] Credly badges to speakers to be filled out by Kristina
