### ISSUE TITLE
KCD Chennai 2023 (July 22)

### ISSUE THREAD

**Issue by senthilrch** [cncf/kubernetes-community-days#461]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Chennai, India
* [x] Event Date and Time: July 22, 2023 9:00 AM to 6:30 PM IST
* [x] Expected Number of Attendees: 300
* [x] Event cost per ticket, and if you will have early bird pricing or not

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Senthil Raja Chermapandian, Ericsson, Principal Software Engineer, [senthilrch@gmail.com](mailto:senthilrch@gmail.com), CNCF slack: senthilrch
* [x] Organizer 2: Gayathri R, gopaddle.io, UI/UX Developer & QA Lead, [gayathri.r@gopaddle.io](mailto:gayathri.r@gopaddle.io), CNCF slack: Gayathri R
* [x] Organizer 3: Kannan V, Tata Communications, Senior Technical Lead, [kannanv06@gmail.com](mailto:kannanv06@gmail.com), CNCF slack: Kannan V
* [x] Organizer 4: Manikandan Krishnamurthy, TCS, GCP Architect, [manikandank276@gmail.com](mailto:manikandank276@gmail.com), CNCF slack: Manikandan
* [x] Organizer 5: Pavithra Vasudevan, VMware, MTS-III, [pavithravasu@gmail.com](mailto:pavithravasu@gmail.com), CNCF slack: Pavithra Vasudevan
* [x] Organizer 6: Veera Ashok Cherukuri, VMware, Member of Technical Staff, [veeraashok2000@gmail.com](mailto:veeraashok2000@gmail.com), CNCF slack: Veera Ashok
* [x] Organizer 7: Mohan Muthukumar, Avalara, Lead Software Engineer, [mohan@extrasalt.org](mailto:mohan@extrasalt.org), CNCF slack: Mohan
* [x] **CFP Admin**: Senthil Raja Chermapandian, Ericsson, Principal Software Engineer, [senthilrch@gmail.com](mailto:senthilrch@gmail.com), CNCF slack: senthilrch
* [x] Fiscal Sponsor: Celexsa (Senthil Raja Chermapandian main point of contact)

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1: Tata Communications
Sponsor 2: Talentship
Sponsor 3: SnappyFlow
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments: Celexsa Technologies Private Limited.
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-chennai@kubernetescommunitydays.org](mailto:organizers-chennai@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Venue
* TBD Hotel
* Sponsors outreach once venue is secured

Ticketing
* Platform TBD
* Will do early bird pricing
-- will decide pricing after sponsorships are secured
* Celexa (web dev company) is Fiscal Sponsors

CFP
* Will close 8 weeks ahead of the event

To-Dos
* Senthil to send Audra additional 4 organizers to be added to existing email alias

**Comment by senthilrch** [comment]
@AudMonte01 

I've added couple more co-organizers to the team (updated the issue).
Please add following email Ids to the KCD Chennai email alias: organizers-chennai@kubernetescommunitydays.org
- mohan@extrasalt.org
- veeraashok2000@gmail.com
- karthick.kk@hotmail.com
- pavithravasu@gmail.com
- vadivel.g@gmail.com
- vijayabharathimail@gmail.com
- vinobalaeee@gmail.com

**CFP dates decided:**

- CFP Opens: 16th March
- CFP Closes: 15th May

**Comment by AudMonte01** [comment]
Excellent - thank you @senthilrch ! Adding @k8tgreenley who has the email alias power. :-) Katie - please see the above comment from Senthil.

**Comment by k8tgreenley** [comment]
The email alias has been updated with all of the above email addresses: organizers-chennai@kubernetescommunitydays.org

**Comment by AudMonte01** [comment]
Hello @senthilrch - I noticed [your main KCD chapter page](https://community.cncf.io/kcd-chennai/) has information for your upcoming KCD, but it looks like an event needs to be created within that chapter. I took the liberty of starting [a draft event here](https://community.cncf.io/accounts/dashboard/#/chapter-484/events-Draft/) for you. Please let me know if you would like to schedule some time to walk through this.

**Comment by AudMonte01** [comment]
MEETING NOTES FROM APRIL 4

8 weeks of CFP (currently 10 submissions)
* focused more on quality talks
* will do outreach to encourage speakers to submit
* plan to have 1 track starting at 09:00 in the morning early for India)

Sponsors
* Already reached out to 50+ sponsors (last year's sponsors, and networks sponsors)

Registration
* Not opened yet
* Using [Townscript](https://www.townscript.com/us/online) for ticketing

Engagements ahead of the event
* Online quizes
* Online blogathon contest (6 weeks)
-- will host a workshop ahead of time with best practices for blog writing

Venue
* Convention Center, Chennai Trade Centre
* Capacity 750 (event goal is 300)
* Additional lobby and reception area

Volunteers
* will have the option 2 weeks prior

To-Do
* Audra sent Senthil CKA voucher code via email
* Senthil to work on creating Bevy event and let Audra know once it's ready so she can add to drop-down

**Comment by AudMonte01** [comment]
May 2 MEETING NOTES

Ticket sales
* 137 sold so far
* Could potentially go up to 

Sponsors
* 2 confirmed (Platinum and Silver) and 2 more pending
* Audra to plug prospectus in KubeWeekly

Program
* Will not review in SMapply, but offline
* Check out the weighting in scale in SMapply

Marketing
* K8s and CN quiz with 10 questions. Quiz will start this week and run for 4-5 days
* Workshops will be held in the Chennai CNCF community chapters
* Blogathon is already happening with submissions coming in
-- consider having 1 of 3 winners go on to be published on the CNCF blog
* Pixelate (blurred picture where people have to guess the technology)

Scholarships to be rolled out in about 2 weeks
* Student Scholarships (allocating a certain amount of free tickets)
* Cloud Native Enthusiast Scholarship (criteria based on credentials, OSS contributions, or blog posts) - 20% discount

**Comment by AudMonte01** [comment]
JUNE 13 MEETING NOTES

Blogathon winners
* Just 1 winner
* [ ] Audra to review to consider to publish on CNCF blog once @senthilrch sends in a Google doc

Sponsorships
* Spf5 behind NGINX
* Talking with Google
 
Pre-event workshops roadshow
* 100% turnout (90 people registered and showed up)
* CTO of the company said they would promote KCD Chennai
* Planning to do another one on July 1 with a different company

Community Partners
* 3 different communities, and 1 is related to Azure. And others are interested
* Must support by promoting the KCD within their community, in return they will get a discount code, and logos will be added to the kcdchennai.in website

Content
* 79 submissions, sent out acceptances, today is the last day for confirming their acceptance
-- at least 1 non-male speaker in lineup, and 1 first-time speaker
-- one speaker from Sri Lanka will be checking travel
-- A lot of good representation from other cities in India
* 5-member technical panel (3 people outside organizer team)

CNCF pre-recorded video
* More in-depth for the Indian community

Attendees
* More inclined in DevOps culture

**Comment by AudMonte01** [comment]
JULY 11 MEETING NOTES

Marketing
* July 13 is when K8s version 1.0, so there will be a 24-hour sale

Sponsors
* Zoho is a new sponsor
* Almost at a breakeven point

In-Person Workshop
* This week
* 150+ registration

Venue Preparations
* 90% is done
* Have done site visits, and layout has been communicated
* Banner locations
* Still need to order food - but vendor has been decided

Content
* Emcees are lined up
* Backup speaker lined up
* Housekeeping slides are in the works

**Comment by AudMonte01** [comment]
JULY 17 MEETING NOTES

* Currently at 425 tickets might make 450
-- max capacity at 500
* Food and beverage has been ordered
* Designs for sponsor booths is done, and printing is about to occur

11 Volunteers
* Registration
* Passing mic, and checking badges to enter room
* Distributing momentos to speakers
* Checking badges against identification to enter the convention center 

Upcoming
* 1 more site visit this Thursday
* Designing standees (pop-up banners) for quizzes with QR codes
* Second and third emails to attendees to go out on Wednesday and Friday of this week
* [ ] Senthil to send Audra the latest attendee update for KCD membership

Actions
* [ ] Audra to send Senthil to a mentee testimonial video (if we have one)

**Comment by AudMonte01** [comment]
UPDATE
* Senthil curated a blog post
* Audra sent Senthil transparency report template

**Comment by AudMonte01** [comment]
RETROSPECTIVE MEETING NOTES

* Senthil shared blog post. Audra checking with Jessie to see when it will be published
* Pros, Cons and data can be found [here](https://docs.google.com/document/d/1yL24_dPniGJk3MRmzW-HwGGs4Tstw1GBd2UgrYRQ2-E/edit?usp=sharing)
* Fun fact: Attendees 80% were from Chennai, so this looks good for the local community

Action Items
* [ ] Audra to let Senthil know when blog post will be published
* [ ] Senthil to work on transparency report
* [ ] Senthil to fill out credly badge form for speakers
