### ISSUE TITLE
KCD Washington DC 2023 (September 12)

### ISSUE THREAD

**Issue by faheem556** [cncf/kubernetes-community-days#464]
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Location: 
American Red Cross DC
1730 E Street NW 20006 
Washington DC

### Event Date and Time: 
Sep 12th, 2022 - 9am to 5pm

### Event type:  
In Person

### Submission checklist for organizers:

*Please check each of these as you complete them:

* [x] No other Kubernetes Community Day event in the same region 
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] Monthly check in with KCD Core Organizer scheduled
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Reviewed the [Bevy Virtual Conference Overview](https://training.cmxhub.com/p/how-to-run-a-virtual-conference), the full course can be had for free upon request
* [x] Agree to use SM Apply for CFP
* [x] Event date and time has been chosen
* [x] Agree that there will not be an all male speaker lineup
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles

CfP open and close dates: TBD
Website launch date: TBD

### Submission checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CfP created

### Post Event checklist:
* [ ] Removed from Bevy header
* [ ] CfP deactivated
* [ ] Videos uploaded to Youtube and linked to event page

### Organizer 1:
Matthew Cascio, Executive Director, matthew.cascio@redcross.org, (slack) Matthew Cascio

### Organizer 2:
Faheem Memon, Freewheel Inc, Sr Manager SRE, fmemon@freewheel.com, (slack) Faheem Memon

### Organizer 3:
Holly Bazemore, Amazon Web Services, Senior Systems Development Manager, cloudhollyb@gmail.com, (slack) ?

### Organizer 4:
Jeff Gallimore, Excella, Chief Technology and Innovation Officer, jeff.gallimore@excella.com, (slack) ?

### Organizer 5:
TBD

### CfP Admin: 
Faheem, TBD

### Sponsor 1
TBD

### Sponsor 2
TBD

### Sponsor 3
American RedCross (HOST)

### Fiscal sponsor that will accept payments
[NaOM Lab](https://opencollective.com/naomlab)

**Comment by AudMonte01** [comment]
MEETING ON 3/3/2023

TO-DO:
* Audra to update issue with new template
* Combine chapter members from NA Washington-DC CNCG and KCD Washington-DC. Audra to look into sub group

Co-located with DevOps Days
* Will KCD speakers be able to attend for free

Early Bird is $20 and then final ticket price is $25
-- number increase in attendance is 
-- use Noamb labs for ticketing

**Comment by AudMonte01** [comment]
Hi @k8tgreenley - can you please update this alias to only have the above organizers on it? [organizers-dc@kubernetescommunitydays.org](mailto:organizers-dc@kubernetescommunitydays.org)

**Comment by sudo-bmitch** [comment]
Pinging @k8tgreenley on the email alias. I'm still getting messages even though I'm not an organizer this year.

**Comment by AudMonte01** [comment]
JULY 10 MEETING UPDATE

Goal
* 200 registrations

CFP
* Camille Clayton and Brandon need to be added to the CFP
* Has offered traveled budget to all CNCF ambassadors who they asked to speak

Marketing
* Audra plugged early-bird tickets in KubeWeekly newsletter

**Comment by AudMonte01** [comment]
AUGUST 7 MEETING

Speaker agenda
* 13 invites and awaiting 2 confirmations, so far 41% non-male speakers
* Might accept 5-minute recordings
* Schedule to be published this week
* Block of rooms for speakers at Hotel Hive

Ancillary event
* Social hour (two venues being explored and 1 is a rooftop bar looking to add covering in case it rains)

Action
* [x] Audra to send voucher codes via email

**Comment by AudMonte01** [comment]
AUGUST 29 MEETING UPDATE

Tickets
* 128 tickets and max is 160 in terms of capacity but 150 in terms of budget (TBD)

Sponsors
* room for 1 more sponsor
* 9 tiered sponsors
* 2 community sponsors
* 9 onsite

On-site tasks
* 4 volunteers
* Brendon can come help
* Matthew to be a runner
* Faheem as emcee

**Comment by AudMonte01** [comment]
SEPTEMBER 5 MEETING NOTES

Tickets
* SOLD OUT!
* Social to go out

Volunteers
* 7 on-site
* Award Credly badges

Action items
* [ ] Audra to set retrospective meeting
* [ ] Audra to send transparency report survey questions
* [ ] Matt to send Audra final attendee data for Bevy final count-down email to event

**Comment by AudMonte01** [comment]
RETROSPECTIVE MEETING NOTES

Data
* Total registered versus total checked in 174 vs 112 (64% SHOW RATE)
* Total speakers with non-male speaker percentage (8 main talks + 7 lightning talks)
-- 65 submissions (8-9 were female ambassadors that Matt had spoken to)
-- 1 bate and switch talk and 3 prerecorded lightning talks (2 were non-males)
-- 15 speakers and 6 non-male speakers (40%), and 6 CNCF Ambassadors
* Total sponsors with insight into profit or loss
-- Event cost was $22,000 total cost
-- 9 paying sponsors out of 18 total sponsors (50% partner/community sponsors)
-- Shared platinum partners
-- Profit and forward to the next KCD event and already bought speakers gifts and donated $1,000 to the Red Cross

Pros of the event
* 20 tickets came from DevOps Days days awareness
* Content, attendees, participation, happy hour and venue were all positive
* 6 people bought tickets the day of the event
* AWS talk was full of energy
* Catherine wants to help organizer next year's event
* Learned a lot from DevOps Days, and released schedule earlier
* Prospectus was attractive

Learnings for next year
* Faheem felt he could have helped more, but new job was taxing. Was helpful with managing content. Would be good to be deemed as program committee chair next year
* Could use more help on-site (had 7 volunteers)
* ATTENDEE FEEDBACK: Lightning talks could have been better, less sponsor talk during talks, lighting in session rooms was too bright to see the screen, would like a longer day
* Will consider a 2-day event next year
* 1 sustainability complaint, but the food didn't go waste. Panera brought in a lot of plastic
* House A/V system was inadequate. Wants a professional A/V company
* Try open spaces (would be good for a 2-day event), and a hand-on workshop at the same time
* Swag could have been ordered further in advance
* First session speaker had a poor delivery and received bad feedback. One speaker was pitchy. One person had a no-show speaker (also a DevOps days speaker that got confused)

Action items
* [ ] Audra to share Transparency report template with Matt
* [ ] Videos - Faheem to create playlist and share with Audra once done to create CNCF Playlist
* [ ] Matthew to write blog post once report and video playlist is ready
* [ ] Matthew to fill out form for Credly badges to be distributed to speakers 
* [ ] 10 training exam vouchers will gifted to volunteers

Keep the conversation going
* meetup has been painful with only 6-10 people showing in person
* Try a location closer to a metro station
* Change meetup name to "Cloud Native NOVA"?
* Changing KCD name and X handle to "KCD DC"
