### ISSUE TITLE
KCD Dalian 2023 (April 15)

### ISSUE THREAD

**Issue by kevin-wangzefeng** [cncf/kubernetes-community-days#465]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: **Dalian, Liaoning, China**
* [x] Event Date and Time: April 15, 2023
* [x] Expected Number of Attendees: 100
* [x] Event cost per ticket: Free
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Kevin Wang, HUAWEICLOUD, Technical Expert, Founder&Maintainer of CNCF KubeEdge, Volcano, Karmada projects, wangzefeng@huawei.com, [@kevin-wangzefeng](https://cloud-native.slack.com/archives/DLAFWKMLZ)
* [x] Organizer 2: Jinghe Ma, JiHu Gitlab, LFAPAC Open Source Evangelist, jhma@jihulab.com, [@Jinghe Ma](https://cloud-native.slack.com/archives/D04Q2RZ7VKR)
* [x] Organizer 3: Xiaohui Zhang, Flomesh, Senior Architect, Technical Evangelist, xiaohui@flomesh.io, [@Addo Zhang](https://cloud-native.slack.com/archives/D04QHCARC66)

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event (we'd prefer to use [wj.qq.com](https://wj.qq.com/) as it is popular in China)

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1: flomesh.io
Sponsor 2: jfrog
Sponsor 3: JiHu GitLab (gitlab.cn)
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments: flomesh.io
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-dalian@kubernetescommunitydays.org](mailto:organizers-dalian@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF videos to be uploaded to YouTube: https://youtube.com/playlist?list=PLj6h78yzYM2Ns1M4okNRZncFDL2y9h5up
* [x] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by majinghe** [comment]
Waiting for the KCD will be hosted in DaLian, where has several famous company, eg, IBM, accenture, SAP, Oracle and there are about 200 thousands software developer here. Looking forward the good news.

**Comment by k8tgreenley** [comment]
I am unable to added the following emails to the organizer email:
 [jhma@jihulab.com
xiaohui@flomesh.io

I have reached out to the support desk. In the meantime, the email is organizers-dalian@kubernetescommunitydays.org has been created and Kevin is currently on the email.

**Comment by addozhang** [comment]
Hi @k8tgreenley thanks. If still not ok, you can try with these two: majinghe008@gmail.com, duwasai@gmail.com. They are also owned by Jinghe Ma and me.

**Comment by caishu97** [comment]
> 3/7/2023 MEETING NOTES
> 
> Dalian (eastern seaside) - 200,000 programers. Some working in Cloud Native and Microservices
> 
> * Meetups in the area had about 100 attendees
> * COVID restrictions are over
> 
> LINEUP
> 
> * 4-8 speakers (half or whole day) depending on interest
> * Already had preparation with speakers
> * Use local CFP tencent doc
> * Will record talks and can share for CNCF cross post on YouTube
> 
> VENUE
> 
> * Free public local locations 100-200 people
> * Near to subway, park and 2 hotels (mid level pricing), and near 2 major universities, and 5 meters are companies, SAP, Oracle, and IBM
> 
> ATTENDEES
> 
> * Free event
> 
> To-Do List
> 
> * Audra to send voucher codes via email
> * @k8tgreenley - please create email alias based on above emails
> * Audra to create a Bevy chapter and email when ready

a couple of IT companies in 5 miles range, IBM、SAP、Oracle and more

**Comment by k8tgreenley** [comment]
I have been able to add the additional email addresses to the alias.

**Comment by majinghe** [comment]
KCD DaLian has already hosted successfully last day. An impressive and amazing Cloud  Native in DaLian, even in China this year. The recap will be posted later. Beautiful images from the meeting can be found in slack channel  https://cloud-native.slack.com/archives/C04SMDFKQFN/p1681659823081679.

**Comment by RainbowMango** [comment]
I've been to many KCD events and this is the most impressive! We've reached out to hundreds of developers and had a good time there!

**Comment by wey-gu** [comment]
What an amazing KCD/meetup! I was grateful to be a presenter and could feel the passion and support from the organizers, volunteers, and everyone in attendance.

I am eagerly anticipating the next Dalian-based CNCF event!

**Comment by AudMonte01** [comment]
UPDATE ON EVENT

* 2 tracks, multiple cluster management & Security
* 20 sessions/topics with 22 speakers
* over 200 people attended

Here are some pictures shared on Slack and WeChat:
![WechatIMG1089](https://user-images.githubusercontent.com/107572090/232619424-5b39932f-ea86-45ce-9f85-f88e71b83b2d.jpeg)
![WechatIMG1087](https://user-images.githubusercontent.com/107572090/232619427-8b84e918-d76a-4873-8271-12e269077da4.jpeg)
![WechatIMG1091](https://user-images.githubusercontent.com/107572090/232619430-44c3d5b1-0dea-4a80-926f-2f53f8cb277c.jpeg)
![WechatIMG1085](https://user-images.githubusercontent.com/107572090/232619443-1c0b87d3-3e8f-432a-b4bf-80a2d31aee02.jpeg)
![WechatIMG1081](https://user-images.githubusercontent.com/107572090/232619470-1fd6fb27-cfa9-42a1-aac2-e70cfc234fee.jpeg)

**Comment by AudMonte01** [comment]
MEETING NOTES

* Pros
-- no need to schedule too far in advance (2-3 months in advance)
-- Location (most people would have to drive 2-3 hours on weekend), so Dalian was much better for 100s of attendees. Also an attractive city
-- Content quality was high (good support from speakers). Topics were security and DevOps
-- Most attendees, speakers, and organizers are willing to come together for cloud native technologies

* Stats
-- Attendee rate is 50-70% (more to come)

Improvements for future KCDs
-- Location was near University and subway and seaside, but not large enough for 2 tracks. They used an air-wall to divide a room
-- Hotel nearby venue
-- Schedule at a time where there is no competition with nearby events and cause hotel rates to be higher

May want to host another KCD in the 2nd half of the year in another city

To-Do
* Co-located event information for KubeCon China @k8tgreenley

**Comment by AudMonte01** [comment]
Hi @kevin-wangzefeng - We are collecting Data on Chinese KCDs for the KubeCon China keynote. How many actual registrations did KCD Dalian have, and actual attendees?

**Comment by RainbowMango** [comment]
I guess @addozhang can help provide the info.

**Comment by addozhang** [comment]
Hi @AudMonte01 , the total registrations is 438 and actual attendees is 223.

**Comment by AudMonte01** [comment]
Thank you, @addozhang

**Comment by AudMonte01** [comment]
Thank you, @addozhang - also can you please share how many topic submissions you had for the event before choosing the final speakers?

**Comment by addozhang** [comment]
You are welcome. There were 33 submissions we received.
