### ISSUE TITLE
KCD Texas 2024 (April)

### ISSUE THREAD

**Issue by chadmcrowell** [cncf/kubernetes-community-days#466]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Austin, Texas
* [x] Event Date and Time: April 12, 2024
* [x] Expected Number of Attendees: 300
* [x] Event cost per ticket, and if you will have early bird pricing or not: $140 early / $200 after Sept 1st, 2023
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify who will be the CFP admin, as well as the financial officer and list each organizer role on the left)
* Organizer Role: Chad Crowell, Civo, Platform Engineer, chad@kubeskills.com, chad
* Organizer Role: Chris Aniszczyk, CNCF, CTO, cra@linuxfoundation.org, caniszczyk
* Organizer Role: Jim Angel, Google, Consultant, jameswangel@gmail.com, Jim Angel
* Organizer Role: Laura Santamaria, Dell, Developer Advocate, laura@nimbinatus.com, Laura Santamaria
* Organizer Role: Mars Toktonaliev, mars.toktonaliev@gmail.com, Mars Toktonaliev
* Organizer Role: Aly Ibrahim, aly.ibrahim@gmail.com, Aly Ibrahim
* Organizer Role: Cristher Castro, COO of Cuemby, cristher@cuemby.com, cristhercastro
* Organizer Role: Joaquin Rodriguez, Senior Software Engineer at Microsoft, joaquin@outlook.com, Joaquin Rodriguez
* Organizer Role: Moeez Mustafa, mr.moeezmustafa@gmail.com, Moeez KCD
* Organizer Role: Alvin Estrada, adawolfs@gmail.com, adawolfs
* Organizer Role: Rafa Brito, rafa@stormforge.io, Rafa Brito

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub forum for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender)
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use Sessionize for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Civo, Dynatrace, and IBM
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-texas@kubernetescommunitydays.org](mailto:organizers-texas@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here (https://docs.google.com/spreadsheets/d/198h8swET8Q5YOS--MZDsbRXQY2EPdC8BIMlZrQ2lFMs/edit?usp=sharing).

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTuve to event page
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
4/5/2023 MEETING NOTES

Team
* Had a lot planned for KCD Austin prior to the pandemic
* Laura and Mars are part of DevOps Days planning team
* Chris A. is local to Austin

Chad
* Instructor background
* Raft is a Silver member use a lot of graduated projects
* Now a CNCF Ambassador

To-Do
* @k8tgreenley - please create an organizer email alias with the above folks in the issue
* Audra to add all organizers to exclusive KCD Organizer

Upcoming agenda for May 3 sync
* Venue
* Finalize Date

**Comment by AudMonte01** [comment]
Thank you @k8tgreenley ! I have added this to the above issue

**Comment by k8tgreenley** [comment]
New alias: organizers-texas@kubernetescommunitydays.org

**Comment by AudMonte01** [comment]
May 3 MEETING NOTES

Fiscal Sponsorship
* Matthew Cascio to manage ticket sales. As well as sponsor payments (?)

Venue
* Capital Factory downtown is an option, but it can only hold 150 and the parking is hard
* DevOps Days is happening tomorrow, May 4 so their attendance will help them decide traction with the community (Laura can track)

**Comment by AudMonte01** [comment]
MAY 24 CHECK-IN NOTES

* Venue: Irving Convention Center 
* Event date(s) are now: October 6
* Mars formed an LLC to be the fiscal sponsor (Audra and Katie to meet with him next week)
* VMware is interested in Platinum sponsorship

Action Items:
* Audra to setup Bevy chapter
* Audra to set up SM Apply JJ and Chad (Audra to set up generic dates)

**Comment by AudMonte01** [comment]
JUNE 14 MEETING NOTES

CFP: Launched last week and closes August 30

Call for volunteers?

Tickets
* Working on adjusting early bird and regular pricing

Update on fiscal sponsorship progress
* Mars was able to make down payment today for venue
* Budget

Open Spaces / breakout rooms (BoFs) format and preparation
* Pre event survey to gauge interest
* Designate a certain amount of slots per day
* Pre populated sessions on printed paper
* Leave slots open for open times

DevOps Days Austin attendance from May 4 event (11th year)
* Hit 400 registrations and 371 inn attendance
* Intentional cap at 400 (use to be 600) but open spaces 
* Open spaces was the core

Dallas is not as central as a hub as Austin (closest to the major metropolitan areas)
* Also 1-day vs 2-days is hard to make the trek
* During the week for company to pay for attendance

Other Texas Insights
* Ticket sales are a lot lower after the pandemic
* Sponsorships are event getting hard for new DevOps days
* Driving mailing lists hard, given Twitter complications. Using LinkedIn

Action item
* Audra placed event prospectus and CFP in KubeWeekly newsletter

**Comment by AudMonte01** [comment]
MEETING NOTES JULY 13

Marketing
* Learn K8s (community sponsor)
* Civo verbally agreed to be a wi-fi sponsor
* kubefirst is a coffee sponsor
* Sara is touching base with local companies

Program Committee
* Will use organizers

Naming convention
* Leaving as state this year vs city

Community groups
* Dallas is Mars and Aly are owning that via meetup.com
* Austin - Laura wants to get the Austin K8s meetup groups together and Chad would like to contribute
-- might always be in the shadow of Cloud Austin
* Sara Davila is from the woodlands just outside of Houston (was the organizer for ArgoCD Con)

Action
* [ ] Audra to send voucher codes for stickers and training
* [ ] Audra to touch base with organizers about different community groups around Texas

**Comment by AudMonte01** [comment]
AUGUST 17 MEETING UPDATE

Content
* 1 Keynote speaker. Potentially (Marino Wijay)[https://www.linkedin.com/in/mwijay/]
* CFP submissions so far 26 in review and 9 in pending. Mostly international submissions
* Looking to double submissions in the next two weeks
* CNCF has CFP in KubeWeekly and socializing

Sponsors
* IBM is interested in sponsoring
* DELL will not sponsor
* K8s Learning will be partnering to help promote

Marketing
* [ ] Bart Farrell offered to do a promo video for the agenda with speakers (early September)
* [ ] Chad to send a blog post to get published on CNCF blog by the end this week
* [ ] Chad check to see if Google open source will be a community sponsor and help market the CFP

**Comment by AudMonte01** [comment]
SEPTEMBER 22 MEETING NOTES

Cancelation
* The team has decided to cancel this event due to low registration numbers and sponsorships.
* Cancelation fee is $9k, but the KubeFlow folks may continue to host their event in which this fee might be waived

Next Venue Space
* Co-locate KCD with a larger event
* Might re-entertain Capital Factory (will try a meetup there first). Chris A is a partner there

Sponsorships
* Civo wants them to keep their sponsorships (only 1.5% of the cost)
* Elastic wants to sponsor future events

Speakers
* Email went out and no response yet

CNCF actions
* Audra removed event from Bevy header, removed ticket button on event page, and took down blog post
* [ ] Mars to update blubr on event page

Note
* 5 folks from the team like JJ, Mars, Laura, Chad, and Jim Angel will be at KubeCon Chicago

**Comment by AudMonte01** [comment]
NOVEMBER 20 MEETING NOTES

CFP
* possible opening in November and close 1st or 2nd week of February.
* [ ] Team to let Audra know if they want to open ahead of the holidays or after

Venue
* Co-located with Linux Fest Austin (same organizers as SCALE)
** What comes with the space? F&B? A/V?
** Sponsorship collaboration?

**Comment by AudMonte01** [comment]
DECEMBER 11 MEETING NOTES

Venue
* Palmer event center, downtown Austin

What comes with the co-location of your event
* A/V support on-site but unsure about LIVE broadcast, but will record sessions
* F&B is TBD

Content
* CFP will open tomorrow
* Current logo to be removed. Team can add old logo in the meantime.

Sponsorships
* Texas Linux Fest will allow for Civo and Elastic to come in at the same level (same perks) as the previous KCD planned

**Comment by AudMonte01** [comment]
JANUARY 16 CNCF SYNC NOTES

CFP
* 14 submissions so far and CFP will close on February 9
* [ ] Chad to promote at AWS user group, and K8s Austin, Cloud Native Austin
* [ ] Audra to promote in KubeWeekly, CNCF socials, and ask Chris A. to amplify to his network.

Content
* Up to two tracks, if content allows

Sponsor Prospectus
* All sponsorships will be handled with Texas Linux Fest

**Comment by AudMonte01** [comment]
FINAL CNCF CHECK-IN AHEAD OF EVENT (APRIL 8)

Tickets
* nearly 500 for the total event with KCD on day 1
* room capacity for the second room/session room has a limit of 75
* [ ] Chad to ask team about KCD specific signups

Final on-site logistics
* On-site logistics: 5 people from organizers + 10+ volunteers from UT Austin
* Emcees: 2 folks from Austin Women in Tech
* [ ] Chad to get team to create housekeeping slides to loop ahead of the opening welcome and at breaks

Ancillary
* Local recruiting company (career corner)
* Speaker dinner ahead of event on Thursday

**Comment by AudMonte01** [comment]
APRIL 23 RETROSPECTIVE

Positives
* Great idea to combine with Texas Linux Fest
* Great to see this effort seen through after its struggles last year
* Support from the Austin community was amazing (Women in Tech, NewIron)
* Chris A. hosting speaker dinner and doing keynote as well
* Organization/smooth execution
* Location - both geo and talent strengths
* Cost was very reasonable
* Diversity of the event 

Lessons Learned
* Workload could have been better split
* Commitment from each organizer
* Timing of talks was not on-point
* The line at lune prevented folks from getting back to talks on time. Multiple food trucks as an alternative
* Wi-fi was hard in the workshop - hard wires for speakers
* Booth / Sponsor placement seemed out of site (weird placement)
* Be more inclusive to students

Analytics
* [ ] Number of registrations versus number of check-ins (Mars could get numbers from Ilon) - Audra to reach out to Ilan
* KCD-specific sponsors (Elastic, Civo, Kosmonic, NewIron)
-- RedHat had a big presence
-- Another sponsor
* Total number of speakers versus women speakers (15%)

Post-event marketing
* [ ] Credly badges will be going to speakers
* [ ] Transparency report can only be populated if TLFest folks give demographics, and access to photos
* [ ] Team to write a collaborative Blog Post on cncf.io/blog
* [ ] Video recordings were 480p (not HD), the TLfest is trying to recover some videos. Meeting this Sunday about what's salvageable

**Comment by AudMonte01** [comment]
450 registered for the Texas Linux Fest, and KCD Texas was a co-located within that event (on the same days), so we will count the registrations as half.
