### ISSUE TITLE
KCD Hangzhou 2023 (October)

### ISSUE THREAD

**Issue by gaius-qi** [cncf/kubernetes-community-days#469]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Hangzhou China
* [x] Event Date and Time: 21 October 2023
* [x] Expected Number of Attendees: 300
* [x] Event cost per ticket: Free
* [ } Venue?

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Xu Wang, Ant Group, Senior Staff Engineer, xu@hyper.sh, Xu Wang
* [x] Organizer 2: He Li, Ant Group, Technical Operations Manager, lh01055801@antgroup.com, He Li
* [x] Organizer 3: Shaoyu Huang, OpenAnolis Community, Product Designer & Maintainer  of OpenAnolis Cloud Native SIG, shaoyu.hsy@alibaba-inc.com, Shaoyu Huang
* [x] Organizer 4: Linlin Sun, OpenAnolis Community, Technical Operations Specialist  &  Operating Committee Member of OpenAnolis, jiuwen.sll@alibaba-inc.com, Linlin Sun
* [x] Organizer 5: Qiang Wang, Alibaba Cloud, Software Engineer & Maintainer  of OpenAnolis Cloud Native SIG, CharlesWang@linux.alibaba.com, Qiang Wang
* [x] Organizer 6: Chenyu Zhang(chlins), Harbor Community, Software Engineer, Maintainer of CNCF Harbor, chenyuzh@vmware.com, chlins
* [x] Organizer 7: Wenbo Qi(Gaius), Dragonfly Community, Software Engineer & Maintainer of CNCF Dragonfly, gaius.qi@gmail.com, Gaius

* [x] CFP Admin: Wenbo Qi(Gaius)

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [ ] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a WeCaht channel for your event

### Getting started checklist for CNCF:
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CNCF China team members introduced for marketing help and review of program

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by gaius-qi** [comment]
@AudMonte01 Can you help us advance this issue, thank you very much 😊

**Comment by AudMonte01** [comment]
Hello @gaius-qi - we are meeting with our APAC team next week, as we have been fortunate to have many KCDs all of the sudden coming from China. 

In the meantime, I am happy to meet with you at 8:00am your time next Tuesday, March 21 if that works for the team?

**Comment by gaius-qi** [comment]
Hey @AudMonte01 

Thank you very much for your attention. I have no problem with the meeting time and will attend on time. Can you please provide a meeting link(Zoom) and list the specific issues to be discussed in advance so that I can prepare accordingly? 

Thank you.

**Comment by AudMonte01** [comment]
MEETING NOTES

* Venue will be decided in upcoming months, but the goal is 300 attendees
* Organizers want to use own account for YouTube
* Audra created [Slack group in CNCF workspace for all organizers](https://cloud-native.slack.com/archives/C04V85C8P5F)

To-Dos
* Audra to update Bevy event and Gaius to add event details
** Organizer to create logo and share designed logo in above Slack channel
* Audra and Katie to connect with Keith Chan to help marketing on WeChat

**Comment by AudMonte01** [comment]
Hello [zhanghuidinah](https://github.com/zhanghuidinah) - please connect with these organizers, as there is already a KCD planned in Hangzhou for this year

**Comment by AudMonte01** [comment]
Hi @gaius-qi - we should schedule a meeting to check on the progress of this KCD

**Comment by gaius-qi** [comment]
@AudMonte01 I will confirm the time and reply you in time.

**Comment by gaius-qi** [comment]
@AudMonte01 We plan to hold Hangzhou KCD in October. I'll send you the schedule next week.

**Comment by gaius-qi** [comment]
@AudMonte01 

This is schedule https://www.yuque.com/g/paojiao-nb5zd/kb/ufdpbslo517xvpc5/collaborator/join?token=pokijSJ2LgiVRMyT&source=doc_collaborator#.

```text
2023.9.4 - Call for topics
2023.9.20 - Confirm topics & PPT Templates
2023.9.25 - Email Invitation to Speakers
2023.10.9 - Promotion
2023.10.21 - KCD
```
