### ISSUE TITLE
Write up process for us to accept new events

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#47]
As a sub-page off of organizing, please create the steps that @christinevblum and @iennae will do to accept a new proposal, which means merging a pull request. This will include:

1. View the proposed events site in the staging server linked from the Pull Request. Does is have sufficient information to get started, including sponsor contact info?
2. Is the PR named "New event for city x; closes #n" so that it closes the GitHub issue where the organizers came together?
3. Is all of the metadata correct?
4. Has the organizer address of the form organizers-bouvet-island-2020@kubernetescommunitydays.org been created and did they verify that it works?

**Comment by iennae** [comment]
Would recommend instead of organizers-bouvet-island-2020@kubernetescommunitydays.org  just sticking with organizers-bouvet-island@kubernetescommunitydays.org or bouvet-island@kubernetescommunitydays.org. We're migrating over to that now with devopsdays as in general it's a better experience for everyone (organizers, sponsors, and centralized coordination).

**Comment by dankohn** [comment]
organizers-bouvet-island@kubernetescommunitydays.org sounds good.

**Comment by christinevblum** [comment]
works for me. What is the process to get the emails set up? I am guessing that we need to set this up on our side?

**Comment by dankohn** [comment]
@taylorwaggoner will set up emails for now on ITX and can later show this group how to do so. Taylor, please set this up and have it go to me, you, Chris, and Jennifer.

**Comment by taylorwaggoner** [comment]
@dankohn, organizers-bouvet-island@kubernetescommunitydays.org is now set up and will forward to you, Chris, Jennifer and myself.

**Comment by christinevblum** [comment]
this is completed and approved.
