### ISSUE TITLE
KCD Taiwan 2023 (July 29-30)

### ISSUE THREAD

**Issue by yylin1** [cncf/kubernetes-community-days#470]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location:  Offline(Taiwan)
* [x] Event Date and Time: 07/29/2023 ~ 07/30/2023
* [x] Expected Number of Attendees:  150
* [x] Event cost per ticket, and if you will have early bird pricing or not: 0
#### Event type:
* [ ] Virtual
* [x] Hybrid
* [ ] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Frank Lin, Red Hat, Solution Architect, [yiylin@redhat.com](mailto:yiylin@redhat.com) , Frank Lin
* [x] Organizer 2: Phil Huang, Microsoft Azure, Senior Cloud Solution Architect, [phil.huang@microsoft.com](phil.huang@microsoft.com), Phil Huang
* [x] Organizer 3: Gene Kuo, Mirantis, Infrastructure Engineer, [ckuo@mirantis.com](mailto:ckuo@mirantis.com), Gene Kuo
* [x] Organizer 4: Rico Lin, Vexxhost, Cloud OpenStack Engineer, [ricolin@ricolky.com](mailto:ricolin@ricolky.com), Rico Lin

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel

### Getting started checklist for CNCF:
* [x] Organizer email alias: organizers@cloudnative.tw ?
* [x] Region created in Bevy
* [x] Added to Bevy header
* [ ] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF YouTube video playlist
* [x] Link videos from YouTube to event page
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [x] Create YouTube playlist on CNCF channel
* [x] Send out Credly badges to organizers

**Comment by AudMonte01** [comment]
3/13/2023 MEETING NOTES

Hybrid
* streaming team from COSCUP and post to YouTube

Organizers
* Will also have also other volunteers

* 1.5 days
* Will be a track at COSCUP this year
* Will use the same platform as COSCUP

To-Do List
* Audra to look into best way to simulcast in-person talks (COCUP is using YouTube)
* Looking introductions for Ambassadors and regional maintainers to speak

**Comment by pichuang** [comment]
Done

- Initiated a [Call for Papers](https://blog.coscup.org/2023/04/coscup-2023-coscup-2023-call-for.html) to solicit submissions, and are collaborating with COSCUP.
  - Regular CfP submission begin: April 14, 2023
  - Regular CfP submission deadline: May 22, 2023
- Opened the basic page for [KCD Taiwan](https://community.cncf.io/events/details/cncf-kcd-taiwan-presents-kubernetes-community-day-taiwan-2023/)

To Do

- Drafting Call for Papers introduction and will be publishing it on CNCF's social media platforms, such as Instragram, Facebook, Likedin and so on.

Need to help

- Placing "KCD Taiwan" within the Chapter.

**Comment by AudMonte01** [comment]
Hi @pichuang - I have added KCD Taiwan to the drop-down menu
<img width="1137" alt="Screen Shot 2023-04-17 at 3 21 49 PM" src="https://user-images.githubusercontent.com/107572090/232623362-ea7ed851-6ee4-4f7a-b16e-11bacff09815.png">

**Comment by pichuang** [comment]
20230515

Done

- The CFP announcement has been posted on CNCF's Twitter.
- Regarding the Call for Proposal, 15 speakers have currently submitted.
- Completed the separation of KCD and CNTUG chapter pages.

TODO

- After the CFP concludes on May 22nd, proceed with the review process.
- It is planned to use Bevy for internal testing.

**Comment by AudMonte01** [comment]
May 15 MEETING NOTES

Program
* CFP closes May 22 and 50 Proposals so far
* Review process will be two weeks
* Sponsorships will be handled by COSCUP
* Marketing
-- the team will write a blog post for the agenda announcement 
-- Audra to follow-up about CNCF facebook activity

**Comment by pichuang** [comment]
@AudMonte01 Apologies for any imprecision in my pronunciation; it should be the current tally of 15 proposals.

**Comment by AudMonte01** [comment]
Hi @pichuang - can you confirm this is the correct email alias to use for the KCD organizers: [organizers@cloudnative.tw](mailto:organizers@cloudnative.tw)?

**Comment by AudMonte01** [comment]
Hi @pichuang - let's schedule another check-in meeting ahead of your event on the 29th and 30th: https://calendly.com/audmonte/30min

**Comment by AudMonte01** [comment]
Hi @pichuang - let's schedule a retrospective meeting next week: https://calendly.com/audmonte/kcd-retrospective

**Comment by pichuang** [comment]
@AudMonte01 Finished booking meetings, and thanks

**Comment by pichuang** [comment]
- Total number of submissions: `30`
- Total number of submissions accepted: `16`
- Total number of CNCF/Apache/OpenInfra related projects: `14`, includes WASM / Kong / Apache APISIX / Kubernetes / kwok / m9sweeper / ArgoCD / Atmosphere / Grafana / Tekton / Longhorn / Cloud Native Glossary / kuttl / Prometheus
- Total number of nationalities: `5`, includes Belgium / South Korea / Hong Kong / Taiwan / India
- Total registered versus total checked in: `136 for total registered`, and around `107 for checked in`. The classroom can accommodate a Max. of 120 seats.
- Total speakers with non-male speaker percentage: `N/A`. We have adopted a vetting strategy that looks only at the topic and content of the speakers, with no additional scrutiny of the identity of the speakers, so there is no screening of non-male questions. However, we are prepared to increase the publicity of the call for submissions. We hope that more genders, identities and nationalities will participate.

**Comment by AudMonte01** [comment]
RETROSPECTIVE MEETING

[Pros and Cons](https://hackmd.io/5KctsjhCRmqqPhEPVgZ4RA?view)

Pros
* 6 international speakers (diversity in cultures)
* Taiwan Government came to share how they use cloud native tech
* Real-time translation with Microsoft Teams. Could even choose accent (sponsor)
* CNCF booths and games to talk about the ecosystem 

Cons
* Didn't use a reg system very well, so likely have higher attendance than calculated
* Marketing could be better
* Meet with CNCF more regularly (Slack is the best form of communication for the team)
-- this could have prevented the lack of diversity in gender in their lineup

Sponsorships
* COSCUP helped sponsors international speakers
* 1 company (New Relic) that directly wanted to sponsor KCD, and KubeEvent and KubeCareers, and Microsoft teams were community sponsors

Registration Cost
* Free event

Action items
* [ ] Audra to share transparency report template with [organizers@cloudnative.tw](mailto:organizers@cloudnative.tw)
* [ ] Credly badges for speakers?

**Comment by AudMonte01** [comment]
Hi @pichuang - I have not yet seen a request come through for credly badges. Please let me know if you wish to use this perk, or forego it? Thank you.

**Comment by pichuang** [comment]
@AudMonte01 Sorry for the late reply, I have just submitted 2 badges applications, one for speaker and the other for contributor. Please let me know if there are any questions. Thank you for your help.

**Comment by AudMonte01** [comment]
Thank you, Phil. Each KCD gets 1 additional Credly badge, in addition to
their organizers getting recognized by the Linux Foundation.

That said, would you like to move forward with "Contributor" and this can
be encompassing of both speakers and volunteers?

Audra Montenegro
CNCF Community Program Manager
About Kubernetes Community Days <https://www.cncf.io/kcds/>
Host or join a local community group <https://community.cncf.io/>
US Time zone: Pacific

**Comment by pichuang** [comment]
Hi @AudMonte01 Thank you for your reminder, I'v already re-sent my application here, only applying for `KCD Taiwan 2023 Contributor`

**Comment by AudMonte01** [comment]
Thank you, Phil - The contributor badges have now been created and distributed.

**Comment by AudMonte01** [comment]
Hi @pichuang - remind me, were the sessions recorded and the videos will be uploaded to YouTube or shared with me to do so in the CNCF YouTube channel?

**Comment by pichuang** [comment]
@AudMonte01 Yes. We already upload all recording on our own [YouTube Channel](https://youtube.com/playlist?list=PLGB9Room8gH-pxMscKIF33NHtQ6QyLIxp&si=m5O-_VH90UtFjRaK).

**Comment by AudMonte01** [comment]
Excellent - we have made a copy of the playlist so our subscribers will be notified of it, to further amplify your content: https://youtube.com/playlist?list=PLj6h78yzYM2PWoantELMGhkRBdsIgvAOh&si=XtD-iKULUlqiVHqf.

Since this is the last step for post-event marketing, I will close this issue.
