### ISSUE TITLE
KCD Dhaka  2024 (May)

### ISSUE THREAD

**Issue by mitul3737** [cncf/kubernetes-community-days#471]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Dhaka, Bangladesh at Brac Centre Inn can accommodate
* [x] Event Date and Time: May 11
* [x] Expected Number of Attendees: 200
* [ ] Event cost per ticket, and if you will have early bird pricing or not
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify who will lead each role, like the CFP admin, and financial officer for example)
* [x] Shahriyar Al Mustakim Mitul, CNCF Chattogram, Lead at CNCF Chattogram,  [shahriyarmitul3737@gmail.com](shahriyarmitul3737@gmail.com), Slack: Shahriyar Al Mustakim Mitul
* [x]  Md. Al-Amin Talukdar(Timam), Senior DevOps Engineer, [mail@timam.io](mailto:mail@timam.io),  CHEQ Lifestyle Technology, Slack: Timam
* [x] Amir Hossain, Head of DevSecOps & Cloud Engineering, [shohag_ict@live.com](shohag_ict@live.com), BJIT Limited, shohag_ict
* [x] Md Nasir Uddin,Manager, DevOps, [nasirnjs@gmail.com](nasirnjs@gmail.com), Anwar Enterprise System 
* [x] Md Farhad Hasan Khan,Senior Architect-Infrastructure, Cloud platform Management, [farhadk07@gmail.com](farhadk07@gmail.com), Grameenphone Ltd.
* [x] Reasad Amin Shamrat,Senior System Administrator, Cloud Operations,[shamrat043@gmail.com](shamrat043@gmail.com),Therap BD LTD
* [x] Abdullah Al Reza,Senior DevOps Engineer,[reza.ict@gmail.com](reza.ict@gmail.com),Nifty Coders Ltd
* [x] Mohammad Abdul Aziz,Lead DevOps Engineer,[aziz.ctg.08@gmail.com](aziz.ctg.08@gmail.com),Brainstation23 Ltd.
* [x] Md Arif Hossen,Technical Cloud Architect Consultant,[arif332@gmail.com](arif332@gmail.com), Banglalink,Arif Hossen
* [x] Jasim Alam,Senior DevOps Engineer,[jasimalam211@gmail.com](jasimalam211@gmail.com),Astha IT,Jasim Alam
* [x] Saim Safdar, Wanclouds, Developer Advocate, [saimsafder14@gmail.com](mailto:saimsafder14@gmail.com), Slack: Saim Safdar
* [x] Md. Huzzatun Ali, Co-founder & CEO, TechSpark, [huzzatunali111@gmail.com](mailto:huzzatunali111@gmail.com), Slack: Md. Huzzatun Ali

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1 : Anowar Group
Sponsor 2: Astha IT
Sponsor 3 : KloverCloud
Sponsor 4 : F5
Sponsor 5 : NHQBD
Sponsor 6 :  Appscode
Sponsor 7 : BrilliantCloud
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [x] Provided CNCF access to all event social handles: ([Twitter](https://twitter.com/kcddhaka), [LinkedIn](https://www.linkedin.com/company/kcd-dhaka/), [Facebook Page](https://www.facebook.com/kcddhaka/))

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: bangladesh-organizers@kubernetescommunitydays.org 
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in Sessionize
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Please note that [KCD Kerala](https://github.com/cncf/kubernetes-community-days/issues/455) and [KCD Gurugram](https://github.com/cncf/kubernetes-community-days/issues/472) hope to be in the second half of the year, but they have yet to secure 3 organizers. We require that every KCD that happens in India at least be 2 months a part.

**Comment by mitul3737** [comment]
> Please note that [KCD Kerala](https://github.com/cncf/kubernetes-community-days/issues/455) and [KCD Gurugram](https://github.com/cncf/kubernetes-community-days/issues/472) hope to be in the second half of the year, but they have yet to secure 3 organizers. We require that every KCD that happens in India at least be 2 months a part.

But this is KCD Bangladesh, right?

**Comment by AudMonte01** [comment]
100% yes. Please refer to [the 3rd term listed in the KCD GitHub repository](https://github.com/cncf/kubernetes-community-days/blob/main/README.md). Our goal is to avoid sponsor and speaker competition between KCDs.

Please also refer to the other Indian KCDs in the [KCD Issue repo here](https://github.com/cncf/kubernetes-community-days/issues) that already have the minimum requirement for organizers

**Comment by mitul3737** [comment]
@AudMonte01 , We hope to organize KCD Dhaka 2024 on May 11

**Comment by AudMonte01** [comment]
NOVEMBER 27 KICK-OFF CALL

Organizers
* Shahiryar: CNCF Ambassador and chapter organizers
* Al-Amin: Sr. DevOps Engineer and has been in the field for 8-9 years and 

Community in Bangladesh 
* focusing on professionals and those already focusing on cloud native
* Ecosystem: companies need DevOps Engineers or K8s certified folks
* Incorporate more students
* Community group is weekly
* Goal is to be in-person

Other goals
* May goal
* 1-day event
* Venue: University auditorium 

Action
* [ ] To share the Canva sponsorship prospectus with the team
* [ ] Audra to create Slack channel for organizers + email alias
* [ ] Team to acquire more organizers (10 is a good number to distribute responsibilities, but not required)

**Comment by AudMonte01** [comment]
JANUARY 8 MEETING NOTES

Organizers
* Saim 
* 4-5 more people are working

Venues
* Bangladesh is going through an election (finished January 7)
* Mitul has a meeting with a senior colleague tomorrow, who has experience with booking venues

Sponsorship prospectus
* Will update this week

Logo
* Audra shared raw files with the team via organizer Slack channel

Other action items
* [ ] team to create logo based on raw files
* [ ]  Audra to create an email alias for team

**Comment by AudMonte01** [comment]
May 6 CNCF Sync

Tickets are sold out!
Audra sent training voucher codes to team

**Comment by AudMonte01** [comment]
CNCF RETROSPECTIVE

Positive Feedback
* Comfortable ticket price
* The team had some good media coverage
* Had the happy problem of sponsors wanting to participate in the event after packages were sold out
* People were hyped up due to the lack of cloud native events there, and DevOps is prevalent 

Lessons Learned
* Schedule was very tight and some speakers took 45 minutes instead of 30
* Speakers did not share slides, so the team learned to be more strict with requirements or ask for more in the CFP
* Festivals surround the event delayed some activities
* One keynote speaker ended up pitching their solution
* The venue was complicated with 3 floors which made it either feel crowded or quiet depending on the session held. The goal is to have a venue that is one large level
* Volunteer management could have been better

Analytics
* Total registered was 280 versus total checked in was 275
* Total of 19 speakers 1 woman speaker (5%)
* Total 8 sponsors with $3k leftover to be invested in streaming platform and goodies for the communities and hackathon in upcoming meetups (had the happy problem of more sponsors wanting to come in)

Final marketing to prolong content
* [ ] Mitul has already created the transparency report, and will share kcd@cncf.io
* YouTube session videos have already been [published](https://www.youtube.com/playlist?list=PLHxcWNJL45BgHKueHuXTJztZUkZUXljHn)
* [ ] Team wants to do blog post. Please submit to pr@cncf.io
* [ ] Credly badges will be distributed to volunteers

**Comment by mitul3737** [comment]
@AudMonte01  I have filled out the form for volunteer badge and mailed the transparency report

Thank you

**Comment by AudMonte01** [comment]
Excellent, @mitul3737 - these will get assigned / distributed over the weekend.
