### ISSUE TITLE
KCD Delhi NCR 2025

### ISSUE THREAD

**Issue by Abhinav-26** [cncf/kubernetes-community-days#472]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [ ] Event Location: TBD
* [X] Event Date and Time: ~19th April, 2025
* [X] Expected Number of Attendees: ~450+
* [ ] Event cost per ticket, and if you will have early bird pricing or not: TBD
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [X] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [X] Organizer 1: Abhinav Dubey, Devtron Inc, DevOps Engineer, abhinav@devtron.ai, abhinavd26
* [X] Organizer 2: Ashish Kumar, CloudZenia, CTO, ashish.kumar@cloudzenia.com, ashishkumar99
* [X] Organizer 3: Barun Acharya, AccuKnox, Software Engineer, barun.acharya@accuknox.com, Barun 
* [X] Organizer 4: Satyam Soni, CloudZenia, DevOps Engineer, satyam.s@cloudzenia.com, satyampsoni
* [X] Organizer 5: Aakansha Priya, EmpathyOps, Developer Advocate, aakansha@empathyops.io, Aakansha Priya

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [X] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Please note that [KCD Kerala](https://github.com/cncf/kubernetes-community-days/issues/455) and [KCD Bengladesh](https://github.com/cncf/kubernetes-community-days/issues/471) hope to be in the second half of the year, but they have yet to secure 3 organizers. We require that every KCD that happens in India at least be 2 months a part.

**Comment by awantikan** [comment]
Hi @Abhinav-26 , I am up for collab.

**Comment by Abhinav-26** [comment]
This is great @awantikan Let's have a conversation offline. You can hit me on my Twitter handle [@abhinavd26](twitter.com/abhinavd26) or share yours.

**Comment by awantikan** [comment]
> abhinavd26

NigamAwantika. Pinged you on your twitter handle

**Comment by money8203** [comment]
Seems like there's still shortage for organizers, if so hit me up @Abhinav-26 .

**Comment by AudMonte01** [comment]
Hi @money8203 - we will have to plan this for 2024 due to KubeDay India happening in the second half of the year, which will be lead by CNCF. More to come, but you can keep your eyes out here: https://www.cncf.io/events?_sft_lf-country=in

**Comment by Abhinav-26** [comment]
Hey @AudMonte01 Thanks for the update. We'll plan KCD accordingly.

**Comment by AudMonte01** [comment]
Hi folks - it looks like there is good interest in planning a KCD in Gurugram. I do want to stress the timing of 2024 does not seem like it will work due to the first half of the year already being planned by KCDs in Kerala, Pune, and Hyderabad, and then Chennai and Bengalruru are standing in the wings (so to speak) to hear about KubeCon dates and then they will plan their events accordingly. That said, it might be best to focus on building this community through the community groups chapter and then look into a KCD in 2025. https://community.cncf.io/cloud-native-gurugram/

**Comment by satyampsoni** [comment]
cc @AudMonte01

**Comment by Abhinav-26** [comment]
Hey @AudMonte01 , have updated the organisers, can you please confirm what else details are required for getting it approved?

**Comment by AudMonte01** [comment]
Thank you, @Abhinav-26 
We will now just wait until the new 2025 process is complete before review all 2025 KCD submissions for approval.
In the meantime, please make sure each organizer has completed the Open Source Inclusive course listed above.

**Comment by Abhinav-26** [comment]
> Thank you, @Abhinav-26 We will now just wait until the new 2025 process is complete before review all 2025 KCD submissions for approval. In the meantime, please make sure each organizer has completed the Open Source Inclusive course listed above.

Sure thing. Thanks for the update.

We'll make sure all the organizers will complete the Open Source Inclusive course.

**Comment by AudMonte01** [comment]
Thank you for your submission - we are now ready to accept official applications via Survey Monkey. The deadline for submissions will be Wednesday September 11 at 11:59pm Pacific Daylight Time. More information and the application can be found via https://www.cncf.io/kcds/application/. This GitHub issue is now closed. Should your KCD be accepted into the 2025 program, a core CNCF staff member will open a new issue for program tracking and transparency.

**Comment by moinuddin14** [comment]
I see on this issue the date as 19th April but on the [cncf blog ](https://www.cncf.io/blog/2025/09/26/announcing-h1-2026-kcds/) as February 2025. Which one of these is correct?

**Comment by moinuddin14** [comment]
Thanks @satyampsoni If there's a need for additional organiser or any other way of helping the team, happy to board the train.
