### ISSUE TITLE
KCD Portugal 2024 (TBD)

### ISSUE THREAD

**Issue by nicolastakashi** [cncf/kubernetes-community-days#473]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [ ] Event Location: Porto Portugal (Looking for a place)
* [ ] Event Date and Time: TBD
* [x] Expected Number of Attendees: 350
* [ ] Event cost per ticket, and if you will have early bird pricing or not
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [X] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [X] Organizer 1: Nicolas Takashi, Coralogix, Senior Platform Engineer, nicolas.tcs@hotmail.com, Nicolas Takashi
* [X] Organizer 2: Ricardo Castro, FanDuel/Blip.pt, Principal SRE, mcc.ricardo@gmail.com, CNCF Slack mccricardo
* [X] Organizer 3: William Mendes, Feedzai, Engineer Manager, will.smendes@gmail.com, CNCF Slack William Mendes
* [X] Organizer 4: Lucas Romão, Accenture, Tech Solution Architect Manager, lucasromaomobile@gmail.com, CNCF Slack Lucas A. Romão
* [X] Organizer 5: Rogério Borges, Oracle, Principal Technical Support Engineer, brborges@gmail.com, CNCF Slack Rogerio Borges
* [X] Organizer 5: Iris Dyrmishi, FARFETCH, Platform Engineer, irisdyrmishi@gmail.com, CNCF Slack iris.dyrmishi

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [ ] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [X] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [X] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual-only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-portugal@kubernetescommunitydays.org](mailto:organizers-portugal@kubernetescommunitydays.org)
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [X] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet [here](https://docs.google.com/spreadsheets/d/1h_6vU7_SYvJqAyKaKybWYJd22MufvpEqLqWymJsREgI).
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by nicolastakashi** [comment]
Hey folks!
We aim to host a KCD event in Portugal - Porto region and we're still filling in the base information on the issue creation.
No doubt we will need some advice for sure. 😄

**Comment by nicolastakashi** [comment]
Quick update!
Next Thursday we're going to have a meeting to review the basic information and after this, we should dispatch the first email to the core organizers.

**Comment by AudMonte01** [comment]
April 26 MEETING NOTES

Next Steps
* Look for venue space
* Start with program committee
-- Think about diversity, which means gathering like-minded people to run the program. Here is a presentation we presenting in a KCD Organizer working group last August, that could benefit you: [KCDs - How to Curate a Diverse Line Up](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
-- Thinking about the program committee when creating an agenda. This is helpful to assign people different tasks to help enable speakers. Really think about including at least 1 person with a vast network, and 1 person who has speaking experience and can act as a mentor or coach. [KCDs - building your schedule and enabling speakers](https://docs.google.com/presentation/d/1AQypffHe_qa3O9u_KH3wiH6KgMS5A2Beo6bb98tJHNA/edit#slide=id.g1375398be20_1_10)

Timeline
* Whether your even is in-person, hybrid or virtual, [here is a spreadsheet](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) you can make a copy of and edit with your KCD's specifics. This is a good resource for the types of things you need to be thinking about

NOTES
* 1-day event to gauge interest in the community (400 people as a goal)
* Maybe workshops
* Context: DevOps Days Portugal will be in 2024
* Portuguese or English: defering to English is a common 

Next Steps

**Comment by AudMonte01** [comment]
MAY 24 CHECK-IN

* Timeline: February instead of March
* Exploring venues

Program
* Additional people to join committee for reviewing process, and building the schedule/lineup
* Willing to have different tracks to diversify the program
* Main stage keynote talks in the morning, break, and parallel sessions in afternoon and maybe a fun giveaway session or keynote to end the day

Actions
* Audra to create an organizer slack channel
* @k8tgreenley - would you please create an email alias with the above organizers?

**Comment by AudMonte01** [comment]
JUNE 21 MEETING NOTES 

Venue
* Will discuss with internal companies about sponsoring the space
* Looking at the following Venues
-- PREFERRED: https://www.ccalfandegaporto.com/ (most central, and negotiating parking slots)
-- https://www.editoryhotels.com/porto-palacio/reunioes-eventos/
-- https://www.meetingsinportugal.com/venues/casa-de-vilar
-- https://casadasartes.gov.pt/
* Will encourage people to use 
* The majority of the people should come from Porto, and people can cross the country by car in 4-5 hours, and from Lisbon it takes 3 hours
* Aiming for February 17

Team
* Looking to get an organizer with design background

Logo
* CNCF hopes to provide the new template by the time we meet next in one month from now

**Comment by AudMonte01** [comment]
JULY 19 MEETING NOTES

Venue decision
* https://www.ccalfandegaporto.com
* 7,000 Euros for 4 rooms for 1 day includes parking slots, includes 1 day prior for setup and breakdown the same day
* [ ] Due to have a site visit and meeting to contract

Logo
* Audra showed new template and organizers showed desired logo
* [ ] organizers to send kcd@cncf.io final logo name and chosen design from the 2 templates shared in Slack

Sponsorship prospectus
* [ ] Audra to share template with Iris and Nic

CFP
* Team to think about dates before the next CNCF check-in. Work backwards from official event date by knowing:
-- Launching agenda 6-8 weeks before the events
-- Giving speakers at least 1 week to confirm their acceptance
-- Schedule/Agenda has been determined by the program committee
-- Give at least 1 week prior for reviewing
-- Have CFP open for at least 1 month

**Comment by AudMonte01** [comment]
AUGUST 17 MEETING NOTES

Venue
* Commercial or Business registration. Might contract an event company and will let Audra know next week what they have found in their research.

Logo Decision?
* [ ] Team to get back to Audra on Monday about logo decision

**Comment by AudMonte01** [comment]
MEETING NOTES

* Venue: Non profit company (fiscal sponsor) is going through paper work with the organizers before knowing confirmation 
-- this Friday the team will meet with the fiscal sponsor and let Audra know if there is any documentation needed on the CNCF and LF side like a letter of reccomendation

Action tem
* [ ] Audra to add William to sponsorship prospectus template
* [ ]  Designer to submit to Audra the team's logo request via kcd@cncf.io

**Comment by nicolastakashi** [comment]
Hey @AudMonte01 as we discussed we're closing this issue, since the current working group will not work on the event anymore.

Thanks for all your support
