### ISSUE TITLE
KCD El Salvador 2023 (September 29-30)

### ISSUE THREAD

**Issue by josefloressv** [cncf/kubernetes-community-days#475]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Universidad de El Salvador
* [x] Event Date and Time: September 29-30, 2023
* [x] Expected Number of Attendees: 500 in-person (1000 virtual)
* [x] Event cost per ticket, and if you will have early bird pricing or not: Free
#### Event type:
* [ ] Virtual
* [x] Hybrid
* [ ] In person
#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Melvin Burgos, EDC S.A. de C.V., Software Developer, melvinburgos@gmail.com, melvin burgos
* [x] Organizer 2: Raul Flamenco, Acopula Networks, CEO, raul.flamenco@acopulanetworks.com, Raul Flamenco
* [x] Organizer 3: Jose Flores, Jobsity LLC, Site Reliability Engineer, josefloressv@gmail.com, jose flores
* [x] Organizer 4: Jasson Gomez, Universidad de El Salvador, Computer Science Student, gomezjason010@gmail.com, Jasson Armando Gómez Guevara
* [x] Organizer 5: Carlos Cordero, Universidad de El Salvador, Computer Science Student, carlencordero@gmail.com, Carlos Cordero
* [x] Organizer 6: Fatima Ayala, Universidad de El Salvador, Computer Science Student, fatimajulissa3820@gmail.com, Fatima Ayala
* [ ] Organizer 7:  Antonio Rosales, Digital Ocean, Engineering Director,a.webtone@gmail.com, arosales
* [x] Organizer 8:  Josselin Marquez, Universidad de El Salvador, Teacher,josselin.vanema@gmail.com, TBD

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
-- Carlos, Antonio, Josselin, and Aaron still need to complete
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-el-salvador@kubernetescommunitydays.org](mailto:organizers-el-salvador@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by flanets** [comment]
Hi Jose,

Can you please add Carlos Cordero, Fatima Ayala and Vanessa Marquez to the list of KCD El Salvador 2023 Co-Organizers?

Thanks!

Raul

**Comment by josefloressv** [comment]
Done!

**Comment by AudMonte01** [comment]
April 17, 2023 MEETING NOTES

Program
* 2-day event. Day 1 virtual (geared towards students)l, and Day 2 in-person
* Virtual event will be free

Questions to address in next meeting
* Will the virtual event for students mainly be in Spanish?
* How long to leave the CFP open for?
-- Potential timeline: Open the end of June or the beginning of July or for 1 month which allows to launch schedule and promote it 2 months ahead of event

To-Dos
* Organizers to figure out program committee, and fiscal sponsors (person or non-profit company to handle funds)
* Audra to share KubeCon signage templates
* @k8tgreenley, can you please create an email alias for the above organizers?

**Comment by arosales** [comment]
👋🏽  Thanks for getting this event rolling.
Could you update the PR with my CNCF slack username: `arosales` as co-organizer #7.

**Comment by AudMonte01** [comment]
May 15 MEETING NOTES

* Ticketing: Free event
* CFP: Survey what students to gather desirable topics
* Will for sure talk about different cloud platforms 
* Program Committee: sub committee from organizers
* Bevy Event Page Setup: Audra will add all organizers and create a draft event for them to edit

To-Do
* Cross check the inclusive training with this list of organizers
* Organizers to send Audra the survey questions to build in survey monkey

**Comment by AudMonte01** [comment]
As promised, here are those who have completed the Inclusive Open Source Organizer Training:
* Melvin Burgos, completed
* Raul Flamenco, completed
* Jose Flores, completed

Those who need to complete are:
* Fatima Ayala, enrolled
* Carlos Cordero
* Antonio Rosales
* Josselin Marquez
* Jasson Gomez

**Comment by josefloressv** [comment]
Jasson Gomez has completed the Inclusive Open Source Organizer Training

**Comment by AudMonte01** [comment]
JUNE 12 MEETING NOTES

Survey
* The university put a survey out to gauge interest in topics
1) GitHub Versioning
2) AI
3) Full stack development

Other interest being shown from students
* Hyper-ledger, open main frame

Action
* [ ] Audra to create the CFP in SM Apply and give Raul, Jose, Melvin admin access

Those who need to complete the organizer inclusive training?
* [ ] Fatima Ayala, enrolled
* [ ] Carlos Cordero
* [ ] Antonio Rosales
* [ ] Josselin Marquez

Scholarships for mentees
* It's easier to travel to the EU vs the US

**Comment by AudMonte01** [comment]
JULY 10 MEETING NOTES

Venue
* Satelite of El Salvador University: National Oriental University (Saturday the 30th)
-- Universidad Del Salvador

Content
* Launch CFP on July 12 and have it close by August 11 (1 month from now)
* [ ] Jose to let Audra know when both website and CFP are ready so she can launch both
* Review proposals of the weekend of the 11th,  and send acceptance the following Monday
* Plan to launch the agenda the week of August 21

Marketing CFP
* Audra to add CFP in KubeWeekly newsletter this week
* Organizers to post on social media

**Comment by AudMonte01** [comment]
AUGUST 10 MEETING NOTES

Content
* 23 submissions so far and 8 in progress (CFP closes tomorrow)
* [ ] Jose Flores to send Audra a list of the program committee to add to the reviewing phase in SM Apply
* [ ] Audra to look into CNCF representation in El Salvador

Sponsorships
* Sponsors are paying and coordinating directly with vendors
* 1 women in tech panel contribution toward coffee
* [ ] Audra to share sponsorship template

Registrations
* 73 so far

KCD Colombia help
* Helping with marketing

**Comment by AudMonte01** [comment]
AUGUST 24 MEETING NOTES

CNCF presence
* [ ] Audra to pull stats for El Salvador contributions and members (5 min preso)

Content
* Agenda: 59 presentations accepted across 2 days
* Publish the agenda this week

Actions
* [ ] 20 Volunteers - Audra to check on what kind of discounts can be get for associate level training?

**Comment by AudMonte01** [comment]
SEPTEMBER 19 CHECK-IN MEETING

General notes
* Event is 1.5 weeks away
* Emcees will be 2 people each track
* Videos will be recorded in person

Content
* 1 track is english
* 2 track in Spanish

Virtual
* Using Bevy
* Pedro Galvan may lend his subscription to streamyard

Action items
* [ ] Audra to set up a call between Nicole and Jose, Melvin, Raul, Fatima
* [ ] Audra to have video recording (commits vs contributions) by this Friday

**Comment by AudMonte01** [comment]
Hi folks - checking in to assure your transparency report is being worked on, and what timeline do you project to have it?
Cc @josefloressv

**Comment by josefloressv** [comment]
Hi Audra,
Yeah, we're working on that, we still need to gather some demographic information. We will need at least 2 weeks more. We also are uploading YouTube videos for the talks, Credly badges, and a couple of things post-event.

We will update you ASAP.

**Comment by AudMonte01** [comment]
NOTE: Credly badges were distributed to organizers and speakers last week.

**Comment by AudMonte01** [comment]
Hi @josefloressv - please send me the transparency report for this event ahead of the kick-off of the 2024 version (so in the month of April). I will close this issue in the meantime.
