### ISSUE TITLE
KCD Pune 2023

### ISSUE THREAD

**Issue by Sagar2366** [cncf/kubernetes-community-days#476]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Pune
* [ ] Event Date and Time: 13 or 28 Oct, 2023
* [x] Expected Number of Attendees: 500
* [ ] Event cost per ticket, and if you will have early bird pricing or not : TBD
* [x]  Event type: In person

#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: SAGAR UTEKAR, VMWare Software India PVT LTD, MTS3 SRE , sagarutekar2366@gmail.com, CNCF Slack Username - Sagar Utekar, CFP Admin
* [x] Organizer 2: Nidhish Malav, malavnidhish35@gmail.com, CNCF Slack Username - Nidhish Malav
* [x] Organizer 3: Samyak Jain, samyakj.tech@gmail.com, CNCF Slack Username - Samyak Jain
* [x] Organizer 4: Vipul Chaudhary, vipul.chaudhary2609@gmail.com, CNCF Slack Username - Vipul Chaudhary, Financial officer

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)
* [ ] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by Sagar2366** [comment]
CC - @k8tgreenley  @AudMonte01

**Comment by Sagar2366** [comment]
@AudMonte01 updated the organizers and general date, Let us know when can we connect.

**Comment by AudMonte01** [comment]
Thank you, @Sagar2366! Since you have been working to find organizers, [KubeDay India](https://events.linuxfoundation.org/kubeday-india/) has been scheduled for December 8. Since we require all KCDs in the same country to at least be 2 months apart from or another or another CNCF-hosted or LF-hosted event do you and the team think you can produce an event by the first week of October?

**Comment by Aakash-Punekar** [comment]
Let's connect tomorrow, I am okay anytime between 11 am to 5.30 pm anyday.

Regards
Aakash Punekar

**Comment by Sagar2366** [comment]
> Thank you, @Sagar2366! Since you have been working to find organizers, [KubeDay India](https://events.linuxfoundation.org/kubeday-india/) has been scheduled for December 8. Since we require all KCDs in the same country to at least be 2 months apart from or another or another CNCF-hosted or LF-hosted event do you and the team think you can produce an event by the first week of October?

@AudMonte01 we have got the location for Oct 28th 2023 and all arrangements are done based on that.
Next time we will make sure to keep exact two months gap between the events. Can we make exception this time ?

**Comment by AudMonte01** [comment]
You are suppose to have a kick-off meeting with CNCF ahead of any commitments. Please check availability with the venue for earlier in the month.
Cc @k8tgreenley

**Comment by AudMonte01** [comment]
MEETING 

Dates booked: October 29 and will look to move to October 20 to abide by the 2-month gap term between KCD and CNCF-hosted events.
* [ ] Action: Audra to check on timing with leadership to assure they can proceed
* NOTE: AWS Community Day is happening in the beginning October, which would compete with attendance and sponsorship

Tickets
* will be affordable to students

Volunteers
* 60-65 doing design and social media
* 100 on-site volunteers
* Hosting regular meetings

Action Item
* [ ] Audra to create organizer Slack channel
* [ ] Audra to share sponsorship prospectus template

**Comment by AudMonte01** [comment]
I am closing this issue due to this event being too close to KubeDay India, this tea, will rename their already-planned event and host their KCD in 2024.
