### ISSUE TITLE
KCD Korea 2023 (July)

### ISSUE THREAD

**Issue by jamestokko** [cncf/kubernetes-community-days#478]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: COEX in Seoul, Korea
* [x] Event Date and Time: July 3rd, 2023
* [x] Expected Number of Attendees: 1000
* [x] Event cost per ticket, and if you will have early bird pricing or not
* [x] Event type: In person

#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Seungkyu Ahn / SKTelecom / seungkyua@gmail.com / seungkyua
* [x] James Hyuk Tokko / Huraypositive / tkh@huray.net / protess
* [x]  Jaesang Lee / SK On/ hyangii@gmail.com / jaesanglee
* [x] Seokho Son / Electronics and Telecommunications Research Institute (ETRI) and CNCF Ambassador / [shsongist@gmail.com](mailto:shsongist@gmail.com) / @seokho-son 

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF witht a full list of attendees.
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [ ] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF videos to be uploaded to YouTube
* [x] Link videos from YouTube to event page
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [x] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hello @jamestokko - following up here to see if you would like to meet with me, or our Asia Pacific Team Keith Chan and Donald Liu?

**Comment by jamestokko** [comment]
@AudMonte01 Hello Audra, sorry for the late reply I was on vacation last week and forgot to follow up until now. Me and @seungkyua will be attending the meeting and I have requested a meeting thru calendy just now.

**Comment by AudMonte01** [comment]
MAY 8 MEETING NOTES

General notes
* 1-day event, in-person on July 3
* Venue is the COEX space which is a large complex
* CFP will be via Google forms. Will re-open this week and close at the end of the month
* This KCD has 8 sponsors already
* Goal is around 1,000 attendees (Cloud Native Days in 2022 has more than 1,000)

Organizers
* James has been working with K8s for 6 years
* Seungkyu has created a career group which was founded in 2016 and is now on Facebook and has more than 10,000 people
* 10+ organizers total with 1/2 of them from this career group

Students
* Are expecting college graduates and students 
* Might consider giving away 

Social media platforms used in Seoul
* Facebook
* LinkedIn
* Instagram

**Comment by AudMonte01** [comment]
Hi @jamestokko - it was a pleasure meeting you and Suengkyua today. I meant to ask who from your team of organizers is a member, Ambassador or CNCF employee?
* [Here is our member list for Seoul Korea](https://landscape.cncf.io/card-mode?category=cncf-members&headquarters=south-korea&grouping=category)
* [Here are our newest Ambassadors in South Korea](https://www.cncf.io/people/ambassadors/?_sft_lf-country=kr)

**Comment by seokho-son** [comment]
Hi @jamestokko @seungkyua @AudMonte01 
I am a CNCF Ambassador in South Korea. :)
I have already contacted @seungkyua and am willing to join KCD Korea 2023 organizing members.
Happy to follow up, assist, discuss! (I guess @seungkyua discussed my involvement with the other organizers already)

**Comment by seokho-son** [comment]
- Name: Seokho Son / Affiliation: Electronics and Telecommunications Research Institute (ETRI) / Email: shsongist@gmail.com / GitHub: @seokho-son / (CNCF Ambassador)

brief info :)

**Comment by AudMonte01** [comment]
MAY 29 CHECK-IN MEETING NOTES

Tickets
* Ticketing platform: plan9 (agency they have been using since 2021)
* GDPR regulations are not strict in Korea

Sponsorships: Co-selling with Openinfra Days

Program / Content
* CFP [Using Google Forms](https://docs.google.com/forms/d/e/1FAIpQLScsQSMLQOjB4F3BEpcwVAV4AX7wB8WMRI7hUL2zq7iyftjNSA/viewform)
* 23 submissions so far, and will close tomorrow
* Will be reviewing for 3 days
* Will hold slots for sponsors

On-site volunteers
* Agency will be hiring assistance for on-site guidance

Organizer communications
* Using Discord
* Organizers already added to KCD-organizer channel, and do not need their own CNCF Slack channel

Action Items
* Organizers to let Audra know if training voucher codes are needed for either volunteers, or as a giveaway item
NOTE: We allot 10 certification exam gifts. These are good for not only CKA and CKAD, but associate-level certifications which include SkillCreds, PCA, KCNA, and CKS.
* Seungkyu to send English prospectus to kcd@cncf.io for review

**Comment by seokho-son** [comment]
@jamestokko 
FYI: I have taken the Inclusive Open Source Community Orientation (LFC102)
https://www.credly.com/badges/4077f9b2-53cf-4457-9e03-8ed20840f0a1/public_url :)

**Comment by seokho-son** [comment]
Hi @AudMonte01 
We'd like to offer Credly badges to recognize speakers and organizers of the KCD Korea. 
I guess you can give the request form to us. 
I am sure when is the appropriate timeline to request it, but I'd like to check the form to be prepared in advance. :)

**Comment by AudMonte01** [comment]
Hi @seokho-son - we allow one request per KCD, but someone had a good idea of making a general "KCD Contribution" badge for both speakers and volunteers. Here is the form: https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform

**Comment by AudMonte01** [comment]
JUNE 12 MEETING NOTES

2022
* 1,100 registered and 1,000 attendees

Tickets for 2023
* Updated tickets to external platform
* Organizers will reach out to 15 people who pre-registered 

Marketing 
* [ ] Audra to add registration to KubeWeekly newsletter

**Comment by seokho-son** [comment]
> Hi @seokho-son - we allow one request per KCD, but someone had a good idea of making a general "KCD Contribution" badge for both speakers and volunteers. Here is the form: https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform

Thanks @AudMonte01 :)
I found an existing badge called `Program Committee Member: Kubernetes Community Days 2023`. (here: https://www.credly.com/org/the-linux-foundation/badge/program-committee-member-kubernetes-community-days-)
It appears that this badge can be used universally for all KCD events in 2023. Is my understanding correct?

In that case, would it be possible to use both badges:
 1. the existing badge: `Program Committee Member: Kubernetes Community Days 2023`.
 2. a new badge specific to KCD Korea 2023 such as Speaker(or Contributor): Kubernetes Community Days Korea 2023.

**Comment by AudMonte01** [comment]
RETROSPECTIVE MEETING

* Total registered versus 1,090 versus total checked 940
-- no other cloud native event in their region
-- thinking of reducing the event size in 2024
-- Audra mentioned KubeDay potential and Seungkyu 
* Total speakers were 28 with non-male speaker 3 (11%)
* Total sponsors with insight into profit or loss (breakeven)
-- 10% of cost went to event planning agency
-- 4 sponsors canceled due to not having their name in the title
* KCD Seoul is the only tech hub, and a small country, so naming by city is not as welcoming and 

Action items
* [ ] Seungkyu will send Audra Kubernetes Korea YouTube channel
* [ ] Seungkyu might send blog post in Google doc to publish on CNCF.io
* [ ] Audra waiting on Credly badge form to be filled out by James
* [ ] Audra to send transparency report via Canva

**Comment by seokho-son** [comment]
Hi @AudMonte01 
I've submitted the KCD Credly Badge Request for KCD Korea 2023 ! :)

**Comment by AudMonte01** [comment]
Thank you @seokho-son - I am working on these today and will let you know if I have any questions. Otherwise, they should be assigned to the designate people by your morning tomorrow.

**Comment by AudMonte01** [comment]
Hi @seokho-son - do you have insight into the YouTube playlist and blog post?

**Comment by seokho-son** [comment]
> Hi @seokho-son - do you have insight into the YouTube playlist and blog post?

Hi @AudMonte01 :)
Are you referring to the progress or status of the action items discussed in the retrospective meeting?
(I don't have the context since I wasn't in that RETROSPECTIVE MEETING. By the way, thank you for sharing the meeting outcomes :) )"

> Action items
> 
>  Seungkyu will send Audra Kubernetes Korea YouTube channel
>  Seungkyu might send blog post in Google doc to publish on CNCF.io

**Comment by seungkyua** [comment]
@AudMonte01  - Sorry for the late response. 

Kubernetes Korea Group Channel
- https://www.youtube.com/@kuberneteskoreagroup4284
We're working on a video for this year's KCD Korea event.

and I'll send blog post soon.

**Comment by AudMonte01** [comment]
Hello @seungkyua - will there be a KCD Korea 2023 specific playlist on your YouTube channel?

Noting here that the blog post was sent and posted last week on CNCF.io here: https://www.cncf.io/blog/2023/08/17/a-story-of-growing-a-kubernetes-community-in-south-korea-korean-language-blog/

**Comment by seungkyua** [comment]
Hi @AudMonte01 

There is no specific playlist yet. but I'm going to make one when I upload the video.
Thanks for helping with the blog post. 👍

**Comment by AudMonte01** [comment]
Thank you, @seungkyua - checking in to see if you will soon have a chance to upload the videos to YouTube?

**Comment by AudMonte01** [comment]
Excellent - I have created a copy of the playlist on the CNCF YouTube account so our subscribers will get notified.
https://youtube.com/playlist?list=PLj6h78yzYM2O0HzPtuR-KJa-8tAy5Rnjt&si=GWbrsmxyiInHj_62
