### ISSUE TITLE
KCD ShangHai 2023

### ISSUE THREAD

**Issue by zhanghuidinah** [cncf/kubernetes-community-days#479]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: ShangHai, China
* [x] Event Date and Time: 2023
* [x] Expected Number of Attendees: 150
* [x] Event cost per ticket, and if you will have early bird pricing or not: Free

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)
* [x] Organizer 1: Hui Zhang, NetEase OSPO, CNCF Ambassador, Curve Maintainer, Chaos Mesh Ambassador, @dinahzhang0420@gmail.com, Hui Zhang(Dinah)
* [x] Organizer 2: Fog Dong, Alibaba Cloud, Senior Engineer in Alibaba Cloud and the maintainer of KubeVela, wuwuglu19@gmail.com, Fog Dong
* [x] Organizer 3: Xiaoyu Zhang, Tencent Cloud, Leader of Private Cloud’s Application and System Stability, K8s community member, zxysjtu@gmail.com
* [x] Organizer 4: Keao Yang, PingCAP, R&D, Maintainer of CNCF Chaos Mesh project, yangkeao@pingcap.com
* [x] Organizer 5: Pengcheng Tang, Volcano Engine, Senior Software Architect of Volcano Engine Cloud Native Team and KubeWharf, tangpengcheng.tangpc@bytedance.com 
* [x] Organizer 6: Xudong Guo, JiHu GitLab, LFAPAC Open Source Evangelist, CNCF Shanghai Community Organizer, Maintainer of CNCF ChaosBlade project, Approvers of KubeVela, guoxudong.dev@gmail.com @sunny0826 guoxudong

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event(we'd prefer to use [wj.qq.com](https://wj.qq.com/) as it is popular in China)

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a social media (WeChat) handle specific to your KCD event

### Getting started checklist for CNCF:
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CNCF China team introduced for marketing amplification, program review and guidance

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by zhanghuidinah** [comment]
Hi @AudMonte01 

 Can we change the location to Shanghai cause many of our organizers are based there?

**Comment by AudMonte01** [comment]
Hello @zhanghuidinah - yes, you may change the location to Shanghai, but please also change the date because KCD Beijing will be on June 3, and we do not want to form competition in nearby regions.

**Comment by zhanghuidinah** [comment]
> Hello @zhanghuidinah - yes, you may change the location to Shanghai, but please also change the date because KCD Beijing will be on June 3, and we do not want to form competition in nearby regions.

Okay, the expected time frame is from the end of June to early August, and the timing is negotiable.

**Comment by AudMonte01** [comment]
Excellent! Please keep July in mind because [KCD Hangzhou](https://github.com/cncf/kubernetes-community-days/issues/469) will be held in mid August.

**Comment by sunny0826** [comment]
KCD Shanghai will be held in July, and we will confirm the exact date as soon as possible.

**Comment by AudMonte01** [comment]
Hi @sunny0826 - with July around the corner, I fear it might be too late to plan this unless 1-month's time is enough preparation for a call for speakers, review of the schedule, and release with enough time to promote?

**Comment by zhanghuidinah** [comment]
Hi @AudMonte01  - Our venue and some of the lecturers have been confirmed, the date is set for July 29th. And 
we will conduct activity promotion and recruitment in several communities in the near future.

**Comment by AudMonte01** [comment]
Hello @zhanghuidinah - kindly schedule some time to meet with me, otherwise, we will need to assure that no KCD or CNCF branding is used on your event. Thank you

**Comment by zhanghuidinah** [comment]
> Hello @zhanghuidinah - kindly schedule some time to meet with me, otherwise, we will need to assure that no KCD or CNCF branding is used on your event. Thank you

Sorry, due to early maternity leave, I have to postpone the KCD ShangHai 2023.

**Comment by AudMonte01** [comment]
Thank you for the update @zhanghuidinah, and congratulations on the newest member of your family. <3

I will close this GitHub issue for now, and we can reopen it when you and the team are ready to meet to plan for the event.
