### ISSUE TITLE
KCD New York 2024 (May)

### ISSUE THREAD

**Issue by abebars** [cncf/kubernetes-community-days#480]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [X] Event Location: [NYC Life Sciences Lab Space | Cure.](https://cure.345pas.com/events/)
* [x] Event Date and Time: May 22
* [x] Expected Number of Attendees: 250
* [x] Event cost per ticket, and if you will have early bird pricing or not: 120 Regular and $100 Early Bird
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [X] In person
#### Organizers Details (identify who will be the CFP admin, as well as the financial officer)
* [X] Organizer 1: Ahmed Bebars, The New York Times, Staff Software Engineer, ahmed.bebars@cloudnativecommunity.io, abebars
* [ ] Organizer 2: Andres Vega, Messier 42 (M42), K8s Project Maintainer, av@monkey.org, aV
* [ ] Organizer 3: Lesley Cordero, The New York Times, Staff Software Engineer, me@clesleycode.com, Lesley Cordero 
* [X] Organizer 4:  Valentina Rodriguez Sosa, Red Hat, Principal Technical Marketing Manager, varodrig@redhat.com, Valentina Rodriguez Sosa
* [X] Organizer 5:  Hemanth Malla, Datadog, Senior Software Engineer, hemanth.malla@datadoghq.com, Hemanth Malla
* [X] Organizer 6:  Cedric Clyburn, Red Hat, Developer Advocate, cclyburn@redhat.com, Cedric Clyburn
* [X] Organizer 7: Kelly Revenaugh, Kubeshop, Developer Relations Lead, kelly@kubeshop.io, Kelly Revenaugh
* [ ] Organizer 8: Scott Rigby, Developer Advocate, Freelance, scott@r6by.com, Scott Rigby
* [X] Organizer 9: Julia Furst Morgado, Global Technologist, Veeam, juliafmorgado@gmail.com, Julia Furst Morgado
* [X] Organizer 10: Karen Chu, Head of Community, Fermyon Technologies, chu.karen.h@gmail.com, Karen Chu

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [X] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [X] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF witht a full list of attendees.
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual-only events)
Loft Labs
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments. Cloud Native Community, Inc
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created (kcd-newyork@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF videos to be uploaded to YouTube
* [x] Link videos from YouTube to event page
* [x] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [x] CFP deactivated
* [x] Upload videos to YouTube

**Comment by anvega** [comment]
I'd love to step in and make KCD NYC happen in whichever way I can. Perhaps we can even look at making it happen in the second in the Fall or Winter this year?

**Comment by abebars** [comment]
> I'd love to step in and make KCD NYC happen in whichever way I can. Perhaps we can even look at making it happen in the second in the Fall or Winter this year?

Thanks, Andres, I thought about it earlier for this year, but we may need more time to arrange the event. Early Next year would be a better choice.

**Comment by AdminTurnedDevOps** [comment]
I'd love to help run this or be an organizer as I'm right outside of NY.

**Comment by AudMonte01** [comment]
Hi @abebars - what about adding Michael here? Then you will have met having the 3 organizer minimum and we can schedule a kick-off call!

**Comment by AdminTurnedDevOps** [comment]
@abebars @AudMonte01 I'm available for this :)

**Comment by abebars** [comment]
@AdminTurnedDevOps I just added you as the Thrid Organizer 🎉 . @AudMonte01, I think we are ready fo the kick-off!!

**Comment by AdminTurnedDevOps** [comment]
@abebars awesome! Thanks. What are the next steps?

**Comment by AudMonte01** [comment]
Let's have the kick-off meeting! Can you @abebars find some time that works for you and the others, on my calendar?
https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by abebars** [comment]
> Let's have the kick-off meeting! Can you @abebars find some time that works for you and the others, on my calendar?
> 
> https://calendly.com/audmonte/kcd-onboarding-kickoff-call

@AudMonte01 Awesome, I will try to setup something next week.

**Comment by AdminTurnedDevOps** [comment]
I'll be on vacation until Wednesday of next week, but I'm good to meet Wednesday, Thursday, or Friday.

**Comment by AudMonte01** [comment]
KICK-OFF MEETING

Ahmed platform engineer for the NY Times
* Been in AWS community for a while
* Push for more OS projects and leverage the community
* Bring people along the cloud native journey

Michael self employed (K8s and platform engineering space)
* Prior was lead and principal engineer
* Currently consults (build out K8s enrollments)
* Does live training with O'Reilly
* Also creates content for clients
* Was on the K8s version 1.21 release

Venue Options
* NY Times center or NYU
* AWS could possibly sponsor a loft

Actions
* [ ] Audra to set up Slack channel and add organizers to exclusive KCD organizer channel

**Comment by JustinCappos** [comment]
Context from the NYU side:  I can check about getting a place at NYU.  The auditorium I know we may be able to book has around 200 seats.  There is some mandatory cleaning fee and we would also have some fee for signage, etc.  I don't think any of this is substantial, but does need to come from somewhere.  

Would a weekend event be possible?  Classes are starting in a few weeks and the weekday evening schedule is booked as far as I know.

**Comment by AudMonte01** [comment]
Thanks for this update @JustinCappos - 200 capacity sounds great for a first-time KCD, and you're right, signage and cleaning has to be outsources anyway, so might as well keep it all with the venue as well as it's a nominal fee.

You know the community best, but since it's in North America, I would assume a Friday or Friday/Saturday series would work best. O'Reilly Media always held their in-person events on the weekdays, but that was a different time when companies budgets were more abundant to send employees to these things.

**Comment by AudMonte01** [comment]
SEPTEMBER 8 MEETING NOTES

Organizers
* Lesley Cordero has joined!
* A call for organizers went out on LinkedIn
* [ ] Ahmed to put a request for amplification on the CNCF Slack workspace channel (#socialmedia)[https://cloud-native.slack.com/archives/C12MRQ97A] and tag Katie Meinders

Venue
* NYU is the goal, but it's only available on the weekends
* Boat for an evening reception

Actions
* [ ] Audra to give Ahmed and Lesley to the sponsor prospectus
* [ ] Audra to create an email alias for the team

**Comment by varodrig** [comment]
I'd love to collaborate. I'm very passionate about Kubernetes and this is a great opportunity to give back to the community. I'm in NYC.

**Comment by AudMonte01** [comment]
DECEMBER 15 MEETING NOTES

Venue
* Created an RFP in Cvent to do the search
* Found 3 venues to choose from that have all inclusive packages
* Looking into May dates to avoid competition with OSS and KCD Texas

Questions
* Streaming platform from CNCF?
* [ ] Action: Audra to look into Bevy capabilities with an A/V crew

**Comment by AudMonte01** [comment]
Organizer email address updated with above organizers.

**Comment by AudMonte01** [comment]
JANAURAY 19 CNCF SYNC

Marketing
* Social for meet the organizers video will go out 
* Ticket strategy (early bird, etc): Standard price $140 (early bird if $120), and partners bringing in tickets get a 10% discount
* Julia and Kelly are owning the social

Content
* 18 submissions so far
* 30-minute sessions each for sponsors (7 sessions)
* Streaming platform for in-person content: Cedric is leading these efforts
* Team to host office ours on writing a proposal and tips and tricks for speaking

Sponsorships
* Platinum: Loft signed!
* Gold: DataDog and Isovalent are in talks
* Bronze: Solo is coming but hasn't signed yet
* Organizers is inquiring out to their companies
* NY Times is sponsoring with the gift of time from employees (perhaps make a "Community Sponsor"

**Comment by AudMonte01** [comment]
FEBRUARY 20 CNCF SYNC 

Content
* Office hours for proposal writing and speaking
* Hosted two weeks ago by Julia and Scott and 3 people came through
* 1 keynote locked in and 2 in the works

The numbers so far:
* CFP 114 submissions and 89 good quality sessions
* Hoping to announce schedule on March 21
* 20 tickets so far

Sponsorships acquired
* Signed 3 sponsors
* 10 in progress with a signing deadline on March 1
* Colleen Coll (previously The New Stack) is helping with sponsorships

Marketing efforts
* [ ] Audra to point to tickets in KubeWeekly newsletter
* [ ] 5 of the team will be in Paris to promote at the Kiosk
* [ ] Audra to set up sync in Paris with the team

**Comment by AudMonte01** [comment]
APRIL 26 SYNC

Volunteers
* Recognition with Credly badges (along with speakers "Hero" or "Contributor") or training vouchers?
* [ ] Audra to send training vouchers and instructions via email

Streaming
* [ ] Audra to get YouTube streaming key and waiting room setup

**Comment by AudMonte01** [comment]
Audra met with Daniel from ProPresenter and set up the YouTube LIVEstream: https://youtube.com/live/pMCj6nkqmZQ
Does the team want to keep this unlisted or have it public? Cc @abebars

**Comment by abebars** [comment]
> Audra met with Daniel from ProPresenter and set up the YouTube LIVEstream: https://youtube.com/live/pMCj6nkqmZQ
> 
> Does the team want to keep this unlisted or have it public? Cc @abebars 

@AudMonte01 I would love to make it public so we can socialize it late this week.

**Comment by AudMonte01** [comment]
Keeping this open until we have our retrospective meeting and post-event tasks are complete.

**Comment by AudMonte01** [comment]
JUNE 7 RETROSPECTIVE

Positive Feedback
* Attendee feedback was very positive, some said "best KCD they have been to"
* Sponsor feedback liked that the event was not too big, and intimate
* People flew in from India and South America just for the event
* Content: International, diverse, and knowledgeable speakers
* Had lunch & happy hour in sponsor pavilion to drive engagement
* Break time was perfect including the space

Lessons Learned
* Better balancing of organizing team
* Venue format was hard with the sponsor level, as attendees take the elevator (thankfully no one complained and the venue staff was helpful)
* Sponsor setup was difficult for the A/V team, and the logistics of coordinating with the venue
* Better A/V coordination ahead of time, show flow meeting and USB drives with presentations (sneaker-net)
* Doing a solo event without being co-located. A lot of work but fulfilling
* Confidence monitors were not always working

Analytics
* Number of registrations 264 versus 189 check-ins (76%)
* 15 paid sponsors and 6 partner and broke even with the event cost over $150k. Tickets were not a key player ($120 standard price)
* 32 speakers versus women speakers (30% non-male speakers)
* Starting from scratch was hard when sponsorships came late in the game (many came after KubeCon Paris)
* Be careful with how many sponsored talks we have (felt vendor-heavy) out of 21 sessions (7 were sponsored, and 3 were community)

Post-event marketing
* Credly badges have already been distributed to "champions" (speakers & volunteers)
* [ ] Transparency report is in the works. Ahmed to send to Audra to publishing on cncf.io/reports and cncf.io/kcds
* [ ] Team to write a blog Post on cncf.io and send to pr@cncf.io and cc Audra for review and publishing
* [ ] YouTube video recordings will be uploaded soon. Cedric to let Audra know once the playlist is ready
* Post-event email going out next week with survey reminder and event app contacts up and ready

**Comment by AudMonte01** [comment]
[YouTube playlist is ready](https://youtube.com/playlist?list=PLAKeCOriSUu6Zw-C5e0m_qsKcPksiYKh0&si=kULLvvAKc6yaw3kl)
