### ISSUE TITLE
KCD Sri Lanka 2023 (September 9)

### ISSUE THREAD

**Issue by chamodshehanka** [cncf/kubernetes-community-days#482]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: [Trace Expert City, Colombo, Sri Lanka](https://trace.lk/trace-expert-city/)
* [x] Event Date and Time: 9th of September, 9:30 AM (IST)
* [x] Expected Number of Attendees: 300+
* [ ] Event cost per ticket, and if you will have early bird pricing or not: TBD
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Kanchana Wickramasinghe, WSO2, VP & GM, kanchanaw@senathltd.com, kanchanawickramasinghe (CPF Admin)
* [x] Organizer 2: Chamod Perera, ISG, Software Engineer, hcsperera@gmail.com, chamodshehanka (CPF Admin)
* [x] Organizer 3: Kemila De Silva, Aeturnum Inc, DevOps Engineer, kemila.d@aeturnum.com, kemila.d (CPF Admin)
* [x] Organizer 4: Kushantha Charuka, Beta Launch, UI/UX Designer, kushi.charuka@gmail.com, kushantha
* [x] Organizer 5: Bawantha Rathanayake, Orel IT, Software Engineer, bawantharathnayake@gmail.com, bawantha
* [x] Organizer 6: Kaveesha Gimhana, CareHires, Software Engineer, uakaveeshagimhana@gmail.com (financial officer)
* [x] Organizer 7: Chirath Bandara, chirathb14@gmail.com
* [x] Organizer 8: Pathum Rajapakshe - Finance Lead (pathumr@senathltd.com)
* [x] Organizer 9: Suresh Peiris - Production Manager (tsmpmail@gmail.com)
* [x] Organizer 10: Chirath Bandara - Community Admin Lead (chirathb14@gmail.com)
* [x] Organizer 11: Miyuru Gunarathna - Design Lead (miyurupriyawadan@gmail.com)
* [x] Organizer 12: Bawantha Rathnayaka - Design Lead (bawantharathnayaka@gmail.com)
* [x] Organizer 13: Akalanka Perera - Dev Lead (akalankaperera128@gmail.com)
* [x] Organizer 14: Samudra Weerasinghe - Marketing Lead (samudra@wso2.com)
* [x] Organizer 15: Kavishka Fernando - Marketing Lead (kavishka@wso2.com)
* [x] Organizer 16: Nisal Renuja - Social Media Manager (nrenuja@gmail.com)

#### Volunteers
Avin Indrasoma - Volunteer (avinindrasoma@gmail.com)
Sahas Renuja - Volunteer (sahasrenuja@gmail.com)
Sithum Bopitiya - Volunteer (sithumsandeepap@gmail.com)
Ahamed Safnaj - Volunteer (safnaj99@gmail.com)
Raju Nirupan - Volunteer (raju.n@aeturnum.com)
Shaan Jathurshanm - Volunteer (jathurshanm3@gmail.com)
Chanuka Praveen - Volunteer (chanuka.p@aeturnum.com)
Suvin Nimnaka - Volunteer (suvinkodituwakku@gmail.com)

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
WSO2

Sponsor 2
Aeturnum Inc

Sponsor 3
Wiley

* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Scheduled kick-off meeting for May 9

**Comment by AudMonte01** [comment]
JULY 3 CHECK-IN MEETING NOTES

Sponsorships
* Prospectus live and added to repository (Audra to link in Kubeweekly newsletter). No newsletter this week, but we will have one going out on July 14
* Microsoft is pending and RedHat did not say no, but likely doesn't have the budget

Speaker Intros
* Employers sponsoring travel 

Live website (Bevy page)
* Will go live with the website to promote prospectus and CFP this week

Diverse speakers / CFP
* Goal is 50/50

**Comment by AudMonte01** [comment]
JULY 25 MEETING NOTES

Venue
* Changed and affected Max capacity 300

Ticketing
* Event cost per ticket: Early bird ticket price 1500 - 2000 Sri Lankan rupees
* Ticketing platform: integration to website and will let Audra know this week

Content
* CFP closes August 28?
* 12 applications so far
* No responses 
* [ ] Audra to do a 5-minute recorded session for opening (voice over with graphics)

**Comment by AudMonte01** [comment]
AUGUST 8 MEETING NOTES

Sponsorships so far
* 2 Gold sponsor
* 1 Silver

Action items
* [ ] Audra to send voucher codes
-- List shipped items as gifts for customs

Content
* Goal is to have 16-18 speakers
* Website to launch once half the speakers are confirmed

**Comment by AudMonte01** [comment]
AUGUST  MEETING NOTES

Content
* Will aim to announce speaker by the end of this week for 2 weeks promotion time of the agenda
* If someone cannot speak, they will speak at the monthly meetups

Sponsorships
* 3 Gold and 1 Silver
* and 1 additional verbal confirmation
* Partnered with GitHub and GoLang communities in Sri Lanka

Training vouchers
* Both as a gift to volunteers

Action
* [ ] Audra to share session description

**Comment by AudMonte01** [comment]
MEETING UPDATE

Tickets
* Sold out tickets with more than 330

Sponsor update
* Advania signed on

Agenda
* Has been posted
* Will have a break during the giveaways
* Will add a job board

Action item
* [ ] Audra to schedule retrospective meeting with the team

**Comment by AudMonte01** [comment]
Final Steps
* Transparency report has been created shared with CNCF, and is being added to cncf.io/kcds via cncf.io/reports.
* YouTube playlist has been created by team, and copied over to CNCF YouTube channel: https://www.youtube.com/playlist?list=PL7hn1g7tv7EmNtI3qvK8PeYr1FARKoJSb
