### ISSUE TITLE
KCD Lahore 2023 (October)

### ISSUE THREAD

**Issue by farhanashrafdev** [cncf/kubernetes-community-days#484]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Lahore, Pakistan
* [x] Event Date and Time: October 4, 2023
* [x] Expected Number of Attendees 300+
* [x] Event cost per ticket, and if you will have early bird pricing or not: Not paid
#### Event type:
* [ ] Virtual
* [x] Hybrid
* [ ] In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:

* [x] Organizer 1: Farhan, mriceflame@protonmail.com, Organizer and CFP Admin
* [x] Organizer 2: Adil, adilshehzaddev@gmail.com, Organizer
* [x] Organizer 3: Asad, syedasadrazadevops@gmail.com, Organizer
* [x] Organizer 4: Muhammad Manan, muhammadmanan7175@gmail.com,  Co Organizer
* [x] Organizer 5: Zain Naqvi, syedalizain03@gmail.com, Co Organizer
* [x] Organizer 6: Abdul Rauf, abdulraufmujahid@gmail.com, Co Organizer
* [x] Organizer 7: Aftab Ahmed, aftabfremont@gmail.com, Co Organizer
* [x] Organizer 8: Moeez, moeez.exe@outlook.com, Graphics Lead
* [x] Organizer 9: Hasnaat, hasnaatfreelancing@gmail.com,  Development Lead
* [x] Organizer 10: Rashid, rashidwassaan@gmail.com, Public Relations and Marketing
* [x] Organizer 11: Sharjeel, sharjeel924@gmail.com, Social Media Manager
* [x] Organizer 12: Arslan Zaffar, arsalanbinzaffar@gmail.com, Logitics Lead
* [x] Organizer 13: Abdul Raheem, arfarooqix@gmail.com, Co Organizer
* [x] Organizer 14: Arslan Khalid, arslankhalid5798@gmail.com, Graphics Lead
* [x] Organizer 15: Muhammad Talha, talha0750@gmail.com Graphics Team/Social Media Manager
* [x] Organizer 16: Fatima Riaz, riaz.fatima448@gmail.com, Graphics Team
* [x] Organizer 17: Faeez Ahmad, faeez2669@gmail.com, Graphics Team
* [x] Organizer 18: Ibad Elahi, Graphics Team
* [x] Organizer 19: Ali Zain, syedalizain03@gmail.com, PR and Marketing
* [x] Organizer 20: Armaghan bin Zahid, armaghanbinzahid@gmail.com,  PR/Marketing
* [x] Organizer 21: Taskeen Fatima, taskeenfatima2207@gmail.com, Speaker Management
* [x] Organizer 22: Amna Hafeez, amnahafeezkrow@gmail.com, Marketing
* [x] Organizer 23: Usman Hamid, usmanhamid4work@gmail.com,  Marketing
* [x] Organizer 23: Rehan Ahmad, Rehanahmadzafar03@gmail.com,  Marketing
* [x] Organizer 23: Hafiz Hammad , ha8768757@gmail.com,  Marketing

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [organizers-lahore@kubernetescommunitydays.org](mailto:organizers-lahore@kubernetescommunitydays.org)
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
MEETING NOTES

Structure
* 1 week ahead of the event is virtual (2-3 workshops and talks)
* Sept 16 is in-person

Organizers
* Abdul has been part of CNCF a few years ago and has organizer small events since then. Has a CKAD certification
* Farhan - DevSecOps engineer. Have been part of the community for 5 years and has organized a Hackathon, as well as an AWS community day. Working with KubeVilla (Sandbox project?)
* Adil - DevOps Engineer. Helping students get started with programing
* Hasnaat - FullStack developer and graduate student. Teaching front-end development
* Huawei organizer
* Volunteers and students

Venue
* Governments ie providing a National convention center that is free for 1 day
* Or a University of Lahore
* Other co-working spaces that night be available
* Hub of the cloud native community (1.6 million in the city)
* Focus on quality over quantiy

Logo 
* To-Do: Audra to create Slack workspace private channel
* Submission of logo is 1st line item

To-Dos
* Customs issue over $60 USD worth. Might not be able to use CNCF store voucher. @k8tgreenley - can you introduce Farhan to our vendor too assure there won't be any issues. If there are, then they might source a local vendor instead.
* Audra to introduce Jeefy Sicca on the project side and Katie Greenley for community side to Farhan
* Audra to create a private channel in Slack

**Comment by AudMonte01** [comment]
JUNE 8 MEETING NOTES

Team
* Lead organizers
* Design
* Marketing and PR

Venue
* SSI is desired and NIC (software houses) and UET (university) are backup venues
* 

Program
* Jefferey Sica responded about a keynote
* [ ] ACTION: Audra to create CFP in SM Apply in mid July

Swag
* Did Katie introduce you to our swag vendor?

* [ ] ACTION: Audra to reach out Moeez to schedule a 1:1 for the Bevy platform enablement session

**Comment by AudMonte01** [comment]
MEETING NOTES

Virtual event will be held one week before
* Streamyard to broadcast into Bevy

Venue secured
* Official signing is end of July (can accommodate 250-300)
* University of Lahore
* Want to gauge interest from the community during two events this month

Sponsors
* Google, GitHub, are in
* Google will share sponsorship prospectus with partners, as well as Kahoot platform for engagement
* Meeting with Huawei Director of Growth Marketing
* Approaching with RedHat and Cisco this month
* Will talk with startups 
* AWS can sponsor from a community partner perspective (credits and swag)

CFP launching 
* [ ] Audra to create a draft in SM Apply 
* Already have a few people committed for in-person
* AWS workshop
* Google & Microsoft speakers committed

Marketing efforts
* Call for collaboration
* Gathering many community groups to plug the event at their meeting
* Engaging universities
* Audra shared logos and other branding
* Audra sent training voucher codes

**Comment by AudMonte01** [comment]
AUGUST 7 MEETING NOTES

Venue options
* have partnered with [TechHub](https://techub.com.pk/) who can get a venue with a max capacity of 700
* [Jeeny](https://jeeny.me/en/) is a top-tier sponsor is wanting them to host in a hotel that they use for their corporate events

Sponsor
* [ ] Farhan to send Audra sponsor brochure to add to KCD repository

CFP
* [ ] Audra to give Farhan, Abdul Syed access to the CFP in SMApply
* Will shortlist people who are applying for online event as the CFP is open
* Online session 30 minutes with 10 minutes additional Q&A
* [ ] Farhan to send program committee names and email addresses to Audra to add

Tickets
* Tiered pricing
* Platform is a startup app that is synced with [JazzCash](https://www.jazzcash.com.pk/)
* Will shortlist people for free tickets (form submission required)
-- for people who cannot afford a ticket coming from remote areas of Pakistan

Other Actions
* [ ] Audra to connect Moez with projects team to get a sandbox project going

**Comment by AudMonte01** [comment]
@k8tgreenley - can you please create the organizer email alias so I can add it to their CFP ASAP? Thanks in advance.

**Comment by k8tgreenley** [comment]
organizers-lahore@kubernetescommunitydays.org

**Comment by ghamy016** [comment]
Is it still happening?

**Comment by AudMonte01** [comment]
SEPTEMBER 13 MEETING NOTES

In-person event update
* University venue change due to larger audience than expected
* Due to this, the event needs to move to the 30th

Tickets for in-person events
* 700 registered via Google forms (80% professionals and 30% females)
* Returned paid tickets for the original date of September 16
* Virtual event on the 9th had 411 unique visits and 50 people in 1 session at a time 

Sponsors
* Sponsorships are going well - AWS and Grafana
* At a breakeven point 

Content
* 3 Microsoft, 1 grafana labs, 1 aws, 1 aws official lab on venue. 1 qwiwlabs official google
* 5 topics. 2 workshops
* One more virtual session happening on the 16th to keep the hype

Actions
* Audra added  sponsor prospectus to GitHub repo

**Comment by AudMonte01** [comment]
Even postponed due to Conjunctivitis outbreak and universities closing their doors for one week.

**Comment by AudMonte01** [comment]
OCTOBER 11 RETROSPECTIVE MEETING NOTES

Total registered versus total checked in
* 460 people registered and about 300+ (65% turnout rate)
-- mostly professionals, and 10% students

Total speakers with non-male speaker percentage
* 2 women speakers out of 11 and only 1 showed up so an in-person rate of 9%

Total sponsors with insight into profit or loss
* 3 total sponsors including Google and GitHub
* No profit, but a loss of 5-10k PKR ($17 - $36 USD)

Pros and Cons of the event
* 20 volunteers on-site
* Collaborated with Chamod from Sri Lanka
* Party with pizza at a restaurant with CEOs of different startups
* Cloud engineers were new to CNCF and cloud native awareness. This could have helped with local sponsors
* Startups that were government-related who were interested
* Will plan for recording in-person sessions

Post event MARKETING
* Professional photos will be ready this week. No video recording of in-person sessions
* Will have an Instagram reel to promote post-event
* Created labs and challenges to give away the other half of the training vouchers for marketing of next year's event

Action items
* [ ] Audra to share CNCF Transparency report template with Farhan and Adil
* [ ] Team to write a blog post and share with Audra via Google doc for publishing on CNCF.io
* [ ] Credly badges for "Hero", and Farhan to let Audra know when organizers are updated for PC badge

**Comment by ghamy016** [comment]
Very good stats for a wonderful cncf event organized at Lahore. Kudos to all organizers and participants!
