### ISSUE TITLE
KCD Angola 2024 (April)

### ISSUE THREAD

**Issue by antonio-pedro99** [cncf/kubernetes-community-days#486]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [ ] Event Location: ISPTEC
* [x] Event Date and Time: April 5 & 6
* [x] Expected Number of Attendees: 250-500
* [ ] Event cost per ticket, and if you will have early bird pricing or not
#### Event type:
* [ ] Virtual
* [x] Hybrid (livestream to YouTube)
* [x]  In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
* [x] Organizer 1: Antonio Pedro, IIIT-D, CSE Student, antonio20028@iiitd.ac.in, CNCF Slack: @antonio20028
* [x] Organizer 2: Paulo Estêvão, K2 Partnering Solutions, Software Engineer, pl1745240@gmail.com, Slack: @Paulo Lopes Estevão
* [x] Organizer 3: Mário Domingos, Institute of Administrative Modernization, DevOps Engineer, Email: kennymario.k@gmail.com, CNCF Slack: @Kenny Mario
* [x] Organizer 4: Amim Knabben, VMware, CNCF Ambassador (GitHub: @knabben), amim.knabben@gmail.com
* [x] Organizer 5: Daniel Batubenga, Sidea Tecnologia, DevOps Engineer, Email:
daniel.batubenga@gmail.com, Slack: @Daniel Batubenga

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [ ] Agree to use SM to Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: angola-africa@kubernetescommunitydays.org 
* [x] Region created in Bevy
* [] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Schedule post mortem meeting

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by knabben** [comment]
Happy to help in the event organization!

/assign

**Comment by AudMonte01** [comment]
JULY 14 KICK-OFF MEETING NOTES

The Team
* Antonio (LFX mentee)
-- Computer science and engineering student
-- Mobile developer, contributing to OSS since 2021, 2022 best international contributor at a hackathon
* Paolo 
* Daniel
* Mario (Tech Enthusiast)
-- DevOps professional at the Institute of Administrative Modernization
-- Independent 

Learn about Luanda the city
* 7 hours ahead of Pacific Time
* Southern Africa
* High population, good food, and good whether
* Younger generation due to 50+ universities (more private)
-- IT (30%), law, medicine
-- https://www.isptec.co.ao is one of the largest and most prestigious
* Most professionals are closed source (not many contributors) 

Content
* Plan to run a one-month mentorship program
* Introduction to open source and cloud native
* Hybrid: Livestreaming in-person sessions. Goal to broadcast the efforts and impact.
* Prominent language in Angola is Portuguese
* Possible speakers from Brazil

Action Items
* [ ] Organizers to explore venues like Universities 
* [ ] Organizers to do research on CNCF and LF and external, regional events to not conflict with them

**Comment by antonio-pedro99** [comment]
Hi @AudMonte01, the one-month mentorship program is actually out of the scope for the KCD. This is another social project I am working with other peers. This project is called **Angola Open-source Community**, and we plan to run mentorships and workshops to introduce open-source and cloud native technologies in our community.

**Comment by AudMonte01** [comment]
MEETING NOTES

Date in March or April
* Tentative April 13 or 20

Potential venues
* Taking some time to explore further

CNCF Benefits
* Platform
* Training vouchers & CNCF store voucher
* Templates like logos

Action
* [ ] Audra to create CNCF Slack channel for organizers
* [ ] Audra to create email alias

**Comment by AudMonte01** [comment]
MEETING UPDATES

Venue
* [ ] Team to let Audra know official dates to give letter of recommendation, with projected 6 months in advance of April 13 or 20, and send to Mario (Kenny)
--- [Instituto Superior Politécnico de Tecnologias e Ciências ISPTEC](https://www.isptec.co.ao)
* [ ] Audra to give team Bevy access with chapter

Sponsorships
* Team will search Open Collective for a fiscal sponsorship

**Comment by antonio-pedro99** [comment]
The KCD Angola will be happening in 2025. Will closed this issue and reopen it after a while.
