### ISSUE TITLE
KCD Lahore - 2023 (September 2nd)

### ISSUE THREAD

**Issue by SyedAsadRazaDevops** [cncf/kubernetes-community-days#491]
### Submission checklist:

**Event Location:**
Kickstart Gulberg III, Lahore

**Event Date and Time:**
September 2nd, 2023
Time: TBD

**Event type:**

- [x] in-person event

**Terms:**

- [x] No other Kubernetes Community Day event in same major city (check with past organizers)
- [x] Minimum of 3 organizers from 3 different organizations
- [x] Each organizer lives in or just outside of the KCD location
- [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
- [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
- [x] All inquiries/communication to come via the GitHub forum for easy tracking
- [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
- [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
- [ ] Agree to share the sponsor prospectus with CNCF by linking it to your GitHub issue and your website.
- [x] Agree to submit your final lineup to [kcd@cncf.io](mailto:kcd@cncf.io) for review, prior to publishing it
- [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

**Organizers Details (identify who will be the CFP admin, as well as the financial officer)**
- [x] Organizer 1: Syed Asad Raza, Devops Engineer Ascend Solution, CNCF-Ambassador, syedasadrazadevops@gmail.com, CNCF Slack Username - syedasadrazadevops
- [x] Organizer 2: Abdul Rauf, Swyft Logistics, Engineering Lead, abdulraufmujahid@gmail.com, armujahid
- [x] Organizer 3: Adil Shehzad, Strategic Systems International, Devops Engineer, adil.shehzad4146@gmail.com , adilshehzad786

**Getting started checklist for organizers:**
- [ ] Schedule monthly check-ins with KCD Core Organizer(s) ([kcd@cncf.io](mailto:kcd@cncf.io))
- [ ] Minimum of 3 sponsors committed.
     - Github
     - Sponsor 2
     - Sponsor 3

**Getting started checklist for CNCF:**
- [ ] Organizer email alias has been created: organizers@kubernetescommunitydays.org
- [ ] Added to Bevy platform
- [ ] CFP created in SMapply
- [ ] Marketing Plan shared

**Post-event checklist for Organizer:**
- [ ] Send CNCF event analytics
- [ ] Send CNCF videos to be uploaded to YouTube
- [ ] Link videos from YouTuve to the event page
- [ ] Post-event survey sent out

**Comment by AudMonte01** [comment]
Hello @SyedAsadRazaDevops - please note, there is already a KCD Lahore in the works: https://github.com/cncf/kubernetes-community-days/issues/484

If you wish, you can reach out to the organizers to see how you 3 can contribute to that event. With that, I will close this Issue.

**Comment by AudMonte01** [comment]
Hello @SyedAsadRazaDevops - please note, there is already a KCD Lahore in the works: https://github.com/cncf/kubernetes-community-days/issues/484

If you wish, you can reach out to the organizers to see how you 3 can contribute to that event. With that, I will close this Issue.
