### ISSUE TITLE
KCD Tel Aviv 2024 (TBD)

### ISSUE THREAD

**Issue by shimont** [cncf/kubernetes-community-days#495]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [X] Event Location: Tel Aviv
* [X] Event Date and Time: 11/4/2024
* [X] Expected Number of Attendees: 600
* [ ] Event cost per ticket, and if you will have early bird pricing or not
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [X] In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [X] Organizer 1: Shimon Tolts, CNCF Ambassador, Shimon Tolts
* [X] Organizer 2: Itay Shakury, Aqua Security, Open Source Engineer, [itay@itaysk.com](mailto:itay@itaysk.com), itaysk
* [X] Organizer 3: Dana Fine, Datree, Community Manager, [dana@datree.io](mailto:dana@datree.io), Dana Fine
* [X] Organizer 4: Arthur Berezin, JovianX, CEO & Co-Founder, [arthur@jovianx.com](mailto:arthur@jovianx.com), Arthur Berezin
* [X] Organizer 5: Ronen Levinson, Snyk, Senior Software Engineer, [ronenrl21@gmail.com](mailto:ronenrl21@gmail.com), Ronen Levinson

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [X] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [X] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [ ] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [X] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
TBD
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hey @shimont - let's have a kick-off call for this 2024 edition!
https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by shimont** [comment]
We were able to secure a location! at the Tel Aviv Cinematheque. The event will take place on 11/4/2024

**Comment by AudMonte01** [comment]
Hi @shimont - let's have a kick-off call so we can talk about dates and if they are conflicting with any other planned KCD or CNCF-hosted event. https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by shimont** [comment]
Hey! Ive scheduled a call. We signed the contract for KCD 2024 for 11.4

**Comment by AudMonte01** [comment]
KICK-OFF CALL MEETING NOTES

Venue
* Cinema
* Larger venue

Content
* Arthur will be the program chair for content
* Two tracks, fairly technical
* Open tickets to soldiers to expand on age diversity (3 years of soldier work is required right after school)
* October is when Sessionize may be available via CNCF, and CFP is due to open in mid November

Action items
* [ ] Audra to share sponsor prospectus template
* [ ] Audra to submit ticket with LF Creative
* [ ] Audra to inquire with Bevy CSM about chapter organizers and access page builder

**Comment by AudMonte01** [comment]
Hi folks - I want to follow up regarding the Bevy page builder feature. We are looking into creating a custom role that allows organizers to do this. I will let you know once this is enabled, and it should be just a matter of updating the check boxes when you click on the edit pencil for yourself under the "Team" tab in the chapter settings.

**Comment by AudMonte01** [comment]
Postponed until 2025. Please re-open this issue when the time comes
