### ISSUE TITLE
KCD Utrecht 2023 (December)

### ISSUE THREAD

**Issue by ams0** [cncf/kubernetes-community-days#496]
### Event Details
* [X] Event Location: Utrecht
* [X] Event Date and Time: 1st December 2023
* [X] Expected Number of Attendees: 250
* [X] Event cost per ticket, and if you will have early bird pricing or not: possibly free, otherwise around 45€
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [X] In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [X] Organizer 1: Alessandro Vozza, Solo.io, CNCF Ambassador, alessandro (GitHub: @ams0 )
* [X] Organizer 2: William Rizzo, SUSE, Architect, William Rizzo (GitHub: @wrkode )
* [x] Organizer 3:  Pablo Musa, Sysdig, Developer Advocate, Pablo Musa (GitHub: @pmusa)
* [x] Organizer 4: Luca Camphuisen, Java Developer/Owner of Logic Shift

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [ ] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives in or just outside of the KCD location
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [X] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [X] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [X] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [ ] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [X] Agree to use Sessionize for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [X] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [X] Minimum of 3 sponsors committed (not required for virtual only events)

Lovelace Engineering B.V.
Stackstate
EDB

* [X] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Lovelace Engineering B.V.
* [X] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [X] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: utrecht-organizers@kubernetescommunitydays.org 
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [x] Send CNCF videos to be uploaded to YouTube
* [x] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [x] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hi @ams0 - unfortunately each city can only have one KCD per year. I see that you have an issue open for 2024! Let's schedule a kick-off call once you get your 3rd organizer.

**Comment by ams0** [comment]
@AudMonte01 we found a venue, we're in the process of signing, event will be in Utrecht. Should we get an alias like organizers-utrecht@kubernetescommunitydays.org? I can provide a list of names/emails. Can you please re-open it? We can of course meet beforehand too, please ping me/william/pablo on slack! thanks a lot, onward and forward!

**Comment by AudMonte01** [comment]
SEPTEMBER 25 MEETING NOTES

New Organizers
* Luca - first KCD, and has attended many meetups. Role: website actions.
* Karla (new organizer) (her/she)
* Serkan (new organizer) (he/him)
* Carlos  (new organizer) (he/him)
* Ronald  (new organizer) (he/him)
* Saif  (new organizer) (he/him)

Content
* 1 day, 1 track on a Friday
* 15-20 speakers
* Will add end users

Venue
* Near a train station in the city center

Audience
* 250 attendees
* Meetups every month and surveyed the community which folks voted for Utrecht (authentic to Dutch culture and business side)

Sponsorships
* 8 sponsors (2 have already committed) 

Other details
* Taking part of the sustainability week and will announce there
* Free food and party
* Tickets will be low (under 50 Euros)

Action items
* [ ] @ams0 to add these organizer details with job titles and companies, in main issue above
* [ ] Team to send Audra cityscape for logo request
* [ ] Audra to submit logo request to LF Creative

**Comment by ams0** [comment]
Thanks for spotting it, fixed!

**Comment by AudMonte01** [comment]
NOVEMBER 20 MEETING NOTES

Tickets
* Nearly 200 tickets
* Will likely sell out
* Catering wants to know this week the projection

Sponsorships
* Have all the sponsorships (breakeven), but will welcome to more (2-3)
* Profit will go to 2024 event

Other notes
* 3-5 on-site volunteers
* Recording both tracks this time

To-Dos
* [ ] Audra to send voucher codes for training + stickers

**Comment by mbianchidev** [comment]
Hey @AudMonte01 

This is the complete list of organizers for KDC Utrecht 2023, I ran it with @ams0 and everyone should be in with their mail + GH handle

Name | Email | Githiub handle
-- | -- | --
Alessandro Vozza | alessandro@stackmasters.com | @ams0
Carlos Mestre del Pino | carlosmestredp@gmail.com | @mestredelpino
Catalin Jora | catalin.jora@fika.works | @jocatalin
Fahd Ekadioin | fahd@ekadioin.nl |  @fahd-e
Jos van Schouten | jos.vanschouten@gmail.com | @josvanschouten
Karla Valeria Feijoo | karvalfeijoo@gmail.com | @karla-feijoo
Luca Camphuisen | lucamasira@gmail.com | @Camphul
Marcel Kerker | marcel.kerker@hcs-company.com | @mkerker
Matteo Bianchi | matteo@mb-consulting.dev | @mbianchidev
Meg Stefouli | meglicious@gmail.com | @Meglicious
Pablo Musa | pablitomusa@gmail.com | @pmusa
Pavel Chunyayev | pavel.chunyayev@mambu.com | @maple03
Rajesh Gunasekaran | grajesh.ec@gmail.com | @rgunaseknokia
Saifeddine Rajhi | rajhiseif@gmail.com | @seifrajhi
Serkan Capkan | serkan.capkan@gmail.com | @srknc
Sevi Karakulak | sevikarakulak@gmail.com | @sevikarakose
William Rizzo | william.rizzo@gmail.com | @wrkode

We will work with William to figure out badges for speakers too, we'll keep you posted!
Of course we will also upload the recs on youtube and send the survey. Post-mortem meeting is already scheduled :)

**Comment by AudMonte01** [comment]
Excellent - thank you, @mbianchidev !
Let's schedule a retrospective meeting ahead of the holidays: https://calendly.com/audmonte/kcd-retrospective

**Comment by mbianchidev** [comment]
We will try to find a time when at least 3-5 organizers are there, we'll keep you posted!

In the meantime, we also gathered the speakers in a table:

Name | Email 
-- | --
Sarah Gruneisen | sarah@avagasso.com
Louëlla Creemers | mail@louella.dev
Stefan van Gastel | Stefanvangastel@gmail.com
John Stroosnijder |
John Keates | john@keates.nl
Andrea Soldino | andrea.soldino@gmail.com
Shweta Vohra | shweta.vohra@gmail.com
Marco Verleun | marco@verleun.org
Jan Willem Van Hermon | jwp.van.hermon@belastingdienst.nl
Sebastiaan Mannem | sa.mannem@belastingdienst.nl
Rajalakshmi Rajamuthu | raji.rajamuthu@nl.abnamro.com
Remy Simons | rsimons@ilionx.com
Peter van Eijk | p@d1g.nl
Bart van der Berk | bart.berk@outlook.com
Serdar Kalaycı | serdarkalayci@gmail.com
Kasra Amirsarvari | kasra.amirsarvari@hcs-company.com
Sohan Maheshwar | sohan.maheshwar@fermyon.com
Maxim Burgerhout | maxim@wzzrd.com
Nico Krijnen | nkrijnen@gmail.com
Jan Karremans | jan.karremans@spinerdata.com
Sevi Karakulak | sevikarakulak@gmail.com
Erwin de Keijzer | erwin@gnur.nl

We are only missing a single email of a co-speaker, trying to retrieve that!

Can you advise about the best way to craft badges for speakers? As far as I understood we need to send a request to [this Google Form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform).

After having drawn the logo of badge.
Is that correct? am I missing something? Thanks a lot!

**Comment by AudMonte01** [comment]
Thank you @mbianchidev. If you want to spare sharing the speaker emails publicly, you can follow guidelines [in the last bullet point here](https://github.com/cncf/kubernetes-community-days/blob/main/README.md#cncf-support), for the badges.

**Comment by JanKarremans666** [comment]
Is there a date for when the recordings from the sessions might be available?

**Comment by mbianchidev** [comment]
> Is there a date for when the recordings from the sessions might be available?

@JanKarremans666 we don't have a defined date yet, but we are in touch with our video maker and looking forward to it. 
We will send a notice and of course publish on our KCD Netherlands social media as well!

**Comment by AudMonte01** [comment]
RETROSPECTIVE MEETING NOTES

Large Team (lean and efficient)
* Graphic designer, Web team, emcee's like Marcel, Andrew, and William

Analytics
* Total registered versus total checked in (390 people on-site out of 450 registered). 87% turnout rate
-- last 2 weeks they had 50% of registration come through (surge during agenda announcement)
-- Friday seemed to be a good day
* Total speakers with non-male speaker percentage 
* Total sponsors with insight into profit or loss (19%)
-- priority was end-users
-- more diversity in cultural backgrounds and age and experience (had 1 student, and 1 fresh out of college)

If profit, where will remaining funds go?
* [ ] team to answer this questions

Positives and Learnings
* Attendee experience was smooth and did not notice workings on the backend
* Sponsors 
* Pro: The Content was well received
* Minor issue: Agenda on the website could have been more abundant and clear
* Minor Problem: Could have used more food because the majority of the tickets came in the last week. Learn to roughly plan for 450-500 people
* Learning: Have a speaker lounge
* Learning: Have more specific assignments versus one person doing a little bit of everything 

Action Items
* [ ] Team to upload the videos within the coming weeks. Please send YouTube playlist to Audra
* [ ] Team to collaborate in a blog post
* [ ] Team has transparency report template from CNCF, and is working on it
* [ ] Audra to execute Credly badges request submitted by Matteo
* Any social posts can be submitted https://cloud-native.slack.com/archives/C12MRQ97A
* [ ] Tag Jessie Adams-Shore in [#socialmedia Slack channel](https://cloud-native.slack.com/archives/C12MRQ97A), and she can amplify from the main CNCF account

**Comment by mbianchidev** [comment]
Blog post draft has been created and shared, roughly 50-60% is already written as I took my pre-written blog from Medium and edited to fit a more general vibe and less focused on my own experience.

Transparency report will be finalized, hopefully this week, we are at roughly 80% completion.

**Comment by AudMonte01** [comment]
YouTube playlist has been created and copied over to [CNCF YouTube channel here](https://youtube.com/playlist?list=PLj6h78yzYM2P-O-2wgyppNAbNMNSpwQrm&si=FBNqdKINNg8YLABE).

**Comment by AudMonte01** [comment]
Blog post was published last week: https://www.cncf.io/blog/2024/02/01/from-attendees-to-organizers-a-community-story/
