### ISSUE TITLE
KCD São Paulo Brazil 2024 (February)

### ISSUE THREAD

**Issue by krol3** [cncf/kubernetes-community-days#498]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
- [x]  Event Location: São Paulo
- [x]  Event Date and Time: February 23 virtual and Saturday 24 in-person
2024 
- [x]  Expected Number of Attendees: 300 
- [ ]  Event cost per ticket, and if you will have early bird pricing or not

#### Event type:
* [ ] Virtual
* [x] Hybrid: Day 1 in-person and Day 2 virtual
* [ ] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
- [x]  Organizer 1: Amim Knabben, VMware, CNCF Ambassador (GitHub: @knabben), amim.knabben@gmail.com
- [x]  Organizer 2: Carol Valencia, Krol Cloud, CNCF Ambassador (GitHub: @krol3), [valencia0.carol@gmail.com](mailto:valencia0.carol@gmail.com)
- [x]  Organizer 3: Joao Brito, GetUp, CTO (GitHub: @juniorjbn), juniorjbn@gmail.com
- [x]  Organizer 4: Jade Lassery, Datadog, (GitHub: @jlassery), jadellassery@gmail.com
- [x]  Organizer 5: Douglas Luna, Dasa, (GitHub: @douglasluna), sec.douglasluna@gmail.com
- [x]  Organizer 6: Diego Rocha, Aws, (GitHub: @dmroch4), diego.roch4@gmail.com
- [x]  Organizer 7: Tiago Reichert, Aws, (GitHub: @tiagoReichert), tiago@reichert.eti.br
- [x]  Organizer 8: Luiz Bernardo, Redhat, (GitHub: @levenhagen), levenhal@gmail.com
- [ ]  Organizer 9: Igor Eulalio, Sysdig (GitHub: @IgorEulalio), igoreulalio.ie@gmail.com
- [ ] Organizer 10: Fabio Oliveira, Dasa, (GitHub: ), f.rodriguesoliveira10@gmail.com

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: sao-paulo-br@kubernetescommunitydays.org
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in SMapply
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet [here](https://docs.google.com/spreadsheets/d/1GPO--3IH5RTob-bzAHDZ8RPBuNeomQz6TQr4CcFpFww/edit?usp=sharing).
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
JUNE 21 MEETING NOTES

Updated GitHub issue accordingly 

CNCF Actions
* [ ] Audra to create a dedicated KCD Brazil organizer channel
* [ ] @k8tgreenley - please create an email alias for the three organizers here

Organizers
* [ ] Recruitment in discussed areas of organization

**Comment by k8tgreenley** [comment]
Email alias: organizers-brazil@kubernetescommunitydays.org

**Comment by AudMonte01** [comment]
JULY 19 MEETING

Name of the event
* Feedback on KCD global organizer channel
* Leadership to discuss the term and exceptions to be made 

Venue research 
* B-3 central venue for free
* [ ] Audra to get recommendation letter from The Linux Foundation
* [ ] Organizers to find out what is included in the venue and add to budget once contract is signed (person or company)

Organizers
* [ ] Carol to send Audra to send names and email addresses of other committed organizers

**Comment by AudMonte01** [comment]
I have updated the email address in this GitHub issue, as well as the new email alias for the team is now in the above issue as well. Please use that in the sponsor prospectus. Whom should I share that template with via the Canva platform?

**Comment by kcloudn** [comment]
> I have updated the email address in this GitHub issue, as well as the new email alias for the team is now in the above issue as well. Please use that in the sponsor prospectus. Whom should I share that template with via the Canva platform?

Please could you share with me, to create a copy ? @AudMonte01

**Comment by krol3** [comment]
Please could you share with me, to create a copy? @AudMonte01

**Comment by AudMonte01** [comment]
MEETING UPDATES

Logo
* Brazilian flag for background

Venue
* Contract to be signed next week

Action Items
* [ ] Team will send final version of sponsor prospectus in Slack
* [ ] Audra to submit logo request to LF Creative

**Comment by AudMonte01** [comment]
OCTOBER 18 MEETING NOTES

CFP update
* 24 applications + 14 in progress
* Close dates is November 5

Venue update
* [Natura](https://www.natura.com.br/) (Diego is the point of contact)

Action items
* [ ] Carolina to send Audra updated prospectus with new venue
* [ ] Audra to update KubeWeekly newsletter with just prospectus
* [ ] Team to create 1 or 2 slides to use at KubeCon Chicago Kiosk for promotion

**Comment by AudMonte01** [comment]
MEETING NOTES

Venue
* Natura as venue is free the end of February

Sponsors so far
* RedHat
* Grafana Labs?

Contributor Fest
* [ ] Audra to help find a committer who can give a 2-hour workshop how to do a commit from end to end. Have first 30 minutes doing a presentation.

Sponsorships
* [ ] Audra to provide active companies in Brazil they should pursue

**Comment by AudMonte01** [comment]
DECEMBER 20 CNCF SYNC NOTES

How agenda is shaping
* Notifications will go out at the end of the month
* A lot of applications with co-presenters

Sponsors so far
* RedHat, Natura, GetUp (Joao)
* Elastic is almost closing
* In talks with AWS

Marketing
* 100 tickets sold so far
* [ ] Audra to plug agenda in KubeWeekly newsletter on January 12 (if it is released by then)
* [ ] Audra to coordinate CNCF-support promotional video

**Comment by AudMonte01** [comment]
JANUARY 25 CNCF SYNC NOTES

Content
* Agenda to be sent to kcd@cncf.io for review
* Audra generally reviewed in sync, and all looks good

Marketing
* Logo updated by team with small iteration with outline of "Brasil"
* Tickets sold so far 150
* 350 with speakers and sponsors
* [ ] Audra and Jefferey to send Marketing video by EOW?

Benefits
* Dan Kohn scholarship results for KCD Organizer nominations
* [ ] Audra to send sticker and training vouchers

**Comment by AudMonte01** [comment]
FEBRUARY 15 FINAL CNCF SYNC

Sponsors
* Closed 11 sponsorships, and had to turn some away
* Were able to get swag for event and will host an attendee happy hour

On-site
* 12 volunteers on-site
* Signage all printed
* Contracted a vendor to set
* Discussed using WhatsApp group for all attendees to have last-minute notifications on-site
* Friday (Joao and Carolina)
* Saturday (Diego, Bernardo, and Jade)

Marketing
* Sold out tickets!
* Audra shared training vouchers earlier this week, via email

Action Items
* [ ] Audra to set up retrospective summary call

**Comment by AudMonte01** [comment]
MARCH 13 RETROSPECTIVE MEETING

Analytics
* Registration versus checked in
-- Virtual 576 registrations and 412 checked in (72% turnout)
-- 359 registrations and 281 (78% turnaround rate)
* Number of speakers versus number of women speakers
- 74 speakers including virtual speakers (9 woman (was 12) - 12-16%)
- 58 sessions
* Sponsorships: 11 sponsors total. Waiting for 10% payments. Breaking even.

What went well
* Sold out! Could have easily sold 600 tickets. Every batch of tickets (tier) sold in 1 hour
* Natura liked having the event being there
* Volunteers were really engaged (good community spirit). Great "extended arm".
* Feeling of a community event (organized by the community for the community)
* Execution by organizers was great for a first-time event, and close partnerships came through with organizers.
* Many submissions in the CFP, and a lot of great content - great feedback
* Eco bag for attendees had shirt, lunch and coffee tickets, hand cream from Natura

Lessons Learned
* Check-in process could have been smoother (manual process with Simpla platform).Writing names instead of printed badge
* Volunteers could have been organized 1 week before
* Having a tour of the venue for the organizers would have been good because it was a big venue.
* More time between sessions for attendees to get from one place to the other.
* Organization weeks before was tiring (up late at night). Ownership is key - having organizers own a piece and see it through.

Final Marketing
* [ ] Team to fill out form for Credly badges for volunteers + speakers together
* Training vouchers will be distributed to the first 10 people who filled out the feedback survey
* [ ] Video recordings will be on YouTube. Team to send Audra playlist to duplicate on CNCF YouTube channel
* Audra shared Transparency Report template with Carolina
* Team will collaborate on a Blog Post for cncf.io, to wrap up event with all assets

**Comment by AudMonte01** [comment]
Organizer badges have been issued.

**Comment by AudMonte01** [comment]
Hello @krol3 - any idea when the transparency report will be ready for us to publish?

**Comment by kcloudn** [comment]
I will work on it in this month. At the end of the month it will be ready
