### ISSUE TITLE
Some content is missing in the about-organizing.md

### ISSUE THREAD

**Issue by Nitishupkr** [cncf/kubernetes-community-days#499]
### Submission checklist:
https://community.cncf.io/kubernetes-community-days/about-kcd/
note section in the website is not showing in the about-organizing.md 
you can see in video
please verify is it right or wrong

https://github.com/cncf/kubernetes-community-days/assets/95420063/e77185f3-d215-4941-a7fa-232440379c87

**Comment by AudMonte01** [comment]
This page is no longer active and was replaced with cncf.io/kcds
