### ISSUE TITLE
Don't allow event-specific code-of-conduct.md 

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#50]
Could you please delete https://github.com/cncf/kubernetes-community-days/blob/master/content/events/2020-bouvet-island/code-of-conduct.md and ensure that `Code of Conduct` (note capitalization) is the last menu item everywhere on the site. The text should be the same, except that inside of events, the emergency numbers and organizer email should be listed.

**Comment by lucperkins** [comment]
@dankohn The original issue explicitly called for an event-specific COC: https://github.com/cncf/kubernetes-community-days/issues/46

**Comment by dankohn** [comment]
Sorry, Luc, my directions yesterday were in error. I meant to say that the menu item should be the same everywhere, not that there should be an editable page.

**Comment by lucperkins** [comment]
@dankohn Understood. No worries.

**Comment by lucperkins** [comment]
Resolved by 0b1922736ce0c7d40209b841d99624801e2d8910
