### ISSUE TITLE
KCD Shenzhen 2023 (December)

### ISSUE THREAD

**Issue by Iceber** [cncf/kubernetes-community-days#503]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: `Shenzhen`
* [x] Event Date and Time: 12.16
* [x] Expected Number of Attendees: 250
* [x] Event cost per ticket, and if you will have early bird pricing or not: no
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Keith Chan, Linux Foundation APAC, VP of APAC,CNCF, kchan@apac.linux.com, Keith Chan
* [x] Organizer 2: Iceber Gu(蔡威), DaoCloud, Cloud Native R&D Engineer, Clusterpedia Founder & Containerd Maintainer, caiwei95@hotmail.com, Iceber Gu
* [x] Organizer 3: [Shushan Chai](https://github.com/chai2010), Ant Group, Software Engineer, Author of Wa Language & Maintainer of KusionStack, chaishushan@gmail.com,chai2010,
* [x] Organizer 4: Leo Ye(叶立), Shopee, Elastic Compute Platform Engineer,li.ye@shopee.com,,
* [x] Organizer 5: Miley Fu, WasmEdge, DevRel &Founding member, CNCF Ambassador, furao@secondstate.io, Miley-WasmEdge
* [x] Organizer 6: Devin Geng, Tencent, Open Source Expert, NextArch Foundation TOC & SODA Foundation Outreach Committee Member & Ceph Ambassador, devingeng@tencent.com,DevinGeng

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] If there is already a KCD in your country, you agree to schedule your KCD at least two months apart from that pre-planned KCD.
* [x] Minimum of 3 organizers from 3 different organizations
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event(we prefer to use https://wj.qq.com/ as it is popular in China)

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a WeChat handle specific to your KCD event

### Getting started checklist for CNCF:
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CNCF China team introduced for marketing amplification, and review of program

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Hi @Iceber - once the organizers are notified of the date change, let's schedule a kick-off call: https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by AudMonte01** [comment]
AUGUST 22 MEETING NOTES

Monthly meetings
* Audra created a sync, but the team will let her know one week in advance if they feel Kieth has provided all the proper resources

Content
* Will continue with survey for CFP

Event dates
* One-day event and maybe 2 tracks
* Must be two months (or 8 weeks) apart from Hangzhou (October 21) so December 16 at earliest

Actions
* [ ] Action for team to check venue availability for mid to end of December
* [ ] Audra to create Slack channel for organizers
* [ ] Audra to create a Bevy chapter
* [ ] Miley to ask team to create profiles on community.cncf.io

**Comment by AudMonte01** [comment]
MEETING NOTES

Venue
* Not secured yet, but there is one option through Tencent that has a room that can hold at least 100 people, but it's not close to the 2nd room
* Might use Shopee which has 2 meeting rooms

Content
* Not sure if they want 1 or 2 tracks

Sponsors
* Only have discussed who to reach out to on the sponsorships side

Action item
* [ ] Audra to put in request for logo creation with cityscape and globe adjustment for APAC region, and turnaround in 1 week

**Comment by AudMonte01** [comment]
OCTOBER 17 MEETING NOTES

Venue 
* Secured Shope office space that accommodates up to 250 people

Sponsors
* Prospectus completed
* Sponsor for tea break and food, and two others interested like EndGroup and another in Hong Kong
* Many interested in community partnerships 
* 10 booths in the venue space (can include partners)

Content
* CFP published in official CNCF WeChat account
* WebAssembly article written to highlight the new track highlighting the CFP
* Sponsor talks will be project-based

CNCF resources
* [ ] Audra to send exam voucher code via email to Iceber and Miley

**Comment by jiekun** [comment]
I would like to provide some feedback on the CFP process.

There is no doubt that **https://wj.qq.com/** is a popular and user-friendly survey system in China. However, unlike sessionize (which is used in KubeCon + CloudNativeCon), users who have submitted a CFP might not have the ability to view and edit their submissions.

I believe it is important, at the very least, to be able to view the submitted content or receive an email notification. Let's consider the following scenario:
1. A developer submits a CFP.
2. He close the page or browser.
3. He is now no longer able to access the content they submitted, and he's unsure if it was successfully submitted. Could it be lost due to a network issue?

I think one aspect related to user experience is providing timely feedback and confirmation (I'm not talking about the CFP result but a confirmation during early period). People probably dislike the feeling of their submissions disappearing without a trace, similar to a stone sinking into the sea.

So maybe we should look for a proper platform for CFP instead of a survey system?

**Comment by Iceber** [comment]
Thanks for the feedback, I often have the same issues as you in China, I'm not sure if I'm submitting successfully or even if I'm having a hard time remembering what I'm submitting :joy:

As a regional community event, we have to use the most common CFP method for events in China. But it does have its problems.

We could add a checkbox in the future
- [ ] whether to send a copy to the email

**Comment by jiekun** [comment]
@Iceber The checkbox way is a lot better. 

We generally don't have a preference for which platform or system is used for the CFP process, as long as it can be accessed locally. Therefore, platforms such as https://wj.qq.com/, Wjx, or any other similar system would be suitable. The most important feature we are looking for is the ability to **edit** CFPs and send confirmation emails :P

**Comment by Iceber** [comment]
@jiekun I recently discovered wenjuan.com, which reminds the user that a submission record is saved if they log in, and you can edit it.
Might use it next time

**Comment by Iceber** [comment]
BTW, Why I didn't choose sessionize, I like sessionize, it's very well-rounded and the experience is good.
However for some first speakers it might scare them off, e.g. extra login process, English interface, of course it's not too much of a problem, but still would have preferred to go for a simpler platform that encourages them to become a speaker first, and then they might have the guts to get involved in kubecon.

**But that's no reason for CFP not to have editing capabilities, so I'm also looking for platforms that are simple to use and able to edit!**:joy:

**Comment by jiekun** [comment]
> BTW, Why I didn't choose sessionize, I like sessionize, it's very well-rounded and the experience is good. However for some first speakers it might scare them off, e.g. extra login process, English interface, of course it's not too much of a problem, but still would have preferred to go for a simpler platform that encourages them to become a speaker first, and then they might have the guts to get involved in kubecon.

100% agree. Like what we've experienced in software development, there is no silver bullet for these stuffs and they can be accomplished gradually, step by step, instead of trying to find a "perfect" platform right from the beginning.

**Comment by Iceber** [comment]
KCD Shenzhen 2023 🎄🎅 was successfully held🎉.

Thanks to @AudMonte01  for your help🙏, and to cncf for supporting the event.

I'll be uploading photos, slideshows and videos next and will be putting together a report on the event!

**Comment by AudMonte01** [comment]
Excellent! Would your team like a Transparency Report templates via Canva?

**Comment by Iceber** [comment]
@AudMonte01 We need it. Thank you.

**Comment by AudMonte01** [comment]
Hi @Iceber - checking in to see how the transparency report is coming along after I shared it last?
