### ISSUE TITLE
KCD Mumbai 2024

### ISSUE THREAD

**Issue by rohitg00** [cncf/kubernetes-community-days#506]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [ ] Event Location: The Lalit
* [ ] Event Date and Time: May 18-19, 2024
* [ ] Expected Number of Attendees: 500
* [ ] Event cost per ticket, and if you will have early bird pricing or not: TBD

#### Event type:
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Rohit Ghumare, Developer Advocate , [Ghumare64@gmail.com](mailto:Ghumare64@gmail.com), Rohit Ghumare
* [x] Organizer 2: Saiyam Pathak, Civo, Field CTO, [saiyam911@gmail.com](mailto:saiyam911@gmail.com)
* [x] Organizer 3: Divya Mohan, SUSE, Sr Technical Evangelist, [divyamohan0209@gmail.com](mailto:divyamohan0209@gmail.com)
* [ ] Organizer 4: 

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: [contact@kcdmumbai.com](mailto:contact@kcdmumbai.com)
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by rohitg00** [comment]
@saiyam1814 
@divya-mohan0209
🚀😇

**Comment by devarshishimpi** [comment]
Excited!🤩

**Comment by AudMonte01** [comment]
Hi @rohitg00 - do we have a kick-off call scheduled yet? I also want to entertain hosting this in April. Please hold on booking a venue until we have a kick-off call, to avoid conflicts with other KCDs. Thank you!

**Comment by saiyam1814** [comment]
Hi @AudMonte01 I thin May is fine as there is no KCD till now planned in India within that timeframe . These is one tentative in feb so we kept 2 months post that. Yes we can have a kickoff call for this surely.

**Comment by AudMonte01** [comment]
Please book a kick-off call and I can explain our reasoning on timing. Thank you:
https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by AudMonte01** [comment]
KICK-OFF MEETING

Focus
* More technical professionals speaking
* Different tracks and flow

Venues
* They have a few in mind and don't suspect it will an issue in terms of securing

Sponsors
* Already have inquiring sponsors
* Sponsor budgets might be cut for KubeCon

Next steps
* Waiting on next planning phases oh KubeCon India for 2H of FY25
* Also noted the many other KCDs inquiring to host next year. Organizers are willing to collaborate with them

**Comment by AudMonte01** [comment]
KCD Mumbai Organizers have decided to release their KCD to open up opportunity for new KCD events in India.

Thank you for truly remaining in the spirit of open source by remaining collaborative and setting an example for other KCD organizers to share the space.

A note for the community - these organizers / Ambassadors are available to help advise your KCD if you wish for their help and guidance.

**Comment by OmIngale** [comment]
Excited this event

**Comment by saiyam1814** [comment]
@OmIngale Since we had other KCD's and we were requested not to do this event this year so that other communities can also thrive. We have decided not to do the KCD mumbai this year although we would have loved to but we want other communities like Pune Kerala etc to shine as well.
