### ISSUE TITLE
kubernetescommunitydays.org redirects to a non-existent page

### ISSUE THREAD

**Issue by oleg-nenashev** [cncf/kubernetes-community-days#507]
The redirect in the https://kubernetescommunitydays.org/ link is dead. It is used in https://github.com/cncf/kubernetes-community-days description, for example

![image](https://github.com/cncf/kubernetes-community-days/assets/3000480/7c615576-bba3-4908-82f6-c85c7747ff46)

### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [x] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [x] I've described what I expected to see and what I am seeing
* [x] I am not interested or able to instead create a pull request with a proposed fix

**Comment by AudMonte01** [comment]
This page has since been replaced with cncf.io/kcds.
