### ISSUE TITLE
KCD Chennai 2025

### ISSUE THREAD

**Issue by senthilrch** [cncf/kubernetes-community-days#509]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Chennai Trade Centre
* [x] Event Date and Time: Q2 2025
* [x] Expected Number of Attendees: 500
* [x] Event cost per ticket, and if you will have early bird pricing or not

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Senthil Raja Chermapandian, Ericsson, Principal Software Engineer, [senthilrch@gmail.com](mailto:senthilrch@gmail.com), CNCF slack: senthilrch
* [x] Organizer 2: Gayathri R, gopaddle.io, UI/UX Developer & QA Lead, [gayathri.r@gopaddle.io](mailto:gayathri.r@gopaddle.io), CNCF slack: Gayathri R
* [x] Organizer 3: Kannan V, Tata Communications, Senior Technical Lead, [kannanv06@gmail.com](mailto:kannanv06@gmail.com), CNCF slack: Kannan V
* [x] Organizer 4: Manikandan Krishnamurthy, TCS, GCP Architect, [manikandank276@gmail.com](mailto:manikandank276@gmail.com), CNCF slack: Manikandan
* [x] **CFP Admin**: Senthil Raja Chermapandian, Ericsson, Principal Software Engineer, [senthilrch@gmail.com](mailto:senthilrch@gmail.com), CNCF slack: senthilrch
* [x] Fiscal Sponsor: Celexsa (Senthil Raja Chermapandian main point of contact)

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments: Celexsa
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Waiting to heard on KubeCon India dates before finalizing time for this event. Potentially after KubeCon.

**Comment by AudMonte01** [comment]
Hi @senthilrch - per our conversation, let's wait until 2025 to host this event. If you could please re-open this issue 8 months from the time you would like to host it in 2025? Thank you 🙏🏽

**Comment by senthilrch** [comment]
@AudMonte01 Hi Audra, We couldn't host KCD Chennai 2024 in August due to lack of sufficient time for preparation. After discussion with KCD Chennai co-organizers, I've modified this issue title and dates, proposing to host KCD Chennai in **Q2 2025**. Kindly share the survey monkey link for the application.

**Comment by AudMonte01** [comment]
Thank you for your submission - we are now ready to accept official applications via Survey Monkey. The deadline for submissions will be Wednesday September 11 at 11:59pm Pacific Daylight Time. More information and the application can be found via https://www.cncf.io/kcds/application/.

This GitHub issue is now closed. Should your KCD be accepted into the 2025 program, a core CNCF staff member will open a new issue for program tracking and transparency.
