### ISSUE TITLE
KCD Bologna, Italy 2024 (June)

### ISSUE THREAD

**Issue by akelity** [cncf/kubernetes-community-days#513]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Bologna
* [x] Event Date and Time: June 20
* [X] Expected Number of Attendees: Goal is 250-300 attendees 
* [ ] Event cost per ticket, and if you will have early bird pricing or not
* [X] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [X] Organizer 1: Adriano Pezzuto, Founder, [adriano@clastix.io](mailto:adriano@clastix.io), Adriano Pezzuto
* [X] Organizer 2: Annalisa Gennaro, Head of Marketing and Communication, [annalisa.gennaro@sparkfabrik.com](mailto:annalisa.gennaro@sparkfabrik.com), Annalisa Gennaro
* [X] Organizer 3: Dario Tranchitella, Technical Advisor, Dario Tranchitella, [dario@clastix.io]
* [X] Organizer 4: Evangelista Tragni, Manager AI Team & Trainer, [e.tragni@desotech.it]
* [X] Organizer 5: Giovanni D'Anna, Marketing Manager, [g.danna@desotech.it]
* [X] Organizer 6: Jacopo Nardiello, Founder, [jacopo@sighup.io](mailto:jacopo@sighup.io), Jacopo Nardiello
* [X] Organizer 7: Marcello Lustro, Community manager, [marcello@clastix.io](mailto:marcello@clastix.io), Marcello Lustro
* [X] Organizer 8: Maria Pina Di Cataldo, Community manager, [mariapinadc@gmail.com](mailto:mariapinadc@gmail.com), Maria Pina Di Cataldo
* [X] Organizer 9: Michel Murabito, Developer Advocate, [michel.murabito@mia-platform.eu](mailto:michel.murabito@mia-platform.eu), Michel Murabito
* [X] Organizer 10: Natale Vinto, Developer Advocate, [nvinto@redhat.com](mailto:nvinto@redhat.com), Natale Vinto
* [X] Organizer 11: Paolo Mainardi, CTO, [paolo.mainardi@sparkfabrik.com](mailto:paolo.mainardi@sparkfabrik.com), Paolo Mainardi
* [X] Organizer 12: Sara Trappetti, Marketing Team, [sara@sighup.io](mailto:sara@sighup.io), Sara Trappetti
* Third party agency to handle fees and sponsorships

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [X] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [X] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [X] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
* [X] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event. We will use Sessionize at the end of 2023/beginning of 2024.
* [X] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with Audra to make it unique to your KCD.

### Getting started checklist for organizers

* [X] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
Kick-off meeting to determine dates, is scheduled for Wednesday, November 22.

**Comment by AudMonte01** [comment]
NOVEMBER 22 KICK-OFF MEETING

Team
* New team (this issue is up-to-date with the exception of 1 person)
* Some members from last year

Logo
* Everything is digital so far
* Use old logo until new one is created

CNCF Support
* 10 training vouchers
* KubeCon scholarship for 1 person in the community 

Content
* 2 tracks with 8 sessions per track with lightning talks reserved for sponsors
* CFP December 4 opening date is the goal
* [ ] Audra to get Sessionize code

Other notes
* KCD Zurich wants to be a sponsor, and approved the closeness of the event
* Hired a different event planning agency to take care of fiscal sponsorship

**Comment by AudMonte01** [comment]
JANUARY 16 MEETING NOTES

Logo
* Doing another re-work of the logo (bringing in old logo)

CFP is open
* [ ] Audra to point to in KubeWeekly newsletter

Ticketing platform
* ti.to
* Kept all recommended registration questions
* [ ] Team to send Audra URL for ticketing platform and Audra to add button to Bevy

Sponsorships
* So far 4 Gold out of 5 and 2 Silver

**Comment by AudMonte01** [comment]
MARCH 5 CNCF SYNC

Ticket Sales
* 41 of 50 early bird tickets sold (ends March 15)
* Next - prioritize Media and Community partners

Content
* 50 submissions so far
* LF Panel about open source
* Organizing Program Committee with input outside of organizing committee like (Andrea, Alessandro)
* Carla C. might emcee

Marketing
* Prioritize sponsorships and CFP at KubeCon Kiosk
* Many local events happening in the next month where the team will promote their event

Action Items
* Almost all organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/). Team to prompt newcomers to take it.
* [ ] Sara and Mich to work together to duplicate event from Conference to Meetup event type, and will let Audra know when it is ready for publishing and old event is ready for archiving

**Comment by AudMonte01** [comment]
APRIL 16 CNCF CHECK-IN

Content
* Total CFP submissions
* Reviewing has been completed as of yesterday (14 people really engaged / reviewed 90% of talks)
-- 8 talks in Italian and 4 in English
-- Possibly give a free ticket to waitlist speakers
-- A Mix of intermediate and beginner content with 1 advanced talk
-- 2-3 days for speaker confirmations
* Michel and Audra reviewed agenda together. All is approved by CNCF
* [ ] Michel to send official email with agenda spreadsheet to kcd@cncf.io for paper trail of approval
* Agenda may be launched as soon as next week. Potentially announce in pieces

Sponsorships are better than last year
* 4 Gold sponsors with 1 left and a company interested to take the last Gold
* 5 Silver
* 1 Platinum is still available

Website
* [ ] Audra to publish "Meetup" event and cancel "Conference" event type, and work with Bevy on making the link the same

Ancillary
* Team wants to have an attendee party celebrating the 10 year birthday for K8s. 
* [ ] Audra to check in logo usage for stickers, signage etc.

**Comment by AudMonte01** [comment]
@akelity - The winning logo will be in the [CNCF logo repo](https://github.com/cncf/artwork/blob/main/examples/other.md) and free to use it how you wish as long as it is in [the trademark guidelines](https://www.linuxfoundation.org/legal/trademark-usage).

**Comment by AudMonte01** [comment]
MAY 7 CNCF CHECK-IN

Sponsors and if for profit what to do with funds?
* 1 platinum and 1 silver available (Gold is sold out)
* Able to offering an aperitif and more giveaways for attendees

Content
* Andrea Giardini will be speaking to community and CNCF programs in a keynote speakers
* Two emcees (Carla and Frederica), they will also host a diversity panel

Marketing
* After Agenda released last week, 91 tickets at this point which includes some speakers and sponsors
* All declined speakers will get a discounted ticket
* Offering a discount to large groups from companies
* [ ] Audra to announce agenda is now LIVE in Kubeweekly
* [ ] Team to utilize CNCF [#socialmedia Slack channel](https://cloud-native.slack.com/archives/C12MRQ97A) to ask Jessie Adams-Shore to re-share posts from main CNCF account
-- avoid sponsor posts
* Audra sent sticker/decal voucher code via email to team

**Comment by AudMonte01** [comment]
JUNE 4 CNCF CHECK-IN

Sponsors Updates
* Sponsors are sold out

Ticket updates
* 200 tickets out of a goal of 250

Extras
* Photo Booth with KCD logo and K8s 10-year birthday logo
* Tomorrow's virtual KuberTENes party (2 hours with panels)
* [ ] Audra to check on shipping of package (used at physical KCD)

Actions
* [ ] Audra to check on tracking for KuberTENes party
* [ ] Team to fill out [form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) and design Credly badges for all speakers
* [ ] Team to send Audra date of retrospective summary meeting
