### ISSUE TITLE
KCD Costa Rica 2024 (March)

### ISSUE THREAD

**Issue by falconcr** [cncf/kubernetes-community-days#514]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Heredia, Costa Rica a la Universidad Nacional, Campus Benjamín Nuñez (capacity 200 people)
* [x] Event Date and Time: March 1-2 2024
* [x] Expected Number of Attendees: 100-200
* [x] Event cost per ticket, and if you will have early bird pricing or not: Free

#### Event type:
* [ ] Virtual
* [x] Hybrid
* [ ] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:

* [x] Organizer 1: Gerardo Lopez, Veritas Automata, Principal Engineer, gelopfalcon@gmail.com, CNCF Slack Username(@gelopfalcon)
* [x] Organizer 2:  David Perez, Gorilla Logic, Senior DevOps, oso12_90@hotmail.com, CNCF Slack Username (@David Pérez)
* [x] Organizer 3: Vladimir Aguilar, TradeStation, Senior DevOps, mir23cr@gmail.com, CNCF Slack Username (@Vladimir Aguilar )
* [x] Organizer 4: Cristher Castro, Cuemby, CNCF Ambassador, CNCF Slack Username (@CristherCastro)

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [ ] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event. We will use Sessionize at the end of 2023/beginning of 2024.
* [x] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with Audra to make it unique to your KCD.

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: costarica-organizers@kubernetescommunitydays.org 
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in Sessionize
* [x] Marketing Plan shared

### Organizer Planning Timeline
* [x] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [x] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [x] Send CNCF event analytics
* [x] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [x] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by falconcr** [comment]
Updating the terms

**Comment by AudMonte01** [comment]
KICK OFF MEETING NOTES

Organizer team
* Gerardo (Falcon): 12 years in industry as a developer
* David Perez: Gerardo working with David at EMB and HP and moved to DevOps. Great mentor
* Vladimir: New to cloud native and came from the University of Costa Rica. Jumped from Junior to Senior DevOps in one year's time

Event style
* Friday workshops held virtually mid day
* Saturday all day in-person

Venue
* Not an issue
* Everyone wants to host this event

Date
* April - June is summer and good weather
* April is ideal for the event timeline based on other events and company budgets

Fiscal Sponsorships
* Colon ₡ is the local currency
* Might entertain NaOm Labs (10% fee on transactions + currency exchange fees based on day of transactions)

**Comment by falconcr** [comment]
**DATE**:  March 1-2  2024
**VENUE**: Universidad Nacional, Campus Benjamín Nuñez (capacity 200 people)
@AudMonte01

**Comment by AudMonte01** [comment]
OCTOBER 10 MEETING NOTES

Venue
* 3 tracks and 1 keynote session
* Each room can accommodate 30 people. Keynote stage/auditorium can accommodate 200 people
* Free tables, chairs, streaming equipment 

CFP
* [Nigel Poulton](https://www.linkedin.com/in/nigelpoulton) committed as a keynote
* Keynotes in the morning and at the end
* Will use Sessionize and have the CFP ready ahead of KubeCon Chicago and promote at the booth

Marketing plan
* Free ticket cost

**Comment by AudMonte01** [comment]
NOVEMBER 28 MEETING NOTES

Content
* 12 CFP submissions so far
* [ ] team to update name/title in Sessionize to "KCD" to eliminate confusion for those who think it's only an event around Kubernetes

Tickets
* Using Ti.to for registration and have 60 registrations so far

Sponsor
* They have a fiscal sponsor
* 3 committed sponsors

Marketing
* Consistent with social posts, including 
* Cristher Castro (Ambassador) from KCD Colombia is helping with design

**Comment by AudMonte01** [comment]
May 2 Retrospective with CNCF

Positive Feedback
* Good vibe from attendees and sponsors
* Sponsors offered swag and jobs
* Different representation from other countries
* Great support from the venue (A/V, volunteers, flexible to bring people from other Universities)
* Women in Data collaboration with volunteer logistics, and contributions as a sponsor, and virtual  help

Lessons Learned
* Check-in process was a little messy (long lines). No one scanned QR codes in the end, and that's what took long
* Food & Beverage is key for keeping the audience around, so planning that earlier in advance
* There were not a lot of food options at the venue/university
* The timing per slot was not long enough, and some speakers took longer than allotted
-- offering a dedicated Q&A section/space
* Have a small payment just to see commitment in terms of attendance
* Open topics covered to open diversity

Analytics
* Number of registrations (440) versus number of check-ins (185), attendance rate of 42%
* 14 Total sponsors (5 gold + 2 silver + 3 ancillary + 4 community)
* Small small loss of $17
* Virtual: Total number of speakers 12 versus women speakers 2 (17%)
* In-Person: Total speakers was 28 and women were 2 = 7%

Post-event marketing
* Credly badges (distributed)
* [ ] Team finalizing transparency report after Audra shared
* [ ] Team to upload videos from virtual event and keynotes to a YouTube playlist and share with Audra for CNCF channel
* [ ] Team to write blog Post on cncf.io/blog once the above are complete, and point to those assets

**Comment by AudMonte01** [comment]
Hello @falconcr and @cristhercastro - following up here on the transparency report. We would like to publish it via https://www.cncf.io/reports and https://www.cncf.io/kcds/. Gracias

**Comment by falconcr** [comment]
> Hello [@falconcr](https://github.com/falconcr) and [@cristhercastro](https://github.com/cristhercastro) - following up here on the transparency report. We would like to publish it via https://www.cncf.io/reports and https://www.cncf.io/kcds/. Gracias

Hello @AudMonte01, I have shared it with you. Regards.

**Comment by AudMonte01** [comment]
Thank you! It is now published: https://www.cncf.io/reports/kcd-costa-rica-2024/ 

What about the YouTube videos. When do you think the playlist will be ready?

**Comment by falconcr** [comment]
> Thank you! It is now published: https://www.cncf.io/reports/kcd-costa-rica-2024/
> 
> What about the YouTube videos. When do you think the playlist will be ready?

Hello. It is the playlist https://www.youtube.com/@CloudNativeCostaRica

**Comment by cristhercastro** [comment]
Thanks Audra,
We Reposted already in the KCD Costa Rica Channel in LinkedIn

Best
Cristher

From: Gerardo Lopez ***@***.***>
Date: Wednesday, September 18, 2024 at 5:42 PM
To: cncf/kubernetes-community-days ***@***.***>
Cc: Cristher Castro ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/kubernetes-community-days] KCD Costa Rica 2024 (March) (Issue #514)

Hello @falconcr<https://github.com/falconcr> and @cristhercastro<https://github.com/cristhercastro> - following up here on the transparency report. We would like to publish it via https://www.cncf.io/reports and https://www.cncf.io/kcds/. Gracias

Hello @AudMonte01<https://github.com/AudMonte01>, I have shared it with you. Regards.

**Comment by AudMonte01** [comment]
Thank you, @falconcr - I have duplicated the playlist on the main CNCF YouTube channel to promote to our subscribers, and posted about it on LinkedIn.

All post-event marketing details are now complete. This issue/ticket is now closed.

**Comment by falconcr** [comment]
> Thank you, [@falconcr](https://github.com/falconcr) - I have duplicated the playlist on the main CNCF YouTube channel to promote to our subscribers, and posted about it on LinkedIn.
> 
> All post-event marketing details are now complete. This issue/ticket is now closed.

THe experience was amazing, thanks @AudMonte01  @cristhercastro Vladimir and David.
