### ISSUE TITLE
KCD Guadalajara 2024 (February)

### ISSUE THREAD

**Issue by pedrogk** [cncf/kubernetes-community-days#515]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Guadalajara, Mexico - CUCEA Universidad de Guadalajara (co-located event?)
* [x] Event Date and Time: February. 9am to 6 pm
* [x] Expected Number of Attendees: 200. Venue has space for 400 in case we have more participants.
* [x] Event cost per ticket, and if you will have early bird pricing or not: Free.

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Financial officer: Pedro Galvan, Software Guru, Head of Content & Technology, pedro@sg.com.mx, (CNCF: Pedro Galvan), GitHub: [pedrogk](https://github.com/pedrogk)
* [x] Co-organizer / counselor: Víctor Morales, Samsung, Sr Staff Software Engineer, v.morales@samsung.com, (CNCF: Victor Morales), GitHub: @electrocucaracha 
* [x] Co-organizer: Rodolfo Martínez Vega, Globant Software Engineer, rodomar@outlook.com, GitHub: @ramrodo
* [x] Co-organizer: Teyza Ponce, Project Manager, Software Guru teyza@sg.com.mx, CNCF Slack: Teyza Ponce
* [x] Co-organizer: Mara Ruvalcaba, COO, Software Guru, mara@sg.com.mx, CNCF Slack: Mara
* [x] Sponsorships: Claudia Perea, claudia@sg.com.mx
* [x] Operations: Ivett Sanchez, ivett@sg.com.mx
* [x] Tech support: Alberto Rodríguez, alberto@sg.com.mx

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
  * [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event. We will use Sessionize at the end of 2023/beginning of 2024. 
* [x] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with Audra to make it unique to your KCD.

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create social media account(s) specific to your KCD event (CNCF has a social presence on X/Twitter and LinkedIn)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: guadalajara-organizers@kubernetescommunitydays.org
* [x] Region created in Bevy
* [x] Added to Bevy header
* [x] CFP created in Sessionize

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [x] Removed from Bevy header
* [x] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
Hi @pedrogk - we are excited to see this event! Though December is around the corner, we advise for first-time KCDs to give themselves more time. But I would love to hear more about the team's plan in a kick-off call!
https://calendly.com/audmonte/kcd-onboarding-kickoff-call

**Comment by victor** [comment]
Please fix your mentions

**Comment by pedrogk** [comment]
> Please fix your mentions

Oup. Done.

**Comment by AudMonte01** [comment]
KICK-OFF MEETING NOTES

Other organizing contributors
* Rodolfo and Angel

Event Goals
* February date
* Grow into a KubeDay that COSS can be colocated with 

Guadalajara
* Engineering centers (Oracle, Intel, Wizeline and Globant for example)
* Wizeline has most SREs and DevOps Engineers
* Startup-oriented
* Tech flavor is more international 

Venue
* Auditorium and laboratories for workshops
* Co-located with another event (open source contribution summit aka CCOSS)
* Last year's summit had 150 people

Content
* Open CFP before the end of October
* Number of tracks (drone open source software
* Audience level

First Steps
* Make a copy of the in-person timeline from [this spreadsheet](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) and edit according to your event goals and time left
* Create Sponsor Prospectus for funds to secure venue (if not free)
* Secure venue

Action Items
* [ ] Audra to create a Slack channel
* [ ] Audra to create a Bevy chapter
* [ ] Audra to share sponsor prospectus template via Canva
* [ ] Team to decided on logo background (PDF example will be shared in Slack)

**Comment by alsotoes** [comment]
Why not free?

**Comment by pedrogk** [comment]
> Why not free?

1. In order to have a reliable headcount. My experience with in-person free events, especially in Guadalajara, is not good because too many people register and don't attend.

2. Because we are providing lunch.

Other in-person KCDs in Latin America have been with paid ticket (ie Bogotá). I think that is healthy.

We have discounted price for students as well as scholarship tickets reserved for people who would like to attend and can't pay. We will also have sponsorship options focused on providing more scholarships to underrepresented groups.

**Comment by alsotoes** [comment]
Then I'll say to lower the costs and look for more sponsors. I see no reason for such high costs. Will you be giving out free certification vouchers? Swags? Others? Can you please name another community day with this kind of cost in the country?

About Guadalajara (I'm not against the venue), but Wizeline and Globant have offices in Mexico City, and most of the SRE/DevOps are working remotely; flying from Chihuahua, CDMX, and other cities will be expensive for most of them.

About (1): I was part of many OpenStack Days, and there are many ways to tackle that, not by charging the attendees; good marketing is one of them.

GDL airport is far from Zapopan and any other place for that matter. How many universities are in GDL compared with CDMX, and how many startups are also based in GDL compared with CDMX?

Either way, I'll try to be there to talk to Sergio and Victor, but without any hint on who will be there as speaker, I don't think it's a good idea to charge that amount.

Those are my two cents.

**Comment by alsotoes** [comment]
Will you guys will be willing to reconsider venue, an work together with other communities so the cost can be lower?

I'm speaking in behalf of Ceph and OpenInfra local communities.

Let me know.

**Comment by electrocucaracha** [comment]
Hey @pedrogk, our GitHub handles are @electrocucaracha @ramrodo @puerco @sergioarmgpl just in case that you want to update the description of the issue.

**Comment by AudMonte01** [comment]
OCTOBER 16 MEETING NOTES

Venue
* CONFIRMED for February 23 and 24

KCD Costa Rica is on March 2-3
* Travel distance is 4-6 hours, so no competition for attendees
* Speaker collaboration can be a tour aspect
* IDEA: A workshop that has two parts (part 1 in Mexico, and part 2 in Costa Rica)
* [ ] Audra to make intro between Rodlfa and Gerardo and copy Pedro to collaborate

CFP
* Need Sessionize by the end of the month
* Leave CFP open for 6 weeks

Logo
* [ ] Team to discuss background image of either [Glorieta La Minerva](https://es.wikipedia.org/wiki/Glorieta_La_Minerva) as a city scape, or an agave plant

**Comment by AudMonte01** [comment]
NOVEMBER 13 MEETING NOTES

Logo
* Audra disclosed upcoming changes to occur and asked for team's input

CFP
* Using Sessionize
* Deadline is January 9 with 16 proposals from KubeCon awareness alone
* [ ] Audra to add it to the KubeWeekly newsletter Dec 1

Sponsorships
* Might consider discounts for small companies under 50 people
* Team to balance budget with must-haves and nice-to-haves

Registration
* Team planning to open next week
* Hoping to offer scholarships for attendance to support diversity. Will come back to Audra in next meeting with what the team has decided.
* [ ] Teyza will put together a blog post once registration is open, and Audra to publish on cncf.io

**Comment by AudMonte01** [comment]
DECEMBER 4 MEETING NOTES

CFP numbers
* 39 submissions via the CFP with a goal for 100 submissions

Tickets
* Will use Ti.to for registration platform

Sponsorships
* Already have 5+ sponsors between paid and community

Other Marketing efforts and CNCF benefits
* https://posadev.mx/ is happening this Saturday. It's an event that targets local communities in Guadalajara 
-- Rodolfo will be attending, and can promote tickets at the event (open this week)
* Audra to promote CFP in CNCF marketing committee meeting + KubeWeekly newsletter
* [ ] Team to let Audra know once temporary logo is uploaded to Bevy so the event can be published on cncf.io

**Comment by pedrogk** [comment]
@alsotoes This will now be a free event for all attendees.

**Comment by alsotoes** [comment]
Nice to hear that!!!
@pedrogk do you guys have a post on social media that I can share with the community?

**Comment by AudMonte01** [comment]
JANUARY 26 CNCF SYNC

Tickets so far 244 (hoping to close 
* Goal of 70% professionals and 30% students

Review agenda (typically it is sent to [kcd@cncf.io](mailto:kcd@cncf.io) ahead of publishing)

Sponsors so far
* 2 Platinum
* 3 Gold + Oracle is pending Gold
* 4 Silver
* 10 Community Partners and Promotion


CNCF Marketing Help
* [ ] Audra to point to tickets for registration in KubeWeekly newsletter

**Comment by AudMonte01** [comment]
RETROSPECTIVE

What lessons learned
* Better scouting for A/V prep: The university was not ready with the A/V and splitting the rooms, which impacted the sessions
-- to get approvals at a University, you need to go through too many people
* Common channel for organizers to communicate

Positives
* Great content with international speakers
* Great interaction in sessions
* Sponsors were happy
* 7 Ambassadors
* Good student engagement

Analytics
* Total registered were 660 versus 302 total checked-in (46%)
-- non-male attendees 58 out of 302 (19%)
* Speaker diversity: 6 women out of 49 (12%)
* Sponsorships came in at a small loss on the Software Guru side. RedHat did not come through in the last-minute
* Will the team want to host a KCD next year?

Post-event marketing
* The team has their own transparency report
* [ ] Team wants to distribute Credly badges to speakers. Pedro will submit form and graphic
* Video recordings - some are savable. If not, then ask the speakers if they would record their session
* CNCF to amplify blog post that Teyza shared with Audra by re-posting on cncf.io

2025
* The team would like to see KubeDay at the country level

**Comment by alsotoes** [comment]
Some attendants used the public/open slack we have for the LATAM region. Feel free to use it.

https://slack.oss.lat

The only purpose for this is to have a single point to reach out the community and stop segregation.

Cheers.

**Comment by AudMonte01** [comment]
Hello @alsotoes -all  KCDs can also be found via cncf.io/kcds, and communnity.cncf.io.
