### ISSUE TITLE
KCD Bengaluru 2025

### ISSUE THREAD

**Issue by nkhare** [cncf/kubernetes-community-days#516]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [ ] Event Location: TBD
* [ ] Event Date and Time:  May or June 2025 desired
* [ ] Expected Number of Attendees: 800 (this can no longer exceed 500)
* [x] Event cost per ticket - INR 2500 (~$30) Regular and for early bird INR 2000 (~$25) 

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify who will be the CFP admin, as well as the financial officer)
* [x] Organizer 1 and financial officer : Neependra Khare , CloudYuga, Founder & Principal Consultant , neependra@cloudyuga.guru, neependra
* [x] Organizer 2: Kiran Mova, VMware, Senior Manager, kmova@vmware.com, 
* [x] Organizer 3: Aravind Putrevu, Calyptia Inc, Head of Developer Experience, aravind@devrel.cloud,aravind 

### Terms

* [x]  No other Kubernetes Community Day event in same major city (check with past organizers)
* [x]  Minimum of 3 organizers from 3 different organizations
* [x]  Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x]  At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [x]  All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x]  Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event. We will use Sessionize at the end of 2023/beginning of 2024.
* [x] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with Audra to make it unique to your KCD.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: organizers-bengaluru@kubernetescommunitydays.org 
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
Hello @nkhare - thank you for submitting this ticket. I have updated the date to TBD, as we have given priority to KCD Pune a new event who wanted to host in 2023, to decide of they will be in April or June. I am happy to meet in the meantime to further discuss legacy KCDs like this one and their advancement in the CNCF event space.
https://calendly.com/audmonte/30min

**Comment by AudMonte01** [comment]
Awaiting KubeCon India dates, so the team can plan the proper days away from the event.

**Comment by k8tgreenley** [comment]
KubeCon + CloudNativeCon + Open Source Summit India 2024
11-12 December | Delhi 

@AudMonte01 to book follow up call

**Comment by AudMonte01** [comment]
Yes - please see if there is some time here that will work for the three of you: https://calendly.com/audmonte/30min

**Comment by AudMonte01** [comment]
Hello @nkhare - with KubeCon in New Delhi in December, and Chennai not actively trying to plan a KCD, I want to check in to see if the September date is still feasible for your team to plan for, or if this will need to get postponed to 2025?

**Comment by nkhare** [comment]
@AudMonte01 Now September would be too early for us to plan. Lets postpone it to 2025. We discussed among other co-organisers and would like to do May or June 2025. It would be great if we can block that slot now.

**Comment by AudMonte01** [comment]
Thank you for letting me know, and my apologies for the delay in getting back to you. We will have a new submission process we will be launching with an FAQ at the end of this month, so please don't worry about submitting a GitHub issue. You will be notified in the KCD Organizer digest, as well as the organizer Slack channel. We will also host an FAQ in a KCD organizer working group.

**Comment by cloudyuga** [comment]
Thank you. We'll look forward to it.

**Comment by nkhare** [comment]
Thank you. We'll look forward to it.

**Comment by AudMonte01** [comment]
Thank you for your submission - we are now ready to accept official applications via Survey Monkey. The deadline for submissions will be Wednesday September 11 at 11:59pm Pacific Daylight Time. More information and the application can be found via https://www.cncf.io/kcds/application/.

This GitHub issue is now closed. Should your KCD be accepted into the 2025 program, a core CNCF staff member will open a new issue for program tracking and transparency.
