### ISSUE TITLE
KCD Spain 2023 (December)

### ISSUE THREAD

**Issue by raelga** [cncf/kubernetes-community-days#519]
# KCD Organizer Checklist

KCD Spain 2023 edition. Previous editions #440 in 2022 and #385 in 2021.

### Event Details
* [x] Event Location: Spain
* [x] Event Date and Time: December 12th, 2023. Afternoon to be friendly for Spain and Latam
* [x] Expected Number of Attendees: 500
* [x] Event cost per ticket, and if you will have early bird pricing or not: Free

#### Event type:
* [x] Virtual
* [ ] Hybrid
* [ ] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Rael Garcia Arnés, Red Hat, Principal Software Engineer, rael@redhat.com, rael
* [x] Mario Vázquez, Red Hat, Principal Software Engineer, mavazque@redhat.com, Mario Vázquez
* [x] Imma Valls, Grafana Labs, Developer Advocate, imma.valls@gmail.com, Imma Valls
* [x] Jona Apelbaum, Solo.io, Field Engineer, jona.apelbaum@gmail.com,  Jona Apelbaum
* [x] Antonio Berben, Solo.io, Field Engineer, a.berben.m@gmail.com, Antonio Berben
* [x] Jorge Turrado, SCRM Lidl International Hub, Staff SRE, jorge.turrado@hotmail.es, Jorge Turrado
* [x] Bart Farrell, Independent Content Creator, bartholomewfarrell@gmail.com, Bart Farrell
* [x] Cortney Nickerson, Kubeshop, Developer Relations, nickerson.cortney@gmail.com, Cortney Nickerson
* [x] Diego Cristóbal, VMware, Automation Engineer, diecristher@gmail.com, Diego Cristobal Herreros

Full team : https://github.com/kcdspain/spain-2023/issues/1

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies: @raelga
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] ~Agree to offer at least 3 complimentary tickets to increase diversity for the event~ N/A
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event. We will use Sessionize at the end of 2023/beginning of 2024.
* [x] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with Audra to make it unique to your KCD.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] ~Minimum of 3 sponsors committed (not required for virtual only events)~ Virtual Event
* [x] ~Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments~ Free Event
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used): https://twitter.com/KCDSpain

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
KICK-OFF MEETING

Organizers
* two more organizers missing from above list (see link to other GitHub issue)
* already have process in place from previous years

Timing
* Virtually in Spain's afternoon to be able to reach Latin American countries

Content
* Will host in Spanish
* Tracks will depend on CFP (last year they had 100 submissions)

Sponsorships are more community partners
* RedHat and Grafana to allow for donation of employee time
* Account donations like for Streamyard and so on

Action Items
* [ ] Audra to give team access to SM Apply TODAY (duplicate 2022 template)
* [ ] Audra to share social media options for scheduling

**Comment by AudMonte01** [comment]
NOVEMBER 2 MEETING NOTES 

Content
* Keynotes are more like opening notes with housekeeping
* CFP: push push push. Closing date is Nov 10.
* [ ] Audra to add QR code to CFP in Kiosk looping slides
* [ ] Jorge to send Audra program committee for reviewing in SMapply

Other marketing efforts
* [ ] Audra to update email alias for team
* [ ] Audra to send training vouchers

**Comment by AudMonte01** [comment]
NOVEMBER 16 MEETING NOTES

CFP final submissions + reviewing
* almost 50 talks right now, and will do one track with possibly a 60
* Tomorrow is the deadline
* [ ] Audra will ask LATAM KCD organizer channels to submit
* [ ] Team will send Audra the agenda to review next Monday the 20th

Marketing
* Buffer account being used with Jorge's Ambassador budget

Additional Sponsors
* Packt publishing will donate books

**Comment by AudMonte01** [comment]
NOVEMBER 30 MEETING UPDATE

Number of registrations + marketing
* 44 tickets so far
* Barcelona meetup pointed to the event
* Speaker promotion with social copy

Any additional sponsors donating tech or giveaways
* Media/community sponsors including KubeEvents

Streamyard / Bevy logistics

**Comment by AudMonte01** [comment]
DECEMBER 21 RETROSPECTIVE NOTES

Total registered versus total checked in: 272 VS 180 = 66% Attendance 
Total speakers with non-male speaker percentage: 20 talks/23 speakers and 5 non-male = 22% 
-- 50% of the speakers were from Latin America
Total sponsors with insight into profit or loss: No overhead, but sponsorships come from the donation of time approved from companies of organizers

Pros and Cons of the event
* Sessions had a nice balance of companies
* Great attendance in each session
* Good first-time topics
* Short time frame for planning lead to lower registrations. Also made it hard for new organizers
* Would like to shift lead organizers each year
* Imma (organizer) wasn't able to attend
* Cortney (speaker) wasn't able to attend due to travel
* Streamyard worked really well
* Bevy statistics are not great
* It would be great to have CNCF have an overall social account like Buffer, and/or Streamyard because it's web-based

Action Items
* [ ] Audra to share Transparency report template from CNCF with Imma, Rael, and Jorge
* [ ] Imma to lead Blog post to represent the program and upcoming events in Spain events in different cities, with a CTA for organizer collaboration
* [ ] Jona is working on videos to be uploaded to YouTube
-- Please email YouTube playlist to kcd@cncf.io

**Comment by raelga** [comment]
Thanks @AudMonte01 for the notes!
