### ISSUE TITLE
KCD Lima, Peru 2024 (July)

### ISSUE THREAD

**Issue by edithturn** [cncf/kubernetes-community-days#521]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [X] Event Location: Lima, Peru
* [X] Event Date and Time: 20 de Julio
* [X] Expected Number of Attendees: 500
* [x] Event cost per ticket: Free

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [X] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
* [X] Organizer 1: Carol Valencia, Independiente, Solution Architect,  valencia0.carol@gmail.com, carolvalencia
* [X] Organizer 2: Jean Paul Lopez, Red Hat, Senior Consultant, jplope89@gmail.com,
* [X] Organizer 3:  Edith Puclla, Percona, Tech Evangelist, edithpuclla20@gmail.com, Edith Puclla
* [X] Organizer 4:  Ronald Requena, Senior Engineering Manager ,rcronald@gmail.com
* [X] Organizer 5:  Juan Manuel Chávez, Banco de Crédito BCP, Technical Product Owner, jmchavezr@gmail.com, juanmanuelchr

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use Sessionize as the Call for Proposal (CFP) platform.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: lima-peru-organizers@kubernetescommunitydays.org
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
Hi folks - really excited about this KCD! Please gather as a team and meet some of the requirements under the above terms. Some will be a simple agreement. Any questions for me around other terms we can address in our kick-off call. That said, let us schedule a kick-off call once your team has done the above. Thank you!

**Comment by rcronald** [comment]
Agree to offer at least 3 complimentary tickets to increase diversity for the event

**Comment by juanmanuelchr** [comment]
Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). OK with this.

**Comment by GlisseLisbeth** [comment]
Agree to use SM Apply for CFP and to close it at least 6 weeks before the event. We will use Sessionize at the end of 2023/beginning of 2024.

**Comment by AudMonte01** [comment]
KICK-OFF MEETING

* Team will have free tickets
* Team will decide if they want to use Bevy 100% for website, or build their own
* Discussed KCD logo, which will be ready for use in January
* Edith may not be able to 100% attend in-person, but will help with pre-planning

Action Items
* [ ] Audra to create Bevy chapter for team and add organizers
* [ ] Audra to create email alias
* [ ] Audra to share sponsor prospectus
* [ ] Letter of recommendation for University
* [ ] Audra to create Slack channel

**Comment by AudMonte01** [comment]
JANUARY 8 MEETING NOTES

Venue
* University 100% confirmed (co-working space)
* Free if inclusive of students to freely attend
* Open PUCP in San Miguel, Lima
* Central access, even inside a shopping mall
* 500 max capacity

Call for proposals (CFP)
* Timeline: February 1 open date, and close CFP first week of May. Announce program First week of June 
* Sessionize platform

Marketing efforts
* [ ] Website: Bevy or own domain?
* [ ] Team to decided on logo design (Audra shared raw files of new logo via Slack)

**Comment by AudMonte01** [comment]
MARCH 15 CNCF SYNC

Agenda dates
* Inicio CFP: 18 de marzo
* Cierre CFP: 15 de mayo
* Notificación de elegidos: 01 de junio
* Anuncio de horarios y charlas: 15 de June
* Will announce keynote speakers ahead of agenda

Marketing
* Kiosk in Paris will promote the CFP
* [ ] Audra to add Lima to the community.cncf.io drop-down menu
* [ ] When CFP is launched - Audra to add the global KCD Sessionize list
* [ ] Audra to add Sessionize link to April 5 KubeWeekly newsletter

**Comment by AudMonte01** [comment]
AUGUST 12 RETROSPECTIVE WITH CNCF

Positive Feedback
* Grew very fast on social media and well received by many
* Very few negative feedback from attendees
* All stakeholders seemed to be happy
* Many people were interested in the content
* The event felt like a mini KubeCon for many attendees
* The venue was great in terms of facilities and centralization

Lessons Learned
* Support more beginning speakers as more of mentoring effort
* CNCF to host a more friendly registration tool needed (they used Eventbrite)
* Would like to have more engagement / fun interactive opportunities
* Organizer the volunteers earlier, get to know each other better
* More structure during the event to better coordinate how issues can be handled

Analytics
* Total registered versus total checked in  was 2,500 versus 530 (21%)
-- [ ] Team will send list of opt-ins to kcd@cncf.io to upload as KCD chapter members for future event marketing
* Total speakers with non-male speaker percentage (50 speakers versus 5 women = 10%)
* Total of 5 Gold sponsors and 2 Silver sponsors, and a few media sponsors
-- Broke even with signage, F&B, security & cleaning, and swag adding to the quality of the event. Team still owes taxes
-- $21k USD total to host the event

Final marketing to prolong content
* [ ] Audra to share Transparency Report template with the entire team, in Slack channel. Ideally publish within 2 months of the event
* [ ] The team will send Audra playlist of livestreamed main track, and other sessions, once complete (no deadline).
* The team will take assign a "Contributor" badge to both volunteers and  (https://github.com/cncf/kubernetes-community-days/blob/main/README.md#cncf-support) for more information)
* [ ] Edith is curating a blog post with the team with everyone's perspectives, and will be completed this week, as well as  a volunteer's perspective (separate post)

**Comment by AudMonte01** [comment]
The team created playlists for each room:
* [Main stage](https://youtube.com/playlist?list=PLQ9NNP6FdSnBaSGLG0GUrEGFMl0Kw2Rw7&si=O_ZIYsDlR3YgbDXs)
* [Room p01](https://youtube.com/playlist?list=PLQ9NNP6FdSnDyIEU8lNldGMGW-MdSLmjb&si=R9_lntYsAmWfH6Hn)
* [Room p02](https://youtube.com/playlist?list=PLQ9NNP6FdSnC90ZjQugl6_s0XCMx4rTBT&si=OgoV4vFB0GBC3Nas)

Lightning talks and workshops were not recorded.

**Comment by AudMonte01** [comment]
This ticket/issue is now closed.
