### ISSUE TITLE
KCD Zurich 2024 (June)

### ISSUE THREAD

**Issue by phil-pona** [cncf/kubernetes-community-days#522]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Zürich City | Google Zurich venue confirmed
* [x] Event Date and Time: June 12 (workshops) and 13, 2024
* [x] Expected Number of Attendees 200 (250-300 registrations)
* [x] Event cost per ticket, and if you will have early bird pricing or not: CHF 100-150

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Milena Thalmann, Founder White Rabbit Communications, [milena@whiterabbitcom.ch](mailto:milena@whiterabbitcom.ch)
* [x] Organizer 2: Philipp Meier, Isovalent, Head of Global Ecosystem Partner, [philipp@isovalent.com](mailto:philipp@isovalent.com), @tschabalori
* [x] Organizer 3: Thomas Philipona, tim&koko, Founder, [thomas@tim-koko.ch](mailto:thomas@tim-koko.ch), @tphilipona

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use Sessionize for CFP and to close it at least 6 weeks before the event.
* [ ] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with Audra to make it unique to your KCD.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Google
Red Hat/VSHN
Puzzle ITC
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
FEBRUARY 5 CNCF SYNC

Zurich team to give high-level update
* Sold Out already with sponsors tickets left
* With a waitlist of 20 people
* Looking into new locations for next year to grow event

Sponsorships
* All of the sponsors came back + new ones
* If they come ahead, they will put it toward the cloud native community meetup
* Last year they sponsored 2 KCDs and KubeTrain

Marketing
* Website template has a Sessionize integration
* [ ] Audra to point to CFP in KubeWeekly
* [ ] Audra to share sticker voucher code
* [ ] Team to think about how to use the 10 training exam vouchers CNCF provides

CFP submissions so far
* Just opened, and closes end of March, and so far International speakers
* Natalia, Francisca, and Viktor, and Andreas and headliners are now online

**Comment by AudMonte01** [comment]
CNCF CHECK-IN

Content
* Keynotes: Kate Gamanji and Abdul Sch... former Head of Science of NASA (Swiss)
* 4 one-day workshops, and haven't sold tickets (beginner and advanced on Argo, GO, Cilium, and K8s)
* Google has given the space for free (the day before)
* [CFP closes March 31](https://sessionize.com/kcd-zurich-2024) with 74 submissions
* [ ] Katie to push to Ambassadors and maintainers next week

CNCF Marketing Help: Logo, sponsorships, CFP
* [ ] Audra to push workshops in both marketing committee deck and KubeWeekly newsletter
* 73 on the waitlist (sold out in 40 days)

2025
* Goal 350-400 next year
* Venue is Cinema vs Google

**Comment by AudMonte01** [comment]
MAY 6 CNCF SYNC

Sponsorships - sold out
Waitlist - 100 on the ticket waitlist

Workshops
* Will offer two incentives to book the k8s workshop - video promotion to come out this week
* The Workshops themselves are offered at 1/2 the price

KCD Rejects Meetup
* Half day with roof top networking at the end
* Top 6 speakers from rejected KCD proposals?
* Also offering inexpensive workshops
* Repurposed funds for another event for this one, and recognized those sponsors
* 80 attendee goal, and only 22 tickets

Action Items
* [ ] Audra to send 10 training vouchers to team via email

**Comment by phil-pona** [comment]
Thanks for the update @AudMonte01 

I add a bit more details here:

Positives

* Both events were a success. Rejects was a great way to include all the people on the waiting list to be part of the community as well. The main location's max capacity is 250, which we maxed out
* we were lucky to have volunteers from tim&koko
  * @bliemli track host "The next big thing" room
  * @SarahTimKoko Entrance and track hosts "Sponsorspotlight"
  * @laff0 Entrance and track hosts "Sponsorspotlight"
  * and one paid person to monitor the coatroom 

Lessons Learned

* there is almost no way to make everyone happy concerning food. We had vegetarian, vegan and meat options but still got the feedback, that there was not enough vegan, or not enough meat options and vice versa
* The food queues were too long. This is an issue of the venue, which we will fix the next time.
* The beer taps came a bit too late, so people had to wait
* We need more volunteers and helpers in general so that the three of us can better focus on the event. 

Youtube Playlist: https://www.youtube.com/playlist?list=PLA_kepINgW44U8DyijCPWbRTfJBJ4PsCN

And I'll check with the team for the additional Credly badge and the blog post

**Comment by AudMonte01** [comment]
Thank you @phil-pona! Some post-event marketing I would like to follow-up on after my Slack message is:
* [ ] Thank you for providing the YouTube playlist, we have duplicated it on the CNCF channel and is now amplifying to all our subscribers, but pointing back to your videos
* Credly badges - Your team will design a badge once everyone is back from summer vacation. Will this be for speakers or volunteers? Please [submit here](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) when you are ready and we will assign them for you.
* I shared the [transparency report template](https://www.canva.com/design/DAGNSMIyDnY/bW7_PhdOpnZnYQ1WaaFs7Q/edit?utm_content=DAGNSMIyDnY&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) with all of you. You should have received a notification via email
- [ ] please send to kcd@cncf.io once complete
* Does the team want to write a Blog post about their experience and success over the years?

**Comment by phil-pona** [comment]
@AudMonte01 I've just submitted the KCD Zurich Credly Badge

**Comment by AudMonte01** [comment]
Thank you for submitting the Credly badge form, @phil-pona - I have updated the graphic to include the KCD logo. What do you think about [this new version](https://drive.google.com/file/d/1fk0R2Wr38X3D6QAXPdIcotHAA9EnO1G5/view?usp=drive_link)?

**Comment by phil-pona** [comment]
@AudMonte01 that's awesome and works for us. Thanks

**Comment by AudMonte01** [comment]
Excellent - the6 badges have now been issued.

**Comment by phil-pona** [comment]
Transparency report has been filled out and is in review process now, will send it to kcd@cncf.io as soon as it's reviewed and ready

**Comment by phil-pona** [comment]
Report has been reviewed and sent

**Comment by AudMonte01** [comment]
Excellent - thank you, @phil-pona ! This is now published here https://www.cncf.io/reports/kcd-zurich-2024/ and can also be found on cncf.io/kcds.

Should you wish to write more about your experience with the KCD and point to your transparency report, you can submit a Google doc for review to pr@cncf.io and copy me (audra@cncf.io).

Otherwise, all post-event marketing has been completed from a CNCF point of view. Thank you for being a KCD for two years in a row - we valued the partnership. This issue is now closed.
