### ISSUE TITLE
KCD Praha, Czech & Slovak 2024 (June)

### ISSUE THREAD

**Issue by georg007** [cncf/kubernetes-community-days#525]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [X] Event Location: České vysoké učení technické v Praze Address: Thákurova 9, 160 00 Praha 6
FIT ČVUT: Fakulta informačních technologií ČVUT
* [X] Event Date and Time: 6 - 7 june 2024
* [X] Expected Number of Attendees 500 
* [X] Event cost per ticket, and if you will have early bird pricing or not 90Euro

#### Event type:
* [ ] Virtual
* [X] Hybrid
* [X] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [X] Organizer 1: Juraj Hantak, Conag, CTO, [georg007@gmail.com], CNCF Slack Username: Juraj Hantak
* [X] Organizer 2: Filip Pohronsky, DITEC, TSA, [pohronsky@ditec.sk], CNCF Slack Username: Filip Pohronsky
* [X] Organizer 3: Zdenek Vana, Prusa Research a.s., Cloud DevOps Architect, [vanazde1@gmail.com], CNCF Slack zdenek.vana
* [X] Organizer 4: Tomas Jamrich, Prusa Research a.s platform infrastructure engineer, [tomas.jamrich@lmc.eu],CNCF Slack tomas jamrich
* [X] Organizer 5: Tomas Bocinec, Siemens Healthcare s.r.o., Site reliability engineering, [t.bocinec@gmail.com].
* [X] Organizer 6: Lenka Bocincova, Red Hat, Community Architect, [lenka.bocincova@gmail.com], CNCF Slack Lenka Bocincova

### Terms

* [X] No other Kubernetes Community Day event in same major city (check with past organizers)
* [X] Minimum of 3 organizers from 3 different organizations
* [X] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [X] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [X] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies.
* [X] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [X] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [X] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [ ] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [ ] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [ ] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event. We will use Sessionize at the end of 2023/beginning of 2024.
* [ ] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with Audra to make it unique to your KCD.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
KICK-OFF MEETING

Goal
* Feedback from last year's attendees to host during the week
* Will host 2 days vs 3 (last year)

Sponsorships
* [ ] Audra to share template via Canva with Juraj and Lenka

Content
* CFP to open in January when event codes are ready for sessionize

**Comment by AudMonte01** [comment]
DECEMBER 12 MEETING NOTES

CFP timeline and Sessionize
* Audra to give code to team in January

Audra reviewed the new KCD Logo with the team

Sponsor Prospectus 
* Reviewed PDF
* Audra to updated graphic on page 2 of prospectus
* [ ] team to send Audra final PDF once ready

**Comment by AudMonte01** [comment]
JANUARY 16 MEETING NOTES

CFP is ready to go LIVE but waiting on logo
* [ ] Audra to request design logo for team and give v1 to team for review by this Friday the 19th

Website
* [ ] Audra to look into external streaming platform for conference event type
* [ ] Audra to look into past year's naming and URL construct
* [ ] Audra to add to drop-down list

**Comment by AudMonte01** [comment]
FEBRUARY 13 CNCF SYNC

Content
* CFP has 26 submissions and but are not local (20 speakers)
* 5-10 speakers from the sponsors
* Will inquire with speakers on-site at KubeCon Paris

Bevy
* [ ] Audra to explore front-end maps not showing up in Bevy

**Comment by AudMonte01** [comment]
Hello @georg007, I know we have tried to have a retrospective summary meeting, and one was never booked. Following up here, as it is not too late to discuss post-event happenings. Thank you.
https://calendly.com/audmonte/kcd-retrospective

**Comment by AudMonte01** [comment]
Retrospective Summary w CNCF

Positive Feedback
* It was enjoyable
* Sponsors were satisfied
* Content was great and well-received
* Community is larger in the Czech Republic, and the CNCG helped with attendance
* Big photo wall was well received
* Pushed more money towards Ads (LinkedIn and local promotions)
* Better engagement with social media

Lessons Learned
* Streamed event, and not sure if they want to do it again due to it taking away from in-person numbers
* Communication with the venue was a bit challenging, and setup time was limited (student exams were also happening during the event)
* Completely different than last year

Analytics
* Total registered was 387 versus total checked in of 250 (66%)
* 3 out of 44 speakers were non-male speakers (7%)
* 8 paid sponsors + 5 community partners
-- Came out ahead and are using it for the meetups and for next year's event

Post-event marketing
* Transparency report was [published on July 18](https://www.cncf.io/reports/kcd-czech-slovak-2024/)
* [Video recordings are here](https://www.youtube.com/@kcdczechslovak5840)

2025
* Next time in Bratislava (only because they want to change the opportunity and keep it fair for both Czech & Slovak communities)
* Audra summarized [changes to the program](https://www.cncf.io/blog/2024/08/06/refreshing-the-kcd-program-a-new-chapter-in-community-building/)
* Team will look into local event insurance companies
