### ISSUE TITLE
KCD Moscow 2024 (October)

### ISSUE THREAD

**Issue by timur-tukaev** [cncf/kubernetes-community-days#532]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Russia, Moscow
* [x] Event Date and Time: 17 October, 1-day, 10:00-19:00
* [x] Expected Number of Attendees: 400
* [x] Event cost per ticket, and if you will have early bird pricing or not: $100, we have early bird pricing

#### Event type:
* [ ] Virtual
* [x] Hybrid
* [ ] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
* [x] Organizer 1: Timur Tukaev, Flant, DevRel, timur.tukaev@flant.com, Timur Tukaev
* [x] Organizer 2: Alex Belotserkovskiy, VK Cloud and Tarantool, Evangelist Architect, ahriman@ahriman.ru, Alex Belotserkovskiy
* [x] Organizer 3: Pavel Selivanov, Yandex Cloud, Architect, poselivanov@gmail.com, Pavel Selivanov
* [x] Organizer 4: Timofey Kirillov, Flant, Developer of werf and trdl, timofey.kirillov@flant.com, Timofey Kirillov

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF employee, CNCF ambassador, or CNCF project maintainer. NOTE: An employee of a member company, qualifies. — **_Timur Tukaev, Flant (Flant is a silver member of CNCF)_**
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website. **_— We're waiting for approve from CNCF coordinators_**
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form  **_— We're waiting for approve from CNCF coordinators_**
* [x] Agree to use Sessionize as the Call for Proposals (CFP) platform.
* [x] Agree to get logo creation and approval with and from CNCF. NOTE: a new logo will be created in an effort provide unity, and and official KCD stamp of approval.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io) **_— We're waiting for approve from CNCF coordinators_**
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1: Yandex Cloud
Sponsor 2: VK
Sponsor 3: Flant
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments **_— It's Flant_**
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a LinkedIn profile and/or Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) **_— We're waiting for approve from CNCF coordinators_**

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here (https://docs.google.com/spreadsheets/d/1G66gKtxKVheIOQpp5cN8bsoIcC2b6dh5zrqtaXgcStc/edit).
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
FEBRUARY 13 CNCF SYNC

Venue
* Loft Hall is under discussion
* Attendees and vendors

Fiscal
* Flant can be the fiscal sponsorship managing documents

Sponsor
* [ ] Audra to share sponsorship template with Timur

**Comment by AudMonte01** [comment]
CNCF SYNC

Content
* Today they will send CFP to design team to make a landing page
* Publish CFP next week and market via different telegram chats of different CNCF projects
* Produced their own CFP (platform), and will leave it open for 3 months
* Will have workshops for beginners and advanced

Marketing activities, website and logo
* Team is almost done with visual conception
* [Timepad](https://afisha.timepad.ru/moscow) will be used for registration platform

Sponsorships
* List of potentials sponsors and partners

Other logistics
* Venue will change, but date will not change
* Menus under discussion for breaks
* Flant will be fiscal sponsor, and budget has been created
* A/V company is already contracted. Will record sessions and post on YouTube

**Comment by AudMonte01** [comment]
APRIL 9 CNCF SYNC

Venue change
* still looking for something that can accommodate a sponsor space, have a learning track, and be central to the city (easy to get to)

Website - visual conception
* Shared in Slack channel. Audra gave feedback about K8s helm trademark usage
* Will be a technical launch with CFP this week
* Promotions will start after venue is secured

**Comment by k8tgreenley** [comment]
Closing ticket as event will not move forward
