### ISSUE TITLE
KCD Madrid 2025

### ISSUE THREAD

**Issue by lamadome** [cncf/kubernetes-community-days#539]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: TBD
* [x] Event Date and Time: Postponing request to 2025
* [x] Expected Number of Attendees: 200+
* [x] Event cost per ticket, and if you will have early bird pricing or not: 150 Euro with early bird (subject to change)

#### Event type:
* [ ] Virtual
* [x] Hybrid
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Jona Apelbaum, Wiz, SE Manager, jona.apelbaum@gmail.com,  Fireball
* [x] Organizer 2: Antonio Berben, Solo.io, Principal Solutions Engineer, a.berben.m@gmail.com,  Antonio Berben
* [x] Organizer 3: Eduardo Bonilla Rodriguez, Solo.io, Senior Customer Success Engineer, eduboni97@gmail.com, Edu Bonilla
* [x] Organizer 4: Juan Herrara Utande, SUSE,  Senior Technical Marketing Manager, jherrerautande@gmail.com, Juan Herrara Utande
* [x] Organizer 5: Ricardo Noriega de Soto,  RedHat, Principal SW Engineer, rnoriega@redhat.com, oglok
* [x] Organizer 6: José Ángel de Bustos Pérez, Senior Specialist Solution Architect, Red Hat, [jadebustos@gmail.com](mailto:jadebustos@gmail.com), jadebustos

### Terms

IMPORTANT: These are the terms within the checklist that must be abided by. Note - There are exceptions to these requirements in some jurisdictions due to applicable laws & regulations.

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF employee, CNCF ambassador, or CNCF project maintainer.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use Sessionize as the Call for Proposals (CFP) platform.
* [x] Agree to get logo creation and approval with and from CNCF. NOTE: a new logo will be created in an effort provide unity, and and official KCD stamp of approval.

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a LinkedIn profile and/or Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created: madrid-organizers@kubernetescommunitydays.org 
* [x] Region created in Bevy
* [ ] Added to Bevy header
* [x] CFP code given for Sessionize
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by AudMonte01** [comment]
KICK-OFF MEETING

Venue
* University may not be free, but highly discounted
* Jona's brother-in-law works with the purchasing department to connect the team to use CEU University
* Carlos de Cer University

Timeline
* During the week can be successful (even Tues-Thurs)
* Want to host this event around the same timeline as many KCDs in the EU, but it is not a concern to compete with sponsors, as most companies have a local budget

**Comment by AudMonte01** [comment]
Hi @lamadome - let's schedule another sync next week and touch based on the above items, if you would please find time on my calendar that works for a few of you to attend? https://calendly.com/audmonte/30min

**Comment by AudMonte01** [comment]
APRIL 9 CNCF SYNC

Branding under KCD Spain

Timing and venue: October 10 at University?
* Just need approval from teachers

Sponsorships
* [ ] Juan to add KCD Spain branding as a partner
*[ ] Juan to either create a PR to have the prospectus added [here](https://github.com/cncf/kubernetes-community-days/tree/main/sponsor-resources/open-prospectuses) or share a PDF with Audra

**Comment by antonioberben** [comment]
Hi @AudMonte01 , we added a new member to help with organizing. I cannot edit the issue, though.

José Ángel de Bustos Pérez, Senior Specialist Solution Architect, Red Hat, jadebustos@gmail.com, jadebustos

**Comment by AudMonte01** [comment]
MAY 15 CNCF SYNC

Team will reconvene this week, and email kcd@cncf.io alias about final decision on timing.

**Comment by AudMonte01** [comment]
Thank you for your submission - we are now ready to accept official applications via Survey Monkey. The deadline for submissions will be Wednesday September 11 at 11:59pm Pacific Daylight Time. More information and the application can be found via https://www.cncf.io/kcds/application/.

This GitHub issue is now closed. Should your KCD be accepted into the 2025 program, a core CNCF staff member will open a new issue for program tracking and transparency.
