### ISSUE TITLE
KCD Shanghai 2024 (April)

### ISSUE THREAD

**Issue by Iceber** [cncf/kubernetes-community-days#542]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Tech Campus Shanghai, China
* [x] Event Date and Time: 4.20
* [x] Expected Number of Attendees: 200+
* [x] Event cost per ticket, and if you will have early bird pricing or not: free
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Zhenyu Zheng, openEuler, Community Operating Manager, zhengzhenyu@openeuler.sh, Zhengzhenyu
* [x] Organizer 2: Kevin Wang, HUAWEICLOUD, Technical Expert, CNCF TOC member, Founder&Maintainer of CNCF KubeEdge, Volcano, Kamada projects, wangzefeng@huawei.com, kevin-wangzefeng
* [x] Organizer 3: Iceber Gu, DaoCloud, Cloud Native R&D Engineer, CNCF Ambassador, LFAPAC OpenSource Evangelist, Clusterpedia Founder&Containerd Maintainer, caiwei95@hotmail.com, Iceber Gu
* [x] Organizer 4: Betty Zheng, AWS, Senior Developer Advocate, betzheng@amazon.com, Betty zheng
* [x] Organizer 5: Pan Yuxuan, China Mobile Cloud,Technical Expert, Leader of China Mobile Cloud's Cloud Native Team, Kosmos Founder, panyuxuan@cmss.chinamobile.com, Pan Yuxuan
* [x] Organizer 6: Pengcheng Tang, Volcano Engine, Software Architect, Katalyst maintainer, tangpengcheng.tangpc@bytedance.com, Pengcheng Tang

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] If there is already a KCD in your country, you agree to schedule your KCD at least two months apart from that pre-planned KCD.
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF employee, CNCF ambassador, or CNCF project maintainer.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
**openEuler**
**China Mobile Cloud**
**ByteDance**
**AWS**
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a WeChat handle specific to your KCD event

### Getting started checklist for CNCF:
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CNCF China team introduced for marketing amplification, and review of program

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
Excellent! Let us have a kick-off meeting, if someone would please schedule with me at 8:00 or 9:00 in your morning on an upcoming Tuesday?

**Comment by Iceber** [comment]
February 13th, right? I talked to the other organizers. We can meet at 9:00.

**Comment by AudMonte01** [comment]
FEBRUARY 20 KICK-OFF CALL WITH CNCF

Reviewed event details
* Free, in-person event and will have recordings
* Content will be in Chinese
* Currently arranged sponsors (100k RMBs) and already have the venue

Open source insights
* Many cloud native developers
* Many open source meetups in the area
* A big open source and AI conference in March

Marketing
* Each organizer has over 10k followers on WeChat

Actions
* [x] Audra to create Slack channel for collaboration with CNCF and resources
* [ ] Audra to create Bevy chapter for team and add members to edit directly
* [ ] team to create WeChat group

**Comment by Iceber** [comment]
60+ topics were submitted, and we've finalized the jury's scores and recommendations.
We will announce the agenda and open registration this week or next Monday and Tuesday.

**Comment by AudMonte01** [comment]
Thank you, @Iceber - please send the final agenda for review to kcd@cncf.io ahead of publishing.

**Comment by AudMonte01** [comment]
Post-event analytics
* 700 registrations versus 300 checked-in = 43% attendance rate
* 6 out of 48 speakers were non-male/men = 13% diversity rate
* [Transparency report can be found here](https://www.canva.com/design/DAF3bzvDntM/S6qrLmCVqw8X3HN_14U26Q/view?)
