### ISSUE TITLE
KCD Kerala 2025

### ISSUE THREAD

**Issue by humblec** [cncf/kubernetes-community-days#544]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: 
* [x] Event Date and Time: Feb 2025
* [x] Expected Number of Attendees: 1000
* [x] Event cost per ticket, and if you will have early bird pricing or not : Early Bird pricing will be there. Yet to decide the pricing.

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify who will be the CFP admin, as well as the finanical officer)

* [x] **Lead organizer and Financial Officer**:
    Humble Chirammal, VMware, Staff Engineer, humble.devassy@gmail.com

* [x] Organizer 2: ( CFP Admin)
    Sreejith Anujan, Red Hat, Senior Consultant, sreejithanujan@gmail.com 

* [x] Organizer 3: Dhanesh, Salescode, Co-founder & Technology Head , dhaneeshTNair@gmail.com

* [x] Organizer 4: Dipu Devarajan, KnownHost, Support Supervisor,  dipudevarajan@gmail.com

* [x] Event team:  Ranjith Rajaram,  Solutions Architect,  r.ranjithrajaram@gmail.com ,   
* [x] Event team:  Ashik J.M,  Engineering Manager, Cloudera, ashikjm@gmail.com 
* [x] Event team:  Rakesh Radhakrishnan, Principal SE at Microsoft, ASF Member, rakeshr.cncf@gmail.com
* [x] Event team:  Needu D , NeST Digital, Lead Engineer, 
* [x] Event team:  Safeer M, FlipKart, Sr. SRE , safeerm@gmail.com,
* [x] Event team:  Prasad Krishnan,  DevOps Architect, Jaumo, prasadzone@gmail.com
* [x] Event team:  Najmuddin , Technical Solutions Consultant, HP, najum.c@gmail.com 
* [x] Event team:  Jijesh Kalliyat, Technical Account Manager,  jkalliyat@gmail.com 
### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF member employee, CNCF ambassador, or CNCF project maintainer
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer (at minimum) 3 complimentary tickets to increase diversity for the event
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website
* [x] Agree to use SM Apply for CFP and to close it at least 6 weeks before the event

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Red Hat
VMware
Sponsor 3
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments: 
Fiscal sponsor: Ambersand Inc.

* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used) : @KCDKerala
* [x] Provided CNCF access to all event social handles

### Getting started checklist for CNCF:
* [x] Organizer email alias has been created
* [x] Region created in Bevy
* [x] Added to Bevy header
* [ ] CFP created in SMapply
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1bvCiyyDut1seSnBE6pzVevcJkXLeWbxbncvhFsyY8PI/edit#gid=1736864170) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by AudMonte01** [comment]
NOTE: The earliest approval for this KCD will be May 2024

**Comment by libreminds** [comment]
Hi @AudMonte01 , Would this issue auto converted to survey monkey application? if not, can you please kindly share the survey monkey link for the application?

**Comment by AudMonte01** [comment]
Thank you for your submission - we are now ready to accept official applications via Survey Monkey. The deadline for submissions will be Wednesday September 11 at 11:59pm Pacific Daylight Time. More information and the application can be found via https://www.cncf.io/kcds/application/.

This GitHub issue is now closed. Should your KCD be accepted into the 2025 program, a core CNCF staff member will open a new issue for program tracking and transparency.
