### ISSUE TITLE
KCD Finland 2025

### ISSUE THREAD

**Issue by luxas** [cncf/kubernetes-community-days#555]
# KCD Organizer Checklist

Adding a placeholder for a KCD Finland we started planning during KubeCon last week 😄 . Let's make it happen!
We'll start working on the checklists here during the spring.

### Event Details
* [ ] Event Location: Helsinki, most likely Helsinki Congress Paasitorni (https://maps.app.goo.gl/6qujWoqsqebVL3su6)
* [ ] Event Date and Time: TBD, but most likely end of January or beginning of February 2025
* [ ] Expected Number of Attendees: TBD, but maybe around 150-300
* [ ] Event cost per ticket, and if you will have early bird pricing or not: TBD, but we'd like to have at least student/diversity ticket

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person (hopefully we can record the talks, but TBD)

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer (TODO, not yet done)
* [ ] Lucas Käldström @luxas, luxas labs Ltd., CNCF Ambassador, lucas@luxaslabs.com, luxas on CNCF Slack
* [ ] Erno Kurki, Google, Customer Engineer, TBA, TBA
* [ ] Maryam Tavakkoli @MaryamTavakkoli, RELEX Solutions, Senior Cloud Engineer / CNCF Ambassador, TBA, Maryam Tavakkoli on CNCF Slack
* [ ] Oliver Joggerst @ojoggerst, OpenText, Sr. Manager Software Engineering, TBA, Oliver Joggerst on CNCF Slack
* [ ] Gergely Csatári @CsatariGergely, Nokia, Senior Specialist, TBA, csatari on CNCF Slack
* [ ] Anton Lindholm @linant, Walkbase, Software Developer, TBA, LinAnt on CNCF Slack
* [ ] Toni Ylenius @toddnni, OP Financial Group, Expert Developer, TBA, Toni Ylenius on CNCF Slack
* [ ] Annie Talvasto @AnnieTalvasto, VSHN, CMO, TBA, Annie Talvasto on CNCF Slack
* [ ] Kashif Khan @kashifest, Ericsson, Product Owner and Master Developer, TBA, Kashif Khan on CNCF Slack
* [ ] Muhammad Ather Fayyaz, OpenText, Lead Platform Engineer, TBA, TBA

### Terms

IMPORTANT: These are the terms within the checklist that must be abided by. Note - There are exceptions to these requirements in some jurisdictions due to applicable laws & regulations.

* [ ] No other Kubernetes Community Day event in same major city (check with past organizers)
* [ ] Minimum of 3 organizers from 3 different organizations
* [ ] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [ ] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [ ] At least one organizer is a CNCF employee, CNCF ambassador, or CNCF project maintainer.
* [ ] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [ ] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [ ] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [ ] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [ ] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [ ] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [ ] Agree to use Sessionize as the Call for Proposals (CFP) platform.
* [ ] Agree to get logo creation and approval with and from CNCF. NOTE: a new logo will be created in an effort provide unity, and and official KCD stamp of approval.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a LinkedIn profile and/or Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP code given for Sessionize
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1pSnKB7KkMthTdo7Hb-Xm-MN7YUoiV88-Pa63xeVUAcA/edit?usp=sharing) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by lentzi90** [comment]
Great initiative! I'm in, let's make it happen! :star_struck:

**Comment by AudMonte01** [comment]
Hello @luxas -  Thank you for submitting this issue, and your interest in hosting a KCD. While are excited to see a KCD in Finland, please do not confirm anything, sell sponsorships, sign contracts, until our team has met with you, reviewed and  approved this event.

**Comment by luxas** [comment]
Cool. We're planning to meet with the organizers in early August, we could schedule a meeting with you some week(s) after that 👍

**Comment by AudMonte01** [comment]
We are pending an announcement for the updates on the KCD program, so once that has released, then we can start reviewing current issues, and moving forward with approvals.

Here are two KCD organizer newsletters for reference
* [April](https://github.com/cncf/kubernetes-community-days/blob/main/newsletter-updates/KCD%20Monthly%20Digest%20-%20April%2026%2C%202024.pdf)
* [June](https://github.com/cncf/kubernetes-community-days/blob/main/newsletter-updates/KCD%20Monthly%20Digest%20-%20June%2015%2C%202024.pdf)

**Comment by AudMonte01** [comment]
Thank you for your submission - we are now ready to accept official applications via [an official application form](https://www.cncf.io/kcds/application/). The deadline for submissions will be Wednesday September 11 at 11:59pm Pacific Daylight Time. More information and the application can be found via https://www.cncf.io/kcds/application/.

This GitHub issue is now closed. Should your KCD be accepted into the 2025 program, a core CNCF staff member will open a new issue for program tracking and transparency.
