### ISSUE TITLE
KCD HongKong 2024

### ISSUE THREAD

**Issue by huanwei** [cncf/kubernetes-community-days#565]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Hong Kong Science and Technology Parks
* [x] Event Date and Time: 15 June 2024 13:30-17:30
* [x] Expected Number of Attendees: 80
* [x] Event cost per ticket, and if you will have early bird pricing or not: Free
#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person
#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the finanical officer:
* [x] Organizer 1: Huan Wei, HangZhou HarmonyCloud Technologies Co., Ltd, Senior Director, CNCF Ambassador, CNCF KubeEdge TSC member, huan@harmonycloud.cn, U020RF3PNLV
* [x] Organizer 2: Yang Che, Alibaba Cloud, Fluid maintainer, cheyang.cy@alibaba-inc.com, U02ADHXFRSP
* [x] Organizer 3: Kai Zhang, Alibaba Cloud Intelligence, Senior Staff Engineer, wsxiaozhang@gmail.com, U06UWN37TR9
* [x] Organizer 4: Qinghao Meng, H3C, Senior Cloud Engineer, 1018689967@qq.com

### Terms

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] If there is already a KCD in your country, you agree to schedule your KCD at least two months apart from that pre-planned KCD.
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [ ] Each organizer lives in or just outside of the KCD location
* [x] At least one organizer is a CNCF employee, CNCF ambassador, or CNCF project maintainer.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All inquiries / communication to come via GitHub (comment under your KCD issue) for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form

### Getting started checklist for organizers

* [x] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [x] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1: HangZhou HarmonyCloud Technologies Co., Ltd (杭州谐云科技有限公司)
Sponsor 2: Alibaba Cloud
Sponsor 3: H3C
* [x] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [x] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [x] Create a WeChat handle specific to your KCD event

### Getting started checklist for CNCF:
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CNCF China team introduced for marketing amplification, and review of program

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1pSnKB7KkMthTdo7Hb-Xm-MN7YUoiV88-Pa63xeVUAcA/edit?usp=sharing) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizer:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube

**Comment by huanwei** [comment]
ping @AudMonte01

**Comment by AudMonte01** [comment]
Hello @huanwei - all KCD approvals are currently on hold due to the process being restructured on the CNCF side. I hope to have more information about these changes at the end of June / early July.

Reference: https://github.com/cncf/kubernetes-community-days/blob/main/newsletter-updates/KCD%20Monthly%20Digest%20-%20March%2029%2C%202024.pdf

**Comment by AudMonte01** [comment]
This ticket can be re-opened for 2025 since the requested date is tomorrow, and I believe this event is proceeding without the KCD brand given KCD approvals were on hold when this issue was created.
