### ISSUE TITLE
KCD Hanoi 2024

### ISSUE THREAD

**Issue by khanhtc1202** [cncf/kubernetes-community-days#572]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: [Pullman Hanoi](https://pullman-hanoi.com/)
* [x] Event Date and Time: TBD
* [x] Expected Number of Attendees: 500
* [x] Event cost per ticket, and if you will have early bird pricing or not: 20$ early bird / 30$ regular / 40$ late-stage

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
* [x] Organizer 1: Nguyễn Trọng Vĩnh, Viettel, Cloud Engineer, tovin07@gmail.com, Nguyễn Trọng Vĩnh - Tovin Seven
* [x] Organizer 2: Khanh Tran, CyberAgent, Software Engineer, khanhtc1202@gmail.com, khanhtc1202
* [x] Organizer 3: Tuyền Nguyễn, FPT Software, Data Engineer, tuyendev96@gmail.com

### Terms

IMPORTANT: These are the terms within the checklist that must be abided by. Note - There are exceptions to these requirements in some jurisdictions due to applicable laws & regulations.

* [x] No other Kubernetes Community Day event in same major city (check with past organizers)
* [x] Minimum of 3 organizers from 3 different organizations
* [x] Every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Each organizer lives within the KCD city or just outside of it. For small countries, the organizers can live within the region, but must be able to easily travel to the KCD if it were in-person.
* [x] At least one organizer is a CNCF employee, CNCF ambassador, or CNCF project maintainer.
* [x] All organizers agree to follow the event guidelines and CNCF Code of Conduct
* [x] All organizer inquiries / communication for CNCF must be summarized via GitHub (comment under your KCD issue) for easy tracking
* [ ] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Share the sponsor prospectus with CNCF via your GitHub issue, and link it on your website.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, one culture, or from 1 or 2 of the same company). [Here are some tips on how to create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [ ] Agree to use Cloud Native Community Groups for registration, scheduling, and event website. If using a platform outside of Bevy, organizers must provide CNCF with a full list of attendees.
-- Regardless of your platform choice, please use [these questions](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=sharing) to create your registration form
* [x] Agree to use Sessionize as the Call for Proposals (CFP) platform.
* [x] Agree to get logo creation and approval with and from CNCF. NOTE: a new logo will be created in an effort provide unity, and and official KCD stamp of approval.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
Sponsor 1
Sponsor 2
Sponsor 3
* [ ] Identified fiscal sponsor that can accept payments such as from sponsorships and pay out expenses
Fiscal sponsor that will accept payments
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a LinkedIn profile and/or Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header
* [ ] CFP code given for Sessionize
* [ ] Marketing Plan shared

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1pSnKB7KkMthTdo7Hb-Xm-MN7YUoiV88-Pa63xeVUAcA/edit?usp=sharing) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().
* [ ] To assure you have a diverse lineup, you are required to send a copy of your program to kcd@cncf.io before you publish it.

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule post mortem meeting
* [ ] Send CNCF videos to be uploaded to YouTube
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD

### Post event checklist for CNCF:
* [ ] Removed from Bevy header
* [ ] CFP deactivated
* [ ] Upload videos to YouTube
* [ ] Transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by khanhtc1202** [comment]
cc @tovin07

**Comment by tovin07** [comment]
Thank @khanhtc1202 for submitting this. This event will be the first KCD in Vietnam.

**Comment by AudMonte01** [comment]
The timing of this is declined, as it is too close to [KubeCon + CloudNativeCon China happening August 21-23](https://events.linuxfoundation.org/kubecon-cloudnativecon-open-source-summit-ai-dev-china/).

**Comment by khanhtc1202** [comment]
Hi @AudMonte01, thanks for quick reply. I read the term in readme and I think the point you mentioned here is

> Each KCD must consider having their event at least 2 months apart from other pre-planned KCDs within a 2-hour flight away happening in the same language, unless otherwise approved by CNCF. Other events that should be also considered for this are small 1-2 day summits hosted by the CNCF or the Linux Foundation. Have a look at the events calendar to assure your KCD will not compete with another events sponsorships or speakers. Insight into KCDs not yet LIVE but in the planning phases will live in the KCD GitHub issues.

For the request hosting KCD in Hanoi this time, I think we don't violate this term since
- The term mentioned "other pre-planned KCDs" while we're talking about KubeCon
- The KCD in Hanoi and KubeCon Hongkong do not have the same language. KCD Hanoi main language would be vietnamese and audiences are mostly the vietnamese used people.
- Hanoi and Hongkong locations are over 2-hour flight away (minor point)

Also, Chapters in Vietnam (including Hanoi and Ho Chi Minh City) have been organizing small meetup events for a while now and the community wants to organize a larger scale event. We found it possible to co-host with the OpenInfra community in a joint event. Based on the scale of previous events successfully organized by the OpenInfra community in Vietnam, we think the appropriate scale for a co-organized event between the OpenInfra community and Cloud Native should be KCD + OpenInfra Day. It would be quite difficult to actually successfully organize an independent KCD event right now, so the team organizer wants to take advantage of this opportunity to cooperate with the OpenInfra community in Vietnam. Please share your thought or further guideline for us under this condition, thank you.

**Comment by AudMonte01** [comment]
Thank you for your diligence and interest.

Please also take into consideration the following factors:
* "Other events that should be also considered for this are small 1-2 day summits hosted by the CNCF or the Linux Foundation" like KubeDay Japan that attracts an international audience with talks provided in English. This event is hosted on August 27.
* Regardless of the above-mentioned factors, [all KCD approvals have been on hold since March](https://github.com/cncf/kubernetes-community-days/blob/main/newsletter-updates/KCD%20Monthly%20Digest%20-%20March%2029%2C%202024.pdf), so there are many who have submitted issues long before you that have yet to be approved because of this.

Kind regards,
Audra

**Comment by AudMonte01** [comment]
Following up here for the transparency trail. Per our discussion on Slack, @khanhtc1202, and with clarification:

One of the new standards newly implemented while the KCD program was on pause, is that no KCD can be within 2 months of the same region KubeCon (region being Asia). [See first bullet point here](https://github.com/cncf/kubernetes-community-days/blob/main/README.md#terms).

We ask that you either move this event to November, or if you must be co-located to the Open Infra Day, then naming it "Cloud Native Day Vietnam", but this can only be a half-day of content, and should be attached to your new Hanoi chapter as a meetup.

**Comment by khanhtc1202** [comment]
Hi @AudMonte01 - sorry for the late reply 🙏 The organizer team agreed with the option to use Cloud Native Day this time in a collaboration event per your advice. We will withdraw this application for KCD Hanoi 2024 and try opening another for 2025 later. Again, thank you so much for the support and advice 😄

**Comment by AudMonte01** [comment]
Hello @khanhtc1202 - in case you missed it, the KCD 2.0 refresh launched on August 5. [You can read more here](https://www.cncf.io/blog/2024/08/06/refreshing-the-kcd-program-a-new-chapter-in-community-building/).

[Applications are open until September 10 your time](https://www.cncf.io/kcds/application/).
