### ISSUE TITLE
KCD Ahmedabad 2025

### ISSUE THREAD

**Issue by sshiv5768** [cncf/kubernetes-community-days#575]
# KCD Organizer Checklist
Please fill in information, organizers, and sponsors as you assemble them, and then make a new comment when this application is ready for review.

### Event Details
* [x] Event Location: Ahmedabad, Gujarat, India
* [x] Event Date and Time: September/November 2025 (Considering any of the months)
* [x] Expected number of attendees (400+)
* [x] Event cost per ticket, and Early bird tickets will be there. (Tickets pricing are yet not decided.)

#### Event type:
* [ ] Virtual
* [ ] Hybrid
* [x] In person

#### Organizers Details (identify at least 3 organizers). Designate who will be the CFP admin, as well as the financial officer:
* [x] Organizer 1: Shivlal Sharma, OpenXcell, DevOps Engineer, sshivlal9601@gmail.com, shivlalsharma
* [x] Organizer 2: Dharmit Shah, SUSE, Senior Software Engineer, shahdharmit@gmail.com, dharmitshah

### Terms

IMPORTANT: These are the terms within the checklist that must be abided by. Note - There are exceptions to these requirements in some jurisdictions due to applicable laws & regulations.

* [x] Agree your KCD will attract no more than 500 people, and cap your tickets at this amount, which includes organizers, speakers, and sponsors.
* [x] Confirm there are no other KCDs in same major city (check with past organizers)
* [x] Confirm your event at least 2 months apart from other pre-planned KCDs within a 2-hour flight away happening in the same language, unless otherwise approved by CNCF. Other events to be considered are any event held by CNCF or Linux Foundation. Have a look at the [events calendar](https://www.cncf.io/events/) to assure your KCD will not compete with another events sponsorships or speakers. Insight into KCDs not yet LIVE but in the planning phases will live in the [KCD GitHub issues](https://github.com/cncf/kubernetes-community-days/issues).
* [x] Confirm you have a minimum of 3 organizers from 3 different organizations
* [x] Confirm every organizer has an account on [Cloud Native Community Groups](https://community.cncf.io/)
* [x] Confirm the majority of organizers must live in, or just outside of the KCD location
* [x] Confirm at least one organizer is a CNCF ambassador OR CNCF project maintainer
* [x] Confirm all organizers agree to follow the event guidelines and [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)
* [x] All inquiries / communication must at least be summarized, if not initially coming via your GitHub issue for easy tracking
* [x] All organizers have taken [Inclusive Open Source Community Orientation (LFC102)](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
* [x] Agree to use [the new KCD logo](https://drive.google.com/file/d/1jU_DkKTVUzimvhUfBqw8ZHfgZShov0Md/view?usp=drive_link) and work with a CNCF core program manager to make it unique to your KCD.
* [x] Agree to offer at least 3 complimentary tickets to increase diversity for the event
* [x] Agree to share the sponsor prospectus with CNCF by linking it in your GitHub issue and on your website.
* [x] Agree to use Sessionize for CFP and to close it at least 8 weeks before the event, and launch the agenda at least 6 weeks prior to your event. CNCF will provide an event code so Sessionize is free to use if you are charging an event fee.
* [x] Agree to ensure the final program schedule is diverse (e.g., not all speakers of one gender, culture or company). [Here is how you can create a diverse lineup.](https://docs.google.com/presentation/d/1fzT_BdavVKh3mnxxU-PBWyJq9JUfasKwHqekkbYVbw8/edit#slide=id.g56245ab439_0_106)
* [x] Agree to submit your final lineup to kcd@cncf.io for review, prior to publishing it
* [x] Agree to use the designated CNCF registration platform, or have opt-in lagnuage for attendees to agree for CNCF to contact them about future events. [KCD registration questions can be found here](https://docs.google.com/spreadsheets/d/1OEoVQ8Y3eQmEEJeT2abhNOkYIkyk8nAVjebNFvKMTQQ/edit?usp=drive_link) which also helps populate your transparency report.
* [x] Agree to produce a transparency report after your KCD. CNCF will provide a editable copy of [this Canva template](https://www.canva.com/design/DAFhDHqyNBw/H2uJJV_hDX7Ln_R_IGpWkg/edit) for guidance.

### Getting started checklist for organizers

* [ ] Schedule monthly check-ins with KCD Core Organizer(s) (kcd@cncf.io)
* [ ] Identified fiscal entity that can accept payments such as from sponsorships, to pay out expenses, manage income from ticket sales
* [ ] Minimum of 3 sponsors committed (not required for virtual only events)
-- Sponsor 1
-- Sponsor 2
-- Sponsor 3
* [ ] Added usernames for [CNCF Slack](https://slack.cncf.io/) for all organizers so that we can add you to the #kcd-organizers channel
* [ ] Create a LinkedIn profile and/or Twitter handle specific to your KCD event (except for countries like China and Korea where Twitter is not used)

### Getting started checklist for CNCF:
* [ ] Organizer email alias has been created
* [ ] Region created in Bevy
* [ ] Added to Bevy header once event is created and published by organizers
* [ ] Give organizers event code given for Sessionize (CFP)
* [ ] Share marketing plan and highlight CNCF marketing support

### Organizer Planning Timeline
* [ ] Make a copy of [this timeline](https://docs.google.com/spreadsheets/d/1pSnKB7KkMthTdo7Hb-Xm-MN7YUoiV88-Pa63xeVUAcA/edit?usp=sharing) based on whether your event is In-person, Hybrid, or Virtual and link your own spreadsheet here ().

### Post event checklist for Organizers:
* [ ] Send CNCF event analytics
* [ ] Schedule restrospective meeting with team, and then a sumamry with CNCF
* [ ] Send CNCF videos to be uploaded to YouTube (if you chose to record them)
* [ ] Link videos from YouTube to event page
* [ ] Post event survey sent out
* [ ] Fill out [Credly badge request form](https://docs.google.com/forms/d/e/1FAIpQLSex2EhkCNysmK7svQEVeaOlqpsH0fSBe6qoOePRw_WGajZnTw/viewform) for 1 badge per KCD (if desired by organizers for speakers, or volunteers)
* [ ] Post-event blog post by organizers (optional)

### Post event checklist for CNCF:
* [ ] Remove from Bevy header
* [ ] Copy YouTube playlist (if there is one) to amplify to CNCF channel subscribers
* [ ] Publish transparency report and YouTube playlist (if there is one) linked from [cncf.io/kcds](https://www.cncf.io/kcds/)
* [ ] Bevy page marked as dormant

**Comment by sshiv5768** [comment]
Adding @dharm1t into the conversation.

**Comment by AudMonte01** [comment]
Thank you for your submission - we are now ready to accept official applications via Survey Monkey. The deadline for submissions will be Wednesday September 11 at 11:59pm Pacific Daylight Time. More information and the application can be found via https://www.cncf.io/kcds/application/.

This GitHub issue is now closed. Should your KCD be accepted into the 2025 program, a core CNCF staff member will open a new issue for program tracking and transparency.
