### ISSUE TITLE
[Organizer Request] Add Ayesha Yege

### ISSUE THREAD

**Issue by Ayege** [cncf/kubernetes-community-days#589]
### Name of KCD chapter inquiring about

CNCF Santo Domingo

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

I’m Ayesha Yege, a passionate software engineer and technology enthusiast with a strong focus on backend development, cloud infrastructure, and DevOps. I specialize in building scalable applications using modern technologies like .NET, EF Core, Docker, Kubernetes, and cloud services like Azure and AWS.

With a diverse background in software development, I’ve successfully contributed to various projects ranging from API development to cloud-native architectures. I thrive in fast-paced environments, continuously learning new tools and techniques to optimize workflows and deliver high-quality solutions.

I’m also an advocate for open-source contributions and community engagement. I’m actively involved in the CNCF community and excited about sharing knowledge, mentoring others, and fostering collaboration among developers worldwide.

-Name: Ayesha Yege
-Email: yegeayesha@gmail.com
-Company: Sigma Petroleum
-GitHub URL: https://github.com/Ayege
-LinkedIn URL: https://www.linkedin.com/in/ayesha-yege/
-Community Profile URL: https://community.cncf.io/u/m893kc/

### Tell us why you want to be added or removed from the KCD chapter

As a woman in STEM, I am passionate about promoting diversity and inclusivity in the technology community. I believe that fostering a more diverse and representative community can spark innovation, new perspectives, and a stronger support system for underrepresented groups. By joining the CNCF Santo Domingo chapter as an organizer, I aim to encourage more women and diverse individuals to engage with cloud-native technologies, contribute to open-source projects, and pursue careers in tech.

Being involved in this community is important to me because I’ve seen firsthand the impact that mentorship, community engagement, and knowledge sharing can have on individuals who might otherwise feel isolated in this field. I hope to inspire others by showing that gender, background, or circumstances should not be a barrier to success in tech.

With my experience in cloud-native development and active involvement in various technical communities, I am eager to contribute to the CNCF Santo Domingo chapter by organizing events, workshops, and discussions that champion diversity and encourage collaboration among all members of the tech ecosystem.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides/lives

- [x] I confirm I am local to or live near the city of the above-proposed KCD (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from NAME company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree to support the main content of the KCD remaining vendor-nuetral (do not mark if irrelevent to request)

### Remain an active organizer

- [x] I understand that in order to be considered a KCD organizer and get recognition, I need to attend the majority of the planning meetings. (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your KCD lineup/agenda

- [x] I will make an effort recruit diverse speakers in the KCD event agenda. (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @Ayege - please move this to the CNCG GitHub Repository for community group chapters. You [can submit here\(https://github.com/cncf/communitygroups/issues/new?template=organizer-request.yml). I will close this ticket in the KCD repository.
