### ISSUE TITLE
[Organizer Request] Add or Remove Organizer Name

### ISSUE THREAD

**Issue by khareyash05** [cncf/kubernetes-community-days#596]
### Name of KCD chapter inquiring about

CNCG Noida

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Yash Khare, khareyash05@gmail.com, Keploy, www.github.com/khareyash05, www.linkedin.com/khareyash05, Yash Khare ,  https://community.cncf.io/u/mbpddn

### Tell us why you want to be added or removed from the KCD chapter

I, Yash Khare would like to be added as a co-organizer for CNCG Noida as I see tremendous potential in the Cloud Native space to drive the innovation channel. I will bring in my technical as well as community knowledge to the Group which might be helpful while organizing events. I will also bring my network which might benefit the quality of technical space CNCG Noida is building.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides/lives

- [x] I confirm I am local to or live near the city of the above-proposed KCD (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from Keploy which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree to support the main content of the KCD remaining vendor-nuetral (do not mark if irrelevent to request)

### Remain an active organizer

- [x] I understand that in order to be considered a KCD organizer and get recognition, I need to attend the majority of the planning meetings. (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your KCD lineup/agenda

- [x] I will make an effort recruit diverse speakers in the KCD event agenda. (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello - create an [organizer issue in the CNCG GitHub repository](https://github.com/cncf/communitygroups/issues/new?template=organizer-request.yml). Right now, this is in the KCD repo. Thank you, and kind regards.

~ Audra
