### ISSUE TITLE
[Organizer Request] Add another organizer

### ISSUE THREAD

**Issue by mercadoalex** [cncf/kubernetes-community-days#601]
### Name of KCD chapter inquiring about

kCD Guadalajara

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

Alejandro Mercado Peña, Mexico City, Sr.DevOps Automation Platform Engineer at CapitalOne.
mercadoalex@gmail.com
https://www.linkedin.com/in/alexmarket/
would love  to be part of the organizer' teams
Rodolfo, Victor or Domix can give more references about me if needed :-)

### Tell us why you want to be added or removed from the KCD chapter

I have been involve in the community for several years, as contributor and speaker.
Use K8s as a daily basis and like to communicate , and learn of course.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides/lives

- [x] I confirm I am local to or live near the city of the above-proposed KCD (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [ ] I come from NAME company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree to support the main content of the KCD remaining vendor-nuetral (do not mark if irrelevent to request)

### Remain an active organizer

- [x] I understand that in order to be considered a KCD organizer and get recognition, I need to attend the majority of the planning meetings. (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your KCD lineup/agenda

- [x] I will make an effort recruit diverse speakers in the KCD event agenda. (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Thank you, @mercadoalex for submitting this. As you know, this has been approved, and I have added you to the KCD Guadalajara GitHub issue. I have also added you to the chapter as an organizer.

Please add a headshot image to your community.cncf.io profile, as it will be forward-facing on the KCD website.

You should have also just received an automated welcome email from me. :-)
