### ISSUE TITLE
[Organizer Request] Add Hemant Rathore organizer CNCG Noida

### ISSUE THREAD

**Issue by hmntrathore** [cncf/kubernetes-community-days#602]
### Name of KCD chapter inquiring about

CNCG Noida

### Tell us about yourself. List your name, email, company, GitHub URL, LinkedIn URL, and CNCF Slack workspace name (or if you need to be invited), and a required profile link on community.cncf.io

As a Technical Specialist focused on Digital and App Innovation, I help customers build intelligent, modern digital applications by leveraging microservices, Kubernetes, and advanced architecture patterns. I’m dedicated to enhancing developer productivity and optimizing DevOps practices, with deep expertise in GitHub copilots.

I have a passion for integrating generative AI and large language models (LLMs) into applications, driving smarter, more efficient solutions. By utilizing cutting-edge AI technologies, I enable businesses to create intelligent applications that deliver enhanced user experiences, automate complex workflows, and extract valuable insights from data.

Passionate about brainstorming, experimenting, and pushing boundaries, I consistently deliver innovative solutions in Azure, AI, and DevOps. My commitment is to stay at the forefront of technology, helping organizations unlock their potential through cutting-edge digital solutions.

https://www.linkedin.com/in/hmntrathore/
https://community.cncf.io/u/m6bnxm/#/about

### Tell us why you want to be added or removed from the KCD chapter

I have been actively engaged with the CNCG community for over a year, contributing to organizing various events and participating as a speaker. I deeply value the passion, collaboration, and shared learning within this community. Now, I am eager to take my involvement to the next level by officially supporting and helping to grow the community as part of the KCD chapter.

### Code of Conduct

- [x] I agree to follow the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md)

### Where organizer resides/lives

- [x] I confirm I am local to or live near the city of the above-proposed KCD (do not mark if irrelevent to request)

### Organizers companies/affiliations

- [x] I come from NAME company which is differing from that of the current organizers (do not mark if irrelevent to request)

### Inclusive

- [x] I agree. To assure this, I have recently completed the [Inclusive Open Source Community Orientation (LFC102) course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/) (do not mark if irrelevent to request)

### Vendor Neutral

- [x] I have read what [vendor-nuetrality means](https://contribute.cncf.io/maintainers/community/vendor-neutrality/), and I agree to support the main content of the KCD remaining vendor-nuetral (do not mark if irrelevent to request)

### Remain an active organizer

- [x] I understand that in order to be considered a KCD organizer and get recognition, I need to attend the majority of the planning meetings. (do not mark if irrelevent to request)

### Aim to have a diverse representation of speakers in your KCD lineup/agenda

- [x] I will make an effort recruit diverse speakers in the KCD event agenda. (do not mark if irrelevent to request)

**Comment by AudMonte01** [comment]
Hello @hmntrathore - please submit this via the [Cloud Native Community Group repository here](https://github.com/cncf/communitygroups/issues/new?template=organizer-request.yml). You are currently in the KCD repo.

Thank you,
Audra
