### ISSUE TITLE
Just show city name in the events listing

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#61]
2019
SEPTEMBER
Sep 5 - 6: Cape Town
Sep 10 - 12: Portland

OCTOBER
Oct 1 - 2: Raleigh
Oct 2 - 3: Hartford

Don't say the event name. Just have the city link to the event. And please show date range if there is an enddate.

**Comment by lucperkins** [comment]
Resolved by f3a1d982e22115efaba04374b1c7fe3e0f314361
