### ISSUE TITLE
Create Template for new events 

### ISSUE THREAD

**Issue by iennae** [cncf/kubernetes-community-days#7]
The template should be part of the GitHub repo.

**Comment by lucperkins** [comment]
@iennae Could you explain what you mean by templates? The HTML templates are in the repo. Do you mean an example template of a new set of Markdown files for an event?

**Comment by iennae** [comment]
issue template so when folks want to start a new event it is prepopulated with the information they should include. https://help.github.com/en/articles/about-issue-and-pull-request-templates

**Comment by lucperkins** [comment]
@iennae Are you expecting people to begin working on events by opening issues?

**Comment by dankohn** [comment]
Template means a lot of different things. I would suggest that @iennae and @christinevblum create an issue template for organizers looking for partners in a city. We should also create a new project called `Event Formation` that they would be filed under. Then, when they have the prerequisites together, they should just be able to copy of the existing cities to create their event. I'm not sure that an "empty" city would help that much.

**Comment by iennae** [comment]
@dankohn this is available now:

https://github.com/cncf/kubernetes-community-days/issues/new?assignees=christinevblum%2C+iennae&labels=newevent&template=host.md for folks who are ready to host

and 

https://github.com/cncf/kubernetes-community-days/issues/new?assignees=christinevblum%2C+iennae&labels=planningevent&template=interest.md for folks who are wanting to find others who might be interested in organizing with them.

**Comment by dankohn** [comment]
Great, closing.
