### ISSUE TITLE
Adding Date, Location, Etc to Overview Page

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#78]
Please add the following to the overview page (https://kubernetescommunitydays.org/events/2020-bouvet-island/):

Dates (ability to add start and end date, i.e. Tuesday, Sep 10, 2019 - Thursday, Sep 12, 2019
Register)
Location (Venue Name, City)
Register (button that will link to the reg page)
Thanks!

**Comment by lucperkins** [comment]
Resolved by 809c820e8a8d3e6aceef00c768eb399d5ad6f2ba
