### ISSUE TITLE
Location Page

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#80]
Please help. I am having an issue with the Location page.
I updated the copy on:
kubernetes-community-days/content/events/2020-bouvet-island./venue.md 
e: 
But it is not showing up on:
https://kubernetescommunitydays.org/events/2020-bouvet-island/venue/
The name of the page on the menu is location. I am not sure if that is the issue.

**Comment by lucperkins** [comment]
@christinevblum That's because the build is currently failing, as you can see here: https://app.netlify.com/sites/kubernetes-community-days/deploys/5d71840fe4fe7e00073b21a4. I'll get it fixed.
