### ISSUE TITLE
Rewrite Readme

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#84]
Delete most of https://github.com/cncf/kubernetes-community-days/blob/master/README.md and instead link to a page taking people through creating their own event using the GitHub user interface. You can use the Readme just to describe the point of the site.

**Comment by dankohn** [comment]
Page in the site.

**Comment by christinevblum** [comment]
Can I suggest we do as Google Doc for now? I have it set up in suggestion mode, so if anyone runs into an issue they can comment and I can fix. It will be much easier to update in Google. I

**Comment by dankohn** [comment]
I really want all the content in GitHub so we can track it's evolution over time.

**Comment by christinevblum** [comment]
I will add to github. It is 37 pages long with Images. I will need to download all the images from google and put into the image folder.
