### ISSUE TITLE
Only show allowed menu items

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#85]
https://kubernetescommunitydays.org/events/2020-bouvet-island/sponsor-form/ is not an allowed page according to https://github.com/cncf/kubernetes-community-days/blob/master/config.toml#L10-L17 but it still is getting a menu item. Only allowed pages should get menu items.

**Comment by lucperkins** [comment]
Oops, accidentally removed this logic when updating the aesthetic of the navbar. Fixed in 15069dabef5ce5ac49f3985477db21c06efa2c35.
