### ISSUE TITLE
Embed Twitter feed on the homepage

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#86]
Please embed the last 5 tweets from https://twitter.com/kubeconio on the homepage. We'll soon be changing the name of this account to https://twitter.com/kubernetescommunitydays.

Directions: https://help.twitter.com/en/using-twitter/embed-twitter-feed

Please also add a Twitter icon to the footer of every page with a link to https://twitter.com/kubeconio.

**Comment by lucperkins** [comment]
@dankohn Unfortunately, there's no option to select the number of tweets so I set a maximum height instead. I really don't love the widget that they provide so I'm going to continue looking for other options.

**Comment by dankohn** [comment]
There is. See Customize Widget Components on https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview.html or look at https://www.dankohn.com/#recent-tweets

**Comment by dankohn** [comment]
Done, thank you!
