### ISSUE TITLE
Cloudcockookooland 

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#92]
Please describe the location you're interested in organizing an event, proposed dates, and information about your availability and experience with hosting a conference. If you have additional organizers and volunteers, include their information here as well.

Event City: Cloudcuckookooland
Organizer 1: First and Last Name, Company, Title, Email
Chris Blum, xrs888, CEO, cblum@contractor.linuxfoundation.org

I am intersted in hosting a KCF in Cloudkuckookooland on 12/25/19. I have hosted several Meetups in our city. I am looking for other organizers to help me run the event.

**Comment by xrs888** [comment]
We have two more sponsors for the event. Legoland and The Justice League

**Comment by christinevblum** [comment]
Congratulations! Please open issue to have your event officially recognized here: https://github.com/cncf/kubernetes-community-days/issues/new?assignees=christinevblum%2C+iennae&labels=newevent&template=host.md
