### ISSUE TITLE
Bug on event formation 

### ISSUE THREAD

**Issue by christinevblum** [cncf/kubernetes-community-days#99]
### Submission checklist:

*Please check each of these indicating that you have met these requirements:

* [X] I've included a URL where the issue occurs, and a screenshot if that makes things clearer
* [X] I've described what I expected to see and what I am seeing
* [ X] I am not interested or able to instead create a pull request with a proposed fix

https://github.com/cncf/kubernetes-community-days/issues/new

When I log into create an issue as an "event organizer" as xrs888, I dont see the following:
Assignees
Labels
Projects
Milestones 

I am assuming this is because we are hiding these from event organizers.

We need to make sure that on the "Organize Event" Issue submission that we have the project select as "event formation" so that shows up in the projects kanban. 

When I went back to the issue to try and figure out why it was not in the Kanban. The only way I was able to track it down was via the email I received as an Assignee. Then I went in and added the project and it showed up. 
The same thing happened with "interested in organizing" issue request

Can we set it up so the project is automatically checked?  or do the assignees need to go in and manual update these?
Thanks!

**Comment by dankohn** [comment]
Unfortunately, GitHub doesn't support the functionality of automatically adding issues to a project board. Using issue templates we can automatically assign them labels, but not to a project. It's an obvious shortcoming that will be fixed at some point. Lots of people complain about it here: https://github.community/t5/How-to-use-Git-and-GitHub/New-Issues-Not-Being-Auto-Added-to-Project-Board/td-p/6769/page/3

In the meantime, this [link](https://github.com/cncf/kubernetes-community-days/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-project%3Acncf%2Fkubernetes-community-days%2F2+-project%3Acncf%2Fkubernetes-community-days%2F1+) shows all issues not yet assigned to a project, if you want to bookmark it.
